### ISSUE TITLE
Dynamic URI starting with `/{AstroConfig.i18n.defaultLocale}` will result in a browser 404

### ISSUE THREAD

**Issue by SebastienD11** [withastro/astro#10005]
### Astro Info

```block
Astro                    v4.3.3
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

On a clean installation, if using i18N Routing from Astro 3.5.0, the following will happen:

If you have one URI starting with /{AstroConfig.i18n.defaultLocale}, the page will failed to resolve. 

So, given this config: 

```
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  i18n: {
    defaultLocale: 'fr',
    locales: ['en', 'fr'],
    routing: {
      prefixDefaultLocale: false,
    },
  },
});
```

and this "catch-all" page : 

``` [...uri].astro
---
  export function getStaticPaths() {
  return [{ params: { uri: '/test' }}, { params: { uri: '/france' }}]
}
---
Test Page
```

the following examples URL would fails to resolve:
- /france
- /fr 

the following would work:
- /test

anything else would display the Astro 404.

As a note : 
- On the Stacblitz link, only `/france` and `/fr`  would get this browser 404 blank page - all others page (like `/frwhaever` or `/tag/france`) would get the Astro 404. 
- On my Vercel, all the page including `/fr` anywhere in their URL would get the Astro 404 even `/fr and /france`. 
- And locally any pages with `/fr` anywhere in the URL (example : `/fr`, `/france`, `/frwhatever`, `/tag/france`) would get the blank page/browser 404 treatment.

### What's the expected result?

The page needs to resolve correctly even if it's starting with `/fr`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-iqt5vg?file=src%2Fpages%2F%5B...uri%5D.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by samnj** [comment]
I want to add some information because the problem seems to be more general, and I suspect it has the same root.

I changed the directory structure. Here I have `/[lang]/[uri].astro`, so no catch all route and one extra param to match. fr is still the default locale.

To what the stackblitz code shows, I want to add:

- `/test/test `, `test/frtest` and `test/entest` all fail with _Astro 404 template_ , not matching the first one but also using frtest and not getting a browser 404.
- `/test/fr` and `/test/en` however do fail with browser 404. I guess this is intended because both `fr` and `en` should match the first param but are trying to match the second one? Not sure about that.

https://stackblitz.com/edit/withastro-astro-nmbzgs?file=src%2Fpages%2F%5Blang%5D%2F%5B...uri%5D.astro
