### ISSUE TITLE
Issue with nested styles using Sass/SCSS when parent selector is comma separated list

### ISSUE THREAD

**Issue by kevin-powell** [withastro/astro#10144]
### Astro Info

```block
Astro                    v4.4.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

When using `<style lang='scss'>` or (`lang=sass`) within an `.astro` file, if using a comma-separated list of selectors as the parent selector, any nested styles are applied directly to the parent selector, instead of the selected child, *except* for the last selector in the list, which works properly.

For example:

```html
<style lang="scss">
:global(h1, h3, h2) {
    color: red;

    span {
         /* h1 and h3 get this style */
        color: blue;
    }
}
</style>
```

The `h1` and `h3` will be completely blue. Only the the `h2` will be red, with the span inside of it being blue, as expected.

Below is a screenshot of this, with an extra `p` added to the selector list, with the content being added with a `<slot/>`. The paragraph should *only* be red, but is blue as well.

![example of the issue described above on a page](https://github.com/withastro/astro/assets/25749407/dc78638b-6ac1-46e8-b625-15d935a33803)

When the Sass is being compiled to CSS, it is only "seeing" the nested selector for the last element in the list.
![in the dev tools: h1, h3, p, h2 span](https://github.com/withastro/astro/assets/25749407/84d7d832-c940-4601-93ac-941269e2bc41)

### What's the expected result?

The nested selector should work for every element in the list, not only the final one in the list. 

- If you remove `lang='scss'` (or `lang='sass'`) and use native CSS nesting, it works as expected.
- If you remove `:global()`, it works as expected.
- If you remove `:global()`, and use `<style lang='scss' is:global>` it works as expected.
- If you wrap the comma-separated list in an `:is()` or `:where(),` it fixes the issue (as it's now a single selector, I'm guessing).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/beyondcss-astro-04-trqruq?file=src%2Flayouts%2FBaseLayout.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I think this is working as expected, but probably hard to spot the issue. If you [compile the scss code](https://sass-lang.com/playground) manually, the output is:

```css
:global(h1, h3, h2) {
  color: red;
}
:global(h1, h3, h2) span {
  /* h1 and h3 get this style */
  color: blue;
}
```

There will then be an issue in how Astro reads `:global(h1, h3, h2) span`. Astro can't assume that `:global(h1, h3, h2)` automatically expands to apply to each `span`. It's also complex to implement with potential incorrect transformations. What would work instead is `:global(h1) span, :global(h3) span, :global(h2) span`, in which case, it is also what you should write in your SCSS code, which is `:global(h1), :global(h3), :global(h2)` instead of `:global(h1, h3, h2)`.

Closing this as expected.
