### ISSUE TITLE
`astro check` should not run on files in the `public/` directory

### ISSUE THREAD

**Issue by gavinr-maps** [withastro/astro#10174]
### Astro Info

```block
...:~/temp/astro/grateful-galaxy$ ./node_modules/.bin/astro info
Astro                    v4.4.1
Node                     v20.11.1
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

n/a

### Describe the Bug

When I have certain `*.js` files in the `public/` directory, when I run `npm run build`, it runs `astro check`. As part of `astro check` I get a huge amount of terminal output and "hints" are reported. I would expect that `astro check` should **not** run on files within the `public` directory per the guidance on the [documentation page](https://docs.astro.build/en/basics/project-structure/#public): 

> The public/ directory is for files and assets in your project that do not need to be processed during Astro’s build process ... You can place CSS and JavaScript in your public/ directory, but be aware that those files will not be bundled or optimized in your final build.

## Replication Steps

1. `npm create astro@latest`
2. Click <Enter> 6 times to accept all the defaults of the tutorial.
3. `cd grateful-galaxy` (or whatever folder name was chosen for you)
4. `cd public`
5. `wget https://cdn.sstatic.net/Js/stub.en.js`
6. `cd ..`
7. `npm run build`

- Expected output: no errors, warnings, or hints. I.e.:
    ```
    Result: 
    - 0 errors
    - 0 warnings
    - 0 hints
    ```
- Actual output: 

```bash
public/stub.en.js:1:874 - warning ts(6133): 'e' is declared but its value is never read.

1 (()=>{"use strict";var e={p:""};e.p=document.getElementById("w.......

Result (6 files): 
- 0 errors
- 0 warnings
- 35 hints
```

### Link to Minimal Reproducible Example

see above

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
@gavinr-maps thank you for opening this issue.
In the meanwhile, as a workaround, you might try to change the definition of build in package.json:
```
    "build": "astro check --tsconfig tsconfig.json && astro build",
```

**Comment by jacobdalamb** [comment]
`astro check` shouldn't check `dist`

**Comment by martrapp** [comment]
in your tsconfig.json, you might try to add
``` 
 "exclude": ["dist"],
```

**Comment by jacobdalamb** [comment]
> in your tsconfig.json, you might try to add
> 
> ```
>  "exclude": ["dist"],
> ```

But why is that default behavior?

**Comment by martrapp** [comment]
No idea yet, just want to offer a quick workaround while we investigate & fix ;-)

**Comment by Princesseuh** [comment]
> > in your tsconfig.json, you might try to add
> > 
> > ```
> >  "exclude": ["dist"],
> > ```
> 
> But why is that default behavior?

Because the proper way to do it from Astro's perspective isn't that easy. 

- We want it to respect the Astro config for `outDir`, `publicDir` etc. which means that we can't hardcode the value. Additionally, it would have to live in the root `tsconfig.json` (because of how `extends` work (specially those outside the project's directory)) which at the moment we don't touch outside of explicit actions and confirmation (`astro add`)
- We don't want it as a param of `astro-check` that Astro would pass because then it's inconsistent between `tsc`, `astro check` and the code editor, which not only just feels bad, is also philosophically dubious (Astro is supposed to teach you about the underlying tools you're using, in this case TypeScript)

The proper way is then for Astro to modify the `tsconfig.json` for the user, but this comes with a lot of caveats (as always)

- Modifying `tsconfig.json` in JavaScript always sucks, because `tsconfig.json` isn't a standard JSON file, so native tools will mess it up in some ways (ex: will remove comments), with `astro add` this is okay, because we can show the user that this will happen before they accept the change.
- Which brings the question of "Can't Astro have its own hidden `tsconfig.json` that it modifies and extends from?" to which the question is Yes! However, `exclude` is one of the few settings that do not merge between `extends`, so there are additional concerns there too.
  - This is something we're already planning to do, because it unlocks a few benefits regarding type generation (Nuxt uses a similar setup very successfully)
- This requires settings to emulate the power that was taken away from users (I wouldn't want `public` to be ignored, for instance!) so more things to think about.

Sure, there're most likely shortcuts that we could take, like adding the default values to the default exclude for newer projects and stuff, but doing it properly is also fun (and in progress, see linked PR) and since there was already plans for what seems to be the proper way, we didn't consider shortcuts too much and no one sent a PR for it.

**Comment by martrapp** [comment]
Hi @gavinr-maps !

My first advice above was a mistake. Just add 
```
  "exclude": ["public"]
``` 
to your tsconfig.json. For explanation see Princesseuh's detailed comment above.

**Comment by Princesseuh** [comment]
For anyone worrying that this problem isn't tracked, there's an issue on the language-tools repo about essentially the same thing (but for `dist`), either way this will be fixed by the linked PR that's currently in draft.

**Comment by LukeSavefrogs** [comment]
This issue is also fixed by specifying `compilerOptions.outDir` in the `tsconfig.json` file as said [here](https://github.com/withastro/language-tools/issues/643)
