### ISSUE TITLE
Astro Locals not working in production

### ISSUE THREAD

**Issue by sashafklein** [withastro/astro#10254]
### Astro Info

```block
Astro                    v4.3.2
Node                     v20.9.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/react
                         @astrojs/mdx
```

### Describe the Bug

I'm using Astro Locals to attach an API object that handles a bunch of shared behavior for calling an external API the app relies on (authentication headers, etc), so I can do:

```
await Astro.locals.api.get('/whatever')
```

I did this in a `middleware.ts` file:

```ts
export const onRequest: MiddlewareHandler = (context, next) => {
  const { locals, cookies } = context;

  locals.api = makeMyApi(cookies);

  // return a Response or the result of calling `next()`
  return next();
};
```

This works perfectly locally, but in production (on Netlify), I get an undefined error along the lines of `Cannot read properties of undefined (reading "get")`. When I log out `Astro.locals`, it confirms the error -- the `api` value is not there:

```
{
  netlify: {
    context: {
      account: [Object],
      cookies: [Object],
      deploy: [Object],
      flags: Flags {},
      geo: [Object],
      ip: '136.62.171.247',
      json: [Function: json],
      log: [Function (anonymous)],
      next: [Function: next],
      params: [Object],
      requestId: '01HQNSSKRGXDRJGRNZSYY6MMN4',
      rewrite: [Function: rewrite],
      server: [Object],
      site: [Object]
    }
  }
}
```

What might be happening here? Seems like a bug to me, and is definitely derailing the development plan I had here.

### What's the expected result?

Locals should work identically in dev and on production.

I believe the repro should show the same bug on Netlify. Will try to confirm and update this ticket

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-hua8gr

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Does the stackblitz need to be updated?

**Comment by sashafklein** [comment]
I added a StackBlitz, and it should be a minimal repro. The only changes I made to the starter app were to:

1. Add a `src/middleware.js` file
2. Log the `Astro.locals` in `src/pages/index.astro`

This should work locally, but not log the middleware-modified `locals` on Netlify.

**Comment by lilnasy** [comment]
Could you add the netlify adapter as configured in your real project?

**Comment by ematipico** [comment]
@sashafklein this expected.

Not sure if you have a full understanding of the adapter and locals, so I'll try to break it down:
- when using a middleware with the Netlify adapter, the middleware is **transformed** in an edge middleware
- the edge middleware becomes a totally different edge function that is run outside of the Astro workflow. The edge middleware is run **in front** of your astro page
- the Astro page is a separate function (and file) that is run after the edge middleware
- in order to pass locals from the edge middleware to the astro page, we use **request headers**
- these locals, in turn, must be serialised

Now, looking at the error, it seems that `get` is a function, which can't be serialised, and that's why you have the error. 

Also, your reproduction doesn't seem to be close to your use case, so this doesn't help us.

This information is available here: https://docs.astro.build/en/guides/integrations-guide/netlify/#running-astro-middleware-on-netlify-edge-functions
