### ISSUE TITLE
ViewTransition and Font preload not playing nicely together

### ISSUE THREAD

**Issue by markhorn-dev** [withastro/astro#10425]
### Astro Info

```block
Astro                    v4.4.13
Node                     v21.4.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/solid-js
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Firefox, Edge (Warning) , Safari (No warning)

### Describe the Bug

Whenever using ViewTransition and font preload together in the same project, the browser complains

`The resource http://localhost:4324/fonts/atkinson-regular.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

`The resource http://localhost:4324/fonts/atkinson-bold.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

Note, that commenting out or removing completely one or the other, resolves the issue

Option 1: 
Remove ViewTransition from BaseHead.astro

`<ViewTransitions  />`

Option 2:
Remove font preload from BaseHead.astro

```
<link rel="preload" href="/fonts/atkinson-regular.woff" as="font" type="font/woff" crossorigin>
<link rel="preload" href="/fonts/atkinson-bold.woff" as="font" type="font/woff" crossorigin>
```

Other Notes:
Issue occurs on dev, and preview on localhost, and also in production (vercel in my case)
Chrome, Edge, Firefox all complain. Safari does not complain.

I literally took several days debugging this, thinking it was tailwind or the way I was using fonts in the project. But then I tested it on the default astro blog template and no warnings! The second I added ViewTransition the warnings appeared.

I believe it has to do with the swapping nature of ViewTransition.

### What's the expected result?

Expect to be able to use both ViewTransitions and font preloads together

### Link to Minimal Reproducible Example

https://preload-with-view-transitions.vercel.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
I don't think there's a way to fix this, this kinda happens in any case you have a preloading mechanism. You can see a similar error on many SPAs online.

**Comment by martrapp** [comment]
Hello @markhorn-dev,

The browser is complaining because the font preload links are executed on every view transition, but the fonts are not used then. You won't see such a warning on first load because the preload fonts are consumed in global.css. But once the fonts are set, further preloads will not be consumed, hence the warning. 

I assume your actual application is far more complex than the minimal reproduction. Otherwise, you could (as you said) simply remove the font preload links from your layout. 

If you see a good reason why you need the font preload links on first load, you can dynamically remove superfluous preloads from the next pages as you navigate to them. Add something like this to your layout.astro:

```html
  <script>
    import type { TransitionBeforeSwapEvent } from "astro:transitions/client";
    document.addEventListener("astro:before-swap", (e) =>
      [
        ...(e as TransitionBeforeSwapEvent).newDocument.head.querySelectorAll(
          'link[as="font"]'
        ),
      ].forEach((link) => link.remove())
    );
  </script>
```

As in your example, this assumes that all pages have the same preload links in their header, e.g. because you add them with the same layout component. If this is not the case, you need to add more logic to decide which link elements should be removed.

**Comment by markhorn-dev** [comment]
@martrapp 

`  <script>
    import type { TransitionBeforeSwapEvent } from "astro:transitions/client";
    document.addEventListener("astro:before-swap", (e) =>
      [
        ...(e as TransitionBeforeSwapEvent).newDocument.head.querySelectorAll(
          'link[as="font"]'
        ),
      ].forEach((link) => link.remove())
    );
  </script>`

This absolutely worked! Can't believe I didn't think of it, especially since I'm using quite a few astro:*-swap event handlers.

Thanks so much.

**Comment by OliverSpeir** [comment]
Could view transitions router safely ignore preloads if they exist on the previous page? Similar to not rerunning is:inline scripts if they exist on both pages?

**Comment by martrapp** [comment]
With all the "whens" and "ifs" above, I wouldn't recommend it.  Astro does not know how the fonts are used.

The easiest way would be to simply not preload:
When the page is first loaded, it doesn't help much if the font is directly used on the page and after that it is no longer necessary because view transitions soft load does not unload font definitions. 

If you have special requirements, you can still use Astro's life-cycle events.
