### ISSUE TITLE
Node.js ignoring `SIGINT` signals in Docker

### ISSUE THREAD

**Issue by NuroDev** [withastro/astro#10524]
### Astro Info

```block
Astro                    v4.5.8
Node                     v20.11.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

While building a new project with Astro I noticed a small bug when using the Node.js adapter with Docker where once you start the container there is no way to stop it without killing the container. The standard `^C` / `SIGINT` signals do not seem to work.

### What's the expected result?

Ideally when running a SSR Astro app inside of a Docker container when using the Node.js adapter you should be able to send a `SIGINT` signal or `^C` & the process should terminate.

### Steps to reproduce

(Adding a breakdown of the steps to re-produce here because Docker is of course not available via Stackblitz)

- Create a new Astro project with: `astro create PROJECT_NAME`
- Install dependencies: `npm install`
- Add the Node.js adapter: `astro add node -y`
- Create a basic `Dockerfile` using [the guide in the Astro documentation](https://docs.astro.build/en/recipes/docker/#ssr)
- Build the container image: `docker build -t astro-sigint-test`
- Run the container: `docker run --rm -p 4321:4321 --name astro-sigint-test astro-sigint-test`

With the container running you need can access your app fine, but if you try to exit out the container via Control + C (`^C`) or sending a `SIGINT` signal, it will do nothing & keep running.

The only way to get out of the container is to run: `docker kill astro-sigint-test`.

### Link to Minimal Reproducible Example

N/A

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hey @NuroDev, thanks but we are not able to take issues that require extra wrapper programs. Since Docker is the thing responsible for sending signals to the process, the problem is likely there; perhaps they don't do this on purpose. I'm not sure, but we aren't experts on Docker.

If you can isolate the problem further so that Docker is not involved, then please create a new issue. Thank you!

**Comment by joprice** [comment]
@NuroDev The is usually caused by something wrapping the process, causing signals to not be forwarded. In this case, switching `CMD` to `ENTRYPOINT` (`ENTRYPOINT ["node", "./dist/server/entry.mjs"]`), and passing the `--init` flag when running the image will cause signals to be forwarded correctly. Depending on where you end up deploying it, you may want to bake `tini` or similar init manager into the image, but in other contexts (e.g. fly.io), it's unnecessary.

Here's an article that explains the issue: https://dev.to/antoinecoulon/avoid-this-when-running-containerized-applications-in-production-562k
