### ISSUE TITLE
Middleware doesn't run for static files with the vercel adapter's `edgeMiddleware` feature

### ISSUE THREAD

**Issue by lilnasy** [withastro/astro#10536]
### Astro Info

```block
Astro                    v4.5.9
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             none
```

### Describe the Bug

The middleware only runs for on-demand rendered pages with `edgeMiddleware` enabled.

### What's the expected result?

The middleware also runs for prerendered pages and static subresources.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zqkte3?file=src%2Fpages%2Fx.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by myl7** [comment]
Me too even without `edgeMiddleware: true`.
Serving the static file as an endpoint can make it trigger the middleware, which could somehow solve the problem.

**Comment by ematipico** [comment]
This isn't a bug, but a feature. The middleware is designed to be called during the build for SSG, and at each request in SSR.

Mixing this behaviour (each request for SSG) must be done at the adapter level, but Astro also needs to change its architecture and build.

I am going to close it. Users should open a discussion in the roadmap repository

**Comment by ADTC** [comment]
I added `output: "server"` to Astro config in order to force the middleware by making everything SSR. But then, the i18n fallback rewrite doesn't work anymore and the URLs with "missing" pages simply give 404 instead of the rewrite result:

```js
export default defineConfig({
	i18n: {
		routing: {
			fallbackType: "rewrite",
			prefixDefaultLocale: false,
		},
	},
	adapter: vercel({ edgeMiddleware: true }),
	//...
});
```

@ematipico I saw #13964 but the solution is not to then make the pages prerendered with `prerender = true` because then the middleware no longer runs for those static routes. (Also, weirdly, the rewritten static routes are redirects to localhost _in Vercel_).
