### ISSUE TITLE
When integrating Svelte, certain styles and scripts are injected into the `<body>` rather than the `<head>` tag.

### ISSUE THREAD

**Issue by mgxuzy** [withastro/astro#10563]
### Astro Info

```block
Astro                    v4.5.9
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/svelte
```

### Describe the Bug

The current Svelte integration injects **some** output scripts and styles into the `<body>` tag of the HTML document. However, for better performance and adherence to best practices, it's recommended to inject scripts into the `<head>` tag.

### What's the expected result?

As stated in the [Astro's documentation](https://docs.astro.build/en/guides/client-side-scripts/#script-processing), "The processed script will be injected into your page’s `<head>` with [`type="module"`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules)."

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/main/examples/framework-svelte

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is on purpose, for multiple reasons, all related to streaming. Since we stream the page, we cannot put the scripts from the islands inside the head, as the head is already rendered by the time we get to the islands. This is also good for performance, because the `head` is smaller, and so can be rendered quickly.

We won't be changing this, `script` inside the `body` is a very common pattern.
