### ISSUE TITLE
RSS integration ignores trailingSlash:"never" and constructs urls with (/) regardless

### ISSUE THREAD

**Issue by f33w** [withastro/astro#10723]
### Astro Info

```block
not relevant
```

### Describe the Bug

The domain.com/rss.xml renders trailing slash even if trailingSlash is set to "never".

**RSS code:**
```
import { WEBSITE_CREDENTIALS } from "@/components/utilities/Consts.astro";
import rss from "@astrojs/rss";
import { getCollection } from "astro:content";

export async function GET(context) {
  const posts = await getCollection("posts");
  // TODO: add all collections [...posts, ...books] egt.
  const allPosts = [...posts];

  return rss({
    // `<title>` field in output xml
    title: WEBSITE_CREDENTIALS.title,
    // `<description>` field in output xml
    description: WEBSITE_CREDENTIALS.description,
    // Pull in your project "site" from the endpoint context
    // https://docs.astro.build/en/reference/api-reference/#contextsite
    site: context.site,
    // Array of `<item>`s in output xml
    // See "Generating items" section for examples using content collections and glob imports
    items: allPosts.map((post) => ({
      title: post.data.title,
      pubDate: post.data.pubDate,
      description: post.data.description,
      // Compute RSS link from post `slug`
      // This example assumes all posts are rendered as `/posts/[slug]` routes
      link: `/${post.collection}/${post.slug}`,
    })),
    // (optional) inject custom xml
    customData: `<language>en-us</language>`,
  });
}
```

**localhost/rss.xml**
```
<rss version="2.0">
<channel>
<title>MY WEBSITE </title>
<description>Here goes website description.</description>
<link>https://domain.com/</link>
<language>en-us</language>
<item>
<title>My first post, written in mdx. It will be used for testing stuff</title>
<link>https://domain.com/posts/post-1/</link>
<guid isPermaLink="true">https://domain.com/posts/post-1/</guid>
<description>This is the description for my first post, written in mdx, that I am using to test stuff. Description is showing on Google SERP. It doesn't directly impacts SEO</description>
<pubDate>Sun, 31 Mar 2024 00:00:00 GMT</pubDate>
</item>
<item>
<title>The second post. The second post. The second post. The second post. </title>
<link>https://domain.com/posts/post-2/</link>
<guid isPermaLink="true">https://domain.com/posts/post-2/</guid>
<description>The second post. The second post. The second post. The second post. The second post. The second post. The second post. The second post. The second post. The </description>
<pubDate>Mon, 01 Apr 2024 00:00:00 GMT</pubDate>
</item>
</channel>
</rss>
```

It seems like trailingSlash is specified in
```
node_modules/@astrojs/rss/dist/index.js
node_modules/@astrojs/rss/dist/index.d.ts
```
Dunno how to adress that. But according to Google:
**Only include canonical URLs. A common mistake is to include URLs of duplicate pages. This increases the load on your server without improving indexing.**

Source: https://developers.google.com/search/blog/2014/10/best-practices-for-xml-sitemaps-rssatom

### What's the expected result?

Depending on wether thrailingSlash is set to Never or Always:
```
<link>https://domain.com/posts/post-1</link>
//or
<link>https://domain.com/posts/post-1/</link>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1k2ldy?file=src%2Fpages%2Frss.xml.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by BryceRussell** [comment]
I think this is expected behavior, in this case there are two `tailingSlash` options:

- The Astro config has a `tailingSlash` option to set the route matching behavior of the dev server to match production
- The `rss` function from `@astrojs/rss` has a `tailingSlash` option to add/remove trailing slashes from links

Using the `tailingSlash` option from the Astro config to add a trailing slash to RSS links would affect the build output and dev server instead of only the dev server

If you want to remove trailing slashes from your links, you can use option `trailingSlash: false` inside the `rss` function:

```diff
export async function GET(context) {
  return rss({
+   trailingSlash: false,
	...
  });
}
```

**Comment by f33w** [comment]
@BryceRussell that's awesome, thank you. That should def be added to docs!

Also it seems that trailingSlash:false does not impact the domain's link `<link>https://placeholder.com/</link>`. Any ideas on what can be the issue? 

**config:**
```
  trailingSlash: "never",
  site: "https://placeholder.com", // TODO: replace with the real website url
  base: "/",
```

**Rss output**
```
<rss version="2.0">
<channel>
<title>website title</title>
<description>Here goes website description</description>
<link>https://placeholder.com/</link>
<language>en-us</language>
<item>
<title>My first post, written in mdx. It will be used for testing stuff</title>
<link>https://placeholder.com/posts/post-1</link>
<guid isPermaLink="true">https://placeholder.com/posts/post-1</guid>
<description>This is the description for my first post, written in mdx, that I am using to test stuff. Description is showing on Google SERP. It doesn't directly impacts SEO</description>
<pubDate>Mon, 08 Apr 2024 00:00:00 GMT</pubDate>
</item>
<item>
<title>The second post. The second post. The second post. The second post. </title>
<link>https://placeholder.com/posts/post-2</link>
<guid isPermaLink="true">https://placeholder.com/posts/post-2</guid>
<description>The second post. The second post. The second post. The second post. The second post. The second post. The second post. The second post. The second post. The </description>
<pubDate>Mon, 08 Apr 2024 00:00:00 GMT</pubDate>
</item>
</channel>
</rss>
```

**Comment by Fryuni** [comment]
> Any ideas on what can be the issue?

That is a quirk of the URL spec. A trailing slash is up to the interpretation of the application, except when it is the root. In that case, it is specified that it must behave the same.

In an HTTP request, it is impossible to differentiate between the two since the path is sent separately from the host and can't be empty. The request to `http://example.com` will start with:
```
GET / HTTP/1.1
Host: exemple.com
```
Starting with `GET HTTP/1.1` is invalid. So the path is `/`, not an empty string.

Some parsers, like the one used in the JS-native `URL` class, will even parse them to be the exact same object, with `pathname` set to `/`. Since the RSS module uses `URL` objects to internally represent the URLs being constructed, the root URL always has a trailing slash:

```
➜ node
Welcome to Node.js v20.11.1.
Type ".help" for more information.
> new URL('http://example.com').toString()
'http://example.com/'
```

But this is not something to worry about since those two will always behave the same regardless of your `trailingSlash` config.

**Comment by f33w** [comment]
@Fryuni Thank you so much for clarifying that!
And thanks to @BryceRussell for providing a solution. I'll now close the issue
