### ISSUE TITLE
Unable to Access Environmental Variables in React Island Component

### ISSUE THREAD

**Issue by babblebey** [withastro/astro#10736]
### Astro Info

```block
Astro                    v4.5.9
Node                     v20.9.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/mdx
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

Brave (Chromium)

### Describe the Bug

I'm currently working on integrating Astro with React for my project. In one of my React Island components, I'm trying to access an environmental variable using Vite's `import.meta.env.VAR`, but I'm encountering an issue where the variable is not accessible.

**Steps to Reproduce:**
1. Create a React Island component in an Astro project.
2. Create a variable `VAR` with value in your `.env` file
3. Attempt to access that environmental variable using `import.meta.env.VAR` within the React component.

**Actual Behavior:**
The environmental variable is not accessible, returns `undefined`.

### What's the expected result?

The environmental variable should be accessible within the React Island component.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jwz3ys?file=src%2Fcomponents%2FCounter.tsx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
As documented on https://docs.astro.build/en/guides/environment-variables/, only variables prefixed with `PUBLIC_` will be available client side when using `import.meta.env`. Note that it's showing in the console because it's also running on the server first, where the variable is available. Have a look at https://stackblitz.com/edit/github-jwz3ys-6hzqjm?file=src%2Fcomponents%2FCounter.tsx,.env to see it working

**Comment by babblebey** [comment]
🤦🏾‍♂️

Thanks @florian-lefebvre
