### ISSUE TITLE
React hydration error with react table but works fine the same example in next.js

### ISSUE THREAD

**Issue by khanakia** [withastro/astro#10860]
### Astro Info

```block
Astro                    v4.6.3
Node                     v21.7.1
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/react
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

I am using react table with SSR when I use the below tab without `client:load` the table renders correctly but it's not interactive I cannot click anywhere so I added the `client:load` and then it breaks

PS: I used the same code in **Next.js** it works perfectly and it renders and hydrate without any error.

```js
<DataTable data={tasks} columns={columns} />
```
![Screenshot 2024-04-24 at 7 34 49 AM](https://github.com/withastro/astro/assets/2174170/33c7dbe4-2dbe-4bcc-8bcd-c5637f287972)

```js
 <DataTable data={tasks} columns={columns} client:load />
```

![Screenshot 2024-04-24 at 7 34 38 AM](https://github.com/withastro/astro/assets/2174170/8003b0af-73d0-4e12-9ac6-3686cf076385)

### What's the expected result?

It should hydrate with no error

### Link to Minimal Reproducible Example

https://github.com/khanakia/astro_react_table

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hi @khanakia, this is happening because your client code is rendering something different than what was rendered on the server. You can see the problem in the console:

> Warning: Did not expect server HTML to contain a <button> in <th>.

You can further debug this by using `client:only="react"`. This takes server-rendering out of the equation. When doing that you can see that it's rendering blank content.

You can debug this by examining the tree and seeing where the data looks "wrong". I did a little bit and found that `header.column.columnDef.header` is `null` in the client.  Switching back to `client:load` I can see that it's a `function` on the server. That's a different that probably matters a lot. There might be other similar differences.

More than likely this comes down to an incorrect usage of the library, or perhaps a bug within the library when used with Vite. You'll have to debug further to figure out why.

Closing as this is not an Astro bug.

**Comment by khanakia** [comment]
I get it but the same code works correctly on the next.js server rendered and then hydrated correctly on the client. I can share the code as well if needed
