### ISSUE TITLE
[View Transitions]  Using client:only in dev causes page reloads on view transitions

### ISSUE THREAD

**Issue by 1574242600** [withastro/astro#10886]
### Astro Info

```block
Astro                    v4.7.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/solid-js
```

### Describe the Bug

When clicking on any hyperlink:
- in development
![dev](https://github.com/withastro/astro/assets/35765846/eb331c17-d602-45e3-8393-7d91d2f9fa2b)
- in production
![prod](https://github.com/withastro/astro/assets/35765846/096afc6a-0bc0-4737-ab16-5f6d996ea03d)

### What's the expected result?

Clicking on hyperlinks in development mode should produce the same results as in production mode.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-r5pkah?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hey @1574242600, I'm sorry, I do not understand the issue you have. I was not able to see page reloads with your code. Could you please describe the issue in more detail?

**Comment by 1574242600** [comment]
I apologize for not providing a thorough description of the issue. In development, when I click on a hyperlink, the cursor flickers, and in the network requests, it shows that the same page is being fetched twice. However, everything works fine in the production. I'm not sure if this is the expected behavior.


https://github.com/withastro/astro/assets/35765846/f3ab2f2e-a07c-42ce-8966-bb897c101f7d

**Comment by martrapp** [comment]
Ah, now I see what you're wondering about! Yes, unfortunately this cannot be avoided, but it is guaranteed to only occur in DEV mode.

Background: With `client:only`, the styles are created dynamically in DEV mode. You can actually only find out which ones are still needed on the next page by looking at the next page.

That's exactly what Astro does in the background, which is why the page is requested twice, once to display and once to find out how to modify it before it can be displayed. This cannot be completely hidden. None of this is needed in production. If you have any further questions, please feel free to ask. Otherwise I can say that what you see in DEV is to be expected.
