### ISSUE TITLE
Priority problem of nested dynamic routing.

### ISSUE THREAD

**Issue by zhangchuachua** [withastro/astro#11108]
### Astro Info

```block
Astro                    v4.8.6
Node                     v18.20.1
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

I have `/pages/[...lang]/index.astro`, `/pages/[...lang]/[category]/index.astro`, `/pages/[...lang]/[category]/[slug].astro`; 

- The `/pages/[...lang]/index.astro` is a static page.
    ```astro
    export const getStaticPaths = (() => {
      return [{ params: { lang: 'jp' } }, { params: { lang: undefined } }]
    }) satisfies GetStaticPaths
    ```
- The `/pages/[...lang]/[category]/index.astro` and `/pages/[...lang]/[category]/[slug].astro` is an SSR page.

When I visit `/jp/how-to` it will match `/pages/[...lang]/[category]/[slug].astro` instead of `/pages/[...lang]/[category]/index.astro`.

Astro.params is `{ lang: undefined, category: 'jp', slug: 'how-to' }`; 

It's clear to me that this is a prioritization issue with dynamic routing, where `adapter/node` matches the route `/pages/[...lang]/[category]/[slug].astro` has a higher priority, but I'd just like to know if there's a way to make the change? Is this a bug in Astro;

### What's the expected result?

Because `getStaticPaths` in `/pages/[...lang]/index.astro` contains `{ params: { lang: 'jp' } }`, then it should match `/pages/[...lang]/[category]/index.astro`;

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3qfqph

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Fryuni** [comment]
That is the correct behavior. More specific routes (where you define more segments, the first rule of [route priority ordering](https://docs.astro.build/en/guides/routing/#route-priority-order)) are higher priority. When routes are ambiguous, Astro follows those rules to have a stable result.
[Rest parameters](https://docs.astro.build/en/guides/routing/#rest-parameters) can have zero length, so `[...lang]/[category]/[slug]` also match routes with two segments.

So routes like `[...a]/[b]/[c]` will have a higher priority than `[...a]/[d]` and when both are rendered on demand (SSR) you won't get any match for `[...a]/[d]` where `a` is defined since any valid match for that is also a match for `[...a]/[b]/[c]`.

If your `lang` parameter was not a rest para (`[lang]` instead of `[...lang]`) this problem wouldn't happen, if you can organize it like that, maybe extracting the page into a component and having two routes (`/[category]/[slug]` and `/[lang]/[category]/[slug]`) is one way for you to achieve the behavior you want.

**Comment by Fryuni** [comment]
I'll close this as not planned since it is behaving as expected. If you have any suggestions to change that behavior or make it configurable in some way, feel free to open a [discussion on the roadmap](https://github.com/withastro/roadmap/discussions) 😄
