### ISSUE TITLE
💡 RFC: If Astro swallows exception during build, include original error in the error/debug msg

### ISSUE THREAD

**Issue by matsdahlin** [withastro/astro#1110]
### Background & Motivation

When helping debugging an issue with a 3rd party library today, Astro silently swallowed the original error message (window is undefined), which file caused it and replaced it with its own message:

"The window object is not available during server-side rendering (SSR).
Try using \`import.meta.env.SSR\` to write SSR-friendly code.
https://docs.astro.build/reference/api-reference/#importmeta`"

This made the issue take longer to track down than it could have, since the "real" error was inside Astro all along but discarded in favor of the custom error message.

### Possible solutions

I propose that Astro should include the original error message in any error results being returned from `runtime.ts load()` function to ease debugging. It could either be included in the main error output och as an "read original trace" detail maybe.

Perhaps this feature could be on only when in dev server or turned on with a flag.

### Alternatives considered

-

### Risks, downsides, and/or tradeoffs

Risk: Could this extra information be confusing? 

### Open Questions

Other good ways to display this information?

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by drwpow** [comment]
I don’t think this needs discussion; I think everyone can agree that we need this! 🙂 This is something we’re working on right now with the new compiler, and that will solve this issue. But I will leave this open until we release that publicly to track this.

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
