### ISSUE TITLE
ViewTransitions reset scroll position after a form submission

### ISSUE THREAD

**Issue by alexander-entin** [withastro/astro#11124]
### Astro Info

```block
Astro                    v4.8.7
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

Reproduction:
1. open provided StackBlitz
2. click links in the menu to make sure `ViewTransitions` work
3. scroll down
4. press `submit`
5. see scroll position reset

### What's the expected result?

scroll position is preserved

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-uog72f?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @alexander-entin, thank you for this example. 

However, I'm afraid I do not understand the issue here. 
The default action of the submit is the page you put the form on. When loaded, URLs without hash fragment are always shown at scroll position 0. This is the same behavior with or without `<ViewTransitions/>`.

You could return a redirect from your POST and redirect to an URL with a fragment id (e.g. /#form) to show the form after submission. If you really want to keep the scroll position across view transition navigation you could explicitly save and restore it, see for example https://events-3bg.pages.dev/library/NoScroll/

**Comment by martrapp** [comment]
I have not heard from you since. Please re-open this  issue if you are still having problems.
