### ISSUE TITLE
There are different behaviors for custom attributes that do not start with data and attributes that start with data

### ISSUE THREAD

**Issue by ajiho** [withastro/astro#11342]
### Astro Info

```block
View link:https://stackblitz.com/edit/github-x7gejb?file=src%2Fpages%2Findex.astro
```

### Describe the Bug

![image](https://github.com/withastro/astro/assets/107699138/9edbc595-e5f3-49f6-9fe8-ed40caf656f7)
What should I do for attributes that do not start with data if I also want to maintain the absence of attribute values? Their performance is different, and in the final generated HTML file, I only want to keep `custom` instead of `custom="true"`

### What's the expected result?

keep `custom` instead of `custom="true"`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-x7gejb?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This is where we handle how attribute values are handled

https://github.com/withastro/astro/blob/dc95d674af8792773693d491a1f7520d0260e20b/packages/astro/src/runtime/server/render/util.ts#L117-L122

`="true"` can only be omitted if the attribute is a known [boolean attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#boolean_attributes), so `custom="true"` is expected. However, `data-custom` (without value) seems odd to me because it's not known to be a boolean attribute. 

Support for omitting the value if `true` for `data-*` was added in https://github.com/withastro/astro/commit/b958088c3dbabc43f698ff6684e6d54a8ec189f4#diff-3974ff1a07864eae3cb91ceefef360fbc39db051f8036ee2504b9be00764e0ccR226 by @matthewp, which perhaps is a bug? I think we can only omit it if the value is `""`, not `true`, which I also confirm is the behaviour from vue and svelte today.

I'm not sure how breaking this is if we change now, but in practice probably not a lot as the way to check the attributes truthiness will still work? (`hasAttribute`)

**Comment by ajiho** [comment]
To be honest, I am looking forward to this change so that I can confidently migrate from the Twig template engine to Astro

**Comment by matthewp** [comment]
I'm surprised we've gone this long without discovering this. @bluwy I concur with your findings, should be omitted only if `""` is the value, same for data- or non-data.

**Comment by nanarino** [comment]
![Image](https://github.com/user-attachments/assets/6c85995c-0343-453e-bce1-31364c2f3cc3)


Can I request that "popover" be added to the list?

[astro/packages/astro/src/runtime/server/render/util.ts](https://github.com/withastro/astro/blob/latest/packages/astro/src/runtime/server/render/util.ts#L9-L10)

**Comment by nanarino** [comment]
> This is where we handle how attribute values are handled
> 
> [astro/packages/astro/src/runtime/server/render/util.ts](https://github.com/withastro/astro/blob/dc95d674af8792773693d491a1f7520d0260e20b/packages/astro/src/runtime/server/render/util.ts#L117-L122)
> 
> Lines 117 to 122 in [dc95d67](/withastro/astro/commit/dc95d674af8792773693d491a1f7520d0260e20b)
> 
>  // Boolean values only need the key 
>  if (value === true && (key.startsWith('data-') || htmlBooleanAttributes.test(key))) { 
>  	return markHTMLString(` ${key}`); 
>  } else { 
>  	return markHTMLString(` ${key}="${toAttributeString(value, shouldEscape)}"`); 
>  } 
> `="true"` can only be omitted if the attribute is a known [boolean attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#boolean_attributes), so `custom="true"` is expected. However, `data-custom` (without value) seems odd to me because it's not known to be a boolean attribute.
> 
> Support for omitting the value if `true` for `data-*` was added in [b958088#diff-3974ff1a07864eae3cb91ceefef360fbc39db051f8036ee2504b9be00764e0ccR226](https://github.com/withastro/astro/commit/b958088c3dbabc43f698ff6684e6d54a8ec189f4#diff-3974ff1a07864eae3cb91ceefef360fbc39db051f8036ee2504b9be00764e0ccR226) by [@matthewp](https://github.com/matthewp), which perhaps is a bug? I think we can only omit it if the value is `""`, not `true`, which I also confirm is the behaviour from vue and svelte today.
> 
> I'm not sure how breaking this is if we change now, but in practice probably not a lot as the way to check the attributes truthiness will still work? (`hasAttribute`)


Can you help me add "popover" to the list?
