### ISSUE TITLE
`astro:env` not allowing numbers in variable names

### ISSUE THREAD

**Issue by NuroDev** [withastro/astro#11430]
### Astro Info

```block
Astro                    v4.11.3
Node                     v20.12.2
System                   macOS (arm64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
```

### Describe the Bug

I originally opened this [as a discussion](https://github.com/withastro/roadmap/discussions/972) as I assumed this was intentional but apparently this seems more like a bug.

In short: Currently if you try to add an environment variable with any kind of number in the name it will throw the following error:
```bash
[config] Astro found issue(s) with your configuration:
  ! experimental.env.schema.S3_ACCESS_KEY_ID  A valid variable name can only contain uppercase letters and underscores..
```

For the most part numbers in variables names do not make sense. However in some cases, like the one above with S3 credentials, it would be good to still all numbers in variable names.

### What's the expected result?

For the `A valid variable name can only contain uppercase letters and underscores..` validation error above not to get thrown whenever a environment variable name includes a number.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pudfny?file=astro.config.ts

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
Thanks! Yes actually we only want to prevent the first character being a number because it's not a valid identifier. Code happens here:

- https://github.com/withastro/astro/blob/main/packages/astro/src/env/schema.ts#L84
- https://github.com/withastro/astro/blob/main/packages/astro/src/env/schema.ts#L87-L89

It's probably worth
1. Creating a dedicated schema for the key
2. Adding a few tests here https://github.com/withastro/astro/blob/main/packages/astro/test/units/config/config-validate.test.js

**Comment by NuroDev** [comment]
Good idea. For a dedicated Zod schema would it be better here to stick with a Regex pattern, which would likely be faster but performance isn't as critical here, or adding multiple refinements (`.refine()`) to add granular error messages for each requirement?

**Comment by florian-lefebvre** [comment]
Lets go with refine calls! I'm in favor of clearer errors
