### ISSUE TITLE
`/_image` Endpoint fails to return image when using trailingSlashes in vercel.json

### ISSUE THREAD

**Issue by vntw** [withastro/astro#11568]
### Astro Info

```block
Astro                    v4.12.2
Node                     v18.20.3
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             none
```

### Describe the Bug

Deploying to vercel using `output: "hybrid"`, `prerender = false` in the page and defining `trailingSlash: true` in the `vercel.json` in combination with the injected `/_image` endpoint will fail to return an image. The image URL will be redirected from the default image src `/_image?href=…` to `/_image/?href=…` producing a 404 error.

The Astro Image/Picture component also ignores the trailing slash handling so there will always be a redirect in this scenario (if vercel can't be taught to ignore this endpoint).

My GitHub reproduction link also includes a vercel deployment link.

### What's the expected result?

The image should always be returned, whether there's a trailing slash configured or not.

Not really bug related but ideally, the image src links should be generated with/without a trailing slash (whatever the Astro setting says?) to avoid a redirect for every image.

### Link to Minimal Reproducible Example

https://github.com/vntw/astro-repro-vercel-image-trailing-slash

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This has been fixed in Astro 5, unfortunately it is not possible to backport the fix due to how it's been implemented with tandem with the new `image.endpoint.route` option allowing one to customize the endpoint.

If you really need this in Astro 4.x, a possible workaround is to use a custom image service and hardcode it so the `getURL` hook uses a trailing slash (or not, depending on your need)
