### ISSUE TITLE
💡 RFC: hydrate on component interaction

### ISSUE THREAD

**Issue by e111077** [withastro/astro#1160]
### Background & Motivation

Hydrate a component on interaction for those components that are generally visual but not often interacted with.

#### Use Cases

* An image component that will animate when clicked
  * It is visible via SSR which is 👍 
  * only really needs hydration on pointerenter
* A profile menu card when hovering over a profile picture
  * Menu will never be visible on initial render as it's always closed
  * Menus tend to have a lot of JS associated with them and might not want to pass that to the user
  * This component may be visible across many pages but really only ever interacted with very few times if at all per page
* Serving the absolute minimum bundle size to a user but still have the full JS experience
  * Users in regions with high data costs
  * They only download what they are interacting with

### Possible solutions

A client hyrdation directive:

```jsx
<component client:interaction="pointerenter,focus" />
```

in which the directive will hydrate on a set of given "interaction" DOM events such as `click`, `focus`, `[pointer|mouse|touch][enter|down]`.

### Alternatives considered

Google internally has a hydration scheduler like this coupled with something called incremental DOM (see qwik js from Builder.io, it's literally that), but it's quite a hassle to implement as it gives the component authors JS hooks to control hydration making it much more powerful, but similarly leaky and painful to implement components.

### Risks, downsides, and/or tradeoffs

* Adds more JS to a page's initial load
* Might lead to clicks of frustration depending on how long the hydration is
* Idle simply might be a better case for this

### Open Questions

* What's a good root to listen to events
* What is an "interaction" does data system or server interaction count as one?
  * This may be a case for a better name than "interaction" like "event" 
* What should happen on a failed hydration (network down) Try again? Will listeners be cleaned up?

### Detailed Design

Could be implemented quite similarly to [`client:visible`](https://github.com/snowpackjs/astro/blob/main/packages/astro/src/frontend/hydrate/visible.ts#L29)

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by jasikpark** [comment]
How well would code splitting with conditional imports work to solve this?

i.e. load the component on client:idle, and then run an "user interacted for the first time" event that does `const m = await import('n');` so you can load the expensive js?

**Comment by e111077** [comment]
That could work, and I'm quite ignorant on the history of Astro development, but why include `client:visible` with Astro if the same could be done there?

I added a bit more on the discussions channel on a thread Fred started where this directive can help in cases where you're working in a market with high data costs. `client:interaction` could help provide the absolute minimum number of bytes over the wire as it can likely load only the bytes required to use the site.

**Comment by matthewp** [comment]
I think the directive makes sense. Doing it manually is essentially what Astro's renderers already do.

**Comment by e111077** [comment]
Alternatively, (even larger project) there could be a way to extend the hydration directive syntax so that a user can define their own on the Astro side.

Please correct me if I'm wrong, but the way for a user to make their own "directive" is to manually include an `import` via a script with `client:idle`, or an astro directive for the hydration behavior can exist. The cleaner implementation here to me is for the user to write their own hydration directive since `client:idle` wouldn't be semantically communicating the actual method of hydration.

Though I can see these features fit more with a major release in the future since it seems like it'll require quite a lot of work rejigging the architecture and a user-friendly api would have to be designed.

**Comment by matthewp** [comment]
@e111077 yeah, user-defined hydrators has come up a couple of times but we don't have a design for it. Happy to take a look at a new RFC for such an idea. In the meantime this is worth discussing on an RFC call as a standalone thing.

**Comment by matthewp** [comment]
RFC:

* Do not have consensus at this time.
* Some questions about how you show loading state between the time the user interacts and the time the code is loaded. For example, would the hydrator set a class on the element that could be used to show a loading state?
* The example shows `hover` which is not a DOM event. The assumption we had is that this hydrator would only support built-in DOM events, is that correct?
* It would be great to have more specific use-cases. Is the idea to save data for components that might *never* be rendered? It would be good to get clarity here.

Happy to talk about this again in a future call when these ideas are fleshed out.

**Comment by e111077** [comment]
Heya sorry this is late, I've cleaned up this RFC a bit. To tackle some of the questions. On the topic of loading state, I think this is out of scope for this RFC, and that question could extend to all of the hydrators and SSR hydration in general. I think the question around Astro providing the user a hint that hydration is happening is generally just a question on the weight of lazy hydration. I can see someone having clicks of frustration if they have a sufficiently slow connection.

Regardless I'd definitely be in favor of Astro giving the user hints that hydration is happening whether it be a class or a condition for `.astro` files.

Though this is a bit less of an issue with custom elements have the `:defined` selector. e.g.:

```
.selector:not(:defined) {
  &:hover,
  &:focus,
  &:focus-within {
    /* loading styles */
  }
}
```

which can work for hydrators such as `client:interaction="focus,pointerenter"`

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
