### ISSUE TITLE
📘 DOC: Remove the pages doc 

### ISSUE THREAD

**Issue by n7trd** [withastro/astro#1161]
The site https://docs.astro.build/core-concepts/astro-pages describes "pages" as:

> Pages are a special type of Astro Component that handle routing, data loading, and templating for each page of your website. You can think of them like any other Astro component, just with extra responsibilities.

Data loading and templating are already described on other docs sites. And data loading and templating also works outside of the pages folder. 

Routing has also it's own page. There is also a description of the special pages folder an it's implication/workings with .astro & .md components. 

So as i see it, "pages" is just a special folder but not an "Astro component, ... with extra responsibilities."  Thinking of a page as a special kind of astro component could be a bit misleading.

**Comment by FredKSchott** [comment]
That's a good point, we really have fleshed out each section into other parts of the docs site.

`src/pages` is such a key concept though, I do feel like it's important to give it its own section, with the exception of "Page Templating" which does explain some special, page-only rules.

Maybe the page itself should be rewritten? One issue that is separate but related is that `getStaticPaths` is only described in "API Reference", but there's no good "guide" content about it on the site. Maybe we could add that to the Pages page?

**Comment by aFuzzyBear** [comment]
I could take a look at that if you would like

**Comment by n7trd** [comment]
Yes, an intro to `getStaticPaths ` outside of the API doc would really be helpful.

> with the exception of "Page Templating" which does still explain those special, page-only requirements.

Is there a different behavior with html, head, doctype if the .astro component is in some other folder then pages?

**Comment by FredKSchott** [comment]
yea, only `src/pages` will ever be required to have `<html>`, `<head>`, etc. Although any component CAN have `<head>` and `<body>` (we see this in layouts, for example) so maybe this is less of a technical point and more of a "explaining how Pages work conceptually) thing.

Okay, so I think what this thread has made me realize is that we should use it to talk about CONCEPTUALLY what a page is. I think that could look something like:

- Talk briefly about routing, and link to the routing page for more info
- Talk briefly about getStaticPaths, and when you might need it, and link to the API reference for more info
- Talk about the expectation that a page should have an `<html>`, `<body>`, and `<head>` element
- Talk about recommended patterns for pages (mention layouts, mention the pattern of using a `<CommonHead>` component, etc.)

That feels like a really nice improvement on what we have today. @n7trd are you interested in tackling? Otherwise @aFuzzyBear it's all you!

**Comment by n7trd** [comment]
I feel more capable to contribute the german translation a afterwards :sweat_smile:

**Comment by jonathantneal** [comment]
This has since been resolved in docs. Tracking on this was lost. Thanks, all!
