### ISSUE TITLE
 Cursor Flickers Between Pointer and Arrow During Route Transitions with `astro:transitions`

### ISSUE THREAD

**Issue by EveSunMaple** [withastro/astro#11672]
### Astro Info

```block
因为这不是一个构建问题而是一个样式问题，所以 Astro 并没有报错信息。

This is a style issue rather than a build problem, so Astro does not provide any error messages.

Astro                    v4.13.1
Node                     v20.15.1
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         astro-icon
                         @astrojs/sitemap
                         @astrojs/tailwind
                         @playform/compress
                         pagefind
```

### Describe the Bug

使用 `astro:transitions` 在站内切换路由时，鼠标指针样式会闪烁。这个问题在 Astro 项目中普遍存在，比如 https://astrofy-template.netlify.app/ 和 https://astro-paper.pages.dev/

When using `astro:transitions` for internal route switching, the cursor style briefly flickers between the pointer (hand) and the arrow cursor before stabilizing to the pointer. This issue is observed in Astro projects such as [Astrofy Template](https://astrofy-template.netlify.app/) and [Astro Paper](https://astro-paper.pages.dev/).

### What's the expected result?

在站内切换路由时，鼠标指针样式保持手形直到页面加载完成或者移开按钮。

The cursor should remain as a pointer (hand) during internal route transitions until the page has fully loaded or the user moves the cursor away from the button.

### Link to Minimal Reproducible Example

https://frosti.saroprock.com/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @EveSunMaple, thank you so much for bringing this issue to my attention!

I have to admit, I never really considered that effect before. But once you notice it, it’s hard to unsee — and it definitely becomes a bit painful every time you encounter it.

On the other hand: Seeing an arrow instead of the expected pointer during view transitions isn’t entirely a bad thing. It signals to the user that the page is temporarily non-interactive. Even if you force the pointer to remain, clicking links won't work while the animations are playing.

While investigating this issue, I picked up a few new insights.

This effect is inherent to the View Transition API. The default arrow cursor appears as soon as the transition starts and remains until the final animation ends. During view transitions, the screen may look like your HTML, but what you're actually seeing are bitmaps / screenshots (the View Transition pseudo-elements). As a result, normal styling doesn't work. Even the browser's built-in stylesheets, which know to apply a pointer cursor to buttons and links, fail here because what you see only _looks_ like buttons and links, but they aren’t.

Setting the cursor on the pseudo-elements doesn’t seem to work either. However, one approach to minimize the cursor switching and drastically reduce flickering (though not completely eliminate it) is to set the cursor on the `:root` element just before the transition starts and remove it immediately after the animations end. The timing here is crucial because this approach will make the cursor a pointer across the entire page. But for the brief 100 milliseconds of the view transition, this should be acceptable.

Hope that helps.

Inspired by your issue, I added a new component to the [Bag of Tricks](https://www.npmjs.com/package/astro-vtbot) with the correct timing. You can find the documentation [here](https://events-3bg.pages.dev/library/PointerOnNavigation/) and check out a live demo [here](https://events-3bg.pages.dev/jotter/), where the component is used on the navbar of the Starlight pages.

I close this issue, because it is not really related to Astro.

**Comment by EveSunMaple** [comment]
Thank you for the detailed explanation and insights, @martrapp! 🌟
﻿
I completely understand that this issue is more related to the View Transition API rather than Astro itself. I've already addressed the flickering issue by implementing a solution using Swup, which successfully minimized the cursor switching during transitions.
﻿
I appreciate your guidance and the new component you’ve introduced. I'll definitely check it out!
﻿
Thanks again for your help, and I’m glad we could learn from this experience together!

**Comment by martrapp** [comment]
Yes, Swup can be a good alternative here!

**Comment by posti85** [comment]
For anyone facing this related problem: I had a similar issue while using a custom cursor image for my whole app. The cursor becames the default OS one while view transition is being applied. I solved it with a suggestion mentioned in one of the links @martrapp shared:
```
:active-view-transition {
  cursor: url(...) 10 10, auto;
}
```
