### ISSUE TITLE
Cross-collection references are typed weird with Content Layer enabled

### ISSUE THREAD

**Issue by tylermercer** [withastro/astro#12051]
### Astro Info

```block
Astro                    v5.0.0-beta.1
Node                     v20.15.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/sitemap
                         astro-icon
                         astro-meta-tags
```

### Describe the Bug

I have two Content Layer collections, `seasons` and `episodes`. `episodes` has a `season` property that is defined as `reference('seasons')`. But doing things with that reference property is very difficult, due to it's strange type:

```
(property) season: string | {
    id: string;
    collection: string;
} | {
    slug: string;
    collection: string;
}
```

![image](https://github.com/user-attachments/assets/19f05240-da31-46fb-a51e-93ef9761320b)

For example, even though [the docs](https://5-0-0-beta.docs.astro.build/en/guides/content-collections/#accessing-referenced-data) say I can pass this reference property into `getEntry` directly, I'm unable to do so without getting a cryptic type error:

![image](https://github.com/user-attachments/assets/ebe32f73-495d-4131-8125-25c717a24c1d)

Is this the expected type?

### What's the expected result?

The reference property is a type that is both usable in itself without a manual typecheck (e.g. a string or a clearly defined object, but not a union of the two), and it can be passed to `getEntry` without a type error.

### Link to Minimal Reproducible Example

https://github.com/tylermercer/astro-12051-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ascorbic** [comment]
Hi, can you share your content config or ideally share a minimal repro

**Comment by tylermercer** [comment]
Here's a repro: https://github.com/tylermercer/astro-12051-repro. Instructions are in the README.

**Comment by ascorbic** [comment]
Thanks. The issue is that you're using `reference` inside the loader. While this does work, it's more limited (and we need to document this). It's not able to use the inferred type of the other collection because of how types are generated from schemas in loaders. Loaders don't know anything about other collections, and they're meant to be isolated. This is why it's returning a generic type for the reference. If you move it up into the content config file then it works. I'm going to leave this open because I would like to remove that limitation, but it would still be an anti-pattern to include references inside the loader.

**Comment by tylermercer** [comment]
That worked, and makes sense! Thank you for your help.
