### ISSUE TITLE
With Content Layer API, fsPath is no longer part of schema image data object

### ISSUE THREAD

**Issue by anarion80** [withastro/astro#12155]
### Astro Info

```block
Astro                    v4.15.9
Node                     v20.10.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/sitemap
                         astro-dynamic-import
                         auto-import
                         @astrojs/mdx
                         astro-icon
```

### Describe the Bug

Essentially the same as https://github.com/withastro/astro/issues/12136

With a collection defined using Content Layer loader:

```javascript
const blog = defineCollection({
  loader: glob({ pattern: '**/*.md*', base: './src/data/blog' }),
  schema: ({ image }: SchemaContext) =>
    z.object({
      heroImage: image().or(z.string()),
    }),
});
```

the resulting heroImage object does not have `fsPath` like previously with content collections:

```javascript
{
  src: '/_astro/image.Duq8VBCM.png',
  width: 29,
  height: 29,
  format: 'png'
}
```

I have the same situation with Astro 4.15.9 using experimental flag for `contentLayer` or using 5.0 beta without the experimental flag.

Minimal reproduction shows the console dump for the image.

### What's the expected result?

`fsPath` is still there"

```javascript
{
  src: '/_astro/image.Duq8VBCM.png',
  width: 1920,
  height: 1080,
  format: 'jpg',
  fsPath: '/fs/repo/path/src/content/blog/_images/test/image.png'
}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ngcwe1?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
`fsPath` was intentionally never added to types or documented, as it was always intended to be an internal detail more than an actual API. What is your use case with it?

**Comment by anarion80** [comment]
Accessing the file to darken it and blur and then use as background for og image generation.

My current workaround is use the `src` which is available like this:

```javascript
originalImagePath = `dist${page.heroImage.src}`;
```

**Comment by tylermercer** [comment]
I have the same use case. I've got build-time-rendered OG images on https://evelynescobar.art that depend on the fsPath behavior (since it was the only way to get the actual file path of the image from the content collection entry).

This means I can't upgrade that site to Astro 5 because fsPath is undefined for certain collections' images in Astro 5.

It also means adding OG images to my sites that _are_ on Astro 5 is blocked unless I use something like patch-package to expose fsPath again. It'd be amazing if fsPath was made a first-class API member instead, so I don't have to do that!
