### ISSUE TITLE
Component renders twice using islands (islands, nanostores, react)

### ISSUE THREAD

**Issue by karlludwigweise** [withastro/astro#12198]
### Astro Info

```block
﻿Astro                    v4.16.0
Node                     v22.2.0
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### Describe the Bug

When 

* using `nanostores` to set a value (with `client:load`)
* using another component to retrieve the value (with `client:load`) and passes it to children

the component is rendered twice.

The first component is not a rehydrated island and stays static.
The second component fails to replace the first one.

### What's the expected result?

The component is rendered once after rehydration and interactive.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/karlludwigweise/astro-render-twice-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
I don't understand what is not working as expected, it looks fine to me. Could you provide some more detailed steps and explanations?

**Comment by karlludwigweise** [comment]
Yes, sure.

The visual result after 2 seconds (delay for demonstration purposes) is that I'm getting:

<img width="208" alt="Firefox Screenshot with faulty rendering" src="https://github.com/user-attachments/assets/4b796367-c4e7-4b05-bf62-bf98325fabd3">

What I'm expecting is:

<img width="211" alt="Expected" src="https://github.com/user-attachments/assets/81ca04ef-0c86-4beb-aa72-32783771198f">

* The brand name should have been updated to "Example 2"
* The toggle should toggle the boolean value behind it.

**Comment by karlludwigweise** [comment]
I should add that this issue appears not on 100% of page loads. But well above 50% in my experience.

**Comment by ematipico** [comment]
I don't believe it's an Astro bug, but how React decides to render the components and how you decided to pass the props. You're essentially injecting a `store` by importing it as a module and use it. Plus, the two components aren't really connected among them, so the store is manipulated by each component without knowing about each other.

You should use a context, so the two components consume the same store and are synch.

Closing because it's not something that Astro should be aware of.

**Comment by karlludwigweise** [comment]
> Plus, the two components aren't really connected among them, so the store is manipulated by each component without knowing about each other.

It's actually 
* one island writing data and 
* the other consuming it + having it's own state (with other data)

Isn't that why [nanostores are recommended for shared client-side storage](https://docs.astro.build/en/recipes/sharing-state-islands/#why-nano-stores)?

I did some more research here. I found:
1. if the `Island.tsx` returns `null` (at some point in time) it will always render twice
2. if the `Component.tsx` (any sub-component) returns `null` (at some point in time) it will occasionally render twice

If this is an Astro bug, you will know better then me.

But as a developer my expectation is that I can render `null` at some point and if my return value changes the component is not duplicated. Unlike with React I also cannot set a `key` for the component to tell it it's the same.

**Comment by florian-lefebvre** [comment]
What if you render an empty fragment? I think we had such case in the past

**Comment by karlludwigweise** [comment]
Fragments drop the felt likelihood of two components rendering from 95+% to maybe 80%. I think similar to occasionally rendering twice like mentioned above.

**Comment by Fryuni** [comment]
> > Plus, the two components aren't really connected among them, so the store is manipulated by each component without knowing about each other.
> 
> It's actually
> 
> * one island writing data and
> * the other consuming it + having it's own state (with other data)
> 
> Isn't that why [nanostores are recommended for shared client-side storage](https://docs.astro.build/en/recipes/sharing-state-islands/#why-nano-stores)?

The keyword here is _client-side_ storage. By using `client:load`, those components are rendered on the server and then hydrated on the client after the page loads.

The store is being shared across requests, making the value used on the server and the client get out of sync and tripping react.

You can add this code on your `stores.ts` to see it being updated on the server:
```ts
brand.subscribe((value, oldValue) => {
  console.log('Server changed:', {value, oldValue});
});
```

After the first run, the value is the "Example" brand, which was set by the `Stores` component.
When the page is rendered again, the `Island` component will render on the server with the "Example" brand but be hydrated on the client with `null`. Since the `null` case results in not rendering anything, React won't look for matching elements to update and just create new ones.
React expects the server render and the first hydration execution to produce the _exact_ same output to match the HTML of both and add the interactivity.

The very first FAQ item on the section you linked is about using Nanostores on server-side components not being recommended.

You can read Nanostores on the server for the initial render but you should only _change_ the Nanostore on the client. The simple fix here would be to change the `Stores` component to use `client:only="react"` instead of `client:load`.

As an alternative, I made [Request Scoped Nanostores](https://inox-tools.fryuni.dev/request-nanostores) that solves this limitation of Nanostores and allow setting the value on the server without messing things up.

**Comment by Fryuni** [comment]
Another point that make this hard to debug and fix is that the dev server will only reload the changed modules. So fixing `index.astro` won't reset the state of the `stores.ts` module, keeping it with the broken value. You have to restart the server to clear up unintended global state like this.

**Comment by Fryuni** [comment]
The inconsistency is due to the race condition between both components. If the hydration of the `Stores` component runs first then the state of the store on the client will match the server by the time the `Island` component hydrates, making the output match and the problem vanish.

Both hydrations use separate requests for the scripts so the race is at the network level.

**Comment by karlludwigweise** [comment]
Thank you @Fryuni.

I went with allowing everything to be `null` or `undefined` for now, as it's a quicker fix for me (works in production but only in 80% of cases locally excl. hot reload). Will revisit later.
