### ISSUE TITLE
💡 RFC: Global caching system

### ISSUE THREAD

**Issue by okikio** [withastro/astro#1220]
### Background & Motivation

In https://github.com/snowpackjs/astro/issues/706#issuecomment-904963705 I discussed a global caching system that would allow users to avoid having to fetch content multiple times, I wish to expand more on this concept here.

I feel we should have a separate caching system for things that we want all components to have access to no matter what, this cache is only cleared if a file is renamed, moved, or deleted, this should allow for less duplication, and should also avoid multiple fetch requests, but this should be it's own RFC, so, I'll try to create a separate RFC for this. 

### Possible solutions

A possible solution is to have an object set at `Astro.global.cache`, where all components and pages can cache content they expect to be long lived, and to last past multiple page requests. The global cache will on be cleared if a file is renamed, moved, or deleted.

### Alternatives considered

Build upon Temporary Page Storage https://github.com/snowpackjs/astro/issues/706#issuecomment-904963705 and strictly restrict all storage to a by page solution to avoid stale cached content.

### Risks, downsides, and/or tradeoffs

The biggest obstacle to this proposal is the potential of stale cache which cause errors, and are hard to debug.

### Open Questions

Does we need this in Astro right now? Which possible solution do devs most prefer?

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
I'd love to hear the pros and cons of this system vs. #694!

**Comment by okikio** [comment]
@FredKSchott `Astro.defineOnce` doesn't really specify how you save data into storage nor does it tackle cache invalidation. #694 isn't really a competitor to this suggestion, in fact, I'd argue, RFC #694 is overworked and is trying to do what #706 and this proposal are trying to do, but at the same time.

**Comment by eyelidlessness** [comment]
> The biggest obstacle to this proposal is the potential of stale cache which cause errors, and are hard to debug.

Cache invalidation is one of the Four Hard Problems of computer science (along with naming things and off-by-one errors). I think it's probably better to defer as much of that as possible to userland (where you know the cache validity much better than the tool).

Example: I almost added an exception, where it could be considered safe to cache idempotent (ie GET) requests during a single build cycle. But that doesn't account for a complex build that also makes side-effecting calls that **should** invalidate the idempotent request. And there's no way to know at the tooling level whether that occurred.

Without even reading through the memoization issue linked by @FredKSchott, I can already say it's probably a better general approach. Astro users should have control of determining the staleness of their data and how much that matters.

**Comment by eyelidlessness** [comment]
@okikio responded while I was writing, and I looked at the memoization issue after. I agree it also doesn't address this concern.

I think the actual solution is to treat Astro modules like any other ESM module, which is to say they're imported and executed once per request cycle. Global/shared state left up to users, all caching of imports invalidated per build cycle.

Astro can't and won't know enough about your cache to get this right, and it's beyond the scope of any framework to try.

**Comment by okikio** [comment]
The caching mechanism isn't for Astro to know, it's for developers to tell. 

I apologize, I wasn't very clear on how the caching mechanism would work. 

By default Astro doesn't try to cache, you as the dev store the content you want to be cached globally in the `Astro.global.cache` with the understanding that renaming, deleting, moving or other file management events.

In extention,  I'm also thinking we should use `Map`'s for the cache object.

**Comment by eyelidlessness** [comment]
If it's all evicted on save/build that seems perfectly reasonable to me. If there's some effort to caching across build cycles I think it's safer to defer to userland.

**Comment by natemoo-re** [comment]
Just commenting to point out @eyelidlessness' phenomenally subtle joke here! 😂

> Cache invalidation is one of the Four Hard Problems of computer science (along with naming things and off-by-one errors).

**Comment by jasikpark** [comment]
issa good joke :)

**Comment by okikio** [comment]
It can still be manually cleared by users, by simply reseting it, e.g. `Astro.global.cache.page = "markdown content..."`, this can be reset by do this, `Astro.global.cache.page = null`.

**Comment by okikio** [comment]
> Just commenting to point out @eyelidlessness' phenomenally subtle joke here! 😂
> 
> > Cache invalidation is one of the Four Hard Problems of computer science (along with naming things and off-by-one errors).

Yeah, @natemoo-re I don't get the joke

**Comment by jasikpark** [comment]
[cache invalidation, naming things, off-by-one errors] = four hard problems of computer science xD

**Comment by okikio** [comment]
@jasikpark oh so cache invalidation twice

**Comment by jasikpark** [comment]
or an off by one error 4 != 3

**Comment by okikio** [comment]
Oh, LOL

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
