### ISSUE TITLE
View Transitions: Client-loaded content not restored on previous pages

### ISSUE THREAD

**Issue by camdowney** [withastro/astro#12237]
### Astro Info

```block
Astro                    v4.16.5
Node                     v21.7.3
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### Describe the Bug

When navigating away from a page with client-loaded content and then clicking the browser back button, the original content and scroll position are not restored.

To observe this in the repro, please scroll to the bottom of the home page, click a post, then click the browser's back button.

### What's the expected result?

Client-loaded content (and scroll position) on previous pages should be restored.

Note: This may not be a bug, but rather an unimplemented feature. Either way, I believe restoration of the previous page to its exact state before swap is a massive UX win. This is the default for MPAs (including Astro without View Transitions) and ideally should be the same with View Transitions as well.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/camdowney/astro-view-transitions-bug-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @camdowney the combination with `client:load` is a interesting setting.
Thank you for this example.
I agree that the behavior should be as similar as possible with or without view transitions and at least when I just tried after removing `<ViewTranitions/>` from your Layout, the behavior is consistent. Right after the navigation, your index page is just to short for scroll position restoration. 

You could wait for the island to be rendered at the client side and then scroll to the previous scroll position. But that is a bit complicate and error prone. A simpler solution that might give you the desired effect is to enlarge the page enough for the scroll restoration to succeed and let the client-side rendere do its thing independently.

Please try to add the follwoing script to your global layout:

```html
<script>
  document.addEventListener("astro:before-swap",(e) => {
    if (e.navigationType === "traverse") {
      e.newDocument.body.style.minHeight = `${history.state.scrollY + innerHeight}px`;
    }
})
</script>
``` 

Does this help for your situation?

**Comment by camdowney** [comment]
Hey @martrapp thanks for the possible solutions!

Unfortunately, this wouldn't work in the case of the app I'm building in which I originally encountered this issue. I essentially have an infinite scroll feed of posts and would like the user to be able to navigate into posts without losing their spot in the feed. So imagine my repro, except the list of posts could be much longer based on how far the user scrolls; there's no point simply waiting for the initial set of posts to load and/or restoring the previous scroll position. We need the page exactly as it previously was.

The issue is less the lack scroll restoration (though it is a side effect), and more the fact that the entire page's client-side structure is re-rendered rather than loaded from history. In my case, it makes View Transitions unusable (which isn't the end of the world, since Astro is still fantastic without it).

**Comment by martrapp** [comment]
Yes, from your original wording I was afraid there is more to your real issue than scroll restoration.

And yes, view transition and client rendering do not fit together well because the DOM needs to be there when taking the snapshots for the transition. Switching from `<ViewTransitions />` to browser-native cross-document view transitions would not help here either.

But here is an idea that could work well in your case: Instead of rebuilding the post list after navigation, maybe you can just keep it across navigation? Here is how to do this with Astro:

In `index.astro` add `transition:persist="posts"` to the list:
```
  <Posts client:load transition:persist="posts"/>
```
and in the posts, at the end of the page, provide an invisible park position where the list can be stored until the user navigates back:
```
<Layout>
  ...
  <div style="display: none;"><div transition:persist="posts"/></div>
</Layout>
``` 
(https://docs.astro.build/en/guides/view-transitions/#maintaining-state)
Do you want to give that approach a try?

**Comment by martrapp** [comment]
I saw that you opted out of view transitions by setting `<html lang="en" transition:animate='none'>`.

Don't you want the post list entries to morph into the post page?

**Comment by camdowney** [comment]
@martrapp Interesting, I think your approach would indeed solve my original issue. Though there are ultimately a ton of components that I'd like to maintain their state when navigated back to across various pages, so this solution would likely immensely increase in complexity over time.

Sorry to keep expanding the scope on you haha. I just can't help but think that as long as we're not restoring previous pages to their exact state from history, no approach can be considered complete. But I don't have enough knowledge to determine whether that's realistic or even possible for Astro.

I actually did a bit more research and found many client-routed web apps that don't bother restoring previous pages either. Or they're inconsistent about it, e.g. YouTube. Even the app I'm building (still in MPA mode) doesn't restore properly in Chrome, though it does in Firefox which is what I mainly use.

I'm a bit disturbed and wondering how the heck we/browsers are getting away with this horrible UX flaw. Maybe I just need to give up on it. Or maybe there's something I'm missing.

As for the transition animations, I found they didn't work in Firefox so I just disabled them to keep things consistent. I also feel that animations would defy user expectations, and they'd probably just want things to be more snappy.

Let me know if you have any further thoughts. Otherwise I'll probably just close this issue and take the loss here. I greatly appreciate your time so far nonetheless!

**Comment by martrapp** [comment]
> I found they didn't work in Firefox so I just disabled them to keep things consistent

Yes, that is understandable.

I liked your example as it goes beyond the ordinary. But I can also empathize with your distress that it behaves so stubbornly, even without view transitions. Good luck on your future experiments!

**Comment by aleclarson** [comment]
I'll share my own experience with this, in case it would benefit someone. I'm holding on to the most recent DOM element containing the client-loaded home feed, then I use `astro:before-swap` to append the elements to the new document. It seems to work.

```ts
// ...more stuff before this...

loadHomeFeed(document)

document.addEventListener('astro:before-swap', ({ newDocument, to }) => {
  if (to.pathname !== '/') {
    return
  }
  // Append old home feed to the new document, unless it's been >3
  // hours since the first page was loaded.
  const date3HoursAgo = subHours(new Date(), 3)
  if (date3HoursAgo > firstPageLoadedAt) {
    loadHomeFeed(newDocument)
  } else {
    const newContainer = newDocument.getElementById('home-feed')!
    for (const child of Array.from(container.children)) {
      newContainer.appendChild(child)
    }
    container = newContainer
  }
})
```

I have the above logic in a `<script>` in an Astro `src/pages/` component where I also have the `<div id="home-feed" />` element. The `loadHomeFeed` function fetches some HTML and appends it to the `#home-feed` element, while also caching a reference to it in memory for future `before-swap` events.

It's not a perfect solution, since only one instance of the home feed is kept in memory, so all navigations to the home page will have the same state, which might not be ideal for some people, but it's good enough for me.
