### ISSUE TITLE
Matthew Phillips is unprofessional... 

### ISSUE THREAD

**Issue by technologyconsulting** [withastro/astro#12251]
### Astro Info

```block
Basic np create astro@latest
```

### Describe the Bug

Matthew Phillips thinks and uses his so called contributor power unprofessionally. 

### What's the expected result?

Professionallism at all times. Pride in the product you support. 

### Link to Minimal Reproducible Example

Https://Matthew-Phillips

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by yanthomasdev** [comment]
Hey @technologyconsulting, we (the moderation team) have decided to close both of your issues and ban you from the `withastro` organization on GitHub and Discord for violating our [Code of Conduct](https://github.com/withastro/.github/blob/main/CODE_OF_CONDUCT.md). You can also read about our [moderation process](https://github.com/withastro/.github/blob/main/GOVERNANCE.md#moderation) during said violations.

This has been decided because you were [warned in the first issue](https://github.com/withastro/astro/issues/12247#issuecomment-2419938416) for not respecting our bug report process, and instead of continuing the issue as we suggested, decided to make comments that go against our [Code of Conduct's documented standards](https://github.com/withastro/.github/blob/main/CODE_OF_CONDUCT.md#our-standards).
