### ISSUE TITLE
Conditional <style> tags in components do not get scoped

### ISSUE THREAD

**Issue by JaneSmith** [withastro/astro#12265]
### Astro Info

```block
Astro                    v4.16.6
Node                     v20.18.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

In Astro, styles are supposed to be automatically scoped by default, so that they only apply to the component that they are declared in. [The docs](https://docs.astro.build/en/guides/styling/) have this to say:

> Astro `<style>` CSS rules are automatically scoped by default. Scoped styles are compiled behind-the-scenes to only apply to HTML written inside of that same component. The CSS that you write inside of an Astro component is automatically encapsulated inside of that component.

> Scoped styles don’t leak and won’t impact the rest of your site. In Astro, it is okay to use low-specificity selectors like `h1 {}` or `p {}` because they will be compiled with scopes in the final output.

However, this does not seem to apply when using creating the style tags conditionally.

For example, if a component has the following code...

```
{true &&
	<style>
		p {
			background: red;
		}
	</style>
}
```

...the generated output has the following unscoped style tag:

```
<style>
	p {
		background: red;
	}
</style>
```

If we take the exact same style tag, but without the conditional check...

```
<style>
	p {
		background: red;
	}
</style>
```

...then the generated output has a scoped style tag as expected:

```
<style>p[data-astro-cid-ho6gvodc]{background:red}
</style>
```

I suspect that conditional style tags are an untested code path, as there's no mention of doing this anywhere in the documentation.

### What's the expected result?

I expect the conditional style tags to be scoped, just like unconditional ones.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/nifty-matsumoto-w67cl2?file=%2Fsrc%2Fcomponents%2FParagraph.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by gagan-bhullar-tech** [comment]
@ascorbic can you please assign it to me.

**Comment by ematipico** [comment]
@gagan-bhullar-tech it's all yours

**Comment by bluwy** [comment]
Conditional style tags do not work in Astro because the styles are hoisted to the `head`, bundled, and optimized during build, so the style tags need to be exist statically in the config for Astro to pick it up and process it. If you use a dynamic syntax like this, the compiler will treat it as non-static and opt-out of processing it, hence it's not scoped and the style tag ended rendering where it's declared instead of being hoisted to the `head` etc.

I think we should be updating the docs to mention dynamic syntax does not work instead. I'd suggest opening an issue at https://github.com/withastro/docs to track this change. I'll close this for now.
