### ISSUE TITLE
Hello Astro Theme- Nested Side bar Issue

### ISSUE THREAD

**Issue by sreejithkalarikkal** [withastro/astro#12293]
### Astro Info

```block
Hello Astro Theme
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

How to add nested sidebar in hello astro theme .We need to a side bar similar to Starite theme.
We need to add a folder inside another folder and display thet in side bar like Stralite.
Currently this is not supported .We are getting an error while adding new folder as below.
```Expected "slug" to match "[^\/#\?]+?", but got "test-folder/page-4"```

### What's the expected result?

Nested Side bar

### Link to Minimal Reproducible Example

Nil

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sreejithkalarikkal** [comment]
Please use the below git repositor.

https://github.com/hellotham/hello-astro.git

**Comment by ematipico** [comment]
@sreejithkalarikkal 

The error you see is very specific, so I ask you to give us specific instructions. "Create a file" or "create a folder" don't work. Where did you create them? What's their name? Maybe add them to the repository, so we can see the error ourselves

**Comment by ematipico** [comment]
Also, create a minimal reproduction, we don't accept projects because they are too big and difficult to debug.

**Comment by Princesseuh** [comment]
slashes are not allowed in URL params, since with content collections the slug is generated using the folder path and your article is nested, a slash is present. 

You need to either set a custom slug in the frontmatter of the content in that folder, or the theme needs to sanitise the slashes if it's meant to handle nested folders. Either way, this is not a bug in Astro.
