### ISSUE TITLE
Problem with "astro:page-load" and script re-execution.

### ISSUE THREAD

**Issue by dav-leda** [withastro/astro#12494]
### Astro Info

```block
Astro                    v4.16.14
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/mdx
                         @astrojs/sitemap
                         astro-icon
                         astro-icon
```

### Describe the Bug

I'm using View Transitions, wrapping event listeners inside an 'astro:page-load' event for script re-execution like so:

```js
document.addEventListener('astro:page-load', () => {
  document.querySelector('#some-button').addEventListener('click', () => {
    alert('Button clicked')
  });
});
```

When navigating **out** of the page where the event listener is, I get the following error in the browser's console:
```
Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
at HTMLDocument.<anonymous> (about.astro:19:11)
at triggerEvent (router.js?v=eff4607c:17:41)
at onPageLoad (router.js?v=eff4607c:18:26)
at router.js?v=eff4607c:334:5
```
It seems that the script is added to every page so that it gets re-executed on every navigation, but if the event listener is attached to an element that exists on just one page the element won't be found on the next page and an error will be thrown.

The [example shown in the docs](https://docs.astro.build/en/guides/view-transitions/#script-behavior-with-view-transitions) is for a Nav component that's present on every page, but that's not always the case.

This error message can be avoided with optional chaining (`document.querySelector('#some-button')?.addEventListener... etc`) however, I think this is something you might want to warn about in the docs, or refactor `router.js` to address this issue.

### What's the expected result?

No error messages in the browser's console.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4hf8r3?file=src%2Fpages%2Fabout.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @dav-leda! 👋🏼 Thank you for opening this issue.

Yes, the behavior you observed is on purpose and aligns with the documentation. The purpose of `astro:page-load` is to provide an equivalent for `DOMContentLoaded` when using `<ViewTRansitions/>` - that triggers on every navigation. If you're not using View Transitions and instead rely on DOMContentLoaded rather than astro:page-load, the same error would occur.

It can feel irritating at first when code runs even though it isn't defined on the current page. However, `<ViewTransitions/>` effectively turn the application into a single-page application in a technical sense. All event handlers for [View Transition life cycle events](https://docs.astro.build/en/guides/view-transitions/#lifecycle-events) persist intentionally across navigations. They are not reset by navigation. They had been introduced to ensure that functionality like adding event listeners, reactivating dark mode, or similar tasks can be executed across navigation.

As you already pointed out in your issue, the existence of elements varies across pages and as you suggested it is the responsibility of the listener to check whether the element _it want's to fix_ is present or not.
   
If you have ideas for improving the documentation to clarify this behavior in the docs, feel free to contribute a PR to withastro/docs. Your feedback would be greatly appreciated!
