### ISSUE TITLE
"secret server variables" are validated at build time violating the docs

### ISSUE THREAD

**Issue by wangyedev** [withastro/astro#12690]
### Astro Info

```block
Astro                    v5.0.3
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

As described in the documentation, only public environment variables are validated during build time. However, when I set an environment variable as a server secret, it is still being validated at build time, resulting in an error.

While I can temporarily resolve this by assigning a default value to the variable, this workaround is not mentioned in the documentation, and it does not seem to align with the intended behavior outlined.

<img width="793" alt="Screenshot 2024-12-09 at 15 24 39" src="https://github.com/user-attachments/assets/ade69875-6565-40db-8841-0c3831c3665a">

**astro.config.mjs**
```
// @ts-check
import { defineConfig, envField } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  env: {
    schema: {
      PORTAL_HOST: envField.string({
        context: 'server',
        access: 'secret',
      }),
    },
  },
});
```

**Error info**
```
npm run build

> @example/basics@0.0.1 build
> astro build

15:30:36 [content] Syncing content
15:30:36 [content] Synced content
15:30:36 [types] Generated 125ms
15:30:36 [build] output: "static"
15:30:36 [build] directory: /home/projects/withastro-astro-noe3rg6f/dist/
15:30:36 [build] Collecting build info...
15:30:36 [build] ✓ Completed in 163ms.
15:30:36 [build] Building static entrypoints...
15:30:37 [vite] ✓ built in 827ms
15:30:37 [build] ✓ Completed in 1.09s.

 generating static routes 
[EnvInvalidVariables] The following environment variables defined in `env.schema` are invalid:

- PORTAL_HOST is missing

  Error reference:
    https://docs.astro.build/en/reference/errors/env-invalid-variables/
  Location:
    /home/projects/withastro-astro-noe3rg6f/node_modules/astro/dist/core/build/index.js:198:7
  Stack trace:
    at async AstroBuilder.run (file:///home/projects/withastro-astro-noe3rg6f/node_modules/astro/dist/core/build/index.js:198:7)
    at async build (file:///home/projects/withastro-astro-noe3rg6f/node_modules/astro/dist/cli/build/index.js:44:3)
```

### What's the expected result?

The secret server variables should not be validated at build time.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-noe3rg6f?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
It is not validated at build time here. Indeed, you call a secret in a prerendered page and as you can see, the error is thrown while rendering static pages (`generating static routes`). In order to build static pages that use a secret, you need this secret to be set while building. Hope that helps!

**Comment by florian-lefebvre** [comment]
@pothos-dev can you provide a minimal reproduction through https://astro.new?

**Comment by pothos-dev** [comment]
I managed to localize the issue:

Since 5.0.0, `astro build` imports the middleware entry point at build time in `BuildPipeline.retrieveManifest`.
This in turn imports a server-only module that accesses an environment variable in the global scope, which is not defined at build time, and therefore crashes the build.

Previously, the middleware was merely compiled (?), not evaluated by `astro build`.

A workaround might be to not access environment variables in the root scope of a module that is imported in middleware, but wrap it in a function. But this requires us to rewrite a lot of code (our `db` is just a top-level export created on import), and is an unexpected behaviour change coming from the Astro 5 beta to release.

As an example, run `astro build` in this Stackblitz: https://stackblitz.com/edit/github-zmefz6re

**Comment by florian-lefebvre** [comment]
@ematipico I'll need your help on this one

**Comment by ematipico** [comment]
> Previously, the middleware was merely compiled (?), not evaluated by astro build.

This was never the case. The middleware has always been loaded during the build, if you have pre-rendered pages.

**Comment by ematipico** [comment]
@pothos-dev please provide a valid reproduction. It doesn't even have an environment variable

**Comment by pothos-dev** [comment]
> > Previously, the middleware was merely compiled (?), not evaluated by astro build.
> 
> This was never the case. The middleware has always been loaded during the build, if you have pre-rendered pages. This hasn't changed, AFAIK. 

Okay, but it wasn't the case if you had only server-rendered pages. Now it is the case even if you have only server-rendered pages, or no pages at all.

**Comment by ematipico** [comment]
@pothos-dev can you try this preview release an tell us if that fixes your issue? `astro@experimental--middleware-fix`

**Comment by ruohki** [comment]
not fixed. trying to build a ssr app with server output. Iam using these variables in actions and i cannot get this to work same errors as above

**Comment by florian-lefebvre** [comment]
Hi @ruohki this is an old issue, can you open a new one instead? Thank you
