### ISSUE TITLE
Content Layer based collections do not exclude pages starting with underscore (`_`)

### ISSUE THREAD

**Issue by techfg** [withastro/astro#12730]
### Astro Info

```block
Astro                    v5.0.5
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

According to the [docs](https://docs.astro.build/en/guides/routing/#excluding-pages), pages that start with an underscore should be automatically excluded from a site.  However, when using v5 Content Layer API to define a collection, pages that start with an underscore are not excluded.

This issue does not happen with v4 nor does it happen when using [v5 legacy content collections](https://docs.astro.build/en/reference/legacy-flags/#collections).

**Steps to reproduce**
1. Open [repro](https://stackblitz.com/edit/github-pdzrjo-jqkoqpvj)
2. View site root page

**Actual Result**
![image](https://github.com/user-attachments/assets/36b2cdfd-d5ee-4cfb-8099-3c71b07f7af9)

### What's the expected result?

Pages that start with an underscore should be automatically excluded from the site.

## Astro v4
[Repro](https://stackblitz.com/edit/github-pdzrjo-eukuujr3)

![image](https://github.com/user-attachments/assets/c95cfe9e-8bcc-4b4c-ae82-6cae9f1895f3)

## Astro v5 Legacy Collections
[Repro](https://stackblitz.com/edit/github-pdzrjo-qffnecew)

![image](https://github.com/user-attachments/assets/44f0494c-c943-4500-a262-3a49fde271e2)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pdzrjo-jqkoqpvj

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ArmandPhilippot** [comment]
The "Excluded Pages" section in the documentation applies to files in the `src/pages` folder. This behavior is unchanged.

But, yes, there is a difference between v4 and v5: files starting with an underscore in your content collections are no longer automatically excluded because the Content Layer API can retrieve data from many more sources. So it is not safe to expect an underscore to mean exclude that file.

If you need to exclude those files, you can do that in `src/content.config.ts` by updating your `pattern`:
```diff
-loader: glob({ base: './src/content/docs', pattern: '**/*.{md,mdx}' }),
+loader: glob({ base: './src/content/docs', pattern: '**/[^_]*.{md,mdx}' }),
```
You can see this pattern in the [v5 upgrade guide](https://docs.astro.build/en/guides/upgrade-to/v5/#legacy-v20-content-collections-api)

**Comment by ascorbic** [comment]
Yes, @ArmandPhilippot is correct: this is as designed. If you want to exclude underscores then you can put that in the glob. The goal with the glob loader is to give you the flexibility to decide what you want to include or exclude.

**Comment by techfg** [comment]
Thanks for the clarification and makes sense, appreciate @ArmandPhilippot championing [doc updates](https://github.com/withastro/docs/issues/10300) to make this clearer 😄
