### ISSUE TITLE
View Transitions data-astro-reload - not obeyed when using browser back and forward buttons

### ISSUE THREAD

**Issue by dreamstar-enterprises** [withastro/astro#12852]
### Astro Info

```block
5.1.1.
```

### Describe the Bug

I'm getting erratic behaviour when I apply data-astro-reload to an <a> tag. 
It works when clicking on the actual a tag, but not when pressing the browser forward and back buttons

### What's the expected result?

Should browser back and forward buttongs not obey behaviour attached to the <a> link?

### Link to Minimal Reproducible Example

seeabove

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @dreamstar-enterprises :wave:, Yes, that aligns with the documented behavior:
> data-astro-reload: an <a> tag attribute to [force a full-page navigation](https://docs.astro.build/de/guides/view-transitions/#preventing-client-side-navigation)

> Links with the data-astro-reload attribute will be ignored by the router and a full-page navigation will occur.

It has been that way since Astro 3.0.0. and I'm afraid, changing this now will lead to incompatibilities on existing sites.

You can get the effect you expect by 
- adding a click handler that detects the data-astro-reload attribute on the clicked link
- calls history.replaceState to set a marker for the current page
- in an astro:before-preparation listener, detect the marker and call event.preventDefault()
