### ISSUE TITLE
💡 RFC: (bug) `<style lang="scss">` should semantically be `<style type="text/scss">`

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#1294]
### Background & Motivation

In the HTML spec, the `type` attribute is meant to specify the programming language type, whereas the `lang` attribute is meant to specify the human language of the element, so I would say that this is a bug, and that we should provide SCSS and SASS support through `<style type="text/scss">` and `<style type="text/sass">`

https://www.w3schools.com/tags/att_style_type.asp
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style

Brought up by @jonathantneal in call!

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by matthewp** [comment]
I'm conflicted about this. I do understand the desire to not use a non-standard attribute like `lang` but also a couple of counterpoints:

- This doesn't get sent to the rendered HTML, so the browser (which this spec targets) isn't going to see a `type=` attribute anyways.
- Mime types are a low-level concept that I don't think a lot of developers are used to dealing with, I think this would make DX a little worse.

**Comment by jasikpark** [comment]
There's a similar pattern we can see with structured data: `<script type="json+ld">` changes the content of the script from a script to a data structure.

**Comment by FredKSchott** [comment]
I'm okay with adding support for this *if* we keep `lang="scss"` as syntactic sugar. This is pretty popular in Svelte and (I think) Vue, so I think we'd be in good company here.

I might also be okay with doing this without keeping `lang="scss"` support, if we were doing it specifically to make using Sass less easy :)

**Comment by RafidMuhymin** [comment]
Keep it simple! I agree with @jasikpark but `lang="scss"` is totally fine.

**Comment by jonathantneal** [comment]
One nit — the mime types are `text/x-sass` and `text/x-scss`.

> Private values (starting with "X-") may be defined bilaterally between two cooperating agents without outside registration or standardization.
> — [RFC1341: MIME (Multipurpose Internet Mail Extensions): Mechanisms for Specifying and Describing the Format of Internet Message Bodies](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html)

> To provide user-defined fields with a measure of safety, in name selection, such extension-fields will never have names that begin with the string "X-".
> — [RFC822: Standard for ARPA Internet Text Messages](https://www.w3.org/Protocols/rfc822/Overview.html)

Astro can safely support any number of user-land mime types by following this standard.

**Comment by jonathantneal** [comment]
Another nit — the `lang` attribute is already a [global attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) covered by [BCP47](https://www.ietf.org/rfc/bcp/bcp47.txt).

> Private use subtags are separated from the other subtags defined in this document by the reserved single-character subtag 'x'. Private use subtags MUST conform to the format and content constraints defined in the ABNF for all subtags; that is, they MUST consist solely of letters and digits and not exceed eight characters in length.
> — [Tags for Identifying Languages, 2.2.7. Private Use Subtags](https://www.ietf.org/rfc/bcp/bcp47.txt)

**Comment by FredKSchott** [comment]
Ah, great catch. This should be folded into our "finalize the attribute names that we hijack" convo that we need to have before v1.0

**Comment by matthewp** [comment]
@jasikpark I'd love to see how other frameworks manage this. If others use the mime type then I feel more comfortable doing so as well. So if you're able to research a few others that have similar support and write up what they do, that would be helpful.

**Comment by matthewp** [comment]
@drwpow is on vacation this week so I'd like to defer this to another week when he is back, since he implemented Sass support and can give more context for the current attribute.

**Comment by jasikpark** [comment]
Sounds like a plan to me 👍

**Comment by drwpow** [comment]
It’s funny; I think the original way to load Sass was to use `type="text/scss"` exactly as this RFC proposed. After discussing it internally, the major reason for change was lack of precedent; Vue and Svelte both use `lang="scss"` so it felt easier to be consistent with other frameworks.

So to compare to other similar approaches:

- **Vue**: `<style lang="scss">`
- **Svelte**: `<style lang="scss">`
- **Astro**: `<style lang="scss">` and/or `<style type="text/scss">`?
- Are there any others to consider?

**Comment by FredKSchott** [comment]
> I'm okay with adding support for this _if_ we keep `lang="scss"` as syntactic sugar. This is pretty popular in Svelte and (I think) Vue, so I think we'd be in good company here. 
> 
> I might also be okay with doing this without keeping `lang="scss"` support, if we were doing it specifically to make using Sass less easy :)

My previous comment is still more-or-less where I'm at on this! I might be a little more -1 now vs. before, if only just for the the idea of "not having two ways to do things." But if people really feel strongly I won't block consensus!

**Comment by jasikpark** [comment]
Yeah, I'm definitely less confident about this than before.. I really like the idea of actually writing correct HTML where we can though! What prompted this for me was checking out Partytown & their `<script type="text/partytown">`

**Comment by drwpow** [comment]
RFC Discusson:
- Alias could still be allowed, but we still need to agree on “the way“ to do it
    - Could also throw a warning if you used the alias
- `type` does have a different meaning for `<script>` than `<style>`
    - Need some universal approach to do this, e.g. `astro:lang="scss"`?
- Do developers remember MIME types?
- Possibly reword the RFC to move away from overloading the `lang` human language attribute to `[name]:lang` or something; not necessarily pushing _toward_ MIME types
- One possibility: using a `<Style>` component that has access to its slots (#1450)

Decision: need more possible solutions outlined; could be multiple possible ways to address this.

**Comment by FredKSchott** [comment]
Oh, I really like `astro:lang="scss"` or a similar directive!

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
