### ISSUE TITLE
💡 RFC: Make data from pages available in components

### ISSUE THREAD

**Issue by oliverlietz** [withastro/astro#1340]
### Background & Motivation

I want to be able to consume data from pages in components without passing the data down the component hierarchy.

Example:

Data is fetched and processed in `getStaticPaths()` in a page.
Same data should be used to create a navigation.

page (`[...path].astro`) -> `<header>` (`Header.astro`) -> `<nav>` (`Navigation.astro`)

Currently it is required to define a property in each component and pass it down to the child:

```
const { navigation } = Astro.props;
---
<header>
  <Navigation navigation={navigation}/>
</header>
```

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by matthewp** [comment]
HI @oliverlietz, thanks for bringing up this idea! We'll need a proposal in order to advance this into something that gets discussed on an RFC call. You might trying reaching out to people in [ideas-and-suggestions](https://discord.com/channels/830184174198718474/872579324446928896) if you don't have a proposal in mind yourself.

**Comment by jasikpark** [comment]
> HI @oliverlietz, thanks for bringing up this idea! We'll need a proposal in order to advance this into something that gets discussed on an RFC call. You might trying reaching out to people in [ideas-and-suggestions](https://discord.com/channels/830184174198718474/872579324446928896) if you don't have a proposal in mind yourself.

I feel like this could be part of refactoring `Astro.fetchContent` into something more lightweight and generally usable across frameworks.. I'm sure the move to Vite will help with it!

**Comment by drwpow** [comment]
I propose this be merged into https://github.com/snowpackjs/astro/issues/1220 as that seems like one way to solve this problem, unless the author has a different proposal.

**Comment by jasikpark** [comment]
Does this [blog post](https://epicreact.dev/one-react-mistake-thats-slowing-you-down/) about React (that I believe could be translated to Astro) help? You might be able to move elements to the top level like this to avoid the prop-drilling you're encountering.

**Comment by oliverlietz** [comment]
> Does this [blog post](https://epicreact.dev/one-react-mistake-thats-slowing-you-down/) about React (that I believe could be translated to Astro) help? You might be able to move elements to the top level like this to avoid the prop-drilling you're encountering.

I would like to stick to a _context_ pattern which fits in my opinion better to "Atomic Design" approach.

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
