### ISSUE TITLE
💡RFC: Improve Build Stats

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#1424]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When a build is completed, incorrect stats are reported.

```
 ├ /9992/index.html                                          0 B
 ├ /9993/index.html                                          0 B
 ├ /9994/index.html                                          0 B
 ├ /9995/index.html                                          0 B
 ├ /9996/index.html                                          0 B
 ├ /9997/index.html                                          0 B
 ├ /9998/index.html                                          0 B
 └ /9999/index.html                                          0 B
[build] ▶ Build Complete!
Done in 33.14s.
sandbox@sse-sandbox-xnkh9:/sandbox$
```

I have some [notes](https://github.com/snowpackjs/astro/pull/1329#issuecomment-914455736) in #1329 about it, I have a suspect bit of code, but I'm not sure how to fix it.

> https://github.com/snowpackjs/astro/blob/8707d1a4f231a84486b670511399b6e46a9809b1/packages/astro/src/build/stats.ts#L38-L46
> 
> This seems to fail to add stats for `dist/index.html`.. the stats are meant to track the HTML size + all of the assets of the page, right?

### Steps to Reproduce

1. Open https://codesandbox.io/s/github/kometbomb/astro-file-handle-bug?file=/src/pages/%5Bid%5D.astro
2. Open a new terminal & run `yarn build`
3. Boom! See the same output as the screenshot above!

### Link to Minimal Reproducible Example (Optional)

https://github.com/kometbomb/astro-file-handle-bug from https://github.com/snowpackjs/astro/pull/1395

**Comment by jasikpark** [comment]
Ah, from discord chat it appears that the stats are reporting only images & js rather than the HTML of the page - I'd argue that the title of the stats should be updated to reflect that it's only linked resources that are being shown in the stats!

```
   Pages                                                     Page Weight (GZip)
 ┌ /an-image/index.html                                      116 kB
 ├ /index.html                                               0 B
 ├ /js/index.html                                            54 B
 └ /no-js/index.html                                         0 B
[build] ▶ Build Complete!
Done in 5.87s.
sandbox@sse-sandbox-5h0r8:/sandbox$
```

https://codesandbox.io/s/new-dust-5h0r8?file=/src/pages/an-image.astro

**Comment by matthewp** [comment]
I think including the HTML makes sense!

**Comment by jasikpark** [comment]
> I think including the HTML makes sense!

After thinking about it more, I definitely think having a JS only stat could be sweet since JS is the heaviest asset..

**Comment by efleurine** [comment]
> > I think including the HTML makes sense!
> 
> After thinking about it more, I definitely think having a JS only stat could be sweet since JS is the heaviest asset..


If we want to break down the weight of every resource it might offer the user some insight but I still think having the whole view is important; one page is the combination of everything that goes in

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
