### ISSUE TITLE
💡 RFC: Allow access to the content of slots

### ISSUE THREAD

**Issue by jonathantneal** [withastro/astro#1450]
### Background & Motivation

I would like to manipulate slotted content in Astro. For example, I would like to transform rendered content like CSS or JS when used within my component.

I would like to reuse slotted content in Astro. For example, I would like to print the contents of a component multiple times, wrapped in different containers with different widths so that I can observe their responsive styles in a storybook-like environment.

To do this, I need access to the contents of slots. Access to whether they are filled is not sufficient in these cases.

This is a followup to https://github.com/snowpackjs/astro/issues/1301

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by natemoo-re** [comment]
I would love to see this happen! Would love to see an outline for the detailed design before we discuss this as an RFC. If anyone has thoughts please weigh in.

I have a potentially contentious suggestion—rather than exposing strings of HTML, we could bring in [`linkedom`](https://github.com/webreflection/linkedom) to create a serverside DOM representation of the slotted children. This would expose some really cool features like being able to use `querySelector()`. I would really like to use a DOM compatible API rather than introducing more syntax/patterns that folks need to learn, like manual recursion or needing to bring in `linkedom` on their own. Can bikeshed on the name... `host` or `children` or `doc` seem relevant.

I'd also note that we should use a getter or a `function` to access this, so as to not introduce any rendering overhead for files that don't use this feature.

```astro
---
const { host } = Astro;
const titles = Array.from(host.querySelectorAll('h1, h2, h3')).map(el => el.textContent);
---

<ul class="toc">
  {titles.map(title => <li>{title}</li>)}
</ul>
```

On the other hand, this should definitely be documented separately as an advanced use case. I can see where it would be _really_ confusing for new users that the Component script can access children as actual `HTMLElement`s but it's still running on the server. So this DOM isn't the actual DOM in the client!

There are also open questions as to what happens if you mutate any of these elements. Should the elements be read only or should they be mutable and render out where `<slot>` does. `linkedom` has a `toString()` method that serialized them back to HTML.

**Comment by FredKSchott** [comment]
Agreed with Nate, there's not enough here to approve yet imo (both the RFC could use some fleshing out, and a discussion in the thread itself)  but overall +1 to investigating this and trying to solve!

**Comment by drwpow** [comment]
RFC Discussion notes
- original intent was simply to expose the slots as a string
- linkedom: great tool, but maybe shouldn’t be provided out-of-the-box?
    - also may be costly?
- Markdown component does something with its slots; should other components be able to access their slots as well (LaTeX components, etc.)
- Code component already somewhat uses this capability to format/highlight slotted contents
- Overall, RFC may be missing usecases?
- Something like “raw” slot content (rendering the written JS as a string) will be outside the scope of this RFC

Decision: this looks promising, but we need a usecase + proposal to push this forward!

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat

**Comment by Red-CS** [comment]
For smaller uses, I found this great blog post:
https://cassidysmith.dev/posts/modify-astro-slot-children
They use the Astro.slots.render function and manually create a childrens array which can then be operated on.
