### ISSUE TITLE
💡 RFC: Expose Javascript API for CLI commands

### ISSUE THREAD

**Issue by leosvelperez** [withastro/astro#1483]
### Background & Motivation

I want to be able to programmatically invoke the CLI commands. Currently, the only way to consume them is through the CLI, the different functions to load the config, build, start the dev server, and start the preview server are not exported by the package.

A Javascript API would be particularly useful for scenarios where we have custom scripts or tooling to invoke these operations. In these scenarios we might need to manipulate the config once is loaded and before invoking the functions to build or start the dev or preview servers.

### Possible solutions

Export the functions `build`, `dev`, `preview`, `reload` and `loadConfig`.

### Alternatives considered

Create a temporary config on the fly before spawning a process to invoke the CLI and feeding the temporary config to it. This is quite cumbersome and not worthy when a simple Javascript API can be provided.

### Risks, downsides, and/or tradeoffs

The only risk I can think of is about committing to a somewhat stable API. But I'd say the CLI API should be pretty stable at this point, the implementation is changing but I guess the signature for each function is still quite similar. Even if that's not exactly the case, given Astro is in an early beta stage, changes are expected to happen, so, it should be fine.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
