### ISSUE TITLE
💡 RFC: `Astro.fetchContent('./posts/**/*.astro')`

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#1497]
### Background & Motivation

I want to support the workflow used in https://github.com/snowpackjs/astro/tree/main/www

Blog posts are written in `www/src/pages/blog/[*.astro]`, and uses `<Markdown>`.

https://github.com/snowpackjs/astro/blob/main/www/src/pages/blog/index.astro lists all of the posts in a list, which is hardcoded today!

I want to support `let posts = Astro.fetchContent('./pages/blog/**.astro');` as a usecase, 

This will tie in with 

- https://github.com/snowpackjs/astro/issues/1142

### Possible solutions

- just use `import.meta.globEager`
- add `astro` files to the allowed files in `Astro.fetchContent`

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by jasikpark** [comment]
> I personally feel it would be best if we setup Astro files to be imported by `import("./**/*.astro")`, since you already use that syntax to import/export.

So instead of providing the syntax sugar of Astro.fetchContent, just require `const pages = await import.meta.glob("./**/*.astro");`?

https://vitejs.dev/guide/features.html#glob-import

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
