### ISSUE TITLE
💡 RFC: Multiple 404 pages

### ISSUE THREAD

**Issue by hyblocker** [withastro/astro#1582]
### Background & Motivation

I want to be able to define multiple 404 pages. Examples of use cases are:
- Custom 404s for documentation and the rest of the site (e.g. a blog)
- Localized 404s (e.g. you would have `/404.html`, `/it/404.html`, `/fr/404.html` and so on)

An example of a static site hosting provider which allows custom 404s is Cloudflare Pages (I am yet to personally test it, but [according to documentation](https://developers.cloudflare.com/pages/platform/serving-pages#not-found-behavior), it's possible)

### Possible solutions

The paths resolve as follows:
| /src | /dist |
| --- | ---- |
| `/404.astro` | `/404.html` |
| `/en/404.astro` | `/en/404.html` |
| `/es/404.astro` | `/es/404.html` |
| `/it/404.astro` | `/it/404.html` |
| `/fr/404.astro` | `/fr/404.html` |
| `/de/404.astro` | `/de/404.html` |

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
