### ISSUE TITLE
💡 RFC: allow variable string name for Astro.fetchContent

### ISSUE THREAD

**Issue by smakinson** [withastro/astro#1700]
### Background & Motivation

I'm not sure if this is considered a feature request or not. I'm guessing it is based on the error message given:
`Error: [Astro.fetchContent] Only string literals allowed, ex: Astro.fetchContent('./post/*.md')`

I am testing out Astro with Netlify CMS and I have a relation widget that uses a slug for a frontmatter value. I would like to be able to use that slug value to build the path to another markdown file that is in a folder collection managed by Netlify CMS.

https://www.netlifycms.org/docs/widgets/#relation
https://www.netlifycms.org/docs/collection-types/#folder-collections

### Possible solutions
Allow variable or template literals to be used with `Astro.fetchContent()`

### Alternatives considered
I don't think I have an alternative in this use case.

### Risks, downsides, and/or tradeoffs
?

### Open Questions
Perhaps this feature is planned?

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by matthewp** [comment]
Removing the label as I don't think this is ready to discuss on an RFC call yet. Let's continue discussing here, and when a solution is raised we can discuss on the call.

**Comment by smakinson** [comment]
I see a possible workaround by fetching with `*.md` and then looking for the one that has the filename of the slug I wanted to fetch via a concatenated string using `file.pathname` I suppose the downside to this is if there are a large number of files fetched when only one is needed. Perhaps also the unexpected error when trying to concatenate a path to use. Thoughts on this workaround?

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
