### ISSUE TITLE
💡 RFC: SSR import 3rd party lit components

### ISSUE THREAD

**Issue by yinonov** [withastro/astro#1720]
### Background & Motivation

Current interface of renderer-lit supports importing local (authored "in-house") lit-based custom elements in the frontmatter section.
however, when trying to import 3rd party lit-based components from the frontmatter section, the build fails.
Docs doesn't suggest any guidance here and it is expected for same lit component to be imported just the same
currently it is only available to import by module script within the body section.
this result in a non-SSR import as featured by frontmatter declaration and renderer-lit.

Astro currently needs the `tagName` export to properly match component definitions to their usage in HTML and is reasonable to use within the Astro environment but not in 3rd party CE libraries.

### Possible solutions
workaround tagName export and find a practice enabling SSR clean import -
import '@3rd-party/button' as my-button

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

[reproduction here](https://stackblitz.com/edit/github-l5nmfq?file=src/pages/index.astro)

**Comment by natemoo-re** [comment]
Relevant PR 👉🏻 https://github.com/snowpackjs/astro/pull/1722 removes the need for `tagName`.

Unfortunately, `@material/mwc-button` does not appear to be written in a way that is compatible with SSR from what I can see. It's going to take a while for the ecosystem to start authoring web components in an SSR-friendly way.

**Comment by matthewp** [comment]
@yinonov What I've done in the past is create a "wrapper" component for these. Something like:

__src/components/button.js__

```js
import '@3rd-party/button';
const tagName = 'third-party-button';
```

Then you can import this module and use it like you would if you directly imported the npm package name.

**Comment by yinonov** [comment]
> @yinonov What I've done in the past is create a "wrapper" component for these. Something like:
> 
> **src/components/button.js**
> 
> ```js
> import '@3rd-party/button';
> const tagName = 'third-party-button';
> ```
> 
> Then you can import this module and use it like you would if you directly imported the npm package name.

it'll mean proxying all required components right? would do if I wont be able to adjust components to fit as @natemoo-re mentioned

**Comment by natemoo-re** [comment]
> luckily this was just an example and I have control over the 3rd party library. are there any related guidelines you can share on SSR-friendly components?

Ooh great question @yinonov! I don't know if there are any guides out there just yet, Lit SSR is still very early. Sounds like a great question for [@buildwithlit](https://twitter.com/buildwithlit) on Twitter, though!

**Comment by matthewp** [comment]
- There might a manifest file format that helps with this.
- @natemoo-re has an experimental PR. Would to turn that into an implementation in this RFC so we can discuss further.
- We might need better warnings/errors when a custom element doesn't match.

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
