### ISSUE TITLE
💡 RFC: Reference the site tree in a page or component

### ISSUE THREAD

**Issue by jonathantneal** [withastro/astro#1726]
### Background & Motivation

I want to build a `<nav>` for my site based on the available pages. I cannot find a way to reference the other pages on the site, tho I know Astro can build a sitemap file. If I use the `import.meta.glob` or `Astro.fetch` functions to gather references to other pages, those other pages are _also_ evaluated _and_ can lead to infinite loops if they contain the same `<nav>`.

### Possible solutions

An internal package (_or a Vite-Astro-optimized package_) that returns a list of files, like `import.meta.glob` works in Vite, only without evaluating the files.

https://gist.github.com/jonathantneal/ed53cd044e1ec2227db7c2a672a2cc43

### Alternatives considered

To find other Astro pages, I might use something like `Astro.fetchContent('**/*.astro')` or `import.meta.glob('**/*.astro')`, but those will not work because they unnecessarily render the page. And, if those pages include the same navigation, I will experience infinite recursion.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by oliverlietz** [comment]
Navigation is the example used in #1340.

**Comment by jonathantneal** [comment]
@oliverlietz, would you be open to an internal package or `import.meta` handler as your proposal? If so, our RFCs could be merged.

**Comment by jasikpark** [comment]
So something like https://gohugo.io/content-management/cross-references/ isn't quite what you're looking for, it's more that you want both to be able to import pages + just import the existence of those pages rather than their content?

**Comment by oliverlietz** [comment]
@jonathantneal, Not sure. I'm not too familiar with Astro and Vite (yet) – doing my very first steps.
Site/page tree is of course a very common requirement and therefore I picked it up as example but I might need more data from a central place in pages and components (configurations comes to mind).
Would an internal package or `import.meta` work with other data sources beside local files?
Currently my page tree is already coming from a remote source (Sling/AEM):
```
export async function getStaticPaths() {
    const contentService: ContentService = new HttpContentService('http://localhost:3100/content/org/amer/us/web/main')
    const factory: SiteFactory = new DefaultSiteFactory(contentService);
    const site = await factory.build();
    const pages: Page[] = site.pages();
    const paths = pages.map(page => {
        return {
            params: {
                path: page.path
            },
            props: {
                site: site
            }
        }
    });
    return paths;
}
```

**Comment by oliverlietz** [comment]
@jasikpark At least my use cases are not limited to pages. Configurations is another use case, e.g. making login/logout links to SSO available to every page/component.

**Comment by gabrielgrant** [comment]
[Vite's docs for glob imports](https://vitejs.dev/guide/features.html#glob-import) says that glob imports just produce a mapping of filepath => import function, but doesn't actually evaluate the import until you call the import function (or use `import.meta.globEager()`)

<details><summary>Example from docs</summary>

```
const modules = import.meta.glob('./dir/*.js')
```
The above will be transformed into the following:

```
// code produced by vite
const modules = {
  './dir/foo.js': () => import('./dir/foo.js'),
  './dir/bar.js': () => import('./dir/bar.js')
}
```
</details>

So in terms of just getting the file names/the list of which pages exist, it seems that should work, no? Is the issue that you are trying to actually import the pages to extract additional exported data from the page files? Or is there something else I'm missing?

**Comment by jonathantneal** [comment]
> So in terms of just getting the file names/the list of which pages exist, it seems that should work, no?

No, that is not helpful enough, because the particular implementation of `import.meta.glob` seems to impose a limitation on the result. The file itself cannot be picked up by `import.meta.glob`. I suspect this is an undocumented limitation that comes from parity with `globEager`, where a glob finding itself and executing itself would cause infinite recursion.

All that to say — a more API suitable API is still needed.

Now, since the error message has recently changed, I believe there is also an issue with `import.meta.glob` within Astro.

See an example @ https://stackblitz.com/edit/github-f7cp6k?file=src/pages/index.astro

- On the first page, the glob cannot find itself (a limitation in Vite). It includes a link to a page second.
- On the second page, the glob cannot find itself. It includes a link back to the first page.
- Back on the first page, change the value of `<meta name="edit-me" content="test" />` from `test` to `look`.
- `500 Internal Error`, `Maximum call stack size exceeded`, and there is no recovery (a bug in Astro).

```
RangeError: Maximum call stack size exceeded
    at Set.values (<anonymous>)
    at crawlCSS (file:///home/projects/github-f7cp6k/node_modules/astro/dist/core/ssr/css.js:27:45)
```

**Comment by natemoo-re** [comment]
We already generate a route manifest internally! I wonder if it would be enough to just expose that to users? It gets tricky when things get dynamic, but maybe someone has an idea that would expose that with an approachable API?

See https://github.com/snowpackjs/astro/commit/2937c81a8c8c8130f43a429dfc7b2d235af4f69c on [`spike/autonav`](https://github.com/snowpackjs/astro/tree/spike/autonav).

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
