### ISSUE TITLE
💡 RFC: Support Web Components as Components

### ISSUE THREAD

**Issue by jonathantneal** [withastro/astro#1732]
### Background & Motivation

I would like to use web components in Astro the same way I can use React, Sue, and Svelte components.

```js
// components/MyElement.js
export default class MyElement extends HTMLElement {}
```

```astro
---
// pages/index.astro
import MyElement from '../components/MyElement.js'
---
<MyElement />
```

### <a name="proposal">Proposed Solution</a>

Support web components as registered custom elements using a new renderer.

The new renderer will import a Web Component as JS, matching how the Lit renderer works. To prevent errors caused by accessing top-level DOM APIs that are missing in Node or Deno, the Lit renderer will shim these objects. Unlike the Lit renderer, these DOM shims will not need to recreate real DOM functionality, because the component will not be constructed on the server.

The new renderer will produce a tag name for the Web Component. This tag name will be pulled from a top-level `customElements.define` call that matches the constructor. If no matching name is found, a tag name will be generated from the internal display name provided by Astro.

__Example: Web Component (not registered)__
```js
// MyComponent.js
export default class MyComponent extends HTMLElement {}
```

```astro
---
import MyComponent from '../components/MyComponent.js'
---
<MyComponent /><!-- rendered as `<my-component>` -->
```

__Example: Web Component (registered)__
```js
// MyRegisteredComponent.js
export default class MyComponent extends HTMLElement {}

customElements.define('h-component', MyComponent)
```

```astro
---
import MyComponent from '../components/MyRegisteredComponent.js'
---
<MyComponent /><!-- rendered as `<h-component>` -->
```

The new renderer will respect the static `observedAttributes` value of the Web Component, preserving any matching attributes passed into the component for the rendered element. Global attributes will be preserved as well. Any other attributes will be prepended to the element as slotted children.

```js
// MyComponent.js
export default class MyComponent extends HTMLElement {
  static get observedAttributes() {
    return ['special']
  }
}
```

```astro
---
import MyComponent from '../components/MyRegisteredComponent.js'
---
<MyComponent class="joy" special="yay" more="slotted">content</MyComponent>
```
```html
<!-- rendered as: -->
<my-component class="joy" special="yay"><data slot="more">slotted</data>content</my-component>
```

The new renderer will add a small script to import the Web Component script; and, if the name was generated, register the tag name using `customElements.define`. If a Web Component is rendered multiple times, Astro already has built-in functionality that prevents the import script from ever being added more than one time.

```html
<script type="module">
import("path/to/MyComponent.js").then(exports => customElements.define('my-component', exports.default)
</script>
```

```html
<script type="module">
import("path/to/MyRegisteredComponent.js")
</script>
```

### Risks, downsides, and/or tradeoffs

!["Eternal Glory" — Albus Dumbledore](http://i3.ytimg.com/vi/NwPH5rEaURo/hqdefault.jpg)

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by matthewp** [comment]
Couple of things here:

1. We do not have a generic web components renderer at the moment. The `renderer-lit` only works with Lit elements. A generic WC renderer would be nice, but would require a true DOM shim. The `renderer-lit` uses a very minimal shim that is what Lit needs but wouldn't work for any generic WC. Lit also has a special way of rendering on the server that is supposedly faster than it would be to use a DOM shim technique. I say this to explain why it's a lit renderer and not a generic WC one. I created a standalone WC renderer (but its not up to date and likely does work in `next`): https://github.com/matthewp/astro-renderer-webcomponent
1. Using the constructor of a Lit element within an Astro template is already supported and we do not need a manifest to support that style.
1. The reason for the `tagName` is to allow *not* using the constructor, but rather using the tag name, which some people in the WC community were passionate about. Using the manifest file could be an alternative to the `tagName` and could possibly solve https://github.com/snowpackjs/astro/issues/1720

**Comment by jonathantneal** [comment]
I appreciate the attention. I think supporting Web Components similar to other Astro components will be a 'game changer' for the web.

> A generic WC renderer would be nice, but would require a true DOM shim. The renderer-lit uses a very minimal shim that is what Lit needs but wouldn't work for any generic WC.

The proposal has been updated to clarify that it does not evaluate the component’s constructor. The only reason the DOM is shimmed is to prevent top-level access to missing DOM APIs from throwing errors, which is something the Lit renderer also does.

> The reason for the tagName is to allow not using the constructor, but rather using the tag name, which some people in the WC community were passionate about.

The proposal has been updated to illustrate how `customElements.define` is neither required or ignored. In this proposal, the tag name is determined by either by the `name` in `customElements.define(name, ctor)`, or by the display name provided by Astro.

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
