### ISSUE TITLE
💡 RFC: Astro.render API

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/astro#1742]
### Background & Motivation

Currently, we can't assign a Component as the value of a variable. And `v0.21` also removed support for returning components inside a function in the frontmatter. But I think it's a useful and necessary feature to implement. It'll allow performing HTML transformations and will greatly help when fetching data from a CMS.

### Possible solutions

The proposed design by @matthewp is the following:
```js
import { Code } from "astro/components";

Astro.render(Code, { code: '...', lang: '...'})
```

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by matthewp** [comment]
To clarify, I wasn't proposing that API, just throwing out an idea :).

For SSR we were talking about making doing something like this too:

```js
import { Code } from "astro/components";

let html = await Code.renderToString({ code: '...', lang: '...'})
```

That is, have something on the component itself (naming to be bikeshedded of course)

**Comment by drwpow** [comment]
- In general, good proposal; many people have asked for it
- But we’d need to see a proposal with a more clear API (what does it return? etc.)
- Usecase isn’t clear here (components in frontmatter-related, but needs more detail)

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
