### ISSUE TITLE
💡 RFC: Expose all environment variables

### ISSUE THREAD

**Issue by jonathantneal** [withastro/astro#1765]
### Background & Motivation

Astro only exposes `PUBLIC_` prefixed environment variables using `import.meta.env`, but we still need a way to access prefix environment variables on the server.

The `PUBLIC_` limitation is [intended](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser) to protect variables from being accidentally exposed to the browser. However, [Vite appears to discard them entirely](https://github.com/vitejs/vite/blob/v2.6.13/packages/vite/src/node/config.ts#L1005-L1034) so that we have no access to them from the server as well.

Support for environment variables and the `PUBLIC_` restriction are somewhat pointless without server access to public variables. I would expect the following code to behave as expected:

```ini
# .env
SECRET_PLACE=CLUB_33
PUBLIC_PLACE=BLUE_BAYOU
```

```astro
---
console.log(import.meta.env.PUBLIC_PLACE) // logs "BLUE_BAYOU"
console.log(import.meta.env.SECRET_PLACE) // logs "CLUB_33"
---
<script type="module">
console.log(import.meta.env.PUBLIC_PLACE) // logs "BLUE_BAYOU"
console.log(import.meta.env.SECRET_PLACE) // logs undefined
</script>
```

Instead, both logs of `SECRET_PLACE` are `undefined`.

### Possible solutions

Update the implementation for environment variables so that:

1. All environment variables are available to server-side `import.meta.env`.
2. Only public environment variables are available to client-side `import.meta.env`.

### Detailed Design

Vite currently injects `import.meta.env` into client-side scripts like this:

**JavaScript as it is authored**:
```js
console.log(import.meta.env.WHATEVER)
```
**JavaScript as it is served**:
```js
import.meta.env = {"PUBLIC_PLACE":"BLUE_BAYOU","BASE_URL":"/","MODE":"development","DEV":true,"PROD":false,"SSR":false};
console.log(import.meta.env.WHATEVER)
```

Wherever this injection occurs is where I would expect private variables to be omitted.

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by matthewp** [comment]
Seems reasonable to me. Have you done research as to whether this would be a Vite change?

**Comment by natemoo-re** [comment]
Yeah this is a great idea! I think this would need to be a Vite change or some custom handling (which I'd like to avoid).

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat

**Comment by DrecDroid** [comment]
You can pass variables to the serverSide using custom Vite configuration.

```mjs
import dotenv from "dotenv"
import fs from "fs/promises"

const env = dotenv.parse(await fs.readFile(".env"))

export default ({
  vite: {
    define: {
      "process.env.DIRECTUS_URL": `"${env.DIRECTUS_URL}"`,
      "process.env.DIRECTUS_ACCESS_TOKEN": `"${env.DIRECTUS_ACCESS_TOKEN}"`,
    }
  },
})
```

Then inside the app:

```ts
import { Directus } from "@directus/sdk"
import { Collections } from "./models"

// Get Directus client
export async function getDirectus() {
  const directus = new Directus<Collections>(process.env.DIRECTUS_URL!)
  await directus.auth.static(process.env.DIRECTUS_ACCESS_TOKEN!)

  return directus
}
```

Just be sure to use it only in server-side code.

**Comment by natemoo-re** [comment]
I just opened a PR to implement this behavior! https://github.com/withastro/astro/pull/2612
