### ISSUE TITLE
💡 RFC: Support hydratable components without <astro-root>

### ISSUE THREAD

**Issue by jonathantneal** [withastro/astro#1766]
### Background & Motivation

Astro should provide an API to renderers that register Custom Elements.

### The Problem

Astro client directives cannot work as expected.

Consider the following example from [framework-lit](https://stackblitz.com/github/snowpackjs/astro/tree/main/examples/framework-lit?on=stackblitz), where Astro creates an unnecessary `<astro-root>` element: 

**src/index.astro**:
```astro
<my-counter client:load />
```

**dist/index.html**:
```html
<astro-root uid="Z2x4EW2"><my-counter><template shadowroot="open">...
```

The `<astro-root>` element is used by Astro to register individual components. However, Lit does not need Astro to register the individual `my-counter` element, because the component already does this internally. The Lit component hydrates all `<my-counter>` elements by calling `customElements.define('my-counter', Counter)`.

This '_one for all_' functionality also means that client directives like `client:visible` won’t ever work as expected, since the registration of `my-counter` will apply to all `<my-counter>` elements on the page, whether they are visible or not.

Client directives are one of Astro’s biggest features, but their implementation relies on a faulty premise that components are single use only. They are well designed for older frameworks like React and Vue, but this is at the expense of newer frameworks like Lit, Atomico, or native Web Components that leverage the web platform.

### Proposed Solution

- Allow renderers to override client directives.

### Possible solutions

- Allow renderers to handle their own hydration.

This would require the following features:

- The renderer needs to know the URL for the component script, if it is to handle its own client-side registration.
- The renderer needs to know the URL for the current page, to prevent server-side registration from bleeding across pages.
- The renderer needs the ability to disable, control, or influence client directives.

### Open Questions

- Should client directives be built into Astro?
  - Should they be built into renderers?

- Should renderers be allowed to attach scripts without client directives?
  - If renders should not be allowed to do this, how should '_one for all_ ' components work?

- If a React component is used twice on a page using different client directives, what is the expected result?
  - Is this a helpful result for developers or users?

### Detailed Design

A detailed design for Web Components is outlined in https://github.com/snowpackjs/astro/issues/1732

An implementation that _mostly_ works within the current confines of Astro is available at https://github.com/snowpackjs/astro/pull/1737

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by natemoo-re** [comment]
This is a reasonable request, but we also made an intentional decision to not offload hydration complexity to the renderers. I'd be +1 for revisiting that decision as part of a larger Web Component support push, but I'm not sure if it's something we want to prioritize right now.

**Comment by jonathantneal** [comment]
I would also +1 to this being part of a push that could tie into the AST work necessary for Prettier.

**Comment by matthewp** [comment]
I think this is just a bug. `<astro-root>` is not an external API, so we should be able to change implementation with an RFC.

**Comment by jonathantneal** [comment]
> I think this is just a bug.

That would be nice (for me)!

@matthewp, AFAIK, it’s currently behaving as expected by the current `client:` directives, which this RFC seeks to change. If there’s a bug, how should it currently behave?

**Comment by matthewp** [comment]
Oh sorry, I hadn't read the whole thing through at that point.

It's true that if you have both `client:load` and `client:visible` on a Lit component, they will both hydrate on load. However it's also true that with a React or Svelte or any other type of component, they will still *load* (but not hydrate) at the earliest directive.

Since these directives are primarily driven to delay loading I think they still serve the same purpose for Lit components. I can't think of a scenario where you would want a component to load but not hydrate yet. That's not really the reason to use them. 

Given that, I think the difference between the two is acceptable.

**Comment by jonathantneal** [comment]
> Given that, I think the difference between the two is acceptable.

By '_the two_' are you referring to `client:load` and `client:visible`, or to `<my-lit-element>` being wrapped in `<astro-root>` whenever a client directive is used?

This RFC is seeking to change how components are hydrated, but not resolve that particular oddity.

This RFC wants to allow `<any-lit-element>` manage its own hydration without also wrapping it in `<astro-root>`. The wrapping seems unnecessary for components that 1. generate a single HTML element and not a fragment of HTML, and 2. generate an element that will automatically hydrate all other elements automatically.

**Comment by matthewp** [comment]
I think that the developer needing to specify how components load with the client directives is perhaps the most important feature of Astro. It's the thing that [other](https://iles-docs.netlify.app/guide/hydration) [projects](https://slinkity.dev/docs/partial-hydration/) are copying and the thing that [people are talking about](https://syntax.fm/show/403/hasty-treat-what-s-the-deal-with-astro) with Astro.

Allowing renderers to control when hydration occurs would allow them, on purpose or not, to defy the directives and load in a different way. I think this would be a big mistake for us. Plugability is a feature, but not the primary one, of Astro.  `astro-root` though, is something we could solve in another way, without an RFC, just by knowing that the type of renderer being used doesn't need one of those.

**Comment by jonathantneal** [comment]
> `astro-root` though, is something we could solve in another way, without an RFC, just by knowing that the type of renderer being used doesn't need one of those.

Would that be a flag on a renderer that _effectively_ tells Astro not to wrap a component in `<astro-root>`?

If so, such a feature would fulfill the title of this RFC ("_Support hydratable components without `<astro-root>`_") as well as the description ("_Astro should provide an API to renderers that register Custom Elements._").

**Comment by jasikpark** [comment]
> I think that the developer needing to specify how components load with the client directives is perhaps the most important feature of Astro. It's the thing that [other](https://iles-docs.netlify.app/guide/hydration) [projects](https://slinkity.dev/docs/partial-hydration/) are copying and the thing that [people are talking about](https://syntax.fm/show/403/hasty-treat-what-s-the-deal-with-astro) with Astro.
> 

Something someone was talking about in the discord today was how they expected to be able to load a vanilla js animation script w/ astro's loading directives... maybe that's something to think about as well 🤔 though i'm not sure it makes sense since there's no obvious "astro-root" for the animation

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
