### ISSUE TITLE
💡 RFC: Access slot content

### ISSUE THREAD

**Issue by jonathantneal** [withastro/astro#1808]
### Background & Motivation

Currently, if I want to provide content to an Astro component, like [astro-social-images](https://github.com/Princesseuh/astro-social-images), I must use attributes.

```astro
---
import { SocialImage } from "astro-social-images"
---
<SocialImage
  texts={[
    {
      content: "My super title",
      attributes: {
        x: "55",
        y: "105",
        "font-size": "70px",
        fill: "#fefffe"
      }
    }
  ]}
/>
```

However, I would rather use the expressiveness of markup:

```astro
---
import { SocialImage } from "astro-social-images"
---
<SocialImage>
  <text x="55" y="105" font-size="70px" fill="#fefffe">My super title</text>
</SocialImage>
```

Code like this is more cohesive with its surroundings and is why I prefer the Astro format.

Unfortunately, this kind of 'API' would be impossible for the component to use, because Astro components cannot access their own contents.

---

With the current slotting architecture, this is the content I can access within `<SocialImage>`:

```astro
---
console.log(Astro.slots)
---
```
```js
{
  default: true
}
```

And this is the content I want to access:

```astro
---
console.log(Astro.slots)
---
```
```js
{
  default: `\n  <text x="55" y="105" font-size="70px" fill="#fefffe">My super title</text>\n`
}
```

### Proposed Solution

I would like Astro to expose slots as strings, as requested in https://github.com/snowpackjs/astro/issues/1450.

Note: The final feedback to that RFC was:

> Decision: this looks promising, but we need a usecase + proposal to push this forward!

This RFC seeks to provide that use case.

### Possible solutions / alternatives

- Use attributes in Astro files (even when I would rather use slotted content) and treat HTML more like React.
- Use another renderer that allows this expressiveness within HTML.

### Risks, downsides, and/or tradeoffs

- If Astro is conscientious of streaming, any access beyond the tag name is prohibitive. Allowing access to slotted content would require the entire content to be rendered. Of course, this is also true for the current boolean behavior, and this is also true for attributes (which could host a lot of data to workaround the current limitation).

- Depending on yet discussed use-cases, component authors may add their own parsers to extract data passed into components, which may in turn introduce performance decreases where those components are used.

- The current API allows authors to check for attributes in 2 different ways — `name in Astro.slots` and `Astro.slots[name]`. Returning raw strings would mean that an assigned slots with no contents would now return false in the later check.

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by hans-d** [comment]
I'm not sure about the "raw" content of the slots, following the [remark](https://github.com/snowpackjs/astro/issues/1450#issuecomment-934633041) made earlier to have it in a more accessible way

**Comment by jonathantneal** [comment]
That remark was only a suggestion. The actual rejection was based on the lack of a use-case. Now there is one.

If the only way to get access is to invent a server-side DOM, so be it, but that’s a whole different ASK in my opinion. That ask comes with figuring out a 'compatible' API for things like "an attribute value as an object or function", and "what addEventListener does", and "the shape of the AST for a DOM tree, which, to correctly mimic HTML and not JSX, first evaluates by tag, then attribute, then children, then implicit or explicit closure."

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat

**Comment by Mehdi-Hp** [comment]
For anyone coming from a search engine, this is the way:

```js
Astro.slots.render('[slotName]')

// For default slot
Astro.slots.render('default')
```

**Comment by RichardJECooke** [comment]
Is there a way to edit content in a slot yet please?

Like if I wanted to change to make a component called `codeBlock`

````
<codeBlock>
```
git clone {frontmatter.url}
```
</codeBlock>
````

that renders

````
```
git clone https://github.com/example.git
```
````
