### ISSUE TITLE
💡 RFC: Exposing more type definition for a more self documenting library

### ISSUE THREAD

**Issue by Chrissdroid** [withastro/astro#1812]
### Background & Motivation

I like the way Astro is an "Typescript on the go" approach with frontmatter script and .ts files being process in `src/` directory, it's awesome but i think this approach isn't used enough or, more likely not at it's full potential

For exemple, as mentioned on an [thread in the discord](https://discord.com/channels/830184174198718474/907931563415711747/908024376983707678) the page prop returned by the paginate function could be self documented to avoid going back and fourth between doc and IDE just for knowing the exact property name or avoid making silly and useless page number calculator function when it's already given by the function (and yes, i regret my dumb brain sometimes xD)

We could avoid simple getStaticPaths() errors and define more precisely props and links to the docs, more intuitive the lib will integrate with IDEs and be more developer friendly

### Possible solutions

Define the Astro.props relative to the exported Prop interface in .astro files
Define RSS and Paginate functions and attibutes needed with links to te documentation website

### Alternatives considered

Integrate this in the VSCode ext to detect the Prop interface and the uses of paginate function

### Risks, downsides, and/or tradeoffs

Needs to design a good typedef (and maybe traductions ?) for this purpose and integrate it nicely according to the docs
Needs also to have a clear image of design model of Astro to avoid redo when breaking changes append

### Open Questions

If someone can make a list of interesting defs also needed ?
What's your opinion on that (i'm not sure if it would be worth at the current time with the 0.21 coming) ?

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by drwpow** [comment]
Yes I think I see where you’re coming from with this! I think what would really help would be:

- More code examples—what does the code look like today? What would you like the code to change to?
- In VS Code, a screenshot of what you’d like this to look like (could be another library that does this well).

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
