### ISSUE TITLE
💡 RFC: Enhanced attributed spreads (extension of #782)

### ISSUE THREAD

**Issue by hans-d** [withastro/astro#1820]
### Background & Motivation

With `class:list` (RFC #782) it is now possible to easily add classes contained in a variable, or more generically speaking: add values to the specified attribute.

For other attributes this may be usefull as well, eg Alpinejs's [bind](https://alpinejs.dev/directives/bind) function. 

Also, when using attribute-style utility css classes, like with windicss or unocss, it would be nice to easily add a number of attributes (no values needed).
Eg with `const myAttr = [ 'flex', 'flex-grow' ]
- `<div {...myAttr} />` becoming `<div flex flex-grow>` (nb, using splat here as a placeholder)

### Possible solutions

Make `class:list` more generic, eg `<whatever-attrib-or-even-none>:list`, or make it into a function that can be used in {}. The latter would be preferred, as it is less likely to class with another use of `:list`

### Alternatives considered

(taken from #782)
- Including a helper function similar to [clsx](https://github.com/lukeed/clsx)
- just including docs with links to those libraries with and a short example snippet

### Risks, downsides, and/or tradeoffs
- Empty attributes (no value) are allowed by the spec
- Attributes get pretty overused in the frontend, esp with css utility classes, and this would make it even easier to throw more attributes into Astro components

### Open Questions
- is it worth adding such a function?
- should it be used instead of `class:list`, or should `class:list` just be a shorthand using the same implementation

### Detailed Design

See also #782 

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by natemoo-re** [comment]
I actually kind of like the idea of supporting 
```astro
---
const attrs = ['flex', 'flex-grow']
---
<div {...attrs} />
<!-- output is <div flex flex-grow /> -->
```

This would be a pretty simple change in [`packages/astro/src/runtime/server/index.ts`](https://github.com/snowpackjs/astro/blob/252901c1793e8f8dd8c8a4ac81a9a5dc538f852b/packages/astro/src/runtime/server/index.ts#L234-L240)
```diff
 export function spreadAttributes(values: Record<any, any>) {
   let output = '';
+  if (Array.isArray(values)) {
+    for (const key of values) {
+      output += addAttribute(key, '')
+    }
+  } else {
     for (const [key, value] of Object.entries(values)) {
       output += addAttribute(value, key);
     }
+  }
  return output;
}
```

**Comment by natemoo-re** [comment]
Actually, rather than special-casing `Array`, we should [just support any iterable](https://stackblitz.com/edit/node-syft9q?file=index.js)!

This would match the native `...spread` behavior and automatically support `Set`, `Map`, `Array`, and custom `[Symbol.iterator]`. `String` values might seem weird to newcomers, but it would match regular JS behavior where strings are iterable.

**Comment by hans-d** [comment]
I do like the any iterable approach

**Comment by natemoo-re** [comment]
Correct me if I'm wrong, but this seems like it's diverged from #782?

There might actually be two RFCs here!
1. Extend `class:list` to a more generic utility that can serialize attributes with object values to a space-delimited string.
2. Expand the support of our spread operator `<div {...attrs} />` to support any iterable.

**Comment by hans-d** [comment]
That might be the case indeed.
I would even say that "generic utility that can serialize attributes with object values to a space-delimited string" could be considered a special case of the spread operator. Perhaps keeping the two now in one RFC for the initial discussion - as they are related -, but separating them from that point.

**Comment by jonathantneal** [comment]
> For other attributes this may be useful as well

I agree (and `aria-label` is another example). I have hoped we might expose the [internal helper](https://github.com/snowpackjs/astro/issues/782#issuecomment-947860212) that currently powers `class:list` (_and then maybe deprecate `class:list`_).

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
