### ISSUE TITLE
🐛 BUG: Passing empty value attributes in components provide wrong value

### ISSUE THREAD

**Issue by hans-d** [withastro/astro#1826]
### What version of `astro` are you using?

next.3

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Given the component
```
---
const content = Astro.props;
---
<div   {...content}/>
```
When calling with `<Div attr=val empty />` will render it as `<div attr="val" empty="true">`.
An empty attribute, according to the html spec, should have the value of '""'.
The correct rendering must me `<div attr="val" empty>`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bc6mim?file=src/pages/index.astro

**Comment by hans-d** [comment]
Also relevant for #1820

**Comment by natemoo-re** [comment]
Ah I see the issue here! Empty attributes in HTML are treated as `attr=""`, but empty attributes in JSX are treated as `attr={true}`. Astro attempts to mimic this behavior in our compiler. `EmptyAttribute` is actually handled as a specific type.

When we find empty attributes on Component nodes, they will be cast to `true`. On regular Element nodes, they will be treated as `""`.

In this case, you're passing an empty attribute through to a Component (casting it to `{ empty: true }`), then spreading it onto a `div` (where `true` will be treated literally). At this point, we've lost the original context that indicated `empty` was written as an empty attribute rather than a boolean.

IMO we're handling this about as well as could be expected, but if you have any specific ideas on how to improve this, we'd love to hear them!

**Comment by hans-d** [comment]
What about a `Default` or `Empty` type, that depending on where it is actually used will be `true` or `""`. By default it will return `true`, as to keep in line with jsx, but in case it's inside a regular tag, it can be returning `""` (not sure how this would impact implementation, just thinking aloud).

**Comment by natemoo-re** [comment]
That could work... most equality checks would be okay, but this would break anywhere folks use `attr === true` or are explicitly expecting a boolean.

One big problem is that we'd probably have to convert this value _back_ to `true` in the renderer layer, before passing `props` down to framework components. That could be a performance issue because we'd have to recurse through the entire `props` object to find these values.

**Comment by hans-d** [comment]
That would be a breaking change, and perhaps not worth the effort...
Would the spread operator be possible to take into account if it's in a regular tag, and render an `attribute === true` as `attribute` (skipping the ="")

**Comment by jonathantneal** [comment]
I would agree that this looks like a bug. The current behavior breaks HTML expectations, and could affect fragments, layouts, and any other non-React frameworks that expect genuine attribute values (anything using data attributes, Web Components, etc.).

https://stackblitz.com/edit/github-xes2yo?file=src/pages/index.astro

---

@hans-d: I might expect a component passing thru a renderer like React or Preact to transform the props based on the expectations of that given framework. This means, in a specific context, a prop with an empty value _could_ be evaluated as true.

> That would be a breaking change, and perhaps not worth the effort...

IMHO, breaking changes are okay as Astro blooms.

---

@natemoo-re, that’s an excellent and wise point. I did some investigation. At a glance, it looks like the both the [client renderer](https://github.com/snowpackjs/astro/blob/astro%400.21.0-next.3/packages/renderers/renderer-react/client.js#L6) and [server renderer](https://github.com/snowpackjs/astro/blob/astro%400.21.0-next.3/packages/renderers/renderer-react/server.js#L51-L54) create a new props object. I _think_ this is good news, because a spread must create a new object and _also_ loop thru iterable keys. I _hope_ this means we could fix the issue (_if we agree it is a bug, of course_) without anything too concerning for performance. I’m very interested in your thoughts here.

**Comment by jasikpark** [comment]
https://github.com/withastro/astro/issues/307#issuecomment-857387526 has extra context

+ https://github.com/withastro/astro/pull/422 implemented support for both serializing the value as the empty value, while react would still interpret it as true?

It looks like this may have changed in the `v0.20` to `v0.21` shift.

**Comment by jasikpark** [comment]
Testing in `v0.21.12` it looks like it preserves the value for `data-*` attributes and not for other attributes like `empty`! https://stackblitz.com/edit/github-xes2yo-zslymn?file=src/pages/index.astro

<img width="1552" alt="Screen Shot 2021-12-10 at 9 42 04 PM" src="https://user-images.githubusercontent.com/10626596/145662537-a3d74c99-2e52-4631-ad05-116c5e17723e.png">

**Comment by jasikpark** [comment]
It looks like the tests weren't transferred over from uvu:

Testing components:

https://github.com/withastro/astro/blob/80c65e94973b937b408aabc39f75446ae03bf1e8/packages/astro/test/astro-attrs.test.js#L33-L41

Fixture:

https://github.com/withastro/astro/blob/80c65e94973b937b408aabc39f75446ae03bf1e8/packages/astro/test/fixtures/astro-attrs/src/pages/component.astro#L1-L8

**Comment by tony-sull** [comment]
A recent [RFC discussion](https://github.com/withastro/rfcs/discussions/105) was opened to revisit how attribute values are resolved :+1:

**Comment by tony-sull** [comment]
This has been cleaned up since the RFC discussion linked above :+1:

Astro now renders boolean attributes with `=""` as expected.  One note related to the original repro, passing the props through a `Div` component actually runs it through JSX which treats the `empty` attribute as a boolean flag - that forces the HTML to render as `empty="true"`.  Below is how Astro now renders this HTML when using the attributes in plain old HTML (i.e. not routing it through an Astro component that converts to JSX props)

```html
<div attr="val" empty=""></div>
<div empty="" attr="val"></div>
```
