### ISSUE TITLE
💡 RFC: Ability to set an element's `innerHTML` and `textContent`

### ISSUE THREAD

**Issue by natemoo-re** [withastro/astro#1827]
### Background & Motivation

One big TODO on #1222 is:

> To finalize: build output security, XSS, etc. (owner: not yet claimed)

Currently, Astro does not escape any content inside of expressions, meaning the following example will print out the HTML inside of `content`.

```astro
---
const content = "<h1>Hello world!</h1>";
---
<div>{content}</div>
```

If we ever want this behavior to go away, users need an alternative way to set the `innerHTML` and `textContent` of an element.

### Possible solution

Introduce special `set:innerHTML` and `set:textContent` attributes. These mirror the standard [`innerHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) and [`textContent`](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) properties, but are prefixed with `set:` to follow Astro's namespacing conventions.

```astro
---
const content = "<h1>Hello world!</h1>";
---
<div set:innerHTML={content} /> <!-- prints unescaped HTML -->
<div set:textContent={content} /> <!-- prints escaped HTML as text -->
```

#### ⛔️ Follow React's `dangerouslySetInnerHTML={{ __html: content }}` pattern
**Rejected because** Astro is a server-side templating language, where setting `innerHTML` from a trusted remote source is a very common use case. This is an extra hoop for devs to jump through. I'd argue it's an unnecessary extra step.

Solid uses [`innerHTML/textContent`](https://www.solidjs.com/docs/latest/api#innerhtml%2Ftextcontent) without any issue, they just document the inherent security risks.

#### ⛔️ A special `{@html}` directive like Svelte uses
**Rejected because** it doesn't feel very "Astro", by which I mean there are no other features that use a similar syntax.

#### ⛔️ Do not prefix `innerHTML` or `textContent` OR prefix with a special character (`@`, `:`, `$`, etc)
**Reason to reject**: Per convention, attributes that have special meaning in Astro should contain a `namespace:` prefix.

#### ⛔️ Do not introduce these, just continue allowing HTML inside of expressions
This approach is a bad practice. It has the potential for accidental XSS vulnerability introduction. It is unexpected, since it goes against the behavior of most other frameworks (React, Preact, Vue, Svelte, Solid).

It has also lead users down bad paths—I have seen community projects where HTML is dynamically concatenated into a giant string then stuffed into the Astro markup. This makes it impossible for Astro to optimize this markup because it never runs through our compiler. 

### Risks, downsides, and/or tradeoffs

Poor security practices are the main risk here. But I'd argue that having a construct like `set:innerHTML` that needs to be used intentionally is better than allowing arbitrary remote markup to leak into your site accidentally with an expression.

### Open Questions

- Is `set:` the right prefix? Open to ideas!
- What happens if `children` are also passed in?
- What happens if these attributes are set on Component nodes?
- What should we do about the existing HTML inside of expressions "feature"? ~~Likely to be spun off into a different RFC.~~ **See #1828**.
- Is `textContent` needed? It's a nice shorthand, but it depends on implementation complexity.
- Does `<Fragment>` support this? Could be very handy!

### Detailed Design

TBD. This would likely need to be tightly integrated with the compiler.

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by jonathantneal** [comment]
I’ve left a reply for your consideration on https://github.com/snowpackjs/astro/issues/1828#issuecomment-968434361 which is a response to this proposal as well.

**Comment by drwpow** [comment]
### RFC Call 2021-11-16

- Maybe don’t use DOM terminology? Because Astro files run on the server
- Does this mean that if you don’t use these, then content isn’t escaped? Are we making XSS protection opt-in?
  - That’s a separate RFC: 

### Suggestion

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
