### ISSUE TITLE
💡 RFC: Relative path handling in Astro

### ISSUE THREAD

**Issue by jonathantneal** [withastro/astro#1842]
# Background

In Astro HTML, it’s not always easy to know where a **relative** path points to.

```astro
<img src="./kitten.avif" alt="kitty" />
```

If a relative path is used inside of a component, then it might appear to be a reference to something relative to that component _in the source_. Instead, the path will be relative to the URL where the component was used _in the final output_.

### Goals

- Provide an intuitive way to reference locations relative to the source file.
- Provide an intuitive way to reference early (in Frontmatter) and late (in HTML).

### Non Goals

- Certain implementation details like API naming, argument shape, etc., because that can be decided later.
- Issues with relative 'links' that start with `/`, because it’s much more complicated.
  - A link starting with `/` is a relative link, while a path starting with `/` is an absolute path.
  - Vite 'muddies' this distinction by allowing `/` to be used as a relative link, or as an absolute path, or as a project relative path.
  - This RFC focuses on relative links that are also relative paths and calls them 'paths', for simplicity.
- An image component, because it’s much more complicated.
  - This RFC just happens to use a lot of image examples for simplicity.
  - Relative paths also affect `<a>`, `<link>`, `<script>`, etc. and Astro users continue to face issues with these [<sup>1</sup>](https://discord.com/channels/830184174198718474/845451724738265138/909188442653610024) [<sup>2</sup>](https://discord.com/channels/830184174198718474/845451724738265138/909468145075494944) [<sup>3</sup>](https://discord.com/channels/830184174198718474/909920313284890654/909951130795143249).
  - An image component could be a followup to this, focusing on other image-related issues like transformation & compression.

---

# Current Solutions:

Astro currently supports two solutions; one for 'late' resolution in the HTML block and one for 'early' resolution in the Frontmatter block.

### Relative URLs in `Astro.resolve`

> Current Solution 1 for late resolution

To author a relative path that is relative _to the source_, use `Astro.resolve` in Astro HTML.

```astro
<!-- src/components/my-kitten.astro -->
<a href={Astro.resolve('./my-kitten.avif')}>
  <img src={Astro.resolve('./my-kitten.avif')} />
</a>
```

**Pros**:

* This generates a path relative to the source that remains true in the final output.
* The path stays written alongside its context.
* This does not break the way JavaScript works.

**Cons**:

* The author must introduce a JavaScript block into their Astro HTML.
* The JS block interupts the flow of well-formed HTML.
  * This is even more problematic when `srcset` is used:
    ```astro
    <img
      alt="Clock"
      src={Astro.resolve('./my-kitten.avif')}
      srcset=`
        ${Astro.resolve('./my-kitten.avif')} 1x,
        ${Astro.resolve('./my-kitten@2x.avif')}
      `
    />
    ```

### Relative URLs in JavaScript Imports

> Current Solution 2 for early resolution

To author a relative path that is relative _to the source_, use an `import` in Astro Frontmatter.

```astro
---
import Kitten1x from './my-kitten.avif'
import Kitten2x from './my-kitten@2x.avif'
---
<img
  alt="Clock"
  src={Kitten1x}
  srcset=`
    ${Kitten1x} 1x,
    ${Kitten1x}
  `
/>
```

**Pros**:

* This generates a path relative to the source that remains true in the final output.
* The JS block interupts the flow of well-formed HTML much less than `Astro.resolve`.

**Cons**:

* The author must introduce a Frontmatter block into their file and a JavaScript block into their Astro HTML.
  * In cases like `srcset`, this still lacks cohesiveness with HTML.
* The author must move their URL away from its context.
* The author must give a meaningful variable name to the URL.
* This breaks the way JavaScript works.
* This prevents certain kinds if relative paths to be imported.
  * This is even more problematic if the asset _might_ also be import-able to JS:
    ```astro
    ---
    import linkToScript from './script.js'
    ---
    ```

---

# Proposed Solutions

Astro should continue to support two solutions; one for late resolution in the HTML block and one for early resolution in the Frontmatter block.

### Relative URLs in Namespaced Attributes

> Proposed Solution 1 for late resolution

To author a relative path that is relative _to the source_, use a `local` namespaced attribute.

```astro
<img
  alt="Clock"
  local:src="./my-kitten.avif"
  local:srcset="
    ./my-kitten.avif 1x,
    ./my-kitten@2x.avif
  "
/>
```

The `local` namespace would resolve relative paths in the attribute value while dropping the namespace from the attribute in the final output.

**Pros**:

* This generates a path relative to the source that remains true in the final output.
* This source is very cohesive with HTML.
* The author does not need to escape into JavaScript.
  * Which means this also does not break the way JavaScript works.
  * Which means the author does not also need to name any JavaScript variable.

**Cons**:

* The `local` namespace would need to be parsed to locate and transform relative paths.
* The 'late' processsing may increase the time it takes Astro to detect relative paths and add them to an asset graph.

## Relative URLs in Asserted JavaScript Imports

> Proposed solution 2 for early resolution

To author a relative path that is relative _to the source_, use an `import` with assertions in Astro Frontmatter.

```astro
---
import Kitten1x from './my-kitten.avif' assert { type: "url" }
import Kitten2x from './my-kitten@2x.avif' assert { type: "url" }
import linkToScript from './script.js' assert { type: "url" }
---
```

These type assertions would communicate how the file should be interpretted by JavaScript.

**Pros**:

* This generates a path relative to the source that remains true in the final output.
* This respects the way JavaScript works.
* This allows any relative paths to be imported.
* This syntax is permitted by our VSCode extension.

**Cons**:

* The author must introduce a Frontmatter block into their file and a JavaScript block into their Astro HTML.
  * In cases like `srcset`, this still lacks cohesiveness with HTML.
* The author must move their URL away from its context.
* The author must give a meaningful variable name to the URL.
* This syntax is not yet supported by the Astro compiler.

---

# Alternative Solutions:

### Relative URLs with a Custom Scheme

> Alternative solution 1 for late resolution

To author a relative path that is relative _to the source_, use a `local` schema.

```astro
<img
  alt="Clock"
  src="local:./my-kitten.avif"
  srcset="
    local:./my-kitten.avif 1x,
    local:./my-kitten@2x.avif
  "
/>
```

**Pros**:

* This generates a path relative to the source that remains true in the final output.
* This source is very cohesive with HTML.
* The author does not need to escape into JavaScript.
  * Which means this also does not break the way JavaScript works.
  * Which means the author does not also need to name any JavaScript variable.
* The schema could be supported in other APIs (like JavaScript URLs) for consistency.

**Cons**:

* The `local` schema would need to be parsed in every attribute to locate and transform relative paths.
* The 'late' processsing may increase the time it takes Astro to detect relative paths and add them to an asset graph.

### Relative URLs with Query Parameters

> Alternative solution 2 for early resolution

To author a relative path that is relative _to the source_, use an `import` with query parameters in Astro Frontmatter.

```astro
---
import Kitten1x from './my-kitten.avif?type=url'
import Kitten2x from './my-kitten@2x.avif?type=url'
---
```

These query parameters communicate how the file should be loaded.

**Pros**:

* This generates a path relative to the source that remains true in the final output.
* This allows any relative paths to be imported.
* This syntax is permitted by our VSCode extension, and Vite may already support it.

**Cons**:

* The author must introduce a Frontmatter block into their file and a JavaScript block into their Astro HTML.
  * In cases like `srcset`, this still lacks cohesiveness with HTML.
* The author must move their URL away from its context.
* The author must give a meaningful variable name to the URL.
* This breaks the way JavaScript works (without `assert { type: 'json' }`).

---

### Should all relative paths without custom syntax warn or throw? 

No, Astro HTML should respect well known and well established conventions in HTML. If you intentionally use relative paths and are comfortable with this context, you’ll be very glad to know that Astro won’t make you change valid HTML.

### Should Astro Support Multiple Solutions?

Yes, Astro needs to support late resolution and early resolution. For late resolution in Astro HTML, the solution should be cohesive with HTML. For early resolution in Astro Frontmatter, the solution should be cohesive with JavaScript.

### How would import assertions work in Astro?

1. The compiler handling Astro Frontmatter would need to pass thru import assertions.
2. The Acorn plugin for import assertions would need to added to Rollup.
3. The Rollup transform handler would need to return the resolved id path when the assertion instructed so.

**Comment by aFuzzyBear** [comment]
Excellently written, well put together RFC, 

I have to say, given the merits of the arguments presented, it would be more prudent to pursue; Proposed Solution 2,

```
import Kitten1x from './my-kitten.avif' assert { type: "url" }
```

Over the current vite implementation of using URL Query Params, 

This would presumably make resolving the static paths easier to administer

It could also pave the way forward to help federate the imports of different UI components and assertions to their render runtimes,

```
import SideBar from '../components/SideBar.jsx' assert { type: 'react' }
```

( brough from discussion with @jonathantneal, this being pure conjecture ) 
However the considerations implied with this form of assertion would be clearer to not only the compiler but also suit a stronger DX,

**Comment by FredKSchott** [comment]
Thanks for taking a look at this Jon! Really well written! I haven't given it a deep enough read for specific comments yet, but 2 things jump out that I'd love clarity on, both related to Vite's new role in all this after v0.21:

1. Your alternative solution around `?type=url` is already supported in Vite and by extension Astro in 0.21. Isn't it a distraction to call that an alternative solution, since it gives the impression that we're evaluating it against these other solutions, when it already exists today? It feels like it belongs in "Current Solutions" since it is currently supported. https://vitejs.dev/guide/assets.html#explicit-url-imports
2. Similarly, we could probably find out what Vite's plans are regarding import assertions and what that will look like. If they ship support similar to their current approach to `?url`, Astro would also get this for free and the same question as above would apply. It could be worth reaching out and getting some insight. I expect that getting that support for free (no matter what we do) would be a big part of the calculation on what additional work we want to do on our end.

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
