### ISSUE TITLE
🐛 BUG: Using a Sass @mixin after you @use from an Astro component

### ISSUE THREAD

**Issue by chriscoyier** [withastro/astro#2032]
### What version of `astro` are you using?

0.21.4

### What package manager are you using?

npm

### What operating system are you using?

StackBlitz

### Describe the Bug

See example started from the Starter example at astro.new

https://stackblitz.com/edit/github-ze9ebb?file=package.json&on=stackblitz

![CleanShot 2021-11-28 at 07 09 12@2x](https://user-images.githubusercontent.com/69156/143773776-0df04602-4d49-4e5d-a511-d2b8705e6803.png)

Causes this "out of range" panic:

![CleanShot 2021-11-28 at 07 09 48@2x](https://user-images.githubusercontent.com/69156/143773809-7754a86c-dc32-4a27-b41e-c1978cb2bb61.png)

(Happens locally too, not just on StackBlitz)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ze9ebb?file=package.json&on=stackblitz

**Comment by ludofischer** [comment]
I can also reproduce it by replacing the `.module.css` file with an SVG image or a plain CSS file. I suspect this happens with any file type besides `.astro` and `.md`. 
I think the issue is that `createRouteManifest()` does place any file type it finds in `pages` inside `routes`, there are no extension checks 
https://github.com/withastro/astro/blob/56133d1c2084fb8978e347d62df6347ec6c40108/packages/astro/src/core/ssr/routing.ts#L86

**Comment by drwpow** [comment]
We definitely want to show Sass errors rather than “panic.“ It’s definitely undesirable behavior that Sass errors not only are hidden, but often crash the dev server and require a restart. I’ll treat part of this ticket as addressing that.

But from the code posted I think there’s an error. Either the use statement should change to `@use "../styles/test.scss" as *;`, or the mixin should change to `@mixin test.cool;`. But how would you know that from just seeing “panic?”

Once we’re seeing Sass errors come through better, there may be another underlying issue here, TBD.

**Comment by chriscoyier** [comment]
Yeah same. Locally I get:

```
panic: runtime error: index out of range
wasm://wasm/0025ee26:1


RuntimeError: unreachable
    at <anonymous>:wasm-function[205]:0xdf4e
    at <anonymous>:wasm-function[14]:0x9d0
    at <anonymous>:wasm-function[831]:0x69a0a
    at <anonymous>:wasm-function[292]:0x13373
    at resume (<anonymous>:wasm-function[299]:0x1409a)
    at Go._resume (file:///Users/chriscoyier/GitHub/serverless/node_modules/@astrojs/compiler/node/wasm_exec.js:374:28)
    at file:///Users/chriscoyier/GitHub/serverless/node_modules/@astrojs/compiler/node/wasm_exec.js:384:16
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by drwpow** [comment]
Ah so I think it was just a hidden error! This fixed it for me:

```scss
@use "../styles/test" as *;

article {
  @include cool;
}
```

`@mixin` is used to define the mixin; `@include` is used to inject it (which I didn’t know without looking it up; it’s been years since I’ve used mixins!)

**Comment by drwpow** [comment]
#2049 displays good errors from Sass now; so that should be fixed in the next release of Astro.

**Comment by chriscoyier** [comment]
Ah yeah...

Updated the stackblitz to have the correct syntax and it works fine:
https://stackblitz.com/edit/github-ze9ebb?file=src%2Fcomponents%2FTour.astro&on=stackblitz

I'll just close since it's really just a syntax mistake the the sass-killing-astro stuff is already addressed.

**Comment by drwpow** [comment]
`0.21.6` released! Hopefully Sass errors should be more clear now

**Comment by tr1s** [comment]
> ```css-scss
> @use "../styles/test" as *;
> ```

How did you figure out the `as *` part? What exactly is happening here? I just ran into this issue as well because I had it omitted. Thanks!

**Comment by tr1s** [comment]
@drwpow 

> ```css-scss
> @use "../styles/test" as *;
> ```

How did you figure out the `as *` part? What exactly is happening here? I just ran into this issue as well because I had it omitted. Thanks!
