### ISSUE TITLE
🐛 BUG: CSS imported in different layout files are added to html in reverse hierarchy of layouts

### ISSUE THREAD

**Issue by amithgeorge** [withastro/astro#2042]
### What version of `astro` are you using?

0.21.4

### What package manager are you using?

npm

### What operating system are you using?

stackblitz

### Describe the Bug

I am importing css files in my layouts. `BaseLayout` wraps `PageLayout`, which wraps the page-specific content. 

My expectation is that the css file imported in `BaseLayout` should be overridden by the css file imported in `PageLayout`, ie normal CSS cascading. The reality is different. In the dev server mode, the built page first includes the `PageLayout` css, and then the `BaseLayout` css. This is demonstrated on this page https://stackblitz.com/edit/github-qoihup?file=src/pages/index.astro . 

The issue persists even in the production built files present in the dist folder. 

This was confirmed as an issue in the [discord support channel](https://discord.com/channels/830184174198718474/914902575608905779/914906140154949663)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qoihup?file=src%2Fpages%2Findex.astro

**Comment by matthewp** [comment]
Ok, I have a branch with a fix for this, but now I'm having my doubts. This issue comes down to import ordering. Let's take layout components out of the equation. Let's say you had:

```js
import './one.css';
import './two.css';
```

Would you expect `one.css` to override `two.css`? I'm not sure that I do, since I am listening them in order, I am saying that I want `two.css` to win.

This is the same thing that is happening in your example. If you move your CSS import to after the layout import, you get what you wanted.

```astro
---
import BaseLayout from "./BaseLayout.astro"
import "../styles/page-one.css"
---
```

Should work. Happy to discuss this further.

**Comment by matthewp** [comment]
As I think this is working the way I would expect I'm going to close. Happy to keep chatting about it though.
