### ISSUE TITLE
🐛 BUG: Need an option to output raw strings, at least in tag attributes like `href`

### ISSUE THREAD

**Issue by ludwigschubert** [withastro/astro#2095]
### What version of `astro` are you using?

0.21.7

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Say I want to output HTML character references, for example a symbolic one `&amp;` or a numeric one `&#64;`. When I interpolate such a string in an Astro template, I observe two distinct behaviours: when placed in text, the entities are evaluated at build time. When used in tag attributes, such as an anchor tag's `href`, the entities are encoded _again_.

Both behaviours seem helpful by default, but for both it would be nice to provide an "escape hatch" that avoids _any_ additional string processing by Astro.

### HTML entities are being URL encoded in tag attributes:

```jsx
<a href={html_entity_encode("mailto:test@example.com")>Example</a>
```
[The resulting output](https://github.com/ludwigschubert/withastro-astro-issue-escaping-html-entities-in-attributes/blob/8210e25d77d64b2f4a796b08ece92b49939326b1/dist/index.html#L13) looks like `&amp;#116;…` instead of `&#116;…`. One fix may be to detect HTML entities and not double escape them, but more generally I believe I'd like a way to directly tell Astro: I have a string that I'd like you to include verbatim in my build output. 

I believe Svelte used to offer `{{{triple_braces}}}` for such cases, but I have no strong opinion on syntax.

(If you're wondering about a real-world use case: I stumbled over this when trying to obfuscate email addresses using HTML numerical entity encoding.)

### Related Discussion

- Discord #support [thread](https://discord.com/channels/830184174198718474/845451724738265138/915942034899099679)
- (old, potentially unrelated) https://github.com/withastro/astro/issues/704
- https://github.com/withastro/astro/issues/974

Mentioning @natemoo-re who encouraged me to open this as an issue.

### Link to Minimal Reproducible Example

https://github.com/ludwigschubert/withastro-astro-issue-escaping-html-entities-in-attributes/

**Comment by natemoo-re** [comment]
Thanks for opening an issue! Your use case is totally reasonable, and I'd love to find a way to support it. I'd be very curious to hear what others think the syntax should be.

**Comment by tony-sull** [comment]
@natemoo-re Does this look like it would have been fixed with the `set:html` feature?

**Comment by matthewp** [comment]
`set:html` works for HTML but there isn't an equivalent for attributes. We'll need an RFC in order to provide this functionality: https://github.com/withastro/rfcs

**Comment by jlbribeiro** [comment]
@matthewp Given the issue's title (and its original example) is about being able to output raw strings in attributes, couldn't/shouldn't this issue be open?
I stumbled upon this issue with the exact same use case ("obfuscated" `mailto:` URL), which requires such capability.

Thank you!

**Comment by m4rrc0** [comment]
+1 is there an RFC already?

**Comment by einarmagnus** [comment]
Here's another use case:

I have a textarea where I want the placeholder text to be several lines, including gaps.

In raw html this is simple:
```html
<textare placeholder="line1&#10;&#10;line after gap"></textarea>
```

but like above, Astro escapes the ampersands so that my html becomes:
```html
<textare placeholder="line1&amp;#10;&amp;#10;line after gap"></textarea>
```
Which of course doesn't work like I want it to.

If I use `\n` instead, it works if I don't have more then one in a row because chrome 🤷  
The reason there has something to do with whitespace. Astro does not escape `\n`, but does escape `&`, what gives?

Is there a way to either have astro escape `\n` in attributes or not escape `&`? Either will be great.

Thanks 🙏

**Comment by mversic** [comment]
where I would find this useful is when combining astro with html templating. I have frontend code written in astro with a custom backend in Rust. Without going into why I do it like this, on a few occasions, I'm doing very simple manual SSR where I don't want astro to escape my strings (since they are templated Rust code). This is not possible in astro as of today:

```astro
---
import LandingPage from '@/layouts/LandingPage.astro';
---

<LandingPage  pathname='/transfer/{% slugs["en-us"] %}'/>
```
