### ISSUE TITLE
🐛 BUG: Vite looses connection to callbacks of idle and visible

### ISSUE THREAD

**Issue by Tylopilus** [withastro/astro#2139]
### What version of `astro` are you using?

0.21.10

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

After beeing afk vite loses connection to the cb of the idle.js / visible.js running in dev mode locally.

I cannot tell when this happens. A page refresh does not help / nor a different browser. Only way to resolve is restarting the server.
![image](https://user-images.githubusercontent.com/45148577/144932017-a7120bf1-b55e-40e1-8622-92b79d9a0d91.png)
I did not test this on stackblitz

### Link to Minimal Reproducible Example

https://stackblitz.com

**Comment by jonathantneal** [comment]
Thanks for letting us know Could you tell me more about the "afk"? Was this an hour? A few minutes? A few seconds? It’s going to be extremely difficult to diagnose without a bit more detail. 😅

**Comment by markpinero** [comment]
I notice this issue happening when running in dev mode and then running a build on a separate terminal window.

**Comment by tony-sull** [comment]
Hey, this issue is out of date and may have been fixed in the latest version of Astro. If you can still reproduce the issue with the latest version of astro (`npm install astro@next`) please open a new issue and we can take a deeper look. :+1:

This should be fixed in `astro@next` which upgrades to the latest version of Vite and moves Astro over to using Vite's built-in dev server :+1:
