### ISSUE TITLE
🐛 BUG: scoped css misses some tags

### ISSUE THREAD

**Issue by kuworking** [withastro/astro#2159]
### What version of `astro` are you using?

0.21.10

### What package manager are you using?

node 16.13.1 npm 8.1.2

### What operating system are you using?

windows 10

### Describe the Bug

If you render some tag in `.astro` like in here:

```
---
const p1 = {title: 'hi #there#', url:'#hi'}
const p2 = {title: 'ho #thero#', url:'#ho'}
const posts = {js: [p1, p2]}
---
```

```js
    {Object.entries(posts).map(([k, v]) => (
      <div>
        <div class="tag">{k}</div>
        <div class="posts">
          {v.map(p => (
            <div>
              <a class="link" href={p.url}>
                {p.title.split('#').map((el, i) => (i % 2 === 0 ? `<span>${el}</span>` : `<em class="em">${el}</em>`))}
              </a>
            </div>
          ))}
        </div>
      </div>
    ))}
```

Then it seems that `css` can affect `.link` but not `.em`

```
    <style>
        .link {color: #003bff}
        .em {color: #f00}
    </style>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-7tpdkw?file=src/pages/index.astro

**Comment by toSayNothing** [comment]
you can solve it by use `jsx` for the `span` and `em` element
```js
{p.title.split('#').map((el, i) => (i % 2 === 0 ? `<span>${el}</span>` : `<em class="em">${el}</em>`))}
// change to :
{p.title.split('#').map((el, i) => (i % 2 === 0 ? <span>{el}</span> : <em class="em">{el}</em>))}
```
use `jsx`, so astro can attach the scope id for the element

**Comment by tony-sull** [comment]
Hey, this issue is out of date and may have been fixed in the latest version of Astro. If you can still reproduce the issue with the latest version of astro (`npm install astro@next`) please open a new issue and we can take a deeper look. :+1:

Looks like this may have actually been fixed in a more recent version of astro, but if you're still seeing this and the solution above doesn't work feel free to open a new issue with a repro on `astro@next` and we'll dig deeper!
