### ISSUE TITLE
🐛 BUG: Built Javascript lost on server 

### ISSUE THREAD

**Issue by Scaalees** [withastro/astro#2214]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Vite, Vue.js

I'm handing over the dist folder to another developer that is adding to their Salesforce platform.
And all files are integrated correctly with Salesforce `?$staticlink$` query other than the js files inside index.js.

I'm seeing a problem with js triggering a 404 error from the index.js file in assets.

Here's the folder structure of the assets:
<img width="303" alt="Screenshot 2021-12-16 at 15 17 48" src="https://user-images.githubusercontent.com/9265854/146404078-f8cfd3a4-6206-4b39-b1dd-f93d120e516f.png">

And the file in question:
<img width="902" alt="Screenshot 2021-12-16 at 15 36 26" src="https://user-images.githubusercontent.com/9265854/146404119-c51cd1ed-de70-4ccc-84cf-b0d131321f01.png">

As you can see, vendors.js is pulled in on load with the import function at the top of the index.js file:
![Screenshot-2021-12-16-at-15 18 43](https://user-images.githubusercontent.com/9265854/146405123-8736ed7b-b2ea-4a7f-9b1b-5462381d1e7f.jpg)

However other components and files are not:
![Screenshot-2021-12-16-at-15 19 54](https://user-images.githubusercontent.com/9265854/146405105-43bf5d60-849e-4857-bd2c-7a3e9898aa91.jpg)

I'm not sure if this is a problem or just something with Salesforce as the file is resolved eventually. But the 404s aren't ideal.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/yqnixjqla?file=src/pages/index.astro

**Comment by jonathantneal** [comment]
I’m unable to see this StackBlitz link. Could you share it again or share a new one?

**Comment by Scaalees** [comment]
StackBlitz won't allow me to share. But it's just the deault vue project.
https://github.com/Scaalees/astro-vue-dist-files-issues

The issue is in the dist folder that is generated. Check the dist index file.

**Comment by tony-sull** [comment]
Hey, this issue is out of date and may have been fixed in the latest version of Astro. If you can still reproduce the issue with the latest version of astro (`npm install astro@next`) please open a new issue and we can take a deeper look. :+1:

The `@next` release updates astro to the latest version of Vite and migrates to using Vite's built-in dev server, I think that should have this fixed.  If not, try using the `--experimental-static-build` CLI flag with astro which also cleans up a lot of dependency graph issues :+1:
