### ISSUE TITLE
🐛 BUG: Named Slots are not forwarded to Svelte Components

### ISSUE THREAD

**Issue by ptrxyz** [withastro/astro#2238]
### What version of `astro` are you using?

0.21.12

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When I am using named slots with Svelte components, they don't seem to be passed on to the component.
I have a minimal example in here: https://stackblitz.com/github/ptrxyz/astro-bug-named-slots

Please check index.astro, there is a named slot "msg", which then is not rendered in my component.

I thought I would dig a bit into this and check what is actually used to render the markup. I found the file `node_modules/@astrojs/renderer-svelte/server.js` and added some debug to 
```
async function renderToStaticMarkup(Component, props, children) {
  console.log({props, children})
  const { html } = SvelteWrapper.render({ __astro_component: Component, __astro_children: children, ...props });
  return { html };
}
```
The documentation says this is used for the renderers, but it seems my named slots are not even passed to the `renderToStaticMarkup` function. This seems to be broken.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/ptrxyz/astro-bug-named-slots

**Comment by matthewp** [comment]
Slots in Astro files only work with .astro components. Framework components have their own concepts of slots, but they do not work across frameworks, like what is trying to be done in this example. 

What I recommend instead is creating another Svelte component that uses the slots.

**Comment by andersbc** [comment]
@matthewp ..could you provide a little more guidance on the recommendation? I don't get it.. 

(even if you wrap the 'named slot' svelte component with another 'outer' svelte component you still cannot pass content into the inner svelte components' named slots from astro. At least not in an `.md` file)

Named slots a are standard feature of svelte and vue components (I'm using vue) - one that astro has adopted - so it would really cool if astro did support it.

On a side note: I don't understand how this issue is different from https://github.com/withastro/astro/issues/1717

**Comment by Jutanium** [comment]
I agree with @andersbc; this is counterintuitive behavior that should be cleared up!
