### ISSUE TITLE
🐛 BUG: Changes to @imported CSS in a style tag are cached until server restart

### ISSUE THREAD

**Issue by matthewp** [withastro/astro#2317]
### What version of `astro` are you using?

0.22.5

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

If you add CSS to your .astro file like so:

```astro
<style global>
  @import "../styles/main.css";
</style>
```

And then make changes to `main.css`, those changes will never reflect until a server restart. Note that `global` is irrelevant here, the same behavior occurs either way.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-phs6ma?file=src/styles/main.css

**Comment by FredKSchott** [comment]
Did I understand correctly that the CSS inside of a `<style>` tag gets moved into a virtual CSS file that then gets imported by the final compiled JS file? If that's the case, then I'm curious if this happens in normal CSS.

If this is something that we need to tackle on our end, then I also bet that the Svelte or Vue plugins for Vite would give some hints on how to solve this. 

It reminds me of Sass in Snowpack, where we had to add this import tracking ourselves so that `@use` worked correctly with HMR. Hopefully that's not the case here.

**Comment by matthewp** [comment]
> Did I understand correctly that the CSS inside of a <style> tag gets moved into a virtual CSS file that then gets imported by the final compiled JS file? 

In the static build flag yes, but this bug occurs without that flag as well. What it appears is that vite:css sets up the dependency tracking normally, but does not do so with the way that we are calling it for .astro files. I haven't looked into the problem deeply yet though.

**Comment by matthewp** [comment]
Fixed by @2440

**Comment by X7md** [comment]
I upgrade to `astro 0.22.19`, but didn't fixed... I still need to restart dev server...

https://user-images.githubusercontent.com/54203033/151418633-cc5ece0d-90e8-450b-a63f-21586d4896d7.mp4

**Comment by matthewp** [comment]
@X7md this is only fixed if using the `--experimental-static-build` flag.
