### ISSUE TITLE
🐛 BUG: Global CSS is duplicated for hydrating and non-hydrating files (with Tailwind CSS)

### ISSUE THREAD

**Issue by Siilwyn** [withastro/astro#2568]
### What version of `astro` are you using?

0.22.20

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

Using the Preact & Tailwind CSS example I found the generated stylesheet to be saved in two CSS files with identical content. This seems like a bug, maybe it is known unwanted behavior?

The reproducible example runs in production (`astro preview`). The bug is easiest to see by looking at the network tab while clicking through the navigation in a new window: https://ed7un-3000.sse.codesandbox.io/

### Link to Minimal Reproducible Example

https://codesandbox.io/s/astro-with-tailwind-issue-ed7un

**Comment by tony-sull** [comment]
@Siilwyn I think this is actually expected behavior, but wanted to double check that I understood the issue properly :+1:

Are these the duplicated CSS files you're looking at, [static](https://ed7un-3000.sse.codesandbox.io/assets/index.3e360b9b.css) and [hydrated](https://ed7un-3000.sse.codesandbox.io/assets/hydrating-two.edae120e.css)?

If so, there's actually a really subtle difference between those two, I had to run it through a diff tool to see it!  The hydrated CSS includes styles for `astro-root` (at the very end of the CSS).  That's used by astro internally when hydrating client components, so in the case of a fully static page that CSS rule isn't included at all

**Comment by Siilwyn** [comment]
Yes that is exactly what I mean. 👍 

Even it is is expected behavior it might be worth reconsidering? Especially for a small website with a couple of pages and TailwindCSS it makes no sense to essentially double the CSS size.

Sorry if I'm missing the point here but why not always include the astro class, it's so small: `astro-root,astro-fragment{display:contents}`. Unless it can grow?

**Comment by FredKSchott** [comment]
Fixed by no longer recommending `@import` for tailwind for this reason. See the new recommendations here: https://docs.astro.build/en/guides/styling/#-tailwind
