### ISSUE TITLE
🐛 BUG: Tailwind CSS template duplicating CSS on hot reload

### ISSUE THREAD

**Issue by wtchnm** [withastro/astro#2629]
### What version of `astro` are you using?

0.23.0

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

1. Go to the StackBlitz link.
2. Change the button background color in /src/components/Button.
3. Inspect the page. The will be a style tag with the CSS injected by set:html and a link tag referencing the file used by set:html.
![image](https://user-images.githubusercontent.com/37726261/154826769-4e7ab079-e589-40a4-b731-cc3fdda47396.png)

If I use a standard link tag as the **Global styles** section of the [Styling guide](https://docs.astro.build/en/guides/styling/) teaches, HMR works fine and there is no CSS duplication.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/with-tailwindcss

**Comment by wtchnm** [comment]
@tony-sull maybe you can help?

**Comment by tony-sull** [comment]
Oh that's a strange one, when the page is first built it doesn't include a `<link>` for `global.css` but it is added after a hot reload

The current example is a bit of a workaround due to [#2597](https://github.com/withastro/astro/issues/2597), but it looks like we'd be better off using a `<style global>` block to inject the `@tailwind` styles instead

**Comment by tony-sull** [comment]
@wtchnm Thanks for catching this!  I just filed [PR 2640](https://github.com/withastro/astro/pull/2640) with a better approach to importing the global styles to play nice with the dev server's HMR

**Comment by wtchnm** [comment]
@tony-sull thanks!

**Comment by FredKSchott** [comment]
Fixed in v0.24.0!
