### ISSUE TITLE
🐛 BUG: Astro not handling props for the Auth component from @supabase/ui properly

### ISSUE THREAD

**Issue by silverAndroid** [withastro/astro#2635]
### What version of `astro` are you using?

0.23.0

### What package manager are you using?

pnpm (example uses npm)

### What operating system are you using?

Mac

### Describe the Bug

I'm using an Auth component from `@supabase/ui` with Astro and I was able to get it to hydrate client side by setting the `realtime.decode` to an empty function (can see inside `src/lib/supabaseClient.ts` in the example) because it's a native function. However, when the component internally calls `supabaseClient.auth.signIn` (when I press the sign in button), it throws an error saying that it isn't a function.

I know that property is a function because I have it logged as a function inside that file just to be sure. I imagine it's during some part of the hydration process that gets rid of this function.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jwtsln-vudpmv?devtoolsheight=33&file=src/pages/index.astro

**Comment by FredKSchott** [comment]
Good catch! We serialize the props to JSON so that they can run on the client, my guess is that the JSON serialization is getting rid of the function that you want to call.

Instead of passing the JS prop to the island, can you have the whole thing load inside of an React component? This will move the entire supabaseClient logic from server-side (where `.astro` files) to client-side, and skip the JSON serialization step entirely. Here's an example: https://stackblitz.com/edit/github-jwtsln-stue44?devtoolsheight=33&file=src%2Fpages%2Findex.astro
