### ISSUE TITLE
🐛 BUG: Using ?url with hoisted scripts are not included in the build

### ISSUE THREAD

**Issue by matthewp** [withastro/astro#2648]
### What version of `astro` are you using?

0.23.0

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

If you add a hoisted script this way:

```astro
---
import url from '../scripts/test.js?url';
---
<script type="module" src={url} hoist></script>
```

They are not included in the build.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tejeez?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by FredKSchott** [comment]
lol the asset fun continues! 

I think that makes sense, `<script hoist>` is itself a special kind of element that is telling the renderer something to do (vs. rendering something to the page). But it's obviously odd to have `<script src="">` do one thing and `<script hoist src="">` do another.

Because I have my API design hat on, this is a teeny-tiny point to keep in mind in the "should `<script hoist>` really be `<astro:script>`?" discussion when we go to finalize APIs and naming. In retrospect I'm glad I didn't get too far on my `<script @component>` before we hit this :)

**Comment by matthewp** [comment]
This was merged into `next` in the compiler, so going to close this bug. 

https://github.com/withastro/compiler/pull/267
