### ISSUE TITLE
🐛 BUG: <style> @import is scoped to the Astro template incorrectly

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#2655]
## Unexpected Behavior

When I use `<style>@import '...';</style>` inside of an Astro template, the imported CSS file is inlined _before_ scoping takes place, and therefore gets scoped to the template. This makes it impossible to do something like `<style>@import './global.css';</style>` in an Astro component, since the global styles will be scoped to the component itself. 

The current workaround is to use `<style global>@import '...';</style>` for all CSS imports, which skips scoping entirely.

## Why is this happening?

Inside the Astro build (vite) plugin, we ask Vite to transform all styles for us. This is nice because it lets us tap into whatever CSS processors you've enabled for Vite (Sass, Less, etc). However, it also means that Vite will run its dev/build-specific transforms as if the file were being finalized. This includes @import inlining, so that by the time our compiler sees the processed CSS it's already been inlined.

## What should we do to fix?

I believe we should not be calling Vite's built-in CSS transform here, since it is meant to be an internal handler and wasn't designed with this use-case in mind. Instead, I believe that we can implement our own style pre-processor that leaves this Vite internal plugin alone. If built correctly, it can still share a lot of the same logic, and wouldn't involve additional "over-processing".

Some prototyping still needed!

**Comment by FredKSchott** [comment]
Oh no, I found a short-term fix, but yall won't like it!

```
currently: run transformWithVite() on every style style element contents
idea: strip out the `@import` before running transformWithVite(), then add it back after.
```

**Comment by matthewp** [comment]
The current behavior seems ok to me, why do you call `<style global>@import '...';</style>` a workaround? It seems like what I would expect. Since `<style>` scopes I would expect it to also scope imported styles (since a CSS @import is basically just an include). If you don't want it to be scoped use the `global` attribute. I have a side project which does exactly that.

If we disabled scoping for regular `<style>` then how would you say "please scope this"?

**Comment by sentisso** [comment]
Well... now it isn't possible to scope the imported styles...

When SCSS is written inside the `<style lang="scss">` tag, it gets formatted funny and it's just ugly to work with.
I wanted to fix this by creating separate `.scss` files, which get formatted correctly and get all the correct highlighting in all the IDEs, and them import them in their corresponding components or pages.

But none of the ways to import an external style file will make them scoped!

**Comment by sentisso** [comment]
Absolutely agree with @matthewp. This is not the correct way to do this and this doesn't seem like an issue.

My real-world scenario of why it just stay the way it was:
When SCSS is written inside the `<style lang="scss">` tag, it gets formatted funny and it's just annoying to work with.
I wanted to fix this by creating separate `.scss` files, which get formatted correctly and get all the correct highlighting in all the IDEs, and them import them in their corresponding components or pages.

But none of the ways to import an external style file will now make them scoped!

**Comment by rienheuver** [comment]
I would like this issue to be reopend (@natemoo-re ?) since it seems still broken to me. I use this pattern to write my css in `.css` files and not inside my components, it's just what I prefer. So I have a component `menu.astro` accomponied by `_menu.css` and inside `menu.astro` I have:
```
<style>
 @import "./_menu.css";
 </style>
 ```

The css in `_menu.css` gets imported globally _and_ scoped. So it will appear something like this:
```
nav[data-astro-cid-25mmku5a] {
    position: fixed;
    top: 0;
    width: 100%;
   (...)
}
nav {
    position: fixed;
    top: 0;
    width: 100%;
    (...)
}
```

This cannot be intended behaviour since it appears twice now. In my case I only want the scoped css to be there (of course). I use this in a variety of components and it currently breaks my layout since they're not properly scoped.
