### ISSUE TITLE
🐛 BUG: Sourcemap for "@lit-labs/ssr/lib/dom-shim.js" points to missing source files

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/astro#2814]
### What version of `astro` are you using?

0.24.3

### What package manager are you using?

pnpm

### What operating system are you using?

Ubuntu

### Describe the Bug

When running `astro dev` or `astro build` it logs a message to the console that `Sourcemap for "/long/path/to/node_modules/@lit-labs/ssr/lib/dom-shim.js" points to missing source files`. It's a warning so it doesn't affect the build process. But the warning is misleading for the user as they have nothing to do to fix it. So, if possible these warnings should be ignored if they are coming from `@lit-labs/ssr` or any other node module.

### Link to Minimal Reproducible Example

https://astro.new/framework-lit?on=stackblitz

**Comment by FredKSchott** [comment]
Tracking this issue here: https://github.com/lit/lit/issues/2645

We have moved away from swallowing Vite warnings for our users, since the warning is pointing to a valid bug in the dependency package. We should attempt to fix the root issue for all users to benefit from, vs. papering over the issue in our own codebase.
