### ISSUE TITLE
🐛 BUG: <body> styles are not scoped

### ISSUE THREAD

**Issue by ymcheung** [withastro/astro#2827]
### What version of `astro` are you using?

0.24.0

### What package manager are you using?

yarn 3.2.0

### What operating system are you using?

macOS 10.15

### Describe the Bug

I forked Blog template from Doc and started building my own one.
I want to style `<body>` in `/pages/index.astro` and `/layouts/BlogPost.astro`.
At `0.22.20`, styling `<body>` worked well, but `body { ... }` in `BlogPost.astro`  overrode `body { ... }` in `index.astro` after bumping to `0.24.0`. I thought the styles were scoped?

![BlogPost css](https://user-images.githubusercontent.com/4409977/158923422-73c51121-32b1-4c13-8f4c-cd280b2251cf.png)

### Link to Minimal Reproducible Example

https://codesandbox.io/s/mystifying-noether-umny80?file=/src/pages/index.astro

**Comment by tony-sull** [comment]
This is actually by design, it's only valid to have one `<body>` tag on the page so there scoping isn't really necessary

I usually recommend keeping all global styles like `html` and `body` in one place, either a file like `styles/global.css` or in a `<style>` block in the layout component where the `<body>` tag is included

---

### Random

One interesting thing I noticed in the repro, every page uses `<BaseHead>` which is importing `src/styles/blog.css`.  That file is styling the `<body>` with `background: var(--theme-bg);` but that's being overridden in the home page and the blog post layout with `background-color`

Imported CSS files are always bundled after any inline `<style>` blocks, which can lead to really confusing behavior for these tags that don't get scoped.  In this case `background-color` is used in the layouts so that will always take priority over `background`, but it's really easy to end up with frustrating to debug styling issues when the layout's inline style is actually stepped on by the global `.css` file

**Comment by IanVS** [comment]
I just wanted to chime in that I had the same situation happen, my "global" styles were being imported in a base head component.  I expected my scoped styles in the layout component to override them, but it doesn't. The docs just say:

>There are two ways to resolve external global stylesheets: an ESM import for files located within your project source, and an absolute URL link for files in your public/ directory, or hosted outside of your project.

Do you think it would be worth mentioning in the docs that imported styles are always placed after inline styles in the cascade?  Is that accurate?

**Comment by whyte50** [comment]
> I just wanted to chime in that I had the same situation happen, my "global" styles were being imported in a base head component.  I expected my scoped styles in the layout component to override them, but it doesn't. The docs just say:
> 
> >There are two ways to resolve external global stylesheets: an ESM import for files located within your project source, and an absolute URL link for files in your public/ directory, or hosted outside of your project.
> 
> Do you think it would be worth mentioning in the docs that imported styles are always placed after inline styles in the cascade?  Is that accurate?

I also I'm having the same issue at the moment, and I'm using the `! important` on the CSS. Although I'm trying it out for the first time, I'm still concerned going forward with it ( the CSS issue that is )
