### ISSUE TITLE
🐛 BUG: <style global> appears on pages that it shouldn't, build only

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#2908]
### What version of `astro` are you using?

0.25.2

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

When upgrading Astro.build to v0.25, I encountered a weird styling issue. Global styles from the blog page were appearing on the home page, breaking the homepage appearance.

Reverting [this commit](https://github.com/withastro/astro.build/commit/9e1d1dc469365a80df8eba56c21a79e391e4acc3) will re-introduce the error.

<img width="1624" alt="Screen Shot 2022-03-27 at 5 06 33 PM" src="https://user-images.githubusercontent.com/622227/160307100-953a6bf1-cc76-4c67-af72-67e15ff6bd53.png">

Unclear if this was introduced by upgrading to v0.25, OR if the upgrade combined [the fix](https://github.com/withastro/astro.build/commit/17cdf6ec3038228698e5ef05f3c828a37bf75017#diff-7f2bb650ebd4f62eed5e3c6f8b11553b541064b5a9ef01c815cb148e716090beR31-R33) for https://github.com/withastro/astro/issues/2904 introduced the regression.

### Link to Minimal Reproducible Example

https://github.com/withastro/astro.build/commit/9e1d1dc469365a80df8eba56c21a79e391e4acc3

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
This is a strange one!  I reverted astro.build to 0.24 for now and confirmed this was introduced between `0.24.3` and `0.25.2`

Finally managed to get a good reproduction [here](https://stackblitz.com/edit/github-qamimh?file=src%2Fpages%2Fblog.astro&on=stackblitz)

This only hits in dev, in that reproduction running `npm run dev && npm run preview` and you'll see styles are lost on the home page because Tailwind's reset styles were included (it's only actually imported on the `blog.astro` page)

**Comment by tony-sull** [comment]
@FredKSchott @matthewp This reproduces on the `minimal` template without Tailwind as well - styles imported in one page are bundled in for every other page as well

[Repo without tailwind](https://stackblitz.com/edit/github-283xec?file=src%2Fpages%2Fblog.astro&on=stackblitz)
