### ISSUE TITLE
🐛 BUG: Importing components to .MD routes via frontmatter.setup is not working

### ISSUE THREAD

**Issue by readonlychild** [withastro/astro#2983]
### What version of `astro` are you using?

0.26.0

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I upgraded from 0.24.0 to 0.26.0 and after following the documented breaking changes, the only thing that seems pending is when I use Components inside a Markdown route, via the setup frontmatter directive.

There is no error but also no rendered component.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ro2h8b?file=src%2Fpages%2Fblogpost.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by SebasG22** [comment]
+1 this is currently failling. Version 1.0.0-beta.0

**Comment by SebasG22** [comment]
@FredKSchott can you take a look?

**Comment by Barnabas** [comment]
A change to the Markdown API between 0.25 and 0.26 impacted the way frontmatter works (GH-2862). Perhaps something happened somewhere in [packages/astro/src/vite-plugin-markdown/index.ts](https://github.com/withastro/astro/blob/main/packages/astro/src/vite-plugin-markdown/index.ts) so that the setup property is now being ignored?

Astro seems to be very forgiving if you try to add an unknown tag, such as for an unregistered component. If the setup frontmatter property is now being ignored, it is understandable how this could stop working and still pass automated tests.

**Comment by jhuleatt** [comment]
Notes that might help debugging:

- Instead of rendering the component, Astro creates an HTML element whose name matches the component that we're trying to use in the `.md` file.
- If you use `<MyComponent />` syntax (as opposed to `<MyComponent></MyComponent>` syntax), the element is also a parent to all components that come after it in the `.md` file.

Screenshot from devtools for @readonlychild's repro: 

<img width="256" alt="Screen Shot 2022-04-04 at 4 44 20 PM" src="https://user-images.githubusercontent.com/3759507/161629003-bb3a67dd-9467-4559-b07c-f951615715df.png">

**Comment by SlicedSilver** [comment]
It seems that setting the `mode` option  for the markdown parser to `mdx` resolves this issue for me. 

Within your `astro.config.js` file add the following line to configure the markdown options to enable `mdx` mode:
```javascript
markdown: { mode: 'mdx' },
```

Full config example:
```javascript
import { defineConfig } from 'astro/config';
import preact from '@astrojs/preact';

export default defineConfig({
  integrations: [
    preact(),
  ],
  markdown: { mode: 'mdx' },
});

```

Where the value is read within the internal markdown code:
https://github.com/withastro/astro/blob/bffc2128258895fb9f7bd54d29e0bdfe60abf637/packages/markdown/remark/src/index.ts#L43

**Comment by brycewray** [comment]
Can confirm @SlicedSilver's report. That does fix it for me, as well.

Repo: https://github.com/brycewray/astro-site

**Comment by FredKSchott** [comment]
Thanks everyone! I found the fix here: https://github.com/withastro/astro/pull/2991

**Comment by SebasG22** [comment]
@SlicedSilver this solution is working on using the serve dev command but when you tried to generate a build it throws errors.

Context: I have some components with react and others with vue.  The components on the setup property were working previously. Now I got this error.

![image](https://user-images.githubusercontent.com/17608169/161657425-a85ee6d3-0efc-4728-9221-eb9b321afe74.png)

@FredKSchott

**Comment by SebasG22** [comment]
@FredKSchott are you sure this is fixed for components that are not Astro ?

**Comment by Barnabas** [comment]
Thank you @FredKSchott, I confirm that upgrading to 1.0.0-beta.2 fixed the problem. I am using Vue components from markdown, they are [restored](https://barnabas.me/articles/postgres-dbaas/#calculator).

**Comment by Pjaerr** [comment]
Confirmed fixed for me (using Svelte components in markdown files on `1.0.0-beta.2`). Thanks for being so speedy ❤️

**Comment by LorenzoLeonardini** [comment]
I can confirm that, as previously reported by @SebasG22 , the build process is broken, even with the current fix (`1.0.0-beta.2`)

```console
 error   Cannot find the built path for 
    at Object.resolve (./node_modules/astro/dist/core/build/generate.js:136:15)
    at generateHydrateScript (./dist/entry.mjs?time=1649150715401:146:165)
    at renderComponent (./dist/entry.mjs?time=1649150715401:496:28)
```

@FredKSchott I think this issue should be reopened

**Comment by SebasG22** [comment]
I create a new issue to track this behavior #2993

**Comment by fabien** [comment]
I installed a fresh example from https://github.com/withastro/astro/tree/main/examples/with-tailwindcss and found that the button did not render as it should in the `markdown-page.md` page. No styling and no script functionality. Looking at the terminal, I see an error:

```
Astro now supports MDX! Support for components in ".md" files using the "setup" frontmatter is no longer enabled by default. Migrate this file to MDX or add the "legacy.astroFlavoredMarkdown" config flag to re-enable support.
```
In other words, I think the example should be updated.
