### ISSUE TITLE
🐛 BUG: Unable to set multiple cookies

### ISSUE THREAD

**Issue by thepassle** [withastro/astro#3024]
### What version of `astro` are you using?

1.0.0-beta.2

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

It seems like only one cookie is being set, consider the following code:

```js
export function get() {
  const headers = new Headers();
  headers.append('Set-Cookie', `foo=foo; HttpOnly`);
  headers.append('Set-Cookie', `bar=bar; HttpOnly`);

  console.log(headers); //  {'set-cookie': [ 'foo=foo; HttpOnly', 'bar=bar; HttpOnly' ]}

  return new Response('', {
    status: 201,
    headers,
  });
}
```

Only one cookie actually makes it to the browser:

![image](https://user-images.githubusercontent.com/17054057/162264771-0b870464-5097-433c-b510-fd0496ee3c8b.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-v7wdzd?file=src/pages/foo.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Bug in the dev server, we need to use this to allow multiple of the same header: https://nodejs.org/api/http.html#responsesetheadername-value

**Comment by matthewp** [comment]
This is apparent a problem with the fetch standard :/. Think there is probably a workaround though.

**Comment by thepassle** [comment]
Oh really? Thats interesting. Do you have a link or anything? Just for my curiosity

**Comment by matthewp** [comment]
here's one such: https://github.com/whatwg/fetch/issues/973

There's not a method on Headers to get all of the headers. calling .append() results in concatenating the headers, comma-separated. Set-Cookie is the exception which cannot be done this way.

The reason you see it correctly in your console.log is because node-fetch (which we are using for this) has a special `headers.raw()` method which is what I'm going to use.

**Comment by matthewp** [comment]
Reopening to fix the Netlify adapter bug.
