### ISSUE TITLE
🐛 BUG:  A `<style>` tag in a Markdown layout does not apply to the Markdown in an `.md` file

### ISSUE THREAD

**Issue by FullQueueDeveloper** [withastro/astro#3045]
### What version of `astro` are you using?

1.0.0-beta.5

### What package manager are you using?

yarn/StackBlitz

### What operating system are you using?

Mac/StackBlitz

### Describe the Bug

Trying to style Markdown. A `<style>` tag in a Markdown layout does not apply to the markdown file.

See the stack blitz linked.

Workaround is to use Tailwind Typography plugin, which works very well for this problem.

@RafidMuhymin asked me to create this issue.

Previous discussion regarding this issue: https://discord.com/channels/830184174198718474/830184175176122389/883083470061056121

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ozszn7?file=src/layouts/markdown.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
I think this is behaving as expected — even if it might seem slightly unintuitive.

`<style>` blocks in `.astro` files are “scoped” by default, which means they only apply to the contents of that Astro file and nothing else (not even children rendered in `<slot />`).

To opt out of this and apply a style to other parts of your content, you need to either use the `is:global` attribute on the style tag or use the `:global()` pseudo-selector inside the styles.

Docs still show the old `global` attribute instead of the new `is:global`, but this is documented here: https://docs.astro.build/en/guides/styling/#scoped-styles

This is also why Tailwind’s Typography plugin works: it generates global unscoped styles.

**Comment by FullQueueDeveloper** [comment]
Yes, I understand. I wanted to help out by making the ticket that the contributor asked me to make.

**Comment by FredKSchott** [comment]
This is expected behavior! If you need to style the markdown, you should use `<style is:global>`. You also may be able to put a `<style>` tag directly inside of your `.md` file, although I have not tested that myself.

**Comment by noghartt** [comment]
> This is expected behavior!

In this case, why it should be an expected behavior? Thinking about scoped CSS, IMO it should apply the CSS rules in everything below that "tree".

To have the same effect as an scoping, in this case, I should improve the specification of each rule. Would be easier if it could be possible.

**Comment by fwextensions** [comment]
This may be working as designed, but it's certainly not working as (many people seem to have) expected.  I can see an argument for why the default should be to prevent styles from leaking down into a component that may be providing its own styles.  But markdown is, by definition, not markup, and so is unstyled by default.  There should be some easy way for a given Astro component to supply styles for just the markdown that it includes, rather than having to create a global `<p>` style and then try to limit it to just a given component.

**Comment by ostromia** [comment]
For those like me who stumbled across this issue whilst searching for a solution: if you want to apply styling to nested components, like in this issue where markdown is passed into a layout, you just need to import the styling as a file.

In the example below, the styling inside the `<style>` tag will only be applied to the elements inside this file, but the styling inside the `styles.css` file will be applied to the elements inside `<Components />` as well as the elements inside this file.

```astro
---
import Component from '../components/Component.astro';
import "../styles/styles.css";
---

<div>
    <h1>I should be red</h1>
    <Component />
</div>

<style>
    h1 {
        color: red;
    }
</style>
```

So to apply styling to markdown content just import the necessary `.css` file either into your `Layout.astro` or `[...slug].astro` etc.

**Comment by Ethan-Arrowood** [comment]
@ostromia makes an excellent point, global styles is not the right solution here. 

I really enjoy encapsulating styles into my astro file rather than having to write a separate css file. 

Could it be possible to add a new attribute to `<style>` similar to `is:global` that can apply the styles to everything underneath it? Like how the file based import is applied. Or at least with rendering Markdown pages, maybe something I can set on `slot` to indicate it should allow scoped styles through? 

```astro
<style>
h1 { color: blue; }
p { font-size: 1.2rem; }
</style>
<div>
  <h1>{frontmatter.title}</h1>
  <slot inheritStyles={true} />
</div>
```
