### ISSUE TITLE
🐛 BUG: Disabling hashing via vite build options not working in astro config 

### ISSUE THREAD

**Issue by W7T2A** [withastro/astro#3046]
### What version of `astro` are you using?

1.0.0-beta.5

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When using vite config params to disable asset / js hashing when building astro the options passed to asto.config.mjs are ignored / not working:

```js
export default defineConfig({
    vite: {
        build: {
            rollupOptions: {
                output: {
                    entryFileNames: assets/[name].js,
                    chunkFileNames: assets/[name].js,
                    assetFileNames: assets/[name].[ext]`
                }
            }
        }
    }
});
```
The output still generates the hashed file version.
Also would be nice if there's a setting to disable file optimization e.g. when using CloudFlare + CF Pages using CF native optimization options so CF will minimize JS/CSS/HTML on the Edge.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cwttf1?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by destegabry** [comment]
Same to me, seems that every `rollupOptions.build` option is not forwarded to rollup.

**Comment by nikolalakovic85** [comment]
Same to me! I would like to have this option available because I have to serve my CSS as CDN. Until this is not solved I used node.js to rename this single css file that I have. (you can do this also with multiple files but I have only one). 

const fs = require("fs");
const path = require("path");

const cssFolder = path.join(__dirname, "/dist/assets");
const cssFile = fs.readdirSync(cssFolder);

fs.rename(
  "./dist/assets/" + cssFile,
  "./dist/assets/style.css",
  function (err) {
    if (err) {
      console.log("ERROR: " + err);
    } else {
      console.log("SUCCESS! FILE RENAMED!");
    }
  }
);

**Comment by matthewp** [comment]
Thanks! We do not current support this but we really should. So making as something to be fixed.
