### ISSUE TITLE
🐛 BUG: Tailwind Breakpoints Styles are not working as expected when using Astro layouts

### ISSUE THREAD

**Issue by SebasG22** [withastro/astro#3055]
### What version of `astro` are you using?

1.0.0-beta.5

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

This project uses tailwind to manage the styles,

Reproduction Steps:

0. Go to the stackblitz reproduction link and follow these steps.
1. Check the structure of the Astro app and put special attention to the markdown page.
2. According to the docs, layouts can be used on [markdown pages](https://docs.astro.build/en/core-concepts/layouts/#markdown-layouts)
3. Now review the Layout `sample.astro`, and the usage of tailwind.
4. Go to the `http:localhost:3000/markdown-page` and use the function Open in a New Window to test the styles for multiple breakpoints.

What is the expected output when changing sizes?

- Default: Color must be green
- Small: Color must be red
- Medium: Color must be blue

The current behavior of Astro is applying the styles in the wrong way.
You will encounter that using the developer tools looks like its working but it's not:

https://user-images.githubusercontent.com/17608169/162631846-12f03bea-6730-4f24-8bd6-5ef33fc028d1.mp4

If you try to modify the breakpoints using the browser predefined values you will get this behavior:

https://user-images.githubusercontent.com/17608169/162632614-97854ca0-8eb8-467a-bd32-98589b600768.mp4

The breakpoints are not working correctly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-m7id9n-4tgvgt?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
This is actually a (very frustrating) browser dev tools issue.  I've seen this happen before in Chrome where the device emulator isn't respecting media queries

Shrinking the window rather than using the device emulator works like a charm, but for some reason the device emulator thinks its full size no matter what (almost like it's using the browser's window width rather than the emulator's screen size).

Here's a screenshot of the `<h1>` styles when I had the device emulator in Chrome set to an iPhone SE (320px wide), you can see it's actually including the media queries for both 640px and 768px 🙃 


![Screen Shot 2022-04-13 at 11 42 37 AM](https://user-images.githubusercontent.com/15836226/163149917-f4d77ea6-e424-4789-9133-9b25a7992f42.png)
