### ISSUE TITLE
🐛 BUG: Markdown file content no longer available in markdown fetching API

### ISSUE THREAD

**Issue by zadeviggers** [withastro/astro#3072]
### What version of `astro` are you using?

1.0.0-beta.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Previously (pre-`0.26.x`) when using `Astro.fetchContent` the raw markdown file content (with the frontmatter stripped) was available at `Astro.fetchContent()[i].astro.content`. With the updated markdown API (`Astro.glob`), in order to run my custom markdown parser, I have to load all the markdown files manually using `fs` and use an external library to parse and strip away the frontmatter.

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
This was actually an intentional change in the `Astro.glob()` PR to improve performance on larger sites, but you're not the only one that misses the ability to access the source markdown and rendered HTML in `astro.content`!

[PR #3056 ](https://github.com/withastro/astro/pull/3056) was opened recently to add support for getting this content when needed without loading it by default like `Astro.fetchContent` used to :+1:

**Comment by FredKSchott** [comment]
Core team sync:

- there's interest for `getResult()` although `md` and `html` probably aren't the right keys since it's technically `md + components` and `compiled astro output`. Naming tbd by PR creator (maybe `getRawContent()` instead).
- separately, there's interest in adding some common MD use-cases to core (getSummary, getReadingLength, etc.)
- separately, could we actually render to HTML? A few concerns here, probably out of scope for this issue.

**Comment by pol-piella** [comment]
Hey @FredKSchott @bholmesdev 👋  

Awesome work on this! Really helped me add content to my RSS feed 🎉 

I had a quick question around the changes in the latest astro version. I see that using `MDX` is the new recommended approach for having components in Markdown so I was wondering if the `compiledContent()`  would still be available for the `Astro.glob()` response? I have quickly tested it and I can't see it, but might be missing something.

Thanks so much in advance and really appreciate the work you have been doing! Astro is amazing 🧑‍🚀 ❤️

**Comment by zadeviggers** [comment]
It doesn't exist yet, but I understand that it's being worked on. See [this comment](https://discord.com/channels/830184174198718474/872579324446928896/1003171031701262438) in discord.
