### ISSUE TITLE
🐛 BUG: Secret Environment Variables Can Be Shared In Client

### ISSUE THREAD

**Issue by alteredorange** [withastro/astro#3102]
### What version of `astro` are you using?

1.0.0-beta.8

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

pnpm

### What operating system are you using?

WSL

### Describe the Bug

With the below code I can easily leak a secret key to the client. Obviously this is because I take the const and use it in the Astro file, but it would be nice if the compiler gave a warning, or even made it impossible to use this private variable in the client code.
Oddly enough, in stackblitz it's not showing the secret key, but in codesandbox it is (also showing in local dev).
```
---
const { SSR, DB_SECRET, PUBLIC_SOME_KEY } = import.meta.env;
---
<html lang="en">
<head>
</head>
	<header>
			<div>
{DB_SECRET}  //will show secret, should not show
{PUBLIC_SOME_KEY}  //this one should show
                         </div>
	</header>
</html>
```

### Link to Minimal Reproducible Example

https://codesandbox.io/s/busy-sea-uouve7?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
Thanks for filing! 

This would be really hard for us to catch even if we wanted to. And, there are probably valid use-cases where this is actually desired. I think we would consider this intentional behavior, similar to `set:html`. If you are explicitly putting a secret on the page, then we shouldn't get in your way as a framework. Maybe something for linting?
