### ISSUE TITLE
🐛 BUG: Scripts in .astro files are bundled even if they are commented out

### ISSUE THREAD

**Issue by jscheller** [withastro/astro#3115]
### What version of `astro` are you using?

1.0.0-beta.10

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

MacOS 10.14.6

### Describe the Bug

Bringing my project up to date and building now with the 1.0 beta, but noticed some super weird on-site behavior after upgrading.
   
It looks like when everything is bundled, we're now picking up scripts that are commented out. I have some code in my Astro layout file used on all the pages that looks like this...
   
    { (someTest) && (
        <script src='https://xyz.com/some-neccessary-script.js' />
        //<script src='https://xyz.com/evil-script.js' />
    )}
    
 ...and evil-script.js winds up imported in the generated entry.[hash].js files even though that line is commented. Pretty obvious workaround on my side and rebuilding everything now.

### Link to Minimal Reproducible Example

https://none.at.this.time

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@jscheller What about if you wrap them in HTML comments?

**Comment by natemoo-re** [comment]
Yeah this is because the contents of an expression are Astro-style HTML, not JSX. So `//` isn't actually commenting out the script, it's just treated as text before the `<script>`.

You'd have to comment out the script using `<!-- <script src='https://xyz.com/evil-script.js' /> -->`

We have some work to do on the IDE side to make this experience more friendly, because I'm assuming the comment shortcut inserted `//` for you.
