### ISSUE TITLE
🐛 BUG: Importing typescript files as a URL returns `data:video/mp2t;...` 

### ISSUE THREAD

**Issue by okikio** [withastro/astro#3122]
### What version of `astro` are you using?

^1.0.0-beta.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Importing typescript files as URLs like so, 
```astro
---
import url from "../scripts/index.ts?url";
---
<script type="module" src={url} />
```

returns this result 
```html
<script type="module" src="data:video/mp2t;base64,absdf........qweqwe=="></script>
```
![image](https://user-images.githubusercontent.com/17222836/163629026-81b33da6-4c84-4c9e-b423-743583b605e1.png)

This error only occurs when running `astro build`.

I've done some exploration, and I'm thinking the error is from the mime package,
![image](https://user-images.githubusercontent.com/17222836/163629790-295663a6-869e-48b2-99be-9f9cdf10dd29.png)

This is where the mime package is used in Astro,
![image](https://user-images.githubusercontent.com/17222836/163629826-f37cb6b5-29b5-4635-bbe7-40434f23cfb4.png)
https://github.com/withastro/astro/blob/b0ba22c5ffab6575706ae904d0ad8cadc3f48d43/packages/astro/src/core/app/index.ts#L141

This bug also applies to SSR,
![image](https://user-images.githubusercontent.com/17222836/163629874-45263a47-000f-4701-9a64-1173614ae448.png)
https://github.com/withastro/astro/blob/9fa013b4fa04dc65b9abd75d75865bcbfd609170/examples/ssr/server/server.mjs#L20

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yfsanz?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by okikio** [comment]
cc @natemoo-re

**Comment by okikio** [comment]
For better reproduction this might be better than Stackblitz https://gitpod.io#snapshot/5064c721-904b-4e9f-bff6-126755bea7e1

**Comment by okikio** [comment]
A demo of the bug is here, https://625932790185e400082a6434--okikio.netlify.app/

**Comment by natemoo-re** [comment]
So strange. Definitely confirming this as a bug. Looks like...

```astro
---
import scriptURL from '../scripts/index.ts';
---
```

returns `/src/scripts/index.ts` and never gets updated to point to the correct output file. Trying to determine if this is an issue on our end or with Vite, but it could be a combination of the two.

**Comment by tony-sull** [comment]
Looks like this happens in Vite as well 👀 [Vite + TS repro](https://stackblitz.com/edit/vitejs-vite-rv9ikk?file=src%2Fmain.ts&terminal=dev)

I see a couple things going on here -

### `build.assetsInlineLimit`

Vite automatically converts `?url` imports to base64 when the file is less than 4kb by default, that's why it's getting a `/src/...` path in dev but a base64 string in prod

This can be overridden in config with the astro config with
```js
vite: {
    build: {
        assetsInlineLimit: 0
    }
}
```

### content-type

No clue why the `.ts` file gets encoded as `data:video/mp2t;`!  This happens in the Vite + TS reproduction as well so Astro is probably just matching what it gets

@natemoo-re I'm thinking this is an upstream issue we could open on Vite, or do you think this is something we could/should handle on our end?

**Comment by tony-sull** [comment]
Related [Vite issue](https://github.com/vitejs/vite/issues/2642) - looks like the mimetype for `.ts` files is expected 🤦

**Comment by tony-sull** [comment]
Confirmed this isn't supported unforunately, [see here](https://github.com/vitejs/vite/issues/4167#issuecomment-894615262) for more details from the Vite team
