### ISSUE TITLE
🐛 BUG: "update /[file]" logs for irrelevant files (README, `astro.config`, etc)

### ISSUE THREAD

**Issue by bholmesdev** [withastro/astro#3326]
### What version of `astro` are you using?

1.0.0-beta.27

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm, yarn, pnpm

### What operating system are you using?

Mac

### Describe the Bug

Split from #3196 
When editing any file in the base directory (other than `package.json`), Astro will log an "update" in the console:

```sh
12:39:35 PM [astro] update /astro.config.mjs
12:39:57 PM [astro] update /tsconfig.json
12:40:06 PM [astro] update /README.md (x2)
```

This is especially misleading for config files. For instance, seeing `update /astro.config.mjs` after installing an integration _implies_ that integration is ready-to-use. It actually requires a full dev server restart!

### Link to Minimal Reproducible Example

https://astro.new/

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Possible reason for bug: Vite is scoped to the base directory, so any file change is fair game for Vite's info logs.

**Comment by natemoo-re** [comment]
This should be a pretty small one, but would be very nice to fix!

**Comment by FredKSchott** [comment]
With https://github.com/withastro/astro/issues/3196 I believe that this has been fixed. I disagree that we should hide any update logs for some files in the project directory, which I feel like will create more confusion than value.

At the very least, I would consider this an improvement and not a bug, so I'll go ahead and close unless anyone feels strongly otherwise.
