### ISSUE TITLE
[New Framework] Angular

### ISSUE THREAD

**Issue by sinedied** [withastro/astro#346]
Congrats for this project, this looks very interesting 🙂 

Is there any plans down the road to also support Angular in addition to other frameworks?

**Comment by matthewp** [comment]
Thanks @sinedied! We're still figuring out which frameworks to include in Astro core and which not to. In the meantime, creating a renderer is not terribly difficult if you want to give it a try yourself: https://github.com/snowpackjs/astro/blob/main/docs/renderers.md

**Comment by guiseek** [comment]
Any updates?

can i try to help

**Comment by matthewp** [comment]
You definitely can, no one is working on an Angular renderer yet, to my knowledge

**Comment by guiseek** [comment]
> Thanks @sinedied! We're still figuring out which frameworks to include in Astro core and which not to. In the meantime, creating a renderer is not terribly difficult if you want to give it a try yourself: https://github.com/snowpackjs/astro/blob/main/docs/renderers.md

@matthewp 

[Packages Renderers](https://github.com/snowpackjs/astro/tree/main/packages/renderers)
[Docs Renderer reference](https://github.com/snowpackjs/astro/blob/main/docs/src/pages/reference/renderer-reference.md)

are here, right?

**Comment by jasikpark** [comment]
> > Thanks @sinedied! We're still figuring out which frameworks to include in Astro core and which not to. In the meantime, creating a renderer is not terribly difficult if you want to give it a try yourself: https://github.com/snowpackjs/astro/blob/main/docs/renderers.md
> 
> @matthewp
> 
> [Packages Renderers](https://github.com/snowpackjs/astro/tree/main/packages/renderers)
> [Docs Renderer reference](https://github.com/snowpackjs/astro/blob/main/docs/src/pages/reference/renderer-reference.md)
> 
> are here, right?

Yup! https://docs.astro.build/reference/renderer-reference

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat

**Comment by kuncevic** [comment]
I am guessing that is it https://dev.to/brandontroberts/bringing-angular-components-to-astro-islands-52jp
