### ISSUE TITLE
🐛 BUG: import.meta.env.BASE_URL is incorrect when i set base config.

### ISSUE THREAD

**Issue by leon-kfd** [withastro/astro#3567]
### What version of `astro` are you using?

1.0.0-beta.42

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

Set base config to '/blog' in `astro.config.mjs`, but import.meta.env.BASE_URL is still '/'.
![image](https://user-images.githubusercontent.com/30256102/173008537-ff20f25a-e3d7-40da-81c6-7d7accd58e06.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rtg6u1?file=astro.config.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Ah, I see that you're expecting the [`import.meta.env.BASE_URL`](https://vitejs.dev/guide/env-and-mode.html#env-variables) env variable defined by Vite to be available. I think we're overriding this somehow, definitely something we can add.

**Comment by rishi-raj-jain** [comment]
I think this is already supported now: https://docs.astro.build/en/reference/configuration-reference/#base

**Comment by bluwy** [comment]
I'm still seeing `import.meta.env.BASE_URL: '/'` when `base: '/blog'` with the repro and using Astro 1.3.0. Doesn't seem to be fixed yet.

**Comment by rishi-raj-jain** [comment]
@bluwy Can you try: https://stackblitz.com/edit/github-rtg6u1-nmafzt?file=src/pages/index.astro and let me know if it still exists? I still see that working fine.

**Comment by bluwy** [comment]
I was checking it via `console.log(import.meta.env)` where it shows `BASE_URL: '/'`, but yeah your repro is correct too. Form what I can tell, yours work because `vite-plugin-env` (An internal Astro env plugin) replaces it, but with only `console.log(import.meta.env)`, `vite-plugin-env` skips the file, and lets Vite handle it, which Vite doesn't have the information of `BASE_URL`.

Anyways I think we can close this as it's specifically fixed by https://github.com/withastro/astro/pull/3955. Thanks @rishi-raj-jain  for triaging this!
