### ISSUE TITLE
🐛 BUG: `unable to find network to expose` when exposing to network with Node 18.1+

### ISSUE THREAD

**Issue by arimgibson** [withastro/astro#3598]
### What version of `astro` are you using?

1.0.0-beta.46

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

In Node 18.1, a change to the return value of `os.networkInterfaces()` is made, causing Astro to be unable to find a network to host the Astro `dev` or `preview` servers on (specific error is `unable to find network to expose`). This is because when Astro is checking for valid network interfaces, it looks an interface with `family: IPv4`, and Node 18.1 uses a simple integer value of `family: 4`.

This change can be observed in the official Node documentation for the Node 16 LTS vs the Node 18 LTS. Look under the return object properties...

[Node 18 `os.networkInterfaces()`](https://nodejs.org/dist/latest-v18.x/docs/api/os.html#osnetworkinterfaces )
[Node 16 `os.networkInterfaces()`](https://nodejs.org/dist/latest-v16.x/docs/api/os.html#osnetworkinterfaces )

Image example from Node 16
![image](https://user-images.githubusercontent.com/43756494/173743831-6f3d444c-580f-43ea-86ab-4d452741e90b.png)

I'll handle the PR; it's a pretty easy one...

### Link to Minimal Reproducible Example

N/A

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by arimgibson** [comment]
Correcting my bug report to specify that this breaking change is introduced in Node `v18.1.0`, not Node `v18.0.0` like I initially assumed

**Comment by chitowncrispy** [comment]
@arimgibson I am running node version 18.6.0 and I am not able to expose it to the network. It looks like your fix probably works for node versions 18.1.0 to 18.3.0. I am guessing version 18.4.0 nullifies your changes since they seem to have reverted the family property back to a string like it was in Node 16.

For reference:
- https://nodejs.org/en/blog/release/v18.4.0/
- https://github.com/nodejs/node/pull/43054


**Node 18.1.0 working**:
<img width="407" alt="Screen Shot 2022-07-23 at 11 56 49 AM" src="https://user-images.githubusercontent.com/1864955/180615406-26f0c2e7-af26-4a42-8085-9bb49cfec3f9.png">


**Node 18.6.0 not working**:
<img width="408" alt="Screen Shot 2022-07-23 at 12 00 16 PM" src="https://user-images.githubusercontent.com/1864955/180615432-74c31c8b-51be-4020-889f-dc5738b30bc8.png">

**Comment by arimgibson** [comment]
@chitowncrispy really good catch! That's frustrating; I'll go PR an amended version now. Thanks for finding that and letting me know!

**Comment by chitowncrispy** [comment]
@arimgibson No problem. Just as an FYI it looks like the logic you implemented should apply for Node version 18.0.0 as well since that is when Node first introduced the family property as a number.

**Comment by arimgibson** [comment]
Ugh, can't believe I missed that too @chitowncrispy! Updated PR submitted though, thanks again!

**Comment by anurag-roy** [comment]
Facing the same issue 🙁

Node: v18.10.0
Astro: v1.2.1

<img width="748" alt="Screenshot 2022-10-02 at 12 43 05 AM" src="https://user-images.githubusercontent.com/53750093/193424751-cb234e55-ce70-4a2b-b1dd-985431c3514c.png">

**Comment by arimgibson** [comment]
No way, did they change it again 😹 thanks for reporting @anurag-roy , taking a look

**Comment by arimgibson** [comment]
Hmmm, I was unable to replicate this @anurag-roy , though I am on Windows. I noticed that your version of Astro seems to be out of date, current release is `v1.4.2`. Are you able to upgrade Astro and see if you're still encountering this bug?

If the bug still occurs, it might be something macOS-specific which I would not be able to debug as I don't have access to a Mac.

**Comment by anurag-roy** [comment]
@arimgibson Upgrading to `v1.4.2` solved it! Thanks a lot for looking into it!
