### ISSUE TITLE
🐛 BUG: Dynamic require of "node-fetch" is not supported for client-side import of tmi.js

### ISSUE THREAD

**Issue by whitep4nth3r** [withastro/astro#3608]
### What version of `astro` are you using?

1.0.0-beta.46

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to import and use the [tmi.js package](https://www.npmjs.com/package/tmi.js) using a client-side `<script>` tag.

Using the starter code from the [official tmi.js docs](https://tmijs.com/) in `pages/index.js`:

```html
<script>
  import tmi from "tmi.js";

  const client = new tmi.Client({
    channels: ["whitep4nth3r"]
  });

  client.connect();

  client.on('message', (channel, tags, message, self) => {
    console.log(`${tags['display-name']}: ${message}`);
  });
</script>
```

I see the following error in the browser console:

```
chunk-ICLR7M5L.js?v=aadb39fe:27 Uncaught Error: Dynamic require of "node-fetch" is not supported
    at chunk-ICLR7M5L.js?v=aadb39fe:27:9
    at node_modules/tmi.js/lib/api.js (api.js:1:15)
    at __require2 (chunk-ICLR7M5L.js?v=aadb39fe:33:50)
    at node_modules/tmi.js/lib/client.js (client.js:4:13)
    at __require2 (chunk-ICLR7M5L.js?v=aadb39fe:33:50)
    at node_modules/tmi.js/index.js (index.js:1:16)
    at __require2 (chunk-ICLR7M5L.js?v=aadb39fe:33:50)
    at dep:tmi_js:1:16
```

After having a chat with @bholmesdev these are some candid thoughts from him:

```text
Welp, it works in plain Vite and not Astro... lovely
```

```text
Something to do with our bundling but I honestly have no clue 😓
```

```text
My guess is tmi *thinks* it's in Node for some reason (bc we server render everything) and tries to use node-fetch. Not sure yet
```

I have successfully run this code in React, Svelte, plain JavaScript + Parcel, and express in the past using the code sample from the tmi.js documentation without errors.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2ta94v?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Oh that's really interesting, it looks like this actually is one that should be fixed in the `tmi.js` library itself.

It looks like `client.js` is setup to prefer the global `fetch()` function when available but `api.js` is always requiring `node-fetch`

I'm not 100% sure why this would hit in Astro and not Vite (worth further investigation on our end) but I just opened a [PR](https://github.com/tmijs/tmi.js/pull/521) on tmi.js to prefer the global `fetch()` when available :+1:

Closing this out as an external bug, but I'll do a bit of comparison with a plain Vite project to see if we're bundling things differently here as well!
