### ISSUE TITLE
💡 RFC: Build UI improvements

### ISSUE THREAD

**Issue by matthewp** [withastro/astro#362]
Couple of things we could do to enhance the output:

* Show more information about each page: what is the split between JS / CSS/ images? What components are included in each page.
* It becomes noisy with large sites with lots of pages. What can be done about that?

**Comment by drwpow** [comment]
What about something like this?

![Terminal](https://user-images.githubusercontent.com/1369770/121725313-58e95280-caa6-11eb-84ed-1a37407a8b9e.png)

We could the breakdown of HTML/CSS/JS/images etc. across:
- Total site
- Homepage (`index.html`)
- Any additional routes they specify (`/about/index.html` in the mockup, maybe via a minimatch `stats: ["*/index.html"]` config in Astro?). That way users can control what they do/don’t see

**Comment by matthewp** [comment]
That looks great! It also might be nice to have a second that shows specific component weight. Like the top 5 biggest components (gives you something to try and trim)

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
