### ISSUE TITLE
🐛 BUG: on `injectScript` with `page-ssr` option, imports works on dev server but unable to build

### ISSUE THREAD

**Issue by tuhanayim** [withastro/astro#3637]
### What version of `astro` are you using?

1.0.0-beta.47

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I'm injecting CSS and SCSS to all pages with `injectScript`. I successfully can run dev server, and injects. But when building, it throws `Could not resolve '<x>' from astro:scripts/page-ssr.js`.

#### astro.config.js file:
```js
export default defineConfig({
  experimental: {
    integrations: true,
  },
  integrations: [
    {
      name: 'inject-styles',
      hooks: {
        'astro:config:setup': ({ injectScript }) => {
          injectScript('page-ssr', 'import "./src/styles/test.css"');
        },
      },
    },
  ],
});
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yvmfzs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Ah yep the imports inside an integration can get a little tricky!

The import statement is going to be added to every page exactly as-is.  In this case, to make it work for `src/pages/index.astro` you would actually need to inject `import "../styles/test.css"`.  This would still break for deeper pages though, like `src/pages/blog/[slug].astro` since it would need to go up 2 directories to find the styles

For local integrations you should be able to get this to work with aliasing `src/styles` to something like `@styles`.  For any integrations you are publishing to NPM you'll actually want to import the styles from the NPM package similar to our [Tailwind integration](https://github.com/withastro/astro/blob/main/packages/integrations/tailwind/src/index.ts) :+1:
