### ISSUE TITLE
[New Framework] Zustand

### ISSUE THREAD

**Issue by agustinmulet** [withastro/astro#371]
Hi team, I love what you're doing with Astro! I've been playing around a bit and I managed to add support for the state manager [Zustand](https://github.com/pmndrs/zustand), but I've tested it with the basic store from the example. Maybe a more thorough testing is needed.
This was tested on Win 10 and macOS (Catalina).

Steps to get a simple store working:
(from the astro docs)
```sh
# create your project
mkdir new-project-directory
cd new-project-directory
npm init astro

# install your dependencies
npm install
```

We then install Zustand doing `npm i zustand` and if we try to start the project, these errors are shown in the console (maybe someone more knowledgeable can shine a light on why are they thrown):

```sh
npm start

> @astrojs/starter-kit@0.0.1 start
> astro dev

[20:48:44] [snowpack] + zustand@3.5.2
[20:48:44] [esinstall:zustand] ~\astro-test\node_modules\zustand\index.js
   Module "@babel/runtime/regenerator" could not be resolved by Snowpack (Is it installed?).
[20:48:44] [esinstall:zustand] ~\astro-test\node_modules\zustand\index.js
   Module "@babel/runtime/regenerator" could not be resolved by Snowpack (Is it installed?).
   Module "@babel/runtime/regenerator" could not be resolved by Snowpack (Is it installed?).
(node:14636) UnhandledPromiseRejectionWarning: Error: Install failed for zustand.
    at Object.install (~\astro-test\node_modules\snowpack\lib\index.js:94735:23
    at Object.installPackages (~\astro-test\node_modules\snowpack\lib\index.js:
    at ~\astro-test\node_modules\snowpack\lib\index.js:123350:39
    at PackageSourceLocal.buildPackageImport (~\astro-test\node_modules\snowpac
    at PackageSourceLocal.prepare (~\astro-test\node_modules\snowpack\lib\index
    at createSnowpack (file:///~/astro-test/node_modules/astro/src/runtime.ts:4
    at createRuntime (file:///~/astro-test/node_modules/astro/src/runtime.ts:44
    at dev (file:///~/astro-test/node_modules/astro/src/dev.ts:27:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error origin To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-
(node:14636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In th...
```

As it says there if we install @babel/runtime doing `npm i @babel/runtime` and restart the dev server (just in case) we can then create a store and use it without a problem:

`src/store/index.js`:
```js
import create from 'zustand'

const useStore = create(set => ({
  bears: 0,
  increasePopulation: () => set(state => ({ bears: state.bears + 1 })),
  removeAllBears: () => set({ bears: 0 })
}))

export default useStore;
```

`src/components/ZustandTest.jsx`:
```js
import React from 'react'
import useStore from '../store'

function BearCounter() {
  const bears = useStore(state => state.bears)
  return <h1>{bears} around here ...</h1>
}

function Controls() {
  const increasePopulation = useStore(state => state.increasePopulation)
  const removeAll = useStore(state => state.removeAllBears)
  return <div>
    <button onClick={increasePopulation}>one up</button>
    <button onClick={removeAll}>Remove all</button>
  </div>
}

const ZustandTest = () => {
  return <div>
    <BearCounter />
    <Controls />
  </div>
}

export default ZustandTest;
```

`src/pages/index.astro`:
```jsx
---
import ZustandTest from '../components/ZustandTest.jsx'
---

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Astro + Zustand Test</title>
</head>
<body>
    <main>
        <ZustandTest:load />
    </main>
</body>
</html>
```

Et voilà! It's working although there's a warning in the console, this is the stack trace:

![image](https://user-images.githubusercontent.com/31162600/121442995-0c492e80-c963-11eb-91d3-68062edf98e5.png)

Well I hope this is informative enough and I'm up to help doing some other tests with this if needed

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
