### ISSUE TITLE
🐛 BUG: Tailwind integration throws "An argument for 'options' was not provided."

### ISSUE THREAD

**Issue by inwardmovement** [withastro/astro#3716]
### What version of `astro` are you using?

^1.0.0-beta.56

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Tailwind integration throws "An argument for 'options' was not provided." in `astro.config.mjs` at `integrations: [tailwind()]`.

![image](https://user-images.githubusercontent.com/9438102/175802705-38bf577d-152d-4b41-a353-505c66b6c7cf.png)

An easy fix would be to add `?` after `option` at `export default function tailwindIntegration(options?: TailwindOptions): AstroIntegration;` in `node_modules/@astrojs/tailwind/dist/index.d.ts` but I cannot find the source file, otherwise I would have made a PR.

### Link to Minimal Reproducible Example

https://github.com/inwardmovement/vajm.me/tree/astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
Oh great catch, thanks for filing this one!  Looks like this got hidden by how TS is configured in the monorepo, this builds just fine but TypeScript does indeed warn here when options aren't provided

Should be a quick fix since the integration already handles this as optional internally, the fix should be in [packages/integrations/tailwind](https://github.com/withastro/astro/blob/main/packages/integrations/tailwind/src/index.ts) if you're interested in opening a PR!
