### ISSUE TITLE
🐛 BUG: Astro doesn't render properly in GitHub Codespaces on dev mode

### ISSUE THREAD

**Issue by okikio** [withastro/astro#3982]
### What version of `astro` are you using?

1.0.0-beta.72

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

On GitHub Codespaces there is an issue in dev mode where Astro will return HTML as a text file. 
> If you run `astro preview` this issue isn't there

The issue looks like this, 
![image](https://user-images.githubusercontent.com/17222836/179872855-697d70fc-6429-4f75-9378-50cdbc6b448c.png)

The error occurs on all example templates, this is an example repro, but it occurs on all examples 
https://github.com/okikio/astro-codespaces-error-repro

### Link to Minimal Reproducible Example

https://stackblitz.com/github/okikio/astro-codespaces-error-repro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks @okikio! It's hard to tell if this is an issue on our end or with Codespaces. Any chance you can look into this more?

I wonder if changing anything about the Codespaces settings helps here?

**Comment by okikio** [comment]
I'm not sure either, @ran-dall thought changing the Dockerfile would solve the problem, but it didn't. From what I can tell, this is an Astro issue as it only affects the dev mode server, but the `preview` server works as expected.

If you'd like, I can have a debug sesh after work today.

**Comment by ran-dall** [comment]
I was able to replicate @okikio problem a few different ways, which makes me think it isn't something we're doing but rather an interaction of how GitHub is forwarding the Local Ports. You don't get the problem if you use the GitHub CodeSpaces extension on MS Edge or directly from within VSCode. The problem is solely when you're using CodeSpaces from a browser window.

That said, Firefox doesn't even connect to CodeSpaces in this context due to it triggering Security Violations.

Therefore, I'm pretty certain this is a limitation of CodeSpaces...and I'm currently working with GitHub to push the problem to the right people there.

**Comment by okikio** [comment]
That's awesome 👌

**Comment by lloydjatkinson** [comment]
Just encountered this problem too. This used to work, it only stopped working a few weeks ago.

**Comment by matthewp** [comment]
Not sure what's changed since, but this seems to be working perfectly fine now! I created a repo with a project: https://github.com/matthewp/codespaces-astro-project
