### ISSUE TITLE
🐛 BUG: `@astrojs/image` doesn't work on Vercel Edge due to crypto dependency

### ISSUE THREAD

**Issue by PatrikTheDev** [withastro/astro#4035]
### What version of `astro` are you using?

rc-20220722032928

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Deploy to Vercel Edge fails when using `@astrojs/image` because it depends on `etag` which uses `crypto` under the hood.

### Link to Minimal Reproducible Example

n/a

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
The integration only supports Node environments for now, but I'm hoping we'll have that cleared up shortly!  `sharp` is currently used under the covers so even without the `crypto` dependency the integration would fail when trying to import `sharp`

Closing this out as expected behavior for now, but I'm hoping we'll have full support for non-Node environments soon!
