### ISSUE TITLE
🐛 BUG: Using `@astrojs/mdx` with `astro.config.ts` fails to start

### ISSUE THREAD

**Issue by pinanek23** [withastro/astro#4078]
### What version of `astro` are you using?

1.0.0-rc.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

In `with-mdx` example, changing the config file to `astro.config.ts` throws an error:

```
 error   No "exports" main defined in /home/pinanek23/workspace/dev/bug/mdx-ts/node_modules/estree-walker/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:693:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pinanek23/workspace/dev/bug/mdx-ts/node_modules/estree-util-build-jsx/lib/index.js:23:28)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-akf9du?file=astro.config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ndaba1** [comment]
I am facing the same issue here.... I think it's a problem with the `@astro/mdx` plugin since Im using `1.0.0-rc.2` with an `astro.config.js` file but the app fails to start. 

![Screenshot (269)](https://user-images.githubusercontent.com/76922307/181522365-9cf9c30e-e298-4323-b037-af8f937473ae.png)
This is the error that I get. I'm on windows with npm

**Comment by QuiiBz** [comment]
I think it's due to https://github.com/Rich-Harris/estree-walker/issues/26. `estree-walker@>=3.0.0` seems to have this issue, but not `estree-walker@2.0.x`

<img width="501" alt="Screenshot 2022-07-29 at 11 17 36" src="https://user-images.githubusercontent.com/43268759/181727502-b9f49eb1-ed6b-480c-a0fd-a3c505511a61.png">

**Comment by matthewp** [comment]
@ndaba1 can you provide a reproduction? I'm not sure if the issue you're experiencing is the same as the one being reported here.

**Comment by matthewp** [comment]
https://stackblitz.com/edit/github-xsoxnr?file=package.json,astro.config.mjs,src%2Fpages%2Findex.astro,src%2Fpages%2Fpage.mdx&on=stackblitz

**Comment by vkbansal** [comment]
I also faced this issue. This happens when using `pnpm`. Works fine with `npm` and `yarn`.

**Comment by ndaba1** [comment]
@matthewp, it fails even in the plain `with-mdx` example. I've been getting some help from the discord server and this seems to be a windows issue only. It works perfectly well in wsl

**Comment by Alxandr** [comment]
@ndaba1 I'm havving this issue on linux - so definitely not a windows only issue...

**Comment by tanepiper** [comment]
Also getting the same issue on OSX trying to use it with `1.0.0-rc.3`

**Comment by matthewp** [comment]
Was able to break in a test: https://github.com/withastro/astro/commit/60687f52d231bcf94bd7ec4e016bdcd8ea1b0c9e
