### ISSUE TITLE
🐛 BUG: astro preview does not serve custom 404

### ISSUE THREAD

**Issue by tatethurston** [withastro/astro#4113]
### What version of `astro` are you using?

1.0.0-rc.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

[Custom 404 pages](https://docs.astro.build/en/core-concepts/astro-pages/#custom-404-error-page) work with `astro dev` but not with `astro preview`. The later shows the builtin astro 404 instead of the custom 404 page.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/pensive-keldysh-5cqh5s

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Pukimaa** [comment]
Also get it with live version.
Example: https://pukima.site
For me it redirects to the Home Page though

**Comment by FredKSchott** [comment]
Ah, I think that makes sense to add!

@Pukimaa if you are still interested in adding support for this, this one should be fairly straightforward to add! You'll want to make a change that looks something like this:

```diff
// src/preview/index.ts

// HACK: rewrite req.url so that sirv finds the file
req.url = '/' + req.url?.replace(baseURL.pathname, '');
- staticFileServer(req, res, () => sendError('Not Found'));
+ staticFileServer(req, res, () => {
+   // attempt to serve a custom 404 page, if one exists.
+   req.url = '/404.html';
+   res.statusCode = 404;
+   staticFileServer(req, res, () => {
+.    // no custom 404 page exists, send our default instead.
+     sendError('Not Found'));
+   });
+ });
```

**Comment by jablonski** [comment]
@FredKSchott I've tried your code. The custom 404 page is displayed, but the delivered status code is 200 (therefore breaking astro-basic.test.js:preview, because it expects a 404 status code).

My guess is that staticFileServer sets the statusCode to 200, because the 404.html exists in the file system. I don't see any hooks or similar to change this behaviour in sirv.

Possible fix could be to load the 404.html via fs.readFile() and send it via res.send().
