### ISSUE TITLE
Fetch failed - Type error

### ISSUE THREAD

**Issue by i4lina** [withastro/astro#4236]
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm/pnpm

### What operating system are you using?

Mac os

### Describe the Bug

I'm triying to fetch a resource from any source in the componente script in my index page, but so far I only got errors. I followed the Data Fetching example in the docs but I'm always gettingg "fetch failed". I could't gather more insight about why the fetch is failing. I attached an example repo to reproduce the error. 

### Link to Minimal Reproducible Example

https://github.com/i4lina/astro-fetch-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Hey @i4lina! I'm seeing this as well, but I think that's because [`http://radomuser.me/api`](http://radomuser.me/api) is misconfigured. You can reproduce this by running this in the browser, as well.

```js
fetch('http://radomuser.me/api')
```

<img width="376" alt="CleanShot 2022-08-10 at 11 21 23@2x" src="https://user-images.githubusercontent.com/7118177/183962141-47eeb47c-d10c-4312-bf72-7b30eea85923.png">

Please feel free to re-open this issue if you're able to validate that it's an Astro-specific problem!
