### ISSUE TITLE
Unable to create pages starting with an underscore at build time

### ISSUE THREAD

**Issue by capsia37** [withastro/astro#4277]
### What version of `astro` are you using?

v1.0.0-rc.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Ubuntu 20.04.1 LTS

### Describe the Bug

The goal:
Dynamically generate a redirects file for Netlify that should build to a file named "_redirects" in the dist folder. The redirects should be generated at build time, so it is not possible to put the file in the public folder directly.

Proposed behavior:
Use an escape char in the file name that tells Astro to generate the file instead of excluding it. For example "__redirects" could build to "_redirects" and "_redirects" could be ignored.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-g8kyed?file=src/pages/_redirects.js

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by aFuzzyBear** [comment]
Double underscore would make perfect sense for this particular use-case

**Comment by FredKSchott** [comment]
Unsatisfying answer, but this is a feature and not a bug! We use this pattern so that you can co-locate files next to your routes, without them becoming routes themselves.

But this is probably a use-case that we should still support, given how popular Netlify is. We'll just need to think about the right way to do it.

**Comment by tony-sull** [comment]
@capsia37 as a workaround for now, the `injectRoute` API can actually inject routes starting with an underscore.  It's a little extra code writing your own integration just for this route, but that should unblock you if the `_redirects` needs to be built as part of the project instead of included as a static file in `public`

**Comment by capsia37** [comment]
> Unsatisfying answer, but this is a feature and not a bug! We use this pattern so that you can co-locate files next to your routes, without them becoming routes themselves.

It's an undocumented feature that it is interfering with another feature so I didn't know exactly how to submit it since I'm not asking for a new feature. Also some documentation about the underscore feature would be useful. Should I file the issue again as feature request or keep this one?

@tony-sull Yes, another solution would be to generate a `redirects` file and then move it using the `astro:build:done` hook in an integration to move it to `_redirects`

**Comment by matthewp** [comment]
We should take this discussion to the RFC repo.
