### ISSUE TITLE
Importing a page adds scripts to the page that imported it

### ISSUE THREAD

**Issue by obj-obj** [withastro/astro#4295]
### What version of `astro` are you using?

1.0.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Importing a page in any way (such as `Astro.glob`) will embed all of its scripts in the file that's importing it. This only happens on build for some reason, not the dev server.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6upkd4

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by obj-obj** [comment]
It seems like some other stuff, like CSS tags, is also duplicated

**Comment by obj-obj** [comment]
> It seems like some other stuff, like CSS tags, is also duplicated

Nevermind, I reported it as a separate bug that got fixed and I don't think it's related

**Comment by obj-obj** [comment]
This is getting kind of out of hand, one page has the same script inserted 3 times

**Comment by matthewp** [comment]
This is by design. `Astro.glob` is equivalent to importing a file, and if you import a file you take on its scripts. This is because Astro doesn't know what scripts you actually want to use; scripts that get hoisted to the head and not dynamic in nature.

We are working on an alternative to Astro.glob if you only want to get page metadata that will not have this downside.
