### ISSUE TITLE
`@astrojs/image` should support `sharp` crop strategies such as `attention` to find high entropy spots to center on

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#4341]
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

`astro-imagetools` supported choosing the crop-strategy that `sharp` takes when cropping an image, https://sharp.pixelplumbing.com/api-resize#resize, which meant that an image of a lighthouse centered on the lighthouse, while now it simply naively cropped from the bottom and the right of the image, cutting off the lighthouse.

<table>
<tr>
	<td>Original
	<td>New
<tr>
	<td>

![image](https://user-images.githubusercontent.com/10626596/184728655-0cc8c7ab-50fb-43be-89a3-3947fe13d2c7.png)
</td>
	<td>

![image](https://user-images.githubusercontent.com/10626596/184728873-955ad031-bdd4-4bec-b739-0f17ce068ed8.png)
</td>
</table>

I realize that `astro-imagetools` is a community maintained library rather than a 1st party integration, but it'd be great to have feature parity to make migrating to `@astrojs/image` seamless

### Link to Minimal Reproducible Example

https://codesandbox.io/s/astro-4341-9rp30y?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by tony-sull** [comment]
I think we're still a little early in the image integration to add more fine-grained image transformations like this.  The plan right now is to keep the transformations with the built-in service pretty bare bones to avoid painting ourselves into a corner

We're actually hoping to swap `sharp` for [Squoosh](https://www.npmjs.com/package/@squoosh/lib) as the default image transformer soon to add support for web containers and Stackblitz.

Closing this as for now only because we need more time to hammer out the `@astrojs/image` API before committing to more complex transform options. 💯 agree it'd be nice to have this in the future though!

**Comment by brandondeweese-reify** [comment]
2 years later we still can't crop images. is this happening in the near future?

**Comment by JayBox325** [comment]
Still looking to crop images. The example I am always fighting is mobile - desktop use cases. For mobile I'd love to be able to crop to 400x800 around a focal point to best fit the viewport, then for desktop I'd want to crop to 1200 x 675 around a focal point.

**Comment by ematipico** [comment]
@JayBox325 

You probably missed the v5.0 release. This is now an experimental feature: https://astro.build/blog/astro-5/#experimental-features

Relative RFC: https://github.com/withastro/roadmap/pull/1051
