### ISSUE TITLE
Typescript type check fails on linux

### ISSUE THREAD

**Issue by mgcrea** [withastro/astro#4387]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

`tsc --noEmit` does fail on linux (gitlab CI) but does work locally on macOS.
`astro check` works on both environments.

Here is the output issue from the CI:

```
$ tsc --noEmit
[43](https://gitlab.barberine.fr/joonca/joonca-website/-/jobs/2111#L43)node_modules/astro/client-base.d.ts(1,23): error TS2688: Cannot find type definition file for 'vite/types/importmeta'.
```

So looks like some casing issue, the file `client-base.d.ts` does have the proper case but it is somehow transformed at some point to a lowercase resolve that fails.

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by hbthck** [comment]
+1 to the OP.

Facing the same issue while trying to deploy TS project to netlify.
Build is failing with the following error message :
```
node_modules/astro/client-base.d.ts(1,23): error TS2688: Cannot find type definition file for 'vite/types/importmeta'.
```

However the same does NOT happen on my local environment, macOS 12.5.1. Which kinda made it hard to detect

**Comment by rstacruz** [comment]
This also happens to me on Astro 1.0.8 on Linux via WSL2.

**Comment by Princesseuh** [comment]
The reason this happens is because TypeScript somehow turns that import path into a lowercase version on certain OSes. Here's a Vite issue talking about this exact issue. https://github.com/vitejs/vite/issues/4028

They fixed it on their end by using a path reference, but since we can't do that we'll have to find another solution, probably by making a PR to Vite itself

In the meantime, adding `skipLibCheck: true` to your `tsconfig.json` can fix the issue without losing features
