### ISSUE TITLE
QueryParams are stripped 

### ISSUE THREAD

**Issue by pbrissaud** [withastro/astro#4399]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

When navigate to a page with querystring params, the `Astro.url` strip params and `Astro.url.search` and `Astro.url.searchParams` are empty.

Did I misunderstand something or is it a bug ? 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-nxwxap

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
This is expected, because Astro builds a static site by default your build does not have access to search params. Only a server can see the search params, since they are passed by the user when the user makes a request, and static sites are built ahead of time without knowing what search params a user might send.

If you change `output: 'server'` in your config, Astro will stop stripping those values. Learn more: https://docs.astro.build/en/guides/server-side-rendering/

**Comment by pbrissaud** [comment]
Thanks @FredKSchott  for your answer !

I resolved my problem by using a Vue component that can use `window.location.href` function to get params.

**Comment by FredKSchott** [comment]
sounds perfect!

**Comment by vic-cekvenich** [comment]
"Astro builds a static site by default your build does not have access to search params." This is a bug.
That is not how http server(Apache, NGNIX) work, nor other static generators (eg 11ty). Search params are a browser command, so Astro removing it when it is client side is bug. I should not have to use server side just for querystring.

Re-opened: https://github.com/withastro/astro/issues/7489

**Comment by BigWillie** [comment]
I don't appear to be able to query the params from the server side either.

**Comment by HananoshikaYomaru** [comment]
if I set the config output to be `hybrid` and set the `prerender` of the page to be `false`, still the query params are stripped.

**Comment by r6203** [comment]
The search params are also stripped in api endpoints.

**Comment by aleclarson** [comment]
Notably, using `Astro.rewrite` with search params during SSG will result in the search params being stripped, which seems unintuitive to me.

**Comment by fulstadev** [comment]
I am using astro for the local development of the web frontend of a project (SSG). The deployed stack uses custom routing logic, which I have successfully mimicked via the `middleware.js` file to apply to the astro dev server, for an optimized DX. This is really an unexpected point I'm struggling with now, I agree with @aleclarson that, when you do a `rewrite` call in the `middleware` where you explicitly set the query string of the rewritten URL, it is unexpected that this does not carry over, even for SSG. Query strings are provided by the client and its provision is not influenced by the server, but astro's SSG basically behaves as a static rewrite server that affects provided query strings, and thus, client input.

**Comment by Buzu** [comment]
I had a similar issue, but it turned out to be a browser extension.

In an astro site I'm working on, I wanted to access URL parameters on the client, but navigating to `http://192.168.11.106:8081/?utm_source=local` would navigate to `http://192.168.11.106:8081` instead. The problem was not in Astro, but in the DuckDuckGo Privacy Essentials extension in Firefox.

A quick way to debug this is to try with a different parameter: http://192.168.11.106:8081/?my_param=abcd navigates to http://192.168.11.106:8081/?my_param=abcd

The solution is to disable the extension for the specific site you are working on.
