### ISSUE TITLE
"chunks" directory appears in build output, if custom modules are imported in Astro files

### ISSUE THREAD

**Issue by cvh23** [withastro/astro#4435]
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Mac, Linux

### Describe the Bug

I have a module file with helper functions: `src/utils/index.ts`. Some of these exported functions are used (imported) in Astro files. If I execute `astro build` an empty directory called `chunks` appears in `dist` directory (along with the expected/generated files and directories). If I remove all imports of helper functions in Astro files, there is no `chunks` directory in `dist` (intended behavior).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gvdubp-aj1rng

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
During the build we create a bundle for SSR that is used to generate pages. My guess is that a `chunks` folder is being created for that and then not cleaned up in the end. @bluwy to take a look.

**Comment by kasperaamodt** [comment]
This bug is back, and it appears to mess with Vercel deployments.

![Screenshot 2023-01-03 at 23 58 15](https://user-images.githubusercontent.com/44305520/210455184-6d1b44eb-c478-4cda-bed8-8610ad927722.png)

![Screenshot 2023-01-03 at 23 33 36](https://user-images.githubusercontent.com/44305520/210455129-aace99f5-2af8-4580-8003-1dbfe6e11f3b.png)
