### ISSUE TITLE
💡RFC: Should referencing react components with class= get translated to className= automatically?

### ISSUE THREAD

**Issue by radiosilence** [withastro/astro#448]
## What is Missing from Astro Today?

I am on the fence about whether this is too magical but currently the .astro files look like a mixture of:

```
<label class="mb-4" for="bah">Something</label>
<a href="/hi">a link</a>
<MyReactComponent htmlFor="aaa" className="mt-2">Some stuff</MyReactComponent>
```

Which gets ugly and difficult to read and error-prone.

## Proposed Solution

Should we translate common astro JSX props to React props when calling react (or whatever) components? 

## Help Make it Happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.
- [x] I am quite up against it at the moment and not sure if it's even a correct idea.

**Comment by FredKSchott** [comment]
lol love your 4th bullet :)

I'm a little torn as well, but I agree your code snippet looks very odd. 

I think that I would be in support of a special, one-off rule that would translate `class` to `className` inside of the React renderer plugin. I think React is the only framework that needs to deal with this.

**Comment by radiosilence** [comment]
I think a special one off rule could work, but then you still have the general issue of having a one JSX style (astro) including a different one (react) with different rules etc.

I mean perhaps it is best to just keep it explicit as opposed to translating, which is why I am on the fence. Is it worth introducing complexity to prevent "looking odd"?

**Comment by FredKSchott** [comment]
oh I see, like the idea that `style` is a string in HTML but an object in React would be another one. Interesting, yea that's more tricky than just a 1 off.

**Comment by jasikpark** [comment]
I suppose with that it's not invisible as to whether you're interacting with a React or Astro component? I lean towards it being explicit since it's adding an entire new API for how React components are passed props if every prop is translated from camel case to kebab case + string -> object/whatever..

**Comment by natemoo-re** [comment]
Very on the fence about this one! It would be nice for `astro` files to be more consistent, but it's obviously a lot less confusing and error-prone to just pass exactly the format your component needs.

That being said, there's a very clear place where renderers could modify props before passing them to the framework component. So this is more of a question of if we _want_ implicit behavior.

In general, how should Astro handle syntax that is specific to a particular framework? For frameworks that have HTML-specific syntax (like Vue), I think we should encourage the use of that. For JSX-like languages, should we just require users to be explicit?

### React
- Use `className`
- Use `htmlFor`
- Use `style` object

### Vue
- No `:prop`, use `v-bind:prop`
- No `@event`, use `v-on:event`

**Comment by FredKSchott** [comment]
Thought about this a bit more, and I think we should stick to HTML syntax over React or Vue syntax. Reason being, that you're in an Astro component and Astro syntax is a superset of HTML. Using framework specific sugar would break this guarantee.

That would mean converting things like className & htmlFor in the React renderer. To be honest, I bet we could disallow setting the `style` prop on React components for now. But if that's a dealbreaker, we could convert that to an object for you automatically as well.

**Comment by radiosilence** [comment]
I do feel like this should be done within the loader, if at all

**Comment by FredKSchott** [comment]
RFC Dicussion: needs more discussion / thinking around edge cases, specifically vue syntax

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
