### ISSUE TITLE
🏆 DX WEEK

### ISSUE THREAD

**Issue by FredKSchott** [withastro/astro#4541]
## Action Items: Day 1 (Brynn Stream) 
https://www.twitch.tv/videos/1575481405

- [x] Tailwind should be a peer dep of the tailwind integration
- [x] [@bholmesdev] **BUG:** deleting a style tag killed the server! ~2:49:00
- [x] **BUG:** weird error message in the browser when style has an issue: `?style=X` etc. `~2:49:00`
   - [@matthewp] Spent a while trying to recreate but could not
- [x] [@bholmesdev] `astro add`: Rename “Add an Adapter” to “Add an SSR Adapter” or “Server Adapter”
- [x] [@delucis] `astro add`: are our “recommended” hosting still up to date? Would be good to audit that list — #4574
- [x] [@bholmesdev] `create-astro`: add a link to astro.new so that users can see the templates before selecting
  - [@FredKSchott] possibly moot now that we have our new template question asker 
- [x] [@sarah11918 ]`astro.new`: add a preview image to each of our main starter templates. Sort of like https://nextjs.org/examples - https://github.com/withastro/astro.new/pull/16 (starting point)

## Action Items: Day 2 (Dax Stream)
https://www.youtube.com/watch?v=cmb4zVTQ5ZM

- [x] [@sarah11918] `docs`: pull UI Frameworks higher up in the guides sidebar? One of the first things a user looks for, but easy to miss at the bottom.
- [x] [@sarah11918] `docs`: audit that `astro add` is mentioned anywhere that “adding an SSR adapter” is needed. Ex: No Astro add in these docs https://docs.astro.build/en/guides/server-side-rendering/ - Docs PR: https://github.com/withastro/docs/pull/1452 Astro PR (for package READMES): https://github.com/withastro/astro/pull/4595
- [x] [@tony-sull] `astro.build`: Add an SSR adapters collection to the integration catalog
- [ ] `astro`: Add a “standalone” mode for the node adapter
- [ ] `astro`: Allow integration to provide a “preview” command

## Action Items: Day 3  (YuriCodeBot Stream)

- [x] [@FredKSchott] To figure out the right set of templates for create-astro
- [x] [@matthewp] Protect users from bad img src imports  (‘../public’)
- [ ] Protect users from bad img ESM imports (‘../public’)

## Action Items: Day 4 ()

- [x] [@bholmesdev]: Server restart on config change (PR in progress)
- [x] #4601
- [ ] **BUG:** Vue hydration mismatch errors in browser console
- [ ] `basics`: Explore - is there a way to improve styles without ruining the pretty look and feel?

## Action Items: Starter Template Audit
- [x] [@Jutanium] **all:** use `dependencies` instead of `devDependencies` for all package.json deps
- [x] [@Jutanium] **all:** use `<style is:global>` over `:global`
- [ ] **blog:** astro.build/themes screenshot should just be a screenshot, no pretty presentation
- [ ] consistent naming scheme: with-X, etc.
- [x] [@Jutanium] consistent styles: get rid of sass
- [x] consistent styles: use is:global > `:global`
- [x] consistent imports: confirm no more remote CDN / unpkg imports
- [x] [@matthewp] Remove unused CSS rules (just-the-basics still has some).
- [x] Finalize `.stackblitzrc` in examples, StackBlitz has baselined all settings, `dev` is default
- [ ] "astro check" should pass in all examples, add to smoke test

**Comment by aFuzzyBear** [comment]
Tailwind integration has been updated :  #4543

**Comment by Jutanium** [comment]
Quick starter template action items: #4544

**Comment by FredKSchott** [comment]
Update: I added a few more unchecked boxes from an old examples audit to this list. FYI they may be out of date and can be closed / checked off by just confirming!

**Comment by Jutanium** [comment]
@FredKSchott the only template that still uses sass is the portfolio template. But it also has another problem: It uses Preact for components that could be made using `.astro`!

Should I:
1. Just migrate sass to CSS for this PR
2. Both remove sass and Preact for this PR
3. Leave it alone (as there may have been talk of revising this template from the ground up?)

**Comment by FredKSchott** [comment]
1 & 2 both sound good to me! As a reviewer, these should be okay to combine into a single PR so no issue there from me.

**Comment by victorkane** [comment]
`astro.new` When I click on `Open in gitpod` button for any example, instead of a cool online instance experience and then some (more like IDE than Stackblitz and CodeSandbox) what gets put in the window is the document root of the repo and example fails to run.

```bash
Loading example project: with-tailwindcss

> @example/with-tailwindcss@0.0.1 start /workspace/astro/examples/with-tailwindcss
> astro dev

sh: 1: astro: not found
 ELIFECYCLE  Command failed.
gitpod /workspace/astro (latest) $ pwd
/workspace/astro
```

I can then `cd` to appropriate directory (not exactly a friendly experience for newbie) and do `npm i` manually, but that fails. 

**So, with astro.new for me at least gitpod is unusable. Why is this?**

**Comment by sarah11918** [comment]
> `astro.new` When I click on `Open in gitpod` button for any example, instead of a cool online instance experience and then some (more like IDE than Stackblitz and CodeSandbox) what gets put in the window is the document root of the repo and example fails to run.

Ooh, this shouldn't happen @victorkane! There was an issue, but we recently fixed it. I wonder whether something *else* changed in Astro to cause this.

One problem we have in general is that Gitpod right now can only open the entire monorepo. So, we worked with them to create a script that would `cd` you automatically to one particular starter template's root, and then run that starter only. BUT, even though we could do that, we can't stop the file tree from showing the entire monorepo. (We could at least open to the root of a starter, but you still see ALL of `withastro/astro` in Gitpod. So, that's a bit annoying, but we were able to get a starter to run.) 

This is a very recent break (again) and I'll look into it with Gitpod!

**Comment by victorkane** [comment]
> I'm going to ask @shaal if he has advice on this!

Super cool! Not a problem for me, individually, I'm simply trying to reflect a question of DX. I think that part of the problem is that while the noble goal of Astro being a fifth dimension that permeates "all the things", as we spread out from a basic SSG tool with a fantastic Astro component JSX-like experience, to, I can then import UI frameworks, to, I can use Astro for anything, there is a consequent infinite expansion into situations that need e2e testing (mentioned in the chat on Day 2) in many, many, many situations as devs bring enormous expectations... why can't I use `vue.use` in my vue component setup (when one thing is to add in a vue component here, a preact component there, and another is to suppose that Astro must have all the functionality of Nuxt, and Astro must have all the functionality of Next for React squad)... this expands geometrically and places unreasonable pressures on the Astro dev community.

Take Tailwind, for example... hey Tailwind just came out with groovy (sorry) full-scale site templates... they all work with Next.js ... hey why don't they work with Astro??? hey, I paid two hundred bucks for Tailwind UI and they have examples in their extra-special components for React, Vue and HTML... how come they don't work with Astro???  They work with Next.js and Nuxt.js because they were designed with all that cruft in mind for a cruft-addicted and cruft-dependent mindset. Astro is determined to move away from that cruft-dependent all things to all peeps mindset, and say, by default, "NO CRUFT".  

So, DX Week in my opinion should be a huge shout out to lower expectations to be able to, or even want to, meet head on with the cruft-dependency (it's the same thing as the "rockstar coder" grotesque). DX week should be a huge warning to avoid complexity explosion. 

As Gramsci explains from behind prison bars in a pre-WWII context: the main thing is to pursue a war of gaining solid (sorry)  ground positions, and to avoid at all costs an ultra-left, right, up, down, balloon guerrilla war of being in constant maneuver mode, and jumping in here and jumping in there...

So the call out would be to insist on people coming to Astro, to understand the problem we're trying to solve: cruft-dependency, complexity payload, and the rockstar culture needed to supposedly deal with it... we believe in starting out light and flying freely in the cosmos... 80-20... 80% of even huge corporate website needs are marketing landing pages and content first projects... we start out with a rock-solid experience there... and can we do extra SPA on a particular page if needed? yes! spin up these examples and check it out! Can we do SSR using a node.js adapter on your digital ocean weekend server? yes! Does it work on Vercel? yes! Does it work on Netflify? yes, again thanks to hard work, in just a few weeks. Cool. Does SSR work on AWS? hmmmmm Hopefully the guys from the silent movie yesterday will presently be gifting us with a PR... if not, guess it will have to wait... 

Is that a failure? No! Astro has come sooooo far in just a few weeks... Let's gain and hold the ground we're gaining, and relax a bit... Let's plan the e2e tests we all want (hopefully automated) so that we first see a decrease in leaks in the spaceship, then we move successively on to more and more scenarios, testing as we go. That's the valuable lesson this week I think.

**Comment by shaal** [comment]
Hi @victorkane 👋  I think I remember you from the Drupal community :) 

@sarah11918 I'm looking into it.
`pnpm` version should be something that gets updated when the custom docker image gets rebuilt, for some reason it doesn't get a new version. I'll keep you updated

**Comment by shaal** [comment]
@sarah11918 PR for temporary workaround is ready - https://github.com/withastro/astro/pull/4571

**Comment by shaal** [comment]
@natemoo-re @sarah11918 PR #4571 is merged to `main`,
but I noticed https://astro.new/ opens workspaces that are in `latest` branch, which is failing because the changes in this PR are not in that branch.

**Comment by natemoo-re** [comment]
Thanks @shaal! I am tempted to cherry-pick this onto `latest`, but this should be fixed automatically when we do the next release.

**Comment by FredKSchott** [comment]
Closing, thanks everyone for participating in DX Week! Everything not yet checked has still been migrated to items on our core issue tracker.
