### ISSUE TITLE
Vercel Edge Adapter fails to deploy with Sanity integration enabled 

### ISSUE THREAD

**Issue by webcicle** [withastro/astro#4630]
### What version of `astro` are you using?

^1.1.1

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When activating SSR via Vercel edge, the build gives the following error 

```
[commonjs--resolver] Cannot bundle Node.js built-in "url" imported from "node_modules/eventsource/lib/eventsource.js". Consider disabling ssr.noExternal or remove the built-in dependency.
--
15:43:31.768 | file: /vercel/path0/node_modules/@sanity/client/lib/sanityClient.js
15:43:32.007 | error   Cannot bundle Node.js built-in "url" imported from "node_modules/eventsource/lib/eventsource.js". Consider disabling ssr.noExternal or remove the built-in dependency.
```

If I change it to a serverless function the deploy works. This issue is similar to #4391 but appears to be related to Sanity.io integration. 

Here is my astro.config setup as well: 

```
import { defineConfig } from 'astro/config';
import vercel from '@astrojs/vercel/serverless';

export default defineConfig({
	output: 'server',
	adapter: vercel(),
	integrations: [],
});
```

The stackblitz link does not contain a reproducible example but steps to reproduce would be: 
- Setup project and Sanity.io client, connected to CMS
- Add a fetch request from DB
- Deploy to Vercel with Edge adapter

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/minimal?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Have you tried setting `url` to external?

```js
vite: {
  ssr: { external: ['url'] }
}
```

**Comment by matthewp** [comment]
If that works it might be something we should add to the Vercel adapter.

**Comment by webcicle** [comment]
I hadn't, but I just did, and unfortunately it gives me the same error then

**Comment by narration-sd** [comment]
@webicicle, I found a fix for this over on Sanity's client issues, [here](https://github.com/sanity-io/client/issues/14#issuecomment-1426186802), where you use a preproduction client version 5.0.0 (!) to succeed, which appears to work on Netlify also. I had tried a polyfill among other things unsuccessful, before finding this.

But, @matthewp, I then ran into a very similar block due to missing 'http' function under Deno. I've reported this to Sanity with logs, [here](https://github.com/sanity-io/client/issues/14#issuecomment-1441246679), as it looks also accountable for them to patch, given the call is within their library called from their client. 

Deno is fun...not..
