### ISSUE TITLE
Custom 404 page doesn't work in dynamic routes with Vercel

### ISSUE THREAD

**Issue by shishkin** [withastro/astro#4635]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I can't make a custom 404 page work on SSR Vercel in this dynamic routing setup:

```
items/[slug].astro -> returns a 404 response
404.astro
index.astro
```

The routing results are:

* /not-found => renders custom 404 page
* /items/not-found => renders empty 404 response

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1ajmmy-ck4qyy?file=src/pages/items/[slug].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is tricky. If we were to route this back to the custom 404 page then someone could legitimately call that a bug too. Because they might have included a better error message and we would be erasing that by instead using 404.astro. I think we have to assume that if you return a Response from a page you want that to be the *actual response*.

That is to say, I can see both sides here. I would probably propose instead some way to render an Astro component from within the page, so you could do this:

```astro
---
import FourOhFour from '../pages/404.astro';

return new Response(Astro.render(FourOhFour, { props: 'here' }), {
  status: 404
});
---
```

This idea has come up before. It's probably something we need to talk about on the rfcs repo first.

Closing as I don't think we can do anything about this and it would be a breaking change.

**Comment by shishkin** [comment]
Thanks @matthewp! Now I see how it is tricky. I agree that in general when a page returns a custom `Response` it probably shouldn't be changed.
