### ISSUE TITLE
Script tag doesn't get processed by Astro if any attribute is present on it

### ISSUE THREAD

**Issue by hsensh** [withastro/astro#4648]
### What version of `astro` are you using?

1.1.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I followed the guide for importing scripts located inside the src/ folder and I tried the following:

`<script src="../example.js"></script>`

```
<script>
import "../example.js";
</script>
```

Both worked fine and got processed by Astro, however, if I try to add any attribute to either of these it suddenly gives me that the script could not be found or that import statements should only happens inside of modules. It seems like Astro is not even  processing them. It gave the same result it would give if is:inline or is:raw is present on the script.

I need to add the defer attribute to those scripts as I'm using Alpine and these won't load unless they're deferred.

I searched the docs and the bugs on here but could not find anything addressing it.

Do note that the scripts work fine if I put them in the public folder, but I would prefer if they were in the src/ folder since I want them to be processed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8ozic5?file=src/pages/index.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Yep, this is on purpose! Astro only builds script tags without any attributes.

You don't need to add `defer`, we do that automatically for you. If you add any attributes it becomes equivalent of `is:inline`.

**Comment by hsensh** [comment]
But the problem is it doesn't have the same behavior as when I put defer and reference it from the public directory. Alpine just doesn't load correctly.

`<script src="./script.js" defer></script>` referenced from public directory works
However, `<script src="./script.js"></script>` reference from src doesn't

And in the dist folder, the script is referenced with neither a defer attribute, nor async="false", which doesn't ultimately amount to the same behavior.

**Comment by thdoan** [comment]
> Yep, this is on purpose! Astro only builds script tags without any attributes.
>
> You don't need to add defer, we do that automatically for you. If you add any attributes it becomes equivalent of `is:inline`.

@matthewp two questions:

1. Google recommends adding `async` to the GA4 snippet, e.g., `<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>` -- should we remove `async` when adding the snippet to an .astro template?

2. I assume since it's in the documentation, Astro will play well with Partytown if we add `type="text/partytown"` to script tags, right? Right now I'm using this GA4 snippet in my .astro template:

```
<script type="text/partytown" async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
<script type="text/partytown">
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-XXXXXXXXXX');
</script>
```

Please let me know if I should remove `async` from the tag, or it doesn't matter.

**Comment by dankcellar** [comment]
Bump same question as @thdoan 
 
I have not seen any difference doing it one way or the other but an "official astro way" would be nice!

**Comment by thdoan** [comment]
@dankcellar on one of my projects I noticed JS errors in the console when I had `type="text/partytown"` in the inline script tag, so now my code looks like this:

```
<script type="text/partytown" async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-XXXXXXXXXX');
</script>
```

The inline code is so miniscule adding Partytown isn't going to benefit much anyway. Also, if you use an ad blocker like uBlock Origin, you're going to see JS errors in the console.

**Comment by snimavat** [comment]
I have this script, and astro does not process it, the script isnt included in html at all

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src={gtagUrl}></script>
<script define:vars={{id}}>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', id);
</script>

````

**Comment by muddassirhq** [comment]
Hi all, is there any update on this, did it work for anyone? I am also facing similar issue, I want to optimize my site but just adding google tag manager is make the site slow by 20%

**Comment by fulstadev** [comment]
Just came across this, and just wanted to mention the issue I just faced due to the fact that `script` tags get treated as `is:inline` in astro if any attribute is present on it:

1. Had to extend one of my astro components with a named slot as, in some cases, I have to insert a `script` tag within a precise location of the component (already having other slots, including an unnamed one).
2. astro complains that this will resulting in the builder treating the script tag as inline script.
3. this in turn makes that script incompatible with [security.csp](https://docs.astro.build/de/reference/configuration-reference/#securitycsp) set to `true`, as astro does not generate csp-hashes for inline script elements.
4. Result: CSP blocks the script.

This makes the usage of the [named slots](https://docs.astro.build/en/basics/astro-components/#named-slots) incompatible with `script` tags?
