### ISSUE TITLE
💡 RFC: "Permalink” for certain page

### ISSUE THREAD

**Issue by kaleidawave** [withastro/astro#465]
## What is Missing from Astro Today?

It would be nice to specify the name of the HTML file that is outputted. A feature similar to [eleventy permalinks](https://www.11ty.dev/docs/permalinks/#use-data-variables-in-permalink). 

## Proposed Solution

```js
export let permalink = “my-file.html”
```

RHS could be any expression 

## Help Make it Happen!

- [x] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
Awesome, I'd love to kick off a quick discussion for this feature, and then would love your help implementing if you're still interested!

Because we currently use file-based routing, the intention is that a page/post should always live somewhere matching the final URL. If you want to change the final URL / permalink, you should move the post.

Can you explain more about your use-case? Are you happy to just move the file to match the permalink that you'd like to generate?

**Comment by kaleidawave** [comment]
Hey 👋 Currently we have a `404.astro` page in the astro root. We are using firebase hosting and for a 404 route there needs to be top level `404.html` in the output directory (same way GitHub pages works) but currently astro builds it to `dist/404/index.html`.  With permalinks we could specify to build the page to `dist/404.html`. I don't think we could move the astro page/source file anyway to change this behaviour. This suggestion is probably not the simplest solution but it would solve our issue 😄 . 

I think this is around where the addition would happen?:

https://github.com/snowpackjs/astro/blob/02d175cd95d669ce7ca7330cdb1395c51e4632ce/packages/astro/src/build/page.ts#L93

Would adding this cause complications in the dev server?

Is adding a *permalinks* overkill? Would adding a \~`404buildPath`\~ option to astro config be better?

**Comment by natemoo-re** [comment]
File-based routing is definitely one of Astro's design principles, so introducing something like a global `permalink` has the potential to make things quite confusing for users.

That being said, your use case makes total sense! We should definitely expose _something_ to make this work. Possibly related to #452? That is a feature request to control where the build outputs the generated HTML.

**Comment by georges-gomes** [comment]
Throwing ideas: what about treating file a prefix to output slug.html instead of slug/index.html.

Something like !404.astro would generate 404.html.

I expect it to be limited to only a few specific files...

I'm proposing a filename prefix because it's a routing thing and all routing thing is on the file system...

My 2 cents

**Comment by FredKSchott** [comment]
I have such a love-hate relationship with file-based routing. Maybe `$` could just mean "virtual" and be the prefix that you add for both collections and pages where the route !== the filename?

**Comment by georges-gomes** [comment]
Mental models are powerful.👍

**Comment by FredKSchott** [comment]
fyi I ran into some trouble debugging a collection that changed the permalink to not match the file name here: #483

**Comment by FredKSchott** [comment]
RFC Discussion: Can we solve this with config instead? File-based routing is pretty explicit about file location = permalink.

**Comment by georges-gomes** [comment]
Should not hurt. I take it.

**Comment by georges-gomes** [comment]
I have in mind to config just some specific routes... not all of them.

**Comment by kaleidawave** [comment]
Yep the main reason I would like this change is that `404.astro` is built to `404/index.html` when I need it at `404.html`. A option in the config such as *`build404toTopLevel`* as a special case to where to build `404.astro` wouldn't be the cleanest change but would be **incredibly** helpful for firebase and gh page users. It would be great if Astro handled this through a bool in the config rather than messing around with `mv` in `postbuild` 😄

**Comment by natemoo-re** [comment]
Moving this to "On Hold" while we explore #452

**Comment by P-Froggy** [comment]
Just discovered Astro yesterday and I love the concept. However, overwriting the standard file-based routing with a custom route is the one thing that prevents me from switching to Astro right now, since I am only working with internationalized websites.

Right now, with eleventh, I organize my source files like this and generate localized routes in the building process:

> src/pages/career/open-jobs.**en**.md
> src/pages/career/open-jobs.**de**.md

The generated output looks like this:
> /career/open-jobs/index.html
> /karriere/offene-stellen/index html

This makes it easier to work with the source files since I don't have to look in 2 different places when creating a new page or editing an existing one.

Plus, I'm using a helper function which automatically gets the localized url from the file location by just referencing `/pages/career/open-jobs` (without `.de.md`).

So for me personally, it would be best to do it like eleventy an make file-based routing standard, but giving the possibility of overwriting the output path via a custom variable.

**Comment by P-Froggy** [comment]
> Would `[lang]/career/open-jobs/index.astro` be valid w/ file-based routing?

It works as long as you don't need localized routes, which is relatively important for SEO in multi language sites.

**Comment by jasikpark** [comment]
> It works as long as you don't need localized routes, which is relatively important for SEO in multi language sites.

What are "localized routes"?

**Comment by amatiasq** [comment]
> What are "localized routes"?

```
en/career/open-jobs/
es/career/open-jobs/
```
vs
```
en/career/open-jobs/
es/carera/trabajos-disponibles/
```

**Comment by P-Froggy** [comment]
> > It works as long as you don't need localized routes, which is relatively important for SEO in multi language sites.
> 
> What are "localized routes"?

Sorry, maybe it's the wrong term. I just meant that the url should be translated too, so
`https://www.example.com/career/open-jobs/`
Should be (e.g. in German)
`https://www.example.com/de/karriere/offene-stellen/`
and not just an English url with the German language prefix.
I know that this applies only to a certain group of users, who build websites which are multi language and layout centric (in contrast to content centric websites like documentations or wikis), but having the option to set a custom permalink would make development easier for these kind of people.

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat

**Comment by maddsua** [comment]
> Would `[lang]/career/open-jobs/index.astro` be valid w/ file-based routing?

Oh yeah, and if you want, let's say `/en/`, to be the default language, i.e to become just `/`. you need to use `[...lang]` (mind these 3 dots) and also set it to `undefined`. Setting `lang` to `/` didn't work for me.

Posting this bc docs mention the problem, but googling for it brings here first.
