### ISSUE TITLE
Can't install.

### ISSUE THREAD

**Issue by Cruebee** [withastro/astro#4663]
### What version of `astro` are you using?

@latest

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

NPM

### What operating system are you using?

windows

### Describe the Bug

Trying to use CLI ( npm create astro@latest ) but then I keep getting this error code even after installing git, however, my other developer used this CLI prompt fine and they don't have git installed at all. I simply can't use it for whatever reason. Err below:

 × ■■▶ Copying project files...
could not find commit hash for latest
This seems to be an issue with degit. Please check if you have 'git' installed on your system, and install it if you don't have (https://git-scm.com).
If you do have 'git' installed, please run this command with the --verbose flag and file a new issue with the command output here: https://github.com/withastro/astro/issues
npm timing command:create Completed in 4340ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
npm verb stack     at ChildProcess.emit (node:events:527:28)
npm verb stack     at maybeClose (node:internal/child_process:1092:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm verb cwd C:\Windows
npm verb Windows_NT 10.0.19044
npm verb node v16.15.1
npm verb npm  v8.11.0
npm ERR! code 1
npm ERR! path C:\Windows
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-astro
npm verb exit 1
npm timing npm Completed in 4516ms
npm verb code 1

### Link to Minimal Reproducible Example

astro.new

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@Cruebee after you install git you probably need to close and reopen your terminal. Type `git` to be sure its installed properly.

**Comment by ScriptRaccoon** [comment]
I get the same error, but it's not because of Git.

`D:\Development>npm create astro@latest

+—————+  Houston:
| ^ u ^  I'll be your assistant today.
+—————+

 astro   v1.6.0 Launch sequence initiated.

? Where would you like to create your new project? » ./test

? Where would you like to create your new project? » .
? Where would you like to create your new project? » ./test
√ Where would you like to create your new project? ... ./test

√ How would you like to setup your new project? » a few best practices (recommended)
          ■■▶ Copying project files...
npm ERR! code 1
npm ERR! path D:\Development
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-astro`

**Comment by natemoo-re** [comment]
@ScriptRaccoon would you mind opening a new issue for this? This seems like something else.

**Comment by ScriptRaccoon** [comment]
Opened #5227 for this.
