### ISSUE TITLE
Error when hosting concents of dist folder

### ISSUE THREAD

**Issue by MartijnHarmenzon** [withastro/astro#4674]
### What version of `astro` are you using?

1.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When hosting the build result (contents of the dist folder) on AWS S3 as a static website, it will give the following error:

![image](https://user-images.githubusercontent.com/23123158/189144604-f28c1bd9-39d6-402c-948c-a9081342b3dc.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ms6i8w?file=src%2Fscripts%2Falpine_func.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
That looks like you may need some configuration for S3 to serve your JavaScript files with the correct MIME type (`application/javascript` instead of `text/plain`). I’m not an S3 user but maybe this Stack Overflow answer is helpful? https://stackoverflow.com/questions/67925203/aws-cloudfront-serving-javascript-modules-as-wrong-mime-type-text-plain

**Comment by MartijnHarmenzon** [comment]
Thanks @delucis! That was it. Working now.
