### ISSUE TITLE
Providing the HTML element from a component may make it's children fail to render

### ISSUE THREAD

**Issue by EthanStandel** [withastro/astro#4784]
### What version of `astro` are you using?

1.2.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

If you wrap your layout with an Astro component that provides the `<html /> ` element, the direct children of that element won't render in the output. This usually ends up with both the `<body />` & `<head />` elements not existing... but their children are rendered as siblings rather than cousins which causes FOUC on most browsers, alongside just being semantically incorrect HTML.

[This repo shows the issue as a minimum reproduction](https://github.com/EthanStandel/astro-bug-min-repro).
[This is the commit which creates the issue](https://github.com/EthanStandel/astro-bug-min-repro/commit/dff1e5726f060e93dc09e287484d5cc6f58e7be8)

~~Just tried to recreate in [astro.new](https://astro.new) on StackBlitz and it didn't happen, but if I pull the latest version and run locally in both dev mode and after a build, the issue happens.~~ Correction, it was working, but I was grabbing the wrong url when I did view-source in the browser.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2hgchp?file=src/layouts/ThemeProvider.astro

^ you have to see the actual rendered HTML output, because it looks like dev-tools will add a body for you, but that's not what is actually sent over the wire

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Thanks! I think I'm aware of why this happening (sort of). We render a head at the earliest opportunity but because slots work slightly differently we are probably rendering it a second time.

**Comment by matthewp** [comment]
Ok, I've had time to go over this issue and unfortunately this is not something we can support. Let me explain why:

The Astro parser tries to be as close to HTML as possible, and in HTML the `<head>` (and `<body>` and `<html>`) tag is optional. So in order to inject the scripts and styles into the head, the parser adds injection points any time it sees an element/component it doesn't recognize.

So it sees that there is a `<ThemeProvider />` (in your example) and it doesn't know if that contains `<head>` content or `<body>` content, so it inserts an injection point just before. That injection will cause head content to be placed before your defined `<head>`.

My recommendation is to instead move the `<head>` element to inside of `<ThemeProvider>` and use a slot to slot your head content into there.
