### ISSUE TITLE
Server builds fail with Vue plugin

### ISSUE THREAD

**Issue by marshallswain** [withastro/astro#5063]
### What version of `astro` are you using?

1.4.7

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Build fails when using `@astrojs/vue` together with a server plugin. 

Rollup tries to bundle the `src` attribute of `img` tags for images in the public directory.  The problem only occurs when doing server build with the Vue plugin.  I tried two plugins:

- `@astrojs/cloudflare`
- `@astrojs/node`

You can see a screenshot of the error in the repro repo: https://github.com/marshallswain/my-astro-site

### Link to Minimal Reproducible Example

https://github.com/marshallswain/my-astro-site

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
That's pretty odd isn't it. This doesn't happen with regular SSG builds? My first instinct was that the Vue plugin was including these in the build, but perhaps something else is going on here.

**Comment by marshallswain** [comment]
> This doesn't happen with regular SSG builds?

Yeah, thankfully the SSG builds work just fine. It's only when building with a `server` plugin.

**Comment by marshallswain** [comment]
Update on version numbers.  The problem continues with the latest versions:

```
@astrojs/cloudflare  ^3.0.0  →  ^3.1.0
astro                ^1.4.7  →  ^1.5.0
```

**Comment by bluwy** [comment]
Looks like this is because we [turn off `publicDir`](https://github.com/withastro/astro/blob/863391f10e179d87ab1f24f944e8601314ff4db7/packages/astro/src/core/build/static-build.ts#L157) when building for SSR as we don't want to copy the public assets in SSR builds (only client builds).

This means that you can't do `import imgUrl from "/favicon.svg"` in SSR, which is what `@vitejs/plugin-vue` does under-the-hood for the repro's code.

This can be workaround by moving the asset into `src` (out of `/public`), or disable absolute imports like:

```js
integrations: [
	vue({
		template: {
			transformAssetUrls: {
				includeAbsolute: false,
			},
		},
	}),
]
```

Trying to find a solution on the Vite side at the meantime so it works better.

**Comment by bluwy** [comment]
Update: We discussed https://github.com/vitejs/vite/pull/10550 a bit in the last Vite team meeting, but we'd need Evan's input as this is a new feature. I'm hoping to get it in the next Vite 3.2 release, which might be happening at the end of the week.

**Comment by marshallswain** [comment]
Thank you for fixing the issue @bluwy!  I've become accustomed to fixing things myself, so I'm feeling spoiled, right now.  This must be what it feels like to be royalty.  :)  Thank you, again.

**Comment by bluwy** [comment]
No problem 😄 This turned out to be quite an oversight in Vite's SSR implementation and glad it was surfaced!
