### ISSUE TITLE
Heading elements in MDX not being passed to Astro.props 

### ISSUE THREAD

**Issue by fmonper1** [withastro/astro#5084]
### What version of `astro` are you using?

1.5.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

Npm

### What operating system are you using?

Mac

### Describe the Bug

I am authoring some MDX pages where I render a list of tables with a heading for each of the tables using an .astro component.

I would expect this headings from the astro components to be included in the headings property of Astro.props in my layout, but the headings are not included in the props and thus not appear on the table of content.

![image](https://user-images.githubusercontent.com/16008141/195712900-a6876a63-286f-4e8c-96fe-8976c0bc268b.png)

I would expect the `this is not` heading to appear on the table of content but it's not appearing.

Noktasizi from [this discord discussion ](https://discord.com/channels/830184174198718474/1019713903481081876) might be able to provide more content

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qhpm6w?file=src%2Fpages%2Fen%2Fintroduction.mdx,astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kcole93** [comment]
To add a bit more detail based on the discussion taking place on the Discord server, I believe this behavior is unexpected because Astro's built-in `collect-headings` plugin is described as a Rehype plugin that would presumably gather headings from the HTML rendered from a MD or MDX page.

However, in practice *only headings defined in Markdown syntax (e.g., `## Heading 2`) are correctly picked up* by the built-in plugin while headings defined as HTML (e.g., `<h2>Heading 2</h2>`) are not identified or given an ID. This behavior also seems to hold true when using a pipeline of Rehype plugins like `rehypeSlug`, `rehypeAutolinkHeadings` and `toc`. A minimal production of this behavior can be found [here](https://stackblitz.com/edit/github-t1qyad?file=src/pages/example.mdx).

Given this information, it seems like there's potentially something funky going on in the processing pipeline that results in elements defined via HTML markup not being sent further down the line.

**Comment by matthewp** [comment]
@ematipico this is related to the MDX integration in `packages/integrations/mdx`.

**Comment by tudorpopams** [comment]
This issue is happening for `md` files as well, in pre 2.0 versions (currently using 1.6).

**Comment by imchell** [comment]
[`rehypeHeadingIds()`](https://github.com/withastro/astro/blob/b6154d2d57bfb77767a3ccf9e91c1ae4051c81bc/packages/markdown/remark/src/rehype-collect-headings.ts#L13) decides if nodes of type `element` are headings, but ignores all nodes of type `mdxJsxFlowElement`. As of this issue, `<h2>this is not</h2>` is parsed as `mdxJsxFlowElement` by remark, so it cannot be detected by `rehypeHeadingIds()`.

**Comment by ematipico** [comment]
I talked with the UI Team, who told me they use this "feature" to exclude headings from the ToC. If we decided to change the logic, this would break the docs website. 

Although, this feature is not documented at the moment. I think it's best to open in issue in their repository to document this **intended** behaviour.

**Comment by CyberSinh** [comment]
@ematipico, I think this issue is definitely a bug because headers written in Markdown in [imported component](https://github.com/withastro/starlight/issues/2078) are not detected by `rehypeHeadingIds()` either. In any case, I find it hard to see this behavior as "feature".

**Comment by fratzinger** [comment]
For everyone stumbling upon this, see the workaround: https://github.com/withastro/starlight/issues/561#issuecomment-2176366444
