### ISSUE TITLE
Items in public/ are resolved in dev mode without base but not in production

### ISSUE THREAD

**Issue by kasvith** [withastro/astro#5107]
### What version of `astro` are you using?

1.5.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm, pnpm

### What operating system are you using?

Linux

### Describe the Bug

1. Refer a file in `public` folder with  markdown
![image](https://user-images.githubusercontent.com/13379595/196174634-16acdf60-3a87-4186-b69a-adada9d10d02.png)

2. This works fine in dev mode because vite resolves it from public directory
3. Change your base in astro config (i.e to `/docs`)
4. Now do a production build, we assume all will be resolved using `/docs/` as base path now
5. If you open the site with `astro preview` images referred in markdown are now broken. Main reason is astro doesn't post processes content in markdown after build(it does this to CSS, so they resolves correctly with base path `/docs`)
![image](https://user-images.githubusercontent.com/13379595/196175435-f791bba3-9ae6-438c-8f2f-3d7ce7f55273.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jdsqdu

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kasvith** [comment]
I would like to solve this with a little guidance

**Comment by matthewp** [comment]
Thanks, this should not be working on dev mode. We should fix that.

The reason why this doesn't work is because Astro does not modify your `<img>` tags (or any HTML you write). We don't prepend the base. the `base` is used to know how to add our own `<link>` and `<script>` tags for things like the built CSS and the bundled JavaScript.

My advice is to add the base as part of your image tag like so: `<img src="/docs/nested/icon.svg" />`

**Comment by ChrisSki** [comment]
I’m totally ok with this. At least fixing in dev will solve a lot of my frustrations. Thanks for working on it!
