### ISSUE TITLE
define:vars not working in css with content property

### ISSUE THREAD

**Issue by gatapia** [withastro/astro#5169]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

The following code is not working:
```
---
export interface Props {
  test_variable: string;
}
const { test_variable } = Astro.props;
---
<h1></h1>
<style lang="scss" define:vars={{test_variable}}>; 
  $testv: var(--test_variable);
  @debug 'Value: #{$testv}';

  h1::before {
    content: var(--test_variable)
  }
</style>
```
The above simply prints `Value: var(--test_variable)` to the astro dev console and the h1 element does not show the variable text.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-m8pexh?file=src/components/Tour.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by panwauu** [comment]
Your reproducible is with astro 0.20.5. so please update it. 

For me testing your example (without scss though) the `;` after the <style> tag lead to the problem. Also there is no `;` after the content attribute. Does correcting the simicolons remove your problem? Does it work without the vars, if you just type something hardcoded in the content property?

**Comment by gatapia** [comment]
I updated the stackblitz: https://stackblitz.com/edit/astro-m8pexh?file=src/components/Tour.astro

Included:
- upgraded astro to latest 1.5.3
- fixed semicolons
- added example with manual `content` property (which works)
- and two examples of variables not working

**Comment by panwauu** [comment]
I investigated a little bit and the problem seems to be that the content of the js string is converted to css and in the process the `'` quotation marks are removed. The content of the string is used as css. 

This means that the css variables become: 
```css
element {
  --c1: Content 1;
  --c2: Content 2;
}
```

But you want it treated as string. So you need to wrap the content in additional quotation marks. 
```js
const c1 = "'Content 1'";
const c2 = "Content 2";
...
```
By doing so the css variables are interpreted as string content.

```css
element {
  --c1: 'Content 1';
  --c2: Content 2;
}
```

Overall, this is the expected behavior as we usually want the content interpreted as css and not as strings. The `content` property is a special case where you need to use the workaround with the quotation marks to ensure that the variable content is a string in css.

**Comment by panwauu** [comment]
Maybe you can rename this Issue to `define:vars not working in css with content property` to improve the search if somebody else has this problem.

**Comment by matthewp** [comment]
Thanks for the research @panwauu! I agree, this is not a bug. If you pass something like `color` you expect the color to be inserted and not a string `"blue"`. Adding quotes for the content use-case seems like a good compromise.
