### ISSUE TITLE
`import.meta.glob`bing `.md` files in non-`.astro` files gives empty result

### ISSUE THREAD

**Issue by refparo** [withastro/astro#5173]
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

`import.meta.glob`bing `.md` files in non-`.astro` files gives empty result. The results only becomes normal when passed to `.astro` files.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-snzedv?file=src/globbing.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
This is because you've created a circular dependency. globbing depends on index.md which depends on Layout.astro which depends on globbing. When this happens one of the modules is going to execute first and its imports are "unfulfilled" until the circular deps also run. You can see this by adding a setTimeout.

https://stackblitz.com/edit/github-snzedv-musvfk?file=src%2Fglobbing.ts,src%2Flayouts%2FLayout.astro,src%2Fpages%2Findex.md

**Comment by refparo** [comment]
@matthewp But the globbed result doesn't tell anything about Layout.astro. Why should index.md depend on Layout.astro?

**Comment by matthewp** [comment]
index.md depends on Layout.astro. The frontmatter is:

```yaml
---
layout: ../layouts/Layout.astro
---
```

**Comment by refparo** [comment]
@matthewp Sorry, I didn't know that creates a dependency. So, if I want to get the content of the markdown file without creating a circular dependency, do I have to read and parse it manually?

**Comment by matthewp** [comment]
I don't know what your reason is for wanting to have the glob in a separate .ts file, but it should be fine to do it that way as long as you don't attempt to examine the results in the body of the module like you are doing in the example. If you instead do that inside of a function you export then it should be fine. 

This is a normal caveat to using circular deps in ESM.
