### ISSUE TITLE
RSS plugin does not work with Cloudflare Pages

### ISSUE THREAD

**Issue by maxcountryman** [withastro/astro#5280]
### What version of `astro` are you using?

1.6.2

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Say we have an RSS feed defined in our `pages` as `rss.xml.rs` directory like so:

```javascript
import rss from "@astrojs/rss";

export const get = async () => {
    // Data fetching, etc.

    return rss({
        title: "example",
        description: "Some example description",
        site: "https://example.pages.dev", //import.meta.env.SITE,
        items: [ {
                link: "/foo",
                title: "Foo",
                pubDate: "2022-01-02",
            } ]
         ),
    });
};
```

Locally via `npm run dev` and via `npm run preview` (which is wrapping `wrangler preview` as per the docs) this works as expected: we see an RSS feed.

However when deployed to CF Pages we instead see a worker error `Error 1101: Worker threw exception`. Unfortunately it's incredibly opaque and no immediate logging is available. If we take the extra step of integrating Sentry we do get a little more (but enabling this plugin also breaks the Astro deployment: every other refresh will not load the stylesheets!): `TypeError
Invalid URL string.`

Note that the site string is hardcoded in the deployment so I'd be surprised if that's the issue. Removing everything else and just wrapping `rss` and we still see this error so I suspect the issue is in the RSS plugin itself.

### Link to Minimal Reproducible Example

See above

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Unfortunately without more information I'm not sure what to really do to help here. Have you considered contacting Cloudflare support about this?

@AirBorne04 is there anything about how our RSS is written that would cause this issue to your knowledge?

**Comment by maxcountryman** [comment]
The error is presumably in the plug-in code which is not in scope for the support Cloudflare offers.

It's quite easy to reproduce, please see the sample in the original ticket.

**Comment by matthewp** [comment]
@maxcountryman could you please provide:

1. A minimal stackblitz example.
2. A list of steps to deploy (I have rarely used Cloudflare)

That would give me enough to try and debug it.

**Comment by maxcountryman** [comment]
I'd recommend following the Astro docs: they clearly explain how to set up the CF adapter and deploy.

A full reproduction is as simple as creating a default Astro project, installing the adapter, and dropping the snippet provided above in your `pages` directory.

Once you've done so, try to load the RSS feed from your deployed CF Pages domain. 

Hope this helps.

**Comment by matthewp** [comment]
The snippet above is not valid JavaScript or TypeScript. It's also named `rss.xml.rs` which is not right.

If you can provide a breaking example in a Stackblitz please create a new issue and I'll take a look. But the problem here appears to be that the snippet is invalid JS.

**Comment by maxcountryman** [comment]
It's valid TypeScript. It's meant to be .ts that was a typo.

If you're not interested in addressing this issue that's fine but the issue should remain open unless you don't intend to support Cloudflare Pages.

Up to you, but closing prematurely is a bit rude.

**Comment by matthewp** [comment]
It wasn't valid until you edited it 27 minutes ago.

<img width="645" alt="Screen Shot 2022-11-09 at 8 57 13 PM" src="https://user-images.githubusercontent.com/361671/201004409-20b128bf-5469-4fe6-88a0-af445567670d.png">

Like I said, please create a full reproduction and file an issue and I'll take a look. Despite you calling me rude. We have too many issues to spend a lot of time fixing typos and putting together reproductions. I've asked a few times for you to create one and that offer is still open! But I will not do all of the work here.

**Comment by maxcountryman** [comment]
Yikes. What a community you're building here...

I'm sorry for raising the issue with Astro in the first place.

Good luck!

**Comment by AirBorne04** [comment]
@maxcountryman I understand that it might be frustrating at times to follow the rules which are set for different repos. This is something to work through and get accustomed to rather than complain about it. There is value in this rules as you understand that the time people have working on issues is limited.

> It's quite easy to reproduce, please see the sample in the original ticket.

You know there is not really a thing like that, how is the Cloudflare adapter configured? With `mode: "directory"`? What do you mean by:

> Removing everything else and just wrapping rss and we still see this error so I suspect the issue is in the RSS plugin itself.

There are many things that can be confusing to understand, not from your point of view because you know what you describe of course.

> Yikes. What a community you're building here...

The guys are actually doing their best to keep everything on the rails and moving this project forward. I have huge respect for what they are doing, as this is open source and you are not paying anything, you cannot expect Enterprise support. From my point of view you are undervaluing what this project is actually dealing with, supporting 7 ui frameworks and 5 deployment options. The complexity is huge, but therefore there are some rough edges which will be overcome, if they get the support from the users.

Anyhow, I took a look at this and I do not see an issue, I assume that you have configured the adapter to run in default mode not `mode: "directory"` which is described [here](https://docs.astro.build/en/guides/integrations-guide/cloudflare/#mode). With both configurations the page loads but with the default config wrangler log states "_worker.js is importing from another file. This will throw an error if deployed."

@matthewp maybe we should update the default for the build type, because Cloudflare Pages is going out of beta into public availability and I have seen multiple issues which were related to the build mode.

**Comment by matthewp** [comment]
@AirBorne04 Sorry to drag you into this thread that unfortunately turned negative.

My understanding is that this is a static site and not using the adapter. I had pinged you for your general Cloudflare expertise. Again, sorry for that! This highlights the need for a stackblitz example, helps both with debugging the problem and just understanding the exact conditions.

I can't imagine how a static rss file would cause Cloudflare to crash. Will wait to see if someone else reports.

**Comment by AirBorne04** [comment]
No worries always happy to help, when i can. The issue here is that the default config of the adapter is building `advanced` mode and there are certain scenarios (which i have not yet fully understood) where the wrangler cli complains about imports. That needs a bit more digging.

In `directory` mode there is no problem and that mode is the future for pages, it would probably make sense to make this the default for new projects and update the docs in that direction.

I guess similar issues could occur with other plugins as well.
