### ISSUE TITLE
'aspectRatio' must be provided Error on with local image

### ISSUE THREAD

**Issue by silveltman** [withastro/astro#5295]
### What version of `astro` are you using?

1.5.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

yarn

### What operating system are you using?

windows

### Describe the Bug

I get the following bug:
`'aspectRatio' must be provided for remote images.

However, my image is not remote. 

I use the Picture component in a layout and have the image source in the frontmatter of a mardown file which utilizes this layout.

Does a markdown file count as external?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-t8xhrh?file=src/env.d.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I'm not sure if this is a bug, how you are checking if it is remote @tony-sull?

**Comment by tony-sull** [comment]
@silveltman that's actually expected behavior, Markdown support for `@astrojs/image` is one of the rougher edges that we haven't found a clean fix for yet unfortunately

The image is considered remote because it isn't being `import()`ed anywhere.  In the stackblitz link the image integration is given the string `/assets/img/index.jpeg` and expects that is a path to an image file in `/public` which are all treated as remote.

One alternative here since you're using the markdown frontmatter in a layout is to use an image path relative to your project's root and still `import()` it in the `.astro` layout

```md
---
image:
  src: "/src/assets/hero.jpg"
---
```

```html
---
import { Image, Picture } from "@astrojs/image/components";
const { hero } = Astro.props.frontmatter;
---

<Image src={import(hero.src)} />
```

**Why?**

This is kind of an awkward workaround, but using a path relative to your project's root allows the `.astro` layout to import the file and be treated by the integration as a local image
