### ISSUE TITLE
Astro Island Not Passing Attributes to Sub-Components, Rendering Twice, Issues With Lit

### ISSUE THREAD

**Issue by davidbwaters** [withastro/astro#5304]
### What version of `astro` are you using?

1.6.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

CodeSandbox

### Describe the Bug

When using client directives in astro, it's not rendering attributes.  On codesandbox, it's not even passing them when importing as a script.  It's also rendering components twice when importing through a normal script tag.  I've experienced this a little bit when running locally rarely.  Also, when defined in typescript, components aren't hydrating.  Using JS it works.  Just check out the codesandbox example and you'll see what i mean.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/inspiring-agnesi-8h0z1d?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
If you have a reactive property it sets the property rather than the attribute. This is because some properties *have* to be rendered as props. What problem is caused by not setting the attribute?

**Comment by davidbwaters** [comment]
I guess it's just not hydrating when used as an astro component and it's sometimes rendering twice when importing as a script.  Check the codesandbox demo.  i've seen the rendering twice thing in my personal usage also.

![CleanShot 2022-11-18 at 00 17 40@2x](https://user-images.githubusercontent.com/5247627/202654428-c90cbf4b-7b20-4a02-b877-cd5bafc8f2d1.png)

**Comment by matthewp** [comment]
Same issue reported here: https://github.com/withastro/astro/issues/6342

Did a little investigation and I think this is a Lit bug. It happens simply by having:

```html
<script>
  import "lit";
</script>
```

I think what is happening is there is a race condition here. I think that perhaps Lit is rendering before the HTML children have been appended, so it doesn't see that they are there. That is my theory at least. It does seem unrelated to anything Astro is doing though.

Going to ping @e111077 if he wants to take a look, the example in #6342 is a pretty good reduction, but you can remove the client component and just have a `import "lit"` and see the same thing.

**Comment by e111077** [comment]
This is a composition issue on the Astro side. When you include the Astro Lit integration, you should be inserting `import 'lit/experimental-hydrate-support.js'` before the Lit library is loaded anywhere.

Unfortunately I do not know how to do this in the Lit integration. But there are 2 workarounds:

1. **Suggested:** Use the JSX client only syntax we just shipped ([example](https://codesandbox.io/p/sandbox/astro-double-rendering-forked-62ylcu?file=%2Fsrc%2Fpages%2Findex.astro&selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A13%7D%5D))
2. Add the hydration script to `<head>` in your main layout ([example](https://codesandbox.io/p/sandbox/astro-double-rendering-forked-uud84s?file=%2Fsrc%2Flayouts%2FLayout.astro&selection=%5B%7B%22endColumn%22%3A24%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A24%2C%22startLineNumber%22%3A12%7D%5D)) though not sure how Astro handles library loading order

Hopefully there's a way an integration can inject a script to the top of the page, because in that case, loading the lit integration, it should just load the hydration support shim

**Comment by matthewp** [comment]
Ah, we do have the hydration script, perhaps that is not being added correctly? I'll look into this tomorrow, thanks for the research @e111077

**Comment by e111077** [comment]
It might not be loaded early enough, and inline scripts may be injecting before it, or alternatively, it could be how HMR is doing things in relation to loading a Lit element without the `client:only` JSX route

**Comment by e111077** [comment]
clarifiction, the inline scripts i'm talking about – they may be loading the lit module before the lit experimental-hydrate module is loaded. This will cause Lit to skip the hydration step altogether, causing the double rendering

**Comment by RogierdeRuijter** [comment]
When running `npm run build && npm run preview` in this stackblitz. The double rendering happens. It seems to to be ok when running `npm run dev` but with a full build and preview the problems happens. Here is a sandbox. https://stackblitz.com/edit/node-uy3xxu?file=src%2Fpages%2Findex.astro,src%2Fcomponents%2Fcalc-add.js

**Note:** Make sure to run `npm run build && npm run preview` in the console to start the app

**Comment by tjkohli** [comment]
+1 we are also experiencing this issue in a component on a live website. Following 👀

**Comment by marcmalerei** [comment]
Hi, i have the same problem using astro "3.0.12" and @astrojs/lit "3.0.0". Using the directive `client:only="lit"` is not an option in my scenario as i need the static html as well.

**Comment by marcmalerei** [comment]
I think i found one of the problems:

If i have a component (A) which is included in the astro page with a directive "client:visible" i will have duplicate output of the component (B), which is nested in component (A), as long as i do the import of component (B) before a instance of (A) exists.

### This does not work:
**Component A**
`
import { LitElement } from "lit";
import { customElement } from "lit/decorators.js";
import "./component-b";

@customElement("component-a")
export class ComponentA extends LitElement {}
`

**Component B**
`
import { LitElement } from "lit";
import { customElement } from "lit/decorators.js";

@customElement("component-b")
export class ComponentB extends LitElement {}
`

### This does work:
Doing a dynamic import in the connectedCallback does solve the problem. 
 **Component A**
`
import { LitElement } from "lit";
import { customElement } from "lit/decorators.js";


@customElement("component-a")
export class ComponentA extends LitElement {
  connectedCallback(){
    import('./component-b');
  }
}
`

**Component B**
`
import { LitElement } from "lit";
import { customElement } from "lit/decorators.js";

@customElement("component-b")
export class ComponentB extends LitElement {}
`

I hope that helps somehow.

**Comment by ditorodev** [comment]
Im using React, and this has happened to 2 of my users consistently on a Chrome browser. Thing is I cant really replicate it locally and its a really reallyyyy weird bug

**Comment by lilnasy** [comment]
The double rendering bug was fixed and the one remaining issue is that props (`count="0"`, in this case) are not rendered as atttributes. Is that correct?

**Comment by lilnasy** [comment]
Some of the issues pointed out in the original description seem to have been fixed.

Facts as of today:
- The component needs to be imported manually in a script tag for it to be duplicated.: `<script>import '../components/my-counter.js';</script>`
- There must also be a second unrelated lit component used on the same page. It must be imported in the frontmatter and used as an island, but it does not need to be given a client directive: `<CalcAdd/>`
- It affects the dev mode as well, but only if you navigate to another page and then back.

The "not passing props to attributes" seems to have been fixed at some point: `index-2` works now, it did not in `astro@1.6`. Since importing manually is not something we document, the remaining issue would be a corner case.

**Comment by bencipher** [comment]
I am also facing the issue, data gets saved twice to my db as a result of this. I followed the P2: has a workaround link but I didn't quite get it as I saw bunch of issue on a page.

![image](https://github.com/withastro/astro/assets/9444817/22510c74-08f6-4db6-8711-11f95b6a7af3)

**Comment by matthewp** [comment]
Agree with @lilnasy in that many of these issues have been fixed. Going to close as it's difficult to try and fix the remaining issues without a clear example of them. I would suggest that anyone that still has issues related to these in the Lit renderer please create a new issue specifically for them.

**Comment by karlludwigweise** [comment]
I've filed a new issue for this including a reproducible example: https://github.com/withastro/astro/issues/12198
