### ISSUE TITLE
Tailwindcss classes doesn't work correctly when not hard coded

### ISSUE THREAD

**Issue by assalielmehdi** [withastro/astro#5315]
### What version of `astro` are you using?

v1.6.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

In the [reproducible example](https://stackblitz.com/edit/github-xebeeq), you can see that, when a `tailwindcss` class is hard coded, like `text-2xl`, the style is applied, but when the class is contructed, like `text-${size}`, the style is not applied even if the resulting class is a correct `tailwindcss` class.

After looking at the built css file, it seems that `text-2xl` is defined, but not `text-4xl`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xebeeq

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Hi @assalielmehdi!

This is a limitation of Tailwind CSS itself. It requires you to use the full class name in your file so that it knows which classes to add to your CSS bundle. Tailwind documents this here: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

One option is to create a map of your class names and keyed by `size` and apply them like this:

```astro
---
// src/components/Text.astro

const sizes = {
  xl: 'text-xl',
  2xl: 'text-2xl',
  3xl: 'text-3xl',
};

const { size } = Astro.props;
---
<div class={sizes[size]}>
  Text of different sizes!
</div>
```
