### ISSUE TITLE
Generating a 404 page with getStaticPaths() doesn’t work in dev

### ISSUE THREAD

**Issue by amxmln** [withastro/astro#5378]
### What version of `astro` are you using?

1.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Using `getStaticPaths()` to generate a `404.html` route from a dynamic-route Astro-Component, for example in order to have it user controllable from a headless CMS, doesn’t work during development. Once built, `404.html` is there though, so this is just a mismatch between running a page in development vs. running the production version of it.

Thanks for your hard work! :blush: 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wna4eu?file=src/pages/[page].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by MoustaphaDev** [comment]
During dev, `getStaticPaths` runs only when the route it is exported from is matched. So when visiting the `/doesnt-exist` path it doesn't match the dynamic path `[page]` since its `getStaticPaths` doesn't export a `param` of that name.
During build, well *ALL* static paths are built.

As a workaround, you could create a [custom 404 page](https://docs.astro.build/en/core-concepts/astro-pages/#custom-404-error-page) and do the data fetching from the CMS at that level. 
[Demo](https://stackblitz.com/edit/github-wna4eu-7zquyh?file=src%2Fpages%2Findex.astro)

**Comment by MoustaphaDev** [comment]
*Not a team member, I'm just talking from my experience in Astro.*
During dev, `getStaticPaths` runs only when the route it is exported from is matched. So when visiting the `/doesnt-exist` path:
1. It doesn't match the dynamic path `[page].astro` since its exported `getStaticPaths` doesn't return a `param` of that name.
2. Astro cannot know that you have a static path for a "404" page (it would require analyzing all dynamic Astro pages, which is fairly unreasonable IMO), so Astro cannot retrieve and serve your "404" static path when there's 404.

As a workaround, you could create a [custom 404 page](https://docs.astro.build/en/core-concepts/astro-pages/#custom-404-error-page) and do the data fetching from the CMS at that level. 
[Demo](https://stackblitz.com/edit/github-wna4eu-7zquyh?file=src%2Fpages%2Findex.astro)

**Comment by amxmln** [comment]
Thank you for getting back to me about this. I didn’t realise the technical implications of making it work—but I see now that they’re too complex.

I’m closing this since it’s not a bug, but expected behaviour and everything works out fine in production.

Perhaps it would be good to add a note about this in the docs on `getStaticPaths()`?

**Comment by aleclarson** [comment]
In case anyone else stumbles on this, the "workaround" I'm using is `[...page].astro` as a catch-all route.
