### ISSUE TITLE
Pages ending with `.html.astro` are not accessible

### ISSUE THREAD

**Issue by WesSouza** [withastro/astro#5395]
### What version of `astro` are you using?

1.6.7

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn 1

### What operating system are you using?

macOS Ventura

### Describe the Bug

**Reproduction**
1. Create a page in `src/pages/something.html.astro`
2. Visit `example.com/something.html`
3. 404

**Expected result**
`something.html.astro` is displayed

**Description**
I'd love to have control over the extension of some pages.

Currently, Astro allows users to visit `.astro` pages with or without an `.html` extension. I'd like to have pages explicitly require that extension.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pxda6v?file=src%2Fpages%2Fmy-page-2.html.astro&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I think this was exactly fixed recently https://github.com/withastro/astro/pull/5346

**Comment by matthewp** [comment]
Yep, this should be fixed in astro@1.6.8, which will be released today.

**Comment by WesSouza** [comment]
@matthewp wouldn't this be a breaking change?

**Comment by WesSouza** [comment]
Confirmed it is indeed fixed.

**Comment by bluwy** [comment]
That is intentional when we implement it (https://github.com/withastro/astro/issues/5068#issuecomment-1307357138) for SSG.

Since you mentioned using the Vercel Edge adapter and `output: 'server'` (which skips SSG), path matching is done at [here](https://github.com/withastro/astro/blob/eab4a0279fd28163cea9da2b010c5ccde5645e6f/packages/astro/src/core/routing/match.ts#L4-L6) instead. I checked the built output and it should be working unless Vercel strips it out. Do you have [cleanUrls](https://vercel.com/docs/project-configuration#project-configuration/clean-urls) turned on by chance?

**Comment by WesSouza** [comment]
Indeed, I followed the instructions from the [Vercel deploy guide](https://docs.astro.build/en/guides/deploy/vercel/) and didn't put too much attention into what that option did.

I'd suggest adding this caveat to that note then.

Also, my 404s were not working even with this setting on.
