### ISSUE TITLE
@astrojs/rss includes drafts in output

### ISSUE THREAD

**Issue by SeanMcP** [withastro/astro#5505]
### What version of `astro` are you using?

1.6.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When an item is marked as a draft in the frontmatter, it is still included in the XML output. You can see this behavior in the default blog example.

They should be excluded by default, and ideally added based on [integration configuration or build flags](https://docs.astro.build/en/guides/markdown-content/#enable-building-draft-pages).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-exbbav?file=src%2Fpages%2Fblog%2Ffirst-post.md,dist%2Frss.xml&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by equt** [comment]
I'm also looking into this issue and trying to figure out how it could be better. But to make it more intuitive, we might have to change how currently `@astrojs/rss` currently integrates with the main codebase.

Currently, there's no way for the RSS generator to get the metadata from the source.

https://github.com/withastro/astro/blob/5877dcb7e96b638e3f9c7f8d1334d0ee59350f23/packages/astro-rss/src/index.ts#L22

Also, due to how `@astrojs/rss` is used, it could nor access the Astro config unless it parses it manually.

Are there any design considerations here? Is there any possibility of moving it into the `integrations` in the main config?

**Comment by delucis** [comment]
As a workaround, you can filter out the draft items from your `import.meta.glob` result before passing them to the RSS function:

```js
import rss from '@astrojs/rss';

const postImportResult = import.meta.glob('../posts/**/*.md', { eager: true });
const posts = Object.values(postImportResult).filter(
  post => !post.frontmatter.draft
);

export const get = () => rss({
  title: 'Buzz’s Blog',
  description: 'A humble Astronaut’s guide to the stars',
  site: import.meta.env.SITE,
  items: posts.map((post) => ({
    link: post.url,
    title: post.frontmatter.title,
    pubDate: post.frontmatter.pubDate,
  }))
});
```

Should also be fairly simple to add this logic to the RSS package directly:

1. Include `draft` in the `mapGlobResult` return here:

    https://github.com/withastro/astro/blob/2bd23e454fc9559aa00b9a493772acd69ba9ce6c/packages/astro-rss/src/index.ts#L69-L75

2. Then filter out items with `draft: true`, maybe here:

    https://github.com/withastro/astro/blob/2bd23e454fc9559aa00b9a493772acd69ba9ce6c/packages/astro-rss/src/index.ts#L89
