### ISSUE TITLE
Files with a filename including umlauts are not served (404 Not Found error)

### ISSUE THREAD

**Issue by cauboy** [withastro/astro#5613]
### What version of `astro` are you using?

1.6.5

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When I have a file that has a name including an umlaut in the `/public` folder, the file is not found.

How to reproduce:

1. Open StackBlitz Example (https://stackblitz.com/edit/github-v5djuz?file=src%2Fpages%2Findex.astro&on=stackblitz)
2. Run `npm run serve` in the terminal
3. Press `b` to open the browser
4. Click on link "Download a file with a name that includes umlauts (Ü)"
5. Look for `404 Not Found` in the console logs

<img width="962" alt="Screenshot 2022-12-16 at 10 48 37" src="https://user-images.githubusercontent.com/5537152/208071561-ff32aae7-db45-400a-93ce-9867997d20f2.png">

---

Here's a short example:

```md
// Component.astro
---
import MyFile from '../../public/Broschüre.pdf'
---
<a href={MyFile}> Download file with name Broschüre</a>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-v5djuz?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
It looks like the reason it's not working is because the path points to `/assets/filename-that-includes-umlauts-Ü.7a64ab23.pdf`, and it doesn't exist with the repro because it's inlined, which can be fixed with this astro config:

```js
vite: {
    build: {
      assetsInlineLimit: 0
    }
  }
```

After that it's working fine, however the file is duplicated in `dist/` and `dist/assets/` which isn't good. Usually for public files, it's better to refer to the href as is like `href="/filename-that-includes-umlauts-Ü.7a64ab23.pdf"`, instead of importing the asset. You _can_ import the asset if it's not in the public folder since it doesn't duplicate that way.

So with that I'm not sure if umlauts are the problem, could you test this if it fixes the issue?

**Comment by matthewp** [comment]
Closing b/c of no response, please open a new issue if you still have a problem.
