### ISSUE TITLE
Render Custom — Built-in — Element Tag

### ISSUE THREAD

**Issue by JulianCataldo** [withastro/astro#5636]
Hey there!

Based on:

https://github.com/withastro/astro/pull/2473

```js
// Button.js
export default class Button extends HTMLButtonElement {}
customElements.define("h-button", Button, { extends: "button" });
```

```astro
---
// page.astro
import Button from './Button.js'
---
<Button>Button</Button>
```

Yields
```
05:42:12 [astro] reload /src/Button.js
 error   HTMLButtonElement is not defined
```

Should yield
```html
<button is="h-button">Button</button>
```

Quick note: found no docs for this niche feature

**Comment by matthewp** [comment]
We don't officially support this. Our web polyfill comes with a lot of globals but only the fetch related ones are officially supported. We will likely break this in the future. Going to close as this is not something we are going to fix. I would suggest importing a `HTMLButtonElement` implementation rather than depending on a browser global.
