### ISSUE TITLE
Dev script crashes while watching GLSL file with Vite GLSL plugin

### ISSUE THREAD

**Issue by asiryk** [withastro/astro#5672]
### What version of `astro` are you using?

1.7.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I use the latest Astro, but the issue is around for about a few months.
File watcher crashes on saving the GLSL file.

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/61456651/209461713-d76e072a-c79d-4d3c-a018-1383f8893753.png">

To reproduce this issue:
1. Clone the linked repository
2. Start dev script (npm run dev)
3. Open any GLSL file and save it
4. Dev script crashes

### Link to Minimal Reproducible Example

https://github.com/asiryk/subject_ms-VGGI

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
It's a regression by `vite-plugin-glsl` [here](https://github.com/UstymUkhman/vite-plugin-glsl/blob/f0b2dda188228026d31000f0d54aa2dbf9b01b50/src/watchShader.js#L60) since https://github.com/UstymUkhman/vite-plugin-glsl/commit/25fa19ef4d5424057962db2756b613b097346e2d. It relies on the Vite config file and update the utime to restart the server, it should use `server.restart()` instead as it's cross compatible for metaframeworks without a Vite config file. Please report upstream instead.
