### ISSUE TITLE
Nested CSS not exported

### ISSUE THREAD

**Issue by y-nk** [withastro/astro#5675]
### What version of `astro` are you using?

1.7.2

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

yarn

### What operating system are you using?

stackblitz

### Describe the Bug

# How to reproduce

1. Create a `SomeLinks.astro` component such as:

```astro
---
const { class: className } = Astro.props
---

<ul class={className}>
  <li><a href="#">hello world</a></li>
</ul>
```

2. Use as:

```astro
---
import SomeLinks from 'components/SomeLinks'
---

<SomeLinks class="someLinks" />
<style>
.someLinks {
  border: 1px solid red;
}

.someLinks a:hover {
  color: red;
}
</style>
```

# Expected behavior

the links should be red on hover

# Current behavior

the styles responsible for hovering are not applied

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wgatnp?file=src/pages/index.astro,src/pages/SomeLinks.astro&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by y-nk** [comment]
This becomes further a problem when:

1. You want to create themes within pages (not really global)
2. You want to use markdown, but can't use `.md` files (process the content with `micromark` directly)

**Comment by y-nk** [comment]
I found #3045 but this is not the greatest DX. For example, if i want to design a markdown file with a specific theme, i'll have no choice but to do a construct such as:

```astro
---
import { Content } from 'my-page.md'
---

<div class="scoped-wrapper">
  <Content />
</div>

<style is:global>
.scoped-wrapper p {
  // theme 
}
</style>
```

...which seems a bit unpractical? what do you think?

**Comment by bluwy** [comment]
This is expected behaviour. CSS in `<style>` only applies to the tags it sees in that Astro file so it's "scoped". If you want to bleed the style into child components (different Astro file), you can use `.someLinks :global(a:hover)` instead. This is documented at https://docs.astro.build/en/guides/styling/#global-styles.

**Comment by y-nk** [comment]
@bluwy I understand this as well (the link you provided is where i found the `is:global` directive).

My bug/feedback report was to mention this might not be convenient enough since we can't theme easily markdown files _granularly_

If somebody were to want to design a blog where articles are markdown and each post has its own theme, you'd end up with what i described here: https://github.com/withastro/astro/issues/5675#issuecomment-1365725475

Is there really anything to be done to smooth the DX?

**Comment by bluwy** [comment]
If the `:global` directive makes writing CSS themes tricky, then I suppose you can use `style is:global`. I'm not sure how that is unpractical though because you need a `.scoped-wrapper` to make sure your nested selectors don't bleed. Do you have an alternative syntax in mind?

**Comment by y-nk** [comment]
I agree that with the current idea of `scoped-wrapper` it does work, although you see we'd have to create 1 `.astro` per `.md` just to add style.

I think my proposal will be a bit strong, but since there's already `layout` in frontmatter, why not adding a `theme: PathToCssFile` property?

The implementation of underlying `theme` could be more or less that of the `.scoped-wrapper` idea ↑ such as transforming:

```md
---
theme: ./my-theme.css
---

my-markdown-file.md
```

into:

```
---
import { Content } from 'my-markdown-file.md'
---

<div class="scoped-wrapper">
  <Content />
</div>

<style is:global>
  .scoped-wrapper {
    @import(/* theme */)
  }
</style>
```

_(not 100% convinced on the `@import`, rather maybe prefixing all the rules in the same fashion than `:where(astro-xxx)` already happens)_

---

If there's a space to create this as a plugin, you can tell me and i'll try to do it. I don't have enough Astro knowledge at the moment to know what's possible or not from the Plugin API.

**Comment by bluwy** [comment]
I think a simple way to achieve that is to use a `<style>` tag in the `.md` file (no `is:global` needed). That would inject global styles using the markdown tooling.

If you need to scope it, that would involve a fair amount of work. You could perhaps create a rehype plugin that receives the above pattern, and add scope wrappers and scope classes. `@import` likely won't work when nested (I think). But since it's markdown with a single page, Astro's scope hash probably won't help much.

If you're planning on a more complex setup, I'd suggest seeking support on [Astro's Discord server](https://astro.build/chat). It might be easier to get more ideas there.
