### ISSUE TITLE
Conditionally rendered components still load component JavaScript

### ISSUE THREAD

**Issue by kamranahmedse** [withastro/astro#5739]
### What version of `astro` are you using?

1.8.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I have a vanilla astro component (no frameworks involved) and it has some JavaScript inside. This component is being conditionally added to multiple pages i.e. using following:

```jsx
{ showSponsor && <Sponsor />
```

Content of the `<Sponsor />` component is along the lines of:

```jsx
<script src="./sponsor.js"></script>

<div>...</div>
```

Now ideally the pages that do not have the `<Sponsor />` rendered should not have the `sponsor.js` included but that's not the case here. It's including the `sponsor.js` on all the pages regardless.

I know that the JavaScript gets hoisted so it is probably happening because of that. But is there any way to make it not include the JavaScript when the component is not loaded?

### Link to Minimal Reproducible Example

https://codesandbox.io/s/quizzical-lichterman-ggwpqo?file=/src/pages/index.astro:86-103

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Indeed, hoisting is the cause of this. There is no solution other than using `<script is:inline>`.

The reason is that the scripts are bundled. You might have sponsor.js which you are choosing to not render in this example, but you also have foo.js that you are rendering. The only way to support conditionally rendering these would be to not bundle them, which is not desirable.

We do have some primitives not that make it possible to mark certain things as "lazy". We use this for CSS in the content collections API. These primitives could be used in the future for some sort of opt-in conditional scripts too. But we would need a RFC on how that should work.

**Comment by szmarczak** [comment]
Please reopen. No solution does not mean the issue is gone.

> There is no solution other than using <script is:inline>.

There a few problems with this:
- need to manually add `type="module"`
- importing NPM installed modules does not work

**Comment by adbl** [comment]
Adding to this. 

`index.astro`: Iterates over `.mdx` files using `Astro.glob`, rendering links to each `page.url`.

If the `mdx` imports any components with client scripts the scripts are included in `index.astro` html too. That was surprising. I tried to use `optimizeHoistedScript: false` without any difference.
