### ISSUE TITLE
Move /assets folder to /_astro

### ISSUE THREAD

**Issue by matthewp** [withastro/astro#5745]
Move `/assets/` to `/_astro/`

## Reasons

- Avoid route conflicts
- Sets up a namespace for more endpoints like the Image integration
- Helps httparchive with fingerprinting

Note, it would be nice if this were more easily configured. For ex.:

```js
export default {
  build: {
    assets: 'my-assets/'
  }
};
```

This would match what we already have with `build.server`, `build.client`, etc.

**Comment by Tc-001** [comment]
Would it  be useful to have it optionally be outside of dist as well? 
On second thought I only see it being useful together with a CDN domain, and that is definitely a future RFC if there isn't one already

**Comment by plutoniumm** [comment]
Hey, so this creates a problem with github pages deployment since jekyll does not let you fetch from `_` domains on frontend. The problem randomly seems to persist even after adding `.nojekyll`

It could help to do one of these
1. Move _astro to some randomly generated hash
2. Add an adapter for gh-pages where `_astro` is automatically renamed to something non _

Additionally it might help to add this in the docs too in either FAQ or as a warning

**Comment by ARISEN-DEV** [comment]
Hey Matthew, i'm pretty noob with Astro but can you please show how can we configure it? Should be awesome if you can do that :D

**Comment by plutoniumm** [comment]
Hey Arisen you can go to the `astro.config.mjs` file, add a root level key to it called `build` in the defineConfig object, then add a sub key-value pair `assets: 'yourDirName',

You can also check [this](https://docs.astro.build/en/reference/configuration-reference/#buildassets) out from the docs

**Comment by leoplaw** [comment]
Since there is a problem with github pages deployment since jekyll does not let you fetch from _ domains on frontend, what config option is there to change the ``_pagefind`` directory?

**Comment by gibbok** [comment]
@plutoniumm I had the same issue and I was able to solve it. Thansk to your comment!
Would be great have this mentioned in the official docs.
Thanks again

https://github.com/gibbok/typescript-book/blob/main/website/astro.config.mjs#L9
