### ISSUE TITLE
Default astro preview to localhost instead of 127.0.0.1 to match dev

### ISSUE THREAD

**Issue by matthewp** [withastro/astro#5747]

**Comment by Chaciej** [comment]
After spending a week troubleshooting, I've discovered that Nginx was inconsistently delaying requests made to localhost, while requests to 127.0.0.1 proceeded without issue. Specifically, around 10-20% of my requests to localhost experienced significant delays, arriving after 2 seconds instead of the expected milliseconds. This behavior can be quite misleading and difficult to diagnose. If you're encountering similar issues, consider explicitly using 127.0.0.1 in your configurations to avoid potential inconsistencies with localhost.

server: {
  host: '127.0.0.1'
}

Hope this helps someone avoid the confusion I went through!
