### ISSUE TITLE
Dot files like .well-known files are not served with the node adapter

### ISSUE THREAD

**Issue by hibnico** [withastro/astro#5813]
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac,Linux

### Describe the Bug

We want our app to serve a file on the path `/.well-known/apple-app-site-association`. So I have put the file at that path `public/.well-known/apple-app-site-association`.

When running `npm run dev`, the file is being served, a `curl http://127.0.0.1:3000/.well-known/apple-app-site-association` returns a 200.

With a production build (`npm run build`), the file is not being served via `node ./dist/server/entry.mjs`. The same curl returns a 404. (node 16.19.0 on macos, docker image node:16-alpine on linux)

I can see that the `.well-known` folder is being properly copied by the build into `dist/client/.well-known`. But no file or directory starting with a dot is being served.

All that has been observed on our real project, on macos and linux.

I then tried to start a new astro project from scratch, on macos, basically just running:
- `npm create astro@latest`
- `npm install @astrojs/node`
- create a file at `public/.well-known/apple-app-site-association`
- configure astro with `export default defineConfig({
    output: "server",
    adapter: node({
        mode: "standalone",
    }),
});
`

In dev, it works, `npm run dev` and `curl http://127.0.0.1:3000/.well-known/apple-app-site-association` returns a 200.
With a build, it doesn't: `npm run build` and `node ./dist/server/entry.mjs` then `curl http://127.0.0.1:3000/.well-known/apple-app-site-association` returns a 404. But this time, I cannot see any `.well-know` directory in `dist/client`.

I would expect the node server to serve any file of the `public` folder, even the dot files.

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
> I can see that the .well-known folder is being properly copied by the build into dist/client/.well-known.

I can repro the issue altho for me the `.well-known` directory is not copied to `dist/client`.

It looks like the issue can be pinpoint to 2 problems:

1. During the build, when [copying the public directory](https://github.com/withastro/astro/blob/c55fbcb8edca1fe118a44f68c9f9436a4719d171/packages/astro/src/core/build/static-build.ts#L194) over, dot folders are ignored due to `fast-glob` [not including dot folders by default](https://github.com/mrmlnc/fast-glob/tree/a028e3670ba3186a102cb9108e3a6e48c1148a9e#dot):

```ts
const files = await glob('**/*', {
  cwd: fileURLToPath(fromFolder),
});
```

To include dot folders, the code should be:

```ts
const files = await glob('**/*', {
  cwd: fileURLToPath(fromFolder),
  dot: true,
});
```

2. In the server, [when responding to a request](https://github.com/withastro/astro/blob/c55fbcb8edca1fe118a44f68c9f9436a4719d171/packages/integrations/node/src/http-server.ts#L21-L24), `send` is configured to `deny` dotfiles:

```ts
const stream = send(req, encodeURI(pathname), {
  root: fileURLToPath(client),
  dotfiles: 'deny',
});
```

The `dotfiles` property should be changed to `allow` to properly serve dotfiles.

After testing locally both changes, a `.well-known/apple-app-site-association` in the `public` folder can properly be saved.

I could make a PR altho I'm not sure what is the desired behavior. The `dotfiles: 'deny'` configuration seems to have been written on purpose, so can we change it easily? Should this be configurable somehow?

**Comment by bluwy** [comment]
@HiDeoo thanks for digging this out! It looks like your proposed changes make sense to me. Re:

> I could make a PR altho I'm not sure what is the desired behavior. The `dotfiles: 'deny'` configuration seems to have been written on purpose, so can we change it easily? Should this be configurable somehow?

I think we can make it `allow` if the `pathname` starts with `/.well-known/`, and `deny` otherwise.

**Comment by HiDeoo** [comment]
@bluwy Ok, I'll setup a PR with the proposed changes and your suggestion 👍🏼
