### ISSUE TITLE
@astro/image broken images with svg formats

### ISSUE THREAD

**Issue by majkl-zumberi** [withastro/astro#5846]
### What version of `astro` are you using?

^1.9.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

i'm using @astro/image ^0.12.1 for managing all my assets.
To render a svg logo i followed the docs in particular the [local images section](https://docs.astro.build/en/guides/integrations-guide/image/#local-images)

i've set a dir. into `/src/images` for my svg content
and in my .astro component i'm importing images through frontmatter like this
`import DiscordLogo from '../../images/discord-icon.svg'`

`<Image
                src={DiscordLogo}
                alt="discord logo"
                width={36}
                height={36}
                type="svg"
              />`

in dev mode everything is fine, images and svg images are rendered as expected but whether i'm trying to build the project locally with `npm run build` and `npm run preview` to launch the build version locally, my svg images are broken

the svg aren't corrupted because if i use the html tag img to render them, all works fine

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6pqazl?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello! `@astrojs/image` does not support SVGs. As you can see on the page you linked, the only supported formats are `'avif' | 'jpeg' | 'png' | 'webp'`

**Comment by EdoanR** [comment]
A similar problem has happened to me while using `pnpm` as package manager, I fixed by installing the `sharp` package.
[This is documented in this page](https://docs.astro.build/en/guides/images/#default-image-service)

![image](https://github.com/user-attachments/assets/d2ac80d5-108a-4543-a70e-ba1b379ff050)

I know this issue is from 2023 and it is almost 2025 and issue is related to `npm` instead of `pnpm`, I'm just commenting this in case someone find a similar problem :)
