### ISSUE TITLE
When build only: generating static routes error , Named export '_' not found

### ISSUE THREAD

**Issue by genesem** [withastro/astro#5976]
### What version of `astro` are you using?

2.0.1

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

yarn 1.2x

### What operating system are you using?

windows

### Describe the Bug

Please note: this error happens only when `astro build` command has been running,  `astro dev` works well (so stackblitz example shows no error).

Error text:

" generating static routes                                                                                               
 error   Named export '_' not found. The requested module './inc/ch-eecf5216.js' is a CommonJS module, which may not support all module.exports as named exports.                                                                                 CommonJS modules can always be imported 
via the default export, for example using:  ... "

Screenshot:

![FnUYlKXXkAYZgqf](https://user-images.githubusercontent.com/7645532/214569912-2b879fdf-3aaa-4239-87a4-f4bb66df581d.png)

I did some investigation and found that this error caused by config option:

 vite:.build. rollupOptions. output:
            chunkFileNames: `${assetsDir}/ch-[hash].js

when it is presnt bug's fired,
when commented out - all generated successfully.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-f2wbfo?file=astro.config.mjs&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by genesem** [comment]
I'm always using: `astro.config.mjs` so it does not related.

**Comment by natemoo-re** [comment]
Sorry, I meant the `` chunkFileNames: `${assetsDir}/ch-[hash].mjs` `` setting you're using

**Comment by genesem** [comment]
> Sorry, I meant the `` chunkFileNames: `${assetsDir}/ch-[hash].mjs` `` setting you're using


Using " chunkFileNames: `${assetsDir}/ch-[hash].mjs` " resolved this isuue and static routes were generated.
Thank you.

But, it makes the same effect as when this option completelly commented out.

**Comment by matthewp** [comment]
@genesem can you explain what you mean by " it makes the same effect as when this option completelly commented out." ? What effect is that?

**Comment by genesem** [comment]
> @genesem can you explain what you mean by " it makes the same effect as when this option completelly commented out." ? What effect is that?

it means result is the same when you just comment out the whole option.

` // chunkFileNames: ${assetsDir}/ch-[hash].js `

**Comment by bluwy** [comment]
I think this is working as expected. Astro generates ESM files in `dist` by default, so to ensure it's evaluated as ESM, you need either `.mjs` or `"type": "module"` in the `package.json`. Since the custom `chunkFileNames` changed it to be evaluated as CJS, the error happens.

Personally, I'd suggest ```chunkFileNames: `${assetsDir}/ch-[hash].mjs` ``` instead as Astro does internal `.mjs` cleanup in it's pipeline.

Closing as it's a configuration issue.

**Comment by genesem** [comment]
> I think this is working as expected.
Nope it does not.
`chunkFileNames:  "[name]-[hash].js" - are vite.js's standard option mentioned in many manuals.
And it won`n work as user may expect in astro.

**Comment by bluwy** [comment]
It is working as expected that the misconfiguration causes the build to fail. It is mentioned to use `.js`, but since you're changing Astro's internal build defaults, you have to use `.mjs` instead. I don't think we can't implicitly swap that as `.mjs` as changing user config can catch end users off guard, and opens up a can of worms.
