### ISSUE TITLE
`getStaticPaths`' `paginate` function does not support other filenames

### ISSUE THREAD

**Issue by jhuleatt** [withastro/astro#6000]
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have a file named `src/pages/[example].astro`. When I try to use the `paginate` function and navigate to a route (`https://<domain>.com/1`), it errors with the following message:

```
[paginate()] page number param `page` not found in your filepath.
  Rename your file to `[...page].astro` or customize the param name via the `paginate([], {param: '...'}` option.
```

> (side note, error message code snippet says `param`, when it should be `params`, and [doesn't match the `params` type definition](https://github.com/withastro/astro/blob/1335797903a57716e9a02b0ffd8ca636b3883c62/packages/astro/src/%40types/astro.ts#L650-L657))

When I use the [`params` option](https://github.com/withastro/astro/blob/1335797903a57716e9a02b0ffd8ca636b3883c62/packages/astro/src/%40types/astro.ts#L650-L657), I still get the same error. Looking at the source code, it doesn't seem like the `params` option is taken into account before the error is shown:

https://github.com/withastro/astro/blob/1335797903a57716e9a02b0ffd8ca636b3883c62/packages/astro/src/core/render/paginate.ts#L15-L29

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7t6mb9?file=src/pages/[example].astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
> (side note, error message code snippet says `param`, when it should be `params`, and [doesn't match the `params` type definition](https://github.com/withastro/astro/blob/1335797903a57716e9a02b0ffd8ca636b3883c62/packages/astro/src/%40types/astro.ts#L650-L657))

I think `params` is meant to pass additional props to every rendered page that represents a single page of data in the paginated collection on top of the [default `page` prop added when using pagination](https://docs.astro.build/en/reference/api-reference/#the-pagination-page-prop).

Regarding the ability to use a custom URL param name, e.g. `[example].astro` instead of `[page].astro`, the current documentation state that `paginate()` assumes a file name of `[page].astro` or `[...page].astro`.

It looks like this was possible but removed in [this specific commit](https://github.com/withastro/astro/pull/1010/commits/b3232e939f76813c9a874ffdd8b739dff67b7121#diff-2d24e4cccbefccf60bf20968728ef12a9be04f2fc2461f97f0c6b543dd1f77c0R18):

```diff
- const paramName = _param || 'page';
+ const paramName = 'page';
```

- If this is intended, I guess the error message should be updated to not reference the possibility to customize the param name.
- If this is not intended, the code should be updated to check for a `param` parameter in the paginate `args`.

**Comment by wulinsheng123** [comment]
mark

**Comment by FredKSchott** [comment]
Thanks for filing this! Looks like an outdated error message. I've added #6124 to update the error message to match actual behavior.

If you would still like this to be customizable, we consider that an enhancement which should be suggested in https://github.com/withastro/roadmap. It's helpful for us to have a real use-case in mind that this would solve, so if you have one please let us know.

Thanks!
