### ISSUE TITLE
Additional whitespace-only text node between text elements

### ISSUE THREAD

**Issue by Pixxle** [withastro/astro#6011]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

vercel

### What package manager are you using?

npm

### What operating system are you using?

windows

### Describe the Bug

Hey everyone, I'm not the sharpest tool when it comes to web dev; so this could potentially just be user error. But I've looked at the output of astro and compared to other frameworks and don't seem to get the same result from other frameworks. 

Astro seems to render unexpected extra whitespace-only text nodes between text elements.

Example:
```
<text>TLDR :=&nbsp</text>
<text>[</text>
<text class="text-arrayblue">2</text>
<text class="flex-nowrap">]</text>
<text class="text-arrayorange">string</text>
<text>&#123;</text>
```

I expect the outputed HTML to be similar to this (output from nextjs):
![image](https://user-images.githubusercontent.com/5764762/215223912-70b70f2e-8f7a-49e8-9b0f-f33c4ae2d992.png)

But, when writing the same code in astro whitespace-only text nodes gets inserted in between each text element:
![image](https://user-images.githubusercontent.com/5764762/215224077-13f4b400-80ff-441a-aea4-2575bd26c175.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-39xd5t?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Astro is not like JSX. Newlines you write in your source files are preserved in the output. If you do not want newlines then remove them from your source, or you can also use JSX based component libraries like React and SolidJS which will work without the whitespace.

**Comment by jmayergit** [comment]
> Astro is not like JSX. Newlines you write in your source files are preserved in the output.

https://docs.astro.build/en/reference/configuration-reference/
>  By default, Astro removes all whitespace from your HTML, including line breaks, from .astro components.

Configurable like so

```
{
  compressHTML: false
}
```

**Comment by Xevion** [comment]
Currently working with an error like this, unsure how to deal with it without creating messy source code.

```astro
  <nav
    class="text-center text-sm md:text-xl text-white [&>span]:text-[#808080] [&>a]:underline [&>a]:decoration-white/50 [&>span]:select-none [&>a]:text-nowrap"
  >
    <a href="/" aria-label="Link to Home">~/</a>
    <span aria-hidden="true">:</span>
    <a href="https://xevion.dev" aria-label="About Me">~/about/</a>
    <span aria-hidden="true">:</span>
    <a href="https://xevion.dev/projects" aria-label="My Projects">~/projects/</a>
    <span aria-hidden="true">:</span>
    <a href="https://xevion.dev/resume" aria-label="My Resume">~/resume/</a>
  </nav>
```

![image](https://github.com/withastro/astro/assets/44609630/60164db7-4b4c-4de7-b7ee-3b1777817966)

`compressHTML` is enabled by default, so I'm unsure why this whitespace is here.

**Comment by toBeOfUse** [comment]
Based on the documentation, I don't think `compressHTML` is supposed to help here at all - `compressHTML` seems to act on Astro's HTML output; it doesn't control how it interprets input, and the documentation for it says that "Some whitespace may be kept as needed to preserve the visual rendering of your HTML" - which seems to be what we're seeing here.

It's all very well to say that Astro is not like JSX, but it's also not like HTML in this regard, and JSX, HTML, and for that matter Vue template syntax all ignore whitespace in their markup for a reason - they let you format your code without messing up the output. Here, Astro is forcing us to undergo formatting circumlocutions to avoid outputting significant, visible whitespace that makes the final output look weird. The example that I just ran into is this:

```jsx
  <p>
    Tagged as
    {
      meta.tags.map((tag, i) => (
        <Fragment>
          <a href={`/tags/${tag}`} class="p-1 border border-gray-100">
            {tag}
          </a>
          {i !== meta.tags.length - 1 && <span class="mx-2"> - </span>}
        </Fragment>
      ))
    }
  </p>
```

Which produces weird spaces at the end of the `<a>` elements, stretching out the underline, like this:

![image](https://github.com/user-attachments/assets/42c5f295-713f-49ff-933f-8087a04427fb)

And the Astro formatter for VSCode causes this outcome automatically if I have it on. The "solution" is to use a `prettier-ignore` comment (since the Astro extension uses Prettier under the hood) to prevent it from formatting stuff to add the problematic space:

```jsx
{/* prettier-ignore */}
<a href={`/tags/${tag}`} class="p-1 border border-gray-100">{tag}</a>
```

But as the comment above this says, this means Astro effectively requires messier source code.

**Comment by Ocelyn** [comment]
I made a plugin to remove the whitespace on Astro during the build:
[astro-remove-whitespace](https://github.com/utsuboco/astro-remove-whitespace)

**Comment by janis-me** [comment]
I am late to the party, but I encountered this issue right now (An `a` tag without any text renders an extra whitespace-only DOM node), which I wanted to remove, but the formatter would (gladly) refuse to have a bunch of HTML in one line.

I solved this using the zero-width whitespace character - obviously not just pasted in, but instead using `&ZeroWidthSpace;`.

A very weird hack, but worked for me, I wonder how bad this will backfire xD

**Comment by ducmaster01** [comment]
any update here?

**Comment by matt-curtis** [comment]
I'm running into this issue now... this is not an intuitive behavior. It would be really nice to be able to at the least control this behavior.

**Comment by rzeczkowskip** [comment]
> I'm running into this issue now... this is not an intuitive behavior. It would be really nice to be able to at the least control this behavior.

I had same issue recently. In my case it was caused by a script living next to the component and the component being inline. In that case, the extra whitespace causes issues. The fix was to wrap the component in a fragment, which removed the additional whitespaces like

**Original**

```
<a {...props} data-prefetch={IS_PROD ? prefetch : undefined}><slot /></a>

<script>
  document
    .querySelectorAll('a[href][data-prefetch="true"]')
    .forEach((link) => { /* prefetch logic */ });
</script>
```

**Updated**

```
<>
  <a {...props} data-prefetch={IS_PROD ? prefetch : undefined}><slot /></a>
</>

<script>
  document
    .querySelectorAll('a[href][data-prefetch="true"]')
    .forEach((link) => { ... });
</script>
```

In case of the example, wrapping all `text` tags should do the trick like

```
<>
  <text>TLDR :=&nbsp</text>
  <text>[</text>
  <text>3</text>
  <text>]</text>
  <text>string</text>
  <text>&#123;</text>
</>
```
