### ISSUE TITLE
Cloudflare Adapter Directory Mode not working as expected

### ISSUE THREAD

**Issue by benadam11** [withastro/astro#6018]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

Cloudflare

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Running `astro build` should bundle the API routes and create a `functions` directory with a file called `[[path]].js`. With version 6.1 a `functions` dir is created, but the `[[path]].js` file is not (instead it is creating a `_worker.js` file in `dist`). 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xngtpq

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by benadam11** [comment]
There are several issues (but I believe this is the main one) ... The other issue with pre-rendering enabled is if your site has more than a few pages, your `excludes` in the `_route.json` will exceed Cloudflares routes limit (100) which causes a failure as well. Fortunately I can work around that by providing a custom `_routes.json`

**Comment by AirBorne04** [comment]
Hi @benadam11 lets work through it 😄 

what you described is correct, apparently there was a renaming of the `serverEntry` of the `worker.js` to `worker.mjs` @matthewp do you know why that was done during the streaming update [here](https://github.com/withastro/astro/commit/9855db676e61ad616c64382adeaa8c74de05f7e1#diff-2039ec525c2c4d3855197c5d569ef62e843bfb2fe2bc614b206bf541a3d9a46cL52)

For the routes, I implemented a simple algo which is just adding all files from the `dist` folder into the excludes section and for cases you mentioned only create one if not present. A more advanced approach could possibly create issues which are hard to anticipate. Maybe with the latest updates we can generally exclude the `_astro` folder instead of listing all files.

**Comment by matthewp** [comment]
@AirBorne04 sorry about that, this is on my board to fix. If you have a quick fix feel free to submit a PR.

The reason why the extension was changed to `.mjs` was to support prerendering. In prerendering we need the entrypoint to be a .mjs file or Node will complain that it contains imports. 

However, it gets renamed to `_worker.js` at the end of the build. So I'm not sure why people are seeing this issue yet.

**Comment by matthewp** [comment]
@AirBorne04 ok thank you! Will review your PR as soon as it lands as this is an urgent regression to fix.

I would put off the `_astro` change as I think it might need some discussion (for example, it's configuration so it's not guaranteed to be that name).

**Comment by matthewp** [comment]
I see where the problem is too, working on fix.
