### ISSUE TITLE
Named slots are not rendered when using mdx layout prop

### ISSUE THREAD

**Issue by leuke-naam** [withastro/astro#6051]
### What version of `astro` are you using?

2.0.4

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

When using a layout prop named imports are not rendered (as demonstrated in [foo.mdx](https://github.com/leuke-naam/terrestrial-transit/blob/main/src/content/samples/foo.mdx)) whilst they are rendered when when importing an layout directly (as in [bar.mdx](https://github.com/leuke-naam/terrestrial-transit/blob/main/src/content/samples/bar.mdx)). 

Silently not rendering content feels like a potential gotcha and ideally should give a warning 
or behaviour could be changed so that named imports also work in `mdx` files using the layout prop.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Hey @leuke-naam! Yes, I believe this is a limitation with our JSX runtime in how slots are processed. I'll rope in @natemoo-re to see what's possible here (at least in raising a detailed error message). I know that without having the `<Layout>` component explicitly present in the file, slots are difficult to resolve.

**Comment by ericclemmons** [comment]
What's the workaround for this (based on the `p2-has-workaround` label)?

**Comment by bholmesdev** [comment]
@ericclemmons The workaround would be to import and apply your layout directly, like so:

```mdx
import Layout from '../layouts/Layout.astro';

<Layout title="Example">

# MDX content

</Layout>
```

**Comment by natemoo-re** [comment]
I'm not sure if this feature request is possible for us to implement at the moment. I'm guessing it would be quite an engineering effort to pull off. We don't currently support "slot bubbling" from the rendered result of a component, which is very similar to this.

See https://github.com/withastro/astro/issues/7547 for another discussion about this.

Since there hasn't been much discussion on this, I'm going to close this issue in an effort to keep our issues actionable for the dev team. Please feel free to start a discussion [on our Roadmap](https://github.com/withastro/roadmap) so that other can weigh in!
