### ISSUE TITLE
Const exports ignored in content collections for MDX files

### ISSUE THREAD

**Issue by pixeleet** [withastro/astro#6078]
### What version of `astro` are you using?

2.0.4

### Are you using an SSR adapter? If so, which one?

-

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Only frontmatter is considered for content collections, MDX const exports are ignored.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dwvqoj?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Hi @pixeleet! Yes, this was an intentional design choice to keep our content APIs generic between Markdown, MDX, and future file types. Since this is a feature request more than a bug report, I'd suggest [starting a discussion over on our roadmap repo.](https://github.com/withastro/roadmap/discussions) Closing for now!
