### ISSUE TITLE
custom integration: injected catch-all route overwrites local routes

### ISSUE THREAD

**Issue by nowaythatworked** [withastro/astro#6221]
### What version of `astro` are you using?

2.0.10

### Are you using an SSR adapter? If so, which one?

Vercel (error on dev)

### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

I´m injecting a "catch-all" route `[...slug]` inside a custom integration. When doing this all other routes I create inside my pages folder can not be found.
I guess something is wrong in the prioritisation.

I´m willing to help fix this if someone can point me to the right direction in code.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-g758sr?file=astro.config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nowaythatworked** [comment]
@Princesseuh are you sure this is a duplicate? 
The entrypoint is not pointing to files inside src/pages in fact it's in its own package. Also this is not about not catching two of the same routes but wrong priorisation. 

Usually, inside src/pages you can create a file called '[...args].Astro' and the same directory 'index.Astro'. the index will be served when requesting '/' and this is correct. But as soon as an integration registers the pattern '[...args]' this system breaks. Index is no longer served.

**Comment by nowaythatworked** [comment]
Hi @Princesseuh, since this is quite important to me I would love to help fixing this. Could you or somebody else in the team point me towards where the logic for this sits in the code? I´d be happy to create a PR :)

**Comment by Princesseuh** [comment]
I believe @bluwy has the necessary context to help with this, though you might have to wait until the work week start for an answer from him.

**Comment by bluwy** [comment]
It looks like injected route taking the highest priority is an intentional decision:

https://github.com/withastro/astro/blob/869197aafd9802d059dd8db1ef23794fdd938a91/packages/astro/src/core/routing/manifest/create.ts#L430-L443

The PR that added it is https://github.com/withastro/astro/pull/4087. I think what we need is a middleground where injected routes are sorted together with user routes, but injected routes take higher priority than user routes when they have equal priority.

I'm not sure how that can be achieved. Looks like it'll take some leg work to combine both sorted routes, but if you're interested in taking a look, the linked code above (injected routes sorting) and [this user routes sorting code](https://github.com/withastro/astro/blob/869197aafd9802d059dd8db1ef23794fdd938a91/packages/astro/src/core/routing/manifest/create.ts#L306) would be the place to start tweaking.

**Comment by nowaythatworked** [comment]
Thanks a lot! I'll definitely check it out and see what I can come up with. The middle ground as you mentioned sounds good to me.

**Comment by ematipico** [comment]
This should be fixed now. Closing. If you still have the issue, please create a new issue with a more recent version of Astro
