### ISSUE TITLE
Astro components always output a `<!DOCTYPE html>`

### ISSUE THREAD

**Issue by RealOrangeOne** [withastro/astro#6234]
### What version of `astro` are you using?

2.0.10

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Astro components always output a `<!DOCTYPE html>` tag, regardless of whether the content requires it.

I have some use cases where it's necessary to output non-HTML content from an Astro component, mostly to render the content from another page (which isn't possible elsewhere due to https://github.com/withastro/roadmap/discussions/409).

Ideally, the doctype tag wouldn't be submitted automatically at all, and instead down to use the user to add themselves.

### Link to Minimal Reproducible Example

None

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Astro components do not output a doctype, but pages do. This is intentional behavior. 

Let's talk about this in one of these places:

- https://github.com/withastro/roadmap/discussions/409
- https://github.com/withastro/roadmap/discussions/266
- https://github.com/withastro/roadmap/discussions/462

Going to close as there is nothing actionable to do here until one of the above issues are resolved.
