### ISSUE TITLE
Dev mode rebuilds before IDE has finished saving all files

### ISSUE THREAD

**Issue by robatwilliams** [withastro/astro#6246]
### What version of `astro` are you using?

2.0.10

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

When using Save All in VS Code, Astro occasionally starts/progresses rebuilding so quickly that not all the files have finished saving to disk yet. This only happens occasionally.

I have seen it happen and cause a failed build due to the nature of my refactoring changes. I expect that without breaking changes across files, it could simply miss including a change in the build.

### Link to Minimal Reproducible Example

Would not be reproducible

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello!

I unfortunately don't think there's anything we can do here, from the perspective of Astro (or more precisely, Vite) we can't really know that you're saving multiple files at once. Actually, even the operating system doesn't really know that, only VS Code does.

Slowing down the reload just in the case isn't really something we'd want to do, as it would slow down the way more common use case of making small iterative changes to one file.

Sorry! I'll close this issue since there's nothing to be done.
