### ISSUE TITLE
iOS performance issues when fetching a large amount of items in content collections

### ISSUE THREAD

**Issue by davideast** [withastro/astro#6271]
### What version of `astro` are you using?

2.0.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

We created a large recap page that makes uses of query for content collections. This page was originally built in pre-2.0 as well and issue described below exists when using `Astro.glob()` or `getCollection()`.

Astro 2.0 -> https://first-class-blog--pr219-jhuleatt-astro-v2-ofqaphxs.web.app/recaps/2022
Astro 1.x ->  https://firebase.blog/recaps/2022

When you open in Chrome it loads without an issue. However within Safari it grinds to a halt.

The code looks something like the following:

```js
const posts = await getCollection('features');
// Same issue with: await Astro.glob<FeaturesFrontMatter>('../content/features/*.md');
```

I have tried removing the `client:load` property from the island and refactoring from Preact to Astro components but the issue still persists. Unfortunately the repository is not public but I'm happy to showcase and snippets of code I can and detail more if you have questions.

### Link to Minimal Reproducible Example

https://firebase.blog/recaps/2022

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
If I disable JS in safari and reload your page, I still see the page grind to a halt.

I also ran the Safari recorder in the devtools, and as far as I can tell this is entirely some Safari bug. All of the blocking CPU time is spent in Safari's "Layout" rendering step at full CPU usage:
<img width="1512" alt="Screen Shot 2023-02-16 at 10 29 28 PM" src="https://user-images.githubusercontent.com/622227/219566576-26506aaf-5fc8-47a4-b8ae-f86c8d491c60.png">

The fact that you already tried converting it from a Preact component to an Astro component is also interesting, and further confirms that this isn't a JS/rendering issue.

Taken all together, this really makes me think that this is some safari bug related to your actual output, and not Astro or Preact. 

I'd recommend starting to comment different bits of UI out of the page to pin-point what this issue is. From personal experience, sometimes Safari has trouble with advanced canvas/CSS features.

**Comment by davideast** [comment]
This has turned out to be an issue with Safari and Grid. Thank you so much for digging in and Astro is the best 🚀

**Comment by matthewp** [comment]
This is one of the weirdest things I can recall.
