### ISSUE TITLE
Lit component doesn't have attributes in the DOM passed to the component

### ISSUE THREAD

**Issue by RogierdeRuijter** [withastro/astro#6393]
### What version of `astro` are you using?

2.0.11

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When rendering a lit component with SSR, attributes are not set on the html tag. 

**Description**
If we render a component called `my-component` with an attribute `title="hee"`. In astro the lit component will render like this:

`<my-component></my-component>`

The desired outcome would be:

`<my-component title="hee"></my-component>`

This allows for styling based on attributes which values, which is something that we use extensively. 

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/astro-lit-no-attributes-hxe6gp

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Use `reflect: true` if you want a property to reflect to an attribute. Lit does not do so by default. See https://lit.dev/docs/components/properties/#property-options

This is a working example: https://codesandbox.io/p/sandbox/astro-lit-no-attributes-forked-fy9j0y?file=%2Fsrc%2Fcomponents%2Fmy-component.js&selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A11%7D%5D

**Comment by RogierdeRuijter** [comment]
@matthewp 

When you render a lit component client side the initial attribute value is put on the dom element.

Here is a sandbox showing this:
https://codesandbox.io/p/sandbox/astro-lit-attributes-client-side-8bwjve?file=%2Fsrc%2Fpages%2Findex.astro&selection=%5B%7B%22endColumn%22%3A46%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A46%2C%22startLineNumber%22%3A2%7D%5D

As far as I understand `reflect` it can be used to have _updates_ reflected in the attributes.

**Note** I removed the lit integration from the astro.config.mjs to make astro not effect the lit component. If we leave it in it will strip the attributes.

**Comment by matthewp** [comment]
Hm, that doesn't make sense to me. Not all attributes can be reflected, and not all want to be reflected. Anyways, this is how the Lit integration has always worked. Pinging @e111077 in case he has insight into this that I don't have.

**Comment by e111077** [comment]
Several things:

1. you need to load the lit integration in your astro config
2. you are not using the lit client side renderer.
  - by not importing the class, you are using Astro's custom element renderer which blindly puts attributes on the components
  - you need to import the class and use `client:only="lit"` [example](https://codesandbox.io/p/sandbox/astro-lit-attributes-client-side-forked-0ejnsk?file=%2Fsrc%2Fpages%2Findex.astro&selection=%5B%7B%22endColumn%22%3A25%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A25%2C%22startLineNumber%22%3A12%7D%5D)

Additionally, there is ambiguity on how to transform JSX to HTML since JSX doesn't know the difference between a property binding and an attribuye binding. What's been chosen for the Lit integration is to set the property if it detects the property on the class, otherwise set the attribute.

**Comment by RogierdeRuijter** [comment]
Thanks for the clarification!

So the best option is to use `reflect: true` in the lit component if we want to have an attribute binding?

A note about this:
- Why has this property/attribute binding approach been chosen? Can't we just always put the `key=value` pair as an attribute binding on the element? This is also how it works if you render lit components client side.

**Comment by matthewp** [comment]
Here's the PR where that was done if you want to research: https://github.com/withastro/astro/pull/1874

**Comment by e111077** [comment]
@RogierdeRuijter yes, `reflect:true` is your best bet here. This approach has been chosen because it is possible to pass objects in JSX that are not easily stringifiable. Additionally, for micro-performance reasons, Lit would have to go through an attribute-to-property conversion unnecessarily. Also finally, it's not really idiomatic in JSX to have kebab-case bindings.

Additionally, if your component relies on the attribute being there (for like styles or something) but it also has it as a reactive property, your component should be reflecting anyways
