### ISSUE TITLE
Draft frontmatter flag not respected in collection

### ISSUE THREAD

**Issue by gotofritz** [withastro/astro#6400]
### What version of `astro` are you using?

2.0.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

`draft: true` in frontmatter of pages is respected, but in frontmatter of collections it isn't when generating static site.

As a workaround one can create a filter when calling `getCollection` and also `getStaticPath`

```
await getCollection("post", ({ data }) => import.meta.env.DEV || !data?.draft))
```

But that's not consistent with pages (where ItJustWorks) or with user expectations

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tlp8uq

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by gotofritz** [comment]
Also, the type definition for the filter function I suggested in the workaround doesn't make sense, and doesn't match the documentation.

Type definition, .astro/types.d.ts:

```
	export function getCollection<C extends keyof typeof entryMap, E extends CollectionEntry<C>>(
		collection: C,
		filter?: (entry: CollectionEntry<C>) => entry is E
	): Promise<E[]>;
```

[Documentation](https://docs.astro.build/en/guides/content-collections/#filtering-collection-queries):

```
await getCollection('blog', ({ data }) => {
  return data.draft !== true;
});
```

According to the doc the return type of the filter function should be `boolean`, not `entry`. I believe this is correct (at any rate, it does the job) and the type definition wrong

**Comment by ematipico** [comment]
@gotofritz 

The `getCollection` function is defined as an overloaded function:

https://github.com/withastro/astro/blob/main/packages/astro/src/content/template/types.d.ts#L64-L71

The second definition aligns with the documentation. `unknown` is correct because that's how typescript defines their `filter` predicate.

**Comment by gotofritz** [comment]
Yeah, I know TS does it that way, with unknown instead of boolean - wrongly, but as I understand the correct way broke too many existing code But the types.d.ts I get is not overloaded, it only has the first definition, which doesn't work. This is my types.d.ts

```
      ....
	export function getEntryBySlug<
		C extends keyof typeof entryMap,
		E extends ValidEntrySlug<C> | (string & {})
	>(
		collection: C,
		// Note that this has to accept a regular string too, for SSR
		entrySlug: E
	): E extends ValidEntrySlug<C>
		? Promise<CollectionEntry<C>>
		: Promise<CollectionEntry<C> | undefined>;
	export function getCollection<C extends keyof typeof entryMap, E extends CollectionEntry<C>>(
		collection: C,
		filter?: (entry: CollectionEntry<C>) => entry is E
	): Promise<E[]>;

	type InferEntrySchema<C extends keyof typeof entryMap> = import('astro/zod').infer<
		Required<ContentConfig['collections'][C]>['schema']
	>;
     ...
```

**Comment by natemoo-re** [comment]
After much discussion with the team, we've made the decision to deprecate the `drafts` feature in Astro 3.0. It was only ever supported in `.md` and `.mdx` files inside of the `src/pages/` directory, but never implemented in the [Content Collections](https://docs.astro.build/en/guides/content-collections/) API. 

Drafts were introduced back before Astro 1.0, when Astro was purely a static site generator and `.md/x` pages were our recommended way of working with content. Since then, Astro's capabilities and scope have grown to accommodate many different hosts and server runtimes. As such, we feel that the `drafts` feature as originally designed doesn't fit with our current approach to content.

Despite this deprecation, we understand the need for previewing unpublished content. There is [an ongoing roadmap discussion](https://github.com/withastro/roadmap/discussions/564) about supporting preview deployments for headless CMSs. Hopefully whatever eventual API emerges from that discussion can also accommodate local content. In the meantime, manually filtering your Content Collection posts using this approach is a perfectly valid way to implement drafts in userland.

```js
await getCollection("post", ({ data }) => import.meta.env.DEV || !data?.draft))
```

**Comment by gotofritz** [comment]
This is so flipping disappointing.
