### ISSUE TITLE
Whole ui package get bundled in astro

### ISSUE THREAD

**Issue by QuentinDutot** [withastro/astro#6467]
### What version of `astro` are you using?

2.1.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

In a monorepo with an astro project and a solidjs ui package, all the components get bundled when running astro build.

In bigger projects with more components it results in a ton of useless js loaded.

Steps to reproduce in the given repro:
```
- npm i
- npm run build
- open apps/web/dist/_astro/index.xxx.js
- find both button and textarea - even only button is used on index page
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-hjo4xk?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Looks like this is because for each client components imported, the import path is passed directly as Rollup inputs of the client build. Ideally we need to generate a virtual file that takes in account of the named export so that the client build treeshakes the output. This would need a bit of refactor but it sounds doable and feels like it would've affected many component libraries used today.
