### ISSUE TITLE
Rendering content collection entries through a loop with imported astro components causes broken scripts and styles

### ISSUE THREAD

**Issue by putnikproj** [withastro/astro#6672]
### What version of `astro` are you using?

2.1.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

The new Content Collection API lets you import mdx files and render their content anywhere using the `.render()` method, and only imports those components and their styles and scripts when they're used on a page. This works perfectly when generating routes from content - on each page an entry, its scripts and styles are executed and bundled. But when I try to render multiple entries on one page through a loop, scripts and styles don't work.

```js
// pages/page.astro
---
const entries = await getCollection('someColletion');
---
{entries.map(async entry => {
	// Scripts and styles don't work in <Content />
	const { Content } = await entry.render();
	return <Content mdProps="work" />; 
})}
// content/someCollection/some-mdx.mdx
import AstroComponent from 'pathToComponent/AstroComponent.astro';
<AstroComponent />
// components/AstroComponent.astro
<!-- Some html -->
<script>/* Some scripts */</script>
<style>/* Some styles */</style>
```

Everything works when explicitly tell astro which components to render (see reproduction):

```js
---
const { Content } = await entries[0].render();
const { Content: Content2 } = await entries[1].render();
---
<Content />
<Content2 />
```

I want to render my mdx components with imported nested astro components through an array, as this is the only way to use astro components and prevent bundling of unused scripts and styles (https://github.com/withastro/astro/issues/6328)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-b1xdf7-ptottr?file=src%2Fcomponents%2FRenderEntry.astro,src%2Fpages%2Findex.astro,src%2Fpages%2Ffinal.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wulinsheng123** [comment]
I would like to check it.

**Comment by matthewp** [comment]
This is because script/style propagation is dependent on the template being static. We examine the template and see that there are components which contains styles and then wait on that portion before sending the `<head>` tag out. Making the template dynamic in this way prevents this.

I anticipated this problem when working on head propagation but couldn't think of a good solution. I think some explicit API is probably needed here. For example if there was a `{Astro.propagate(entries.map(...))}` or perhaps a `<Propagate>{entries.map(...)}</Propagate>`

**Comment by wulinsheng123** [comment]
> This is because script/style propagation is dependent on the template being static. We examine the template and see that there are components which contains styles and then wait on that portion before sending the `<head>` tag out. Making the template dynamic in this way prevents this.
> 
> I anticipated this problem when working on head propagation but couldn't think of a good solution. I think some explicit API is probably needed here. For example if there was a `{Astro.propagate(entries.map(...))}` or perhaps a `<Propagate>{entries.map(...)}</Propagate>`

```astro
const { Content } = await entries[0].render();
const { Content: Content2 } = await entries[1].render();
---
<Content />
<Content2 />
```
It sounds a little weird.
It doesn't need to add anything in upon example. 
But we must add extra code in another example.
However, I'll continue to finish my PR. It probably is not a good idea though , but there is still a different perception.

**Comment by LushawnDev** [comment]
I'm not sure if this is related but kapa.ai sent me to this issue and it seems relevant.

I'm using content collections with the experimental Astro assets feature.

I'm experiencing similar issues where I import a whole collection (of portfolio projects, which have a title, a description and images), on the page I loop through all the portfolio projects and output their data into a card component I made. 

The image strings get passed to the component as props, but the image strings are being passed as relative file paths as defined in the markdown files, they never render the correct generated URL pointing to the optimised image.

Is this related? If so is there any update on this issue?

Thanks for your time!

**Comment by putnik-projects** [comment]
I wouldn't say the issue is solved. It simply adds wrong html markup with script and style tags. Yes, the browser displays the expected output, but the final generated html is completely wrong and unacceptable (Reproduction: https://stackblitz.com/edit/github-b1xdf7-mcrjxh. `npm run build`, `dist/final.html`).
<img width="668" alt="Screenshot 2023-05-31 at 17 16 44" src="https://github.com/withastro/astro/assets/53861888/3cbfb211-3a85-43ab-a2e5-828cd9e70511">
Moreover, during testing, I noticed another bug with the content collections rendering function, which is related to the first one (the same reproduction, but `dist/index.html`). Although all scripts and styles are correctly propagated to the top `<head>` tag, additional redundant nested html document structure is created inside the body, at the place where I use the `<Content />` component.
<img width="662" alt="Screenshot 2023-05-31 at 17 27 15" src="https://github.com/withastro/astro/assets/53861888/e6fbac21-c44d-42ff-a483-018a8bc7f725">

**Comment by wulinsheng123** [comment]
I think it can only be used as a temporary solution.
I saw that issue in the image you provided. because of this [code](https://github.com/withastro/astro/blob/c86f0c6e3e10efa13bec43969a275d82fb10da15/packages/astro/src/runtime/server/render/astro/instance.ts#L86) 
the reason is the same function key can't be identified in the map .

**Comment by bholmesdev** [comment]
Reopening since this introduced a separate bug, and causes unexpectedly broken Markup as noted by @putnik-projects

**Comment by lilnasy** [comment]
This issue has been reported several times, and is currently being tracked in #7761.
