### ISSUE TITLE
[Vercel Adapter] .wasm files are not being copied to output

### ISSUE THREAD

**Issue by raulfdm** [withastro/astro#6712]
### What version of `astro` are you using?

2.1.8

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Any

### Describe the Bug

I'm using a library called `@wooorm/starry-night` that provides syntax highlights for code. It relies on the wasm provided `vscode-oniguruma` to do the job.

When I run everything locally, it works just fine because, inside the module on the `.pnpm` folder, both the entry point (.js) and the .wasm file is there.

The problem is that using `@astro/vercel`, all dependencies are copied to `functions/render.func/node_modules/...`, but the .wasm files is not:

** root level `node_modules`👇**
![Screenshot 2023-03-30 at 11 30 19](https://user-images.githubusercontent.com/12464600/228793267-f128c159-d126-49de-af9d-fa47b2134cf0.png)

** .vercel/functons/render.func/node_modules 👇**
![Screenshot 2023-03-30 at 11 29 48](https://user-images.githubusercontent.com/12464600/228793136-db59a5b4-466e-4d8f-b05f-30245f2f989c.png)

I believe this is not correct.

As a consequence, when I deploy my project o vercel, the lambda function tries to resolve to that wasm file but because it doesn't exist, it throws an error.

As a workaround, I had to:

- install `vscode-oniguruma` as dependency;
- install `import-meta-resolve`;
- get the path to that file;
- include the .wasm pathname in the `includeFiles` list

## Gotchas

- On Stackblitz, the `.vercel` folder is not shown after creation, probably because of the dot notation.

### Link to Minimal Reproducible Example

- Stackblitz: https://stackblitz.com/github/devraul/astro-vercel-wasm-bug
- Repository: https://github.com/devraul/astro-vercel-wasm-bug

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
The vercel integration use [@vercel/nft](https://github.com/vercel/nft) to trace the files to include. There would sometimes be files left out because of dynamic references, and in this case `includeFiles` would be used to manually include it.

I don't think there's a way for us to fix it. We can't tell `@vercel/nft` to track that WASM file because it doesn't, unless we hardcode it. I believe this is a tradeoff the Vercel deployment target accepts.

**Comment by bluwy** [comment]
Documentation would be great, but I'm not sure how we can frame this in a generic way. Missing files can cause a wide variety of errors. We do have a note at https://github.com/withastro/astro/blob/abf809bacb427242acf3e53c95981ba3967b6e43/packages/integrations/vercel/README.md#includefiles mentioning it though:

> Use this property to force files to be bundled with your function. This is helpful when you notice missing files.

**Comment by Princesseuh** [comment]
Closing since there's nothing actionnable on our end and we already have a mention of this on the integration docs. I think that if we get more issues about this we can consider making the note on the docs more visible, but otherwise it should be fine.

Here's hoping that a native solution for including `.wasm` files exists one day so we (and hosts) don't have to deal with this 😔
