### ISSUE TITLE
Static routes generation fails with `@astrojs/vue` in the root package.json of a monorepo

### ISSUE THREAD

**Issue by wonderbeel** [withastro/astro#6790]
### What version of `astro` are you using?

2.2.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### What browser are you using?

Firefox

### Describe the Bug

When working in a monorepo setup and putting all the packages in the root `package.json` astro can be used in dev mode without problems but it fails to build when generating static routes.
The problem seems to be with `@astrojs/vue` because if I move it in the workspace package everything works.

This is what I see locally
```
> astro build

17:53:25 [content] No content directory found. Skipping type generation.
17:53:25 [build] output target: static
17:53:25 [build] Collecting build info...
17:53:25 [build] Completed in 69ms.
17:53:25 [build] Building static entrypoints...
17:53:25 [build] Completed in 348ms.

 building client
Completed in 333ms.


 generating static routes
 error   Only URLs with a scheme in: file, data are supported by the default ESM loader. Received protocol 'virtual:'
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. Received protocol 'virtual:'
    at new NodeError (node:internal/errors:393:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1026:11)
    at defaultResolve (node:internal/modules/esm/resolve:1106:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
/home/alberto/projects/astro-root-monorepo-repro/apps/example:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  example@0.0.1 build: `astro build`
Exit status 1
```

### Link to Minimal Reproducible Example

https://stackblitz.com/github/wonderbeel/astro-root-monorepo-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Hello! In pnpm monorepos, it is typically intended for dependencies of child packages to be in the child package's `package.json`. The root `package.json` is usually only intended to be used for tools shared by your packages (ESLint, Prettier etc)

While your setup seems to work for some of your deps right now, I suspect that as you go, you'll encounter more and more situations where this won't work. I doubt this is something we can fix ourselves. Sorry.

If you like this kind of setup with all the deps being in the root `package.json`, you might find [Nx](https://nx.dev/) interesting, since I believe it works that way.

**Comment by wonderbeel** [comment]
Hi @Princesseuh , actually I encountered this issue in a nx monorepo so no, using a tool like it isn't a solution (and it makes sense because they don't do anything magic with dependencies, they are still managed by npm/yarn/pnpm).

**Comment by Princesseuh** [comment]
Oh, alright.. Hmm. I'm really not sure what we can do about this ourselves, the error seems to imply that something that's supposed to run in Vite is being ran in Node and I don't really see how that's related. I'll re-open nonetheless, I'm sure we can take at least a look

**Comment by bluwy** [comment]
I looked into this, and it's caused by `@astrojs/vue` not being bundled properly in the final output. Usually it can be bundled by setting `vite.ssr.noExternal: ['@astrojs/vue']`, which we do internally automatically. But the way we do automatically is by reading the project's `package.json`, so the dependency being in the root `package.json` makes it not scannable.

I'm not sure about doing this automatically for the root `package.json`. It could bring a large startup overhead, and possibly cause more issues in the long run. For now, I think it's best to keep it simple, and have all deps required in the project's `package.json` instead. Otherwise, if you do want to keep it at the root, you'd have to manage `ssr.noExternal` yourself.

**Comment by wonderbeel** [comment]
Thanks a lot for looking on this, I will try manually handling `ssr.noExternal` to see if it fixes it.
If it solves this issue would you like to have this documented somewhere? It is an issue that will probably rise up for nx users (putting all the dependencies in the root `package.json` is what they suggest in their integrated and standalone setups) so I am not really sure if it useful to have this documented or if it will only add clutter instead.

**Comment by bluwy** [comment]
I think this would be good to document as well. Maybe https://docs.astro.build/en/guides/troubleshooting/ would be a good spot for it. cc @withastro/maintainers-docs 

Summary: Astro project's dependencies should be put in it's `package.json`. If it's put outside, e.g. the root `package.json` of a monorepo, some packages might not bundle or work correctly. If it can't be avoided, you need to manually set dependencies in `ssr.noExternal` instead. (common for Nx)
