### ISSUE TITLE
Code component does not work with pnpm on Vercel

### ISSUE THREAD

**Issue by kayn1** [withastro/astro#6804]
### What version of `astro` are you using?

2.2.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I have deployed my app to the Vercel hosting today and got this error when I wanted to access one of my pages which is using `Code` component.

```js
nhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: ENOENT: no such file or directory, open '/var/task/node_modules/.pnpm/shiki@0.14.1/node_modules/shiki/languages/html.tmLanguage.json'","reason":{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, open '/var/task/node_modules/.pnpm/shiki@0.14.1/node_modules/shiki/languages/html.tmLanguage.jso
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-s5rj4a?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This is documented at https://docs.astro.build/en/reference/api-reference/#code-

> When using a [strict package manager](https://pnpm.io/pnpm-vs-npm#npms-flat-tree) like pnpm, you may also need to install Shiki so it works during build:

**Comment by kayn1** [comment]
> This is documented at https://docs.astro.build/en/reference/api-reference/#code-
> 
> > When using a [strict package manager](https://pnpm.io/pnpm-vs-npm#npms-flat-tree) like pnpm, you may also need to install Shiki so it works during build:

Yeah, it is documented and I did it and it still did not work.

**Comment by bluwy** [comment]
I'm guessing it's one of those "Vercel didn't include those files" cases: https://github.com/vercel/vercel/discussions/8726.

It would be a bit hard to make this work, but you might need to glob into `./node_modules/.pnpm/shiki@0.14.1/node_modules/shiki/languages/*.json` for all the languages that shiki uses, and pass it to `includeFiles` option in the Vercel adapter.

I can also try to confirm this when I get around deploying a test site. But otherwise _maybe_ we can look into supporting this ootb for the Vercel adapter since `shiki` and `<Code/>` are first-class APIs.

**Comment by kayn1** [comment]
So for me the workaround was to use yarn instead pnpm but it would be nice if there are no difference between package managers.

**Comment by matthewp** [comment]
Closing as there's nothing actionable to be done here and appears to be a bug with Vercel's bundling strategy.
