### ISSUE TITLE
docs → 1.mdoc failed to validate: attribute-type-invalid

### ISSUE THREAD

**Issue by HeartQwQ** [withastro/astro#6865]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the Bug

I want to use components to customize markdown, and I have written it successfully, but I don’t know why I started to report errors later.
![image](https://user-images.githubusercontent.com/64885728/232521561-443ac3fa-5223-4e10-842a-247b74fa694b.png)

and with an additional hint:
A PostCSS plugin did not pass the `from` option to `postcss.parse`. This may cause imported assets to be incorrectly transformed. If you've recently added a PostCSS plugin that raised this warning, please contact the package author to fix the issue.

I made a minimal error case, who can help me, I am so worried

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-se2oev?file=src/components/Heading.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
@bholmesdev any ideas? Example looks fine to me.

**Comment by bholmesdev** [comment]
Interesting, the example looks fine to me as well. I'll take a look!

**Comment by bholmesdev** [comment]
Ah ha! Looks like you want `level: { type: Number }` instead of `type: String` on the markdoc attributes. You can also install `@markdoc/markdoc` to import built-in attributes like so:

```ts
import { defineMarkdocConfig } from '@astrojs/markdoc/config';
import Markdoc from '@markdoc/markdoc';
import Heading from './src/components/Heading.astro';

export default defineMarkdocConfig({
	nodes: {
		heading: {
			render: Heading,
			attributes: Markdoc.nodes.heading.attributes,
		},
	},
});
```

I'll admit this deserves better documentation both from Markdoc and Astro's end. A few action items:
- Explain where to import attributes from in the README
- Make the global `Markdoc` object available from `@astrojs/markdoc` for convenience
- Improve validation error messages to show the full error message
