### ISSUE TITLE
Slots render additional character spaces

### ISSUE THREAD

**Issue by ohansemmanuel** [withastro/astro#6893]
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

It's unclear if this is the expected behaviour, however, here's a brief summary of the rather confusing bit: 

- With `<slots>` rendered in an Astro component, the eventual HTML seems to render with extra character spaces 
- However, this behaviour can be avoided if no spaces are left when the slot is rendered

That's a mouthful, so here's an actual example: 

```astro
❌ will render slot (string) with extra white space(s)
<span>
  <slot />
</span>

✅ will add no extra character spaces
<span><slot /></span>
```

## Expected behaviour 
Both examples render without additional white space  

Please refer to the reproducible code sample below
![CleanShot 2023-04-22 at 20 44 16](https://user-images.githubusercontent.com/10930234/233801347-ba8105f5-2132-4dad-b11e-711d0711f2f0.png)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pt3tw5?file=src/pages/index.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by ohansemmanuel** [comment]
On second look, the behaviour is similar independent of slots i.e., same with a simple string value e.g.: 

```astro
<span> 
string 
</span>
```

It might be worth having this work quite similar to JSX where white spaces are trimmed by default and explicitly added if needed e.g.: 


```astro
<span> 
string {' '}
</span>
```

**Comment by Hacksore** [comment]
Just sharing my workaround here for others to adopt, hope it helps!

https://github.com/overlayeddev/overlayed/commit/a43a8ae2cf5c3133381f4a942230793f468cc84b

**Comment by u3u** [comment]
https://prettier.io/docs/en/options#html-whitespace-sensitivity

I hope to add a new option in the future, allowing users to freely choose whether spaces are irrelevant, which will be more user-friendly for JSX users. And due to the uncontrollability of the Prettier plugin, when I need to remove surrounding spaces, I have to accept uglier code, which is really bad. Most of the time, spaces are unnecessary. If I really need a space, I can freely control the insertion position through `{' '}` instead of guessing the formatting result of the Prettier plugin. I often spend a lot of time adjusting one or two spaces.

[Prettier Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwAQ4CGUA5gLwA6ICVAfBVBTBnIQCb2MxOpZwyE8YdIQBOAZ36UQAVxgAzALQAOKngD0nJjz4C8UQn2kA3AJZwA7gAcIo7iCHR4saRdNsY6MmzhmwcRTcPdDVNBm1mHFMoAGs8UTgcaVNIRgcYAE8rOGSsQhI4dXFjEgBqAA9cNXQE+Wl1eUI-aAA6YpJQrW5mXUEDIyoCqDhRQhhbNVTnGDJgAEFxGFEIFqGRsdsAXw0unhhTGBw4WgWliDxSvAAVQlMcNyg2AGEAZRfUdX3D4-DmdXRWBxwlxUAAjCBsDK7ZhsUzGIREcTiaQkUTuPBWIj+RQHOBYcSKfywEZ4dCKcRgBIIRzE2CEhDwUR0X4RVBWaERACqkjwxDwqCeEOOpnkH0FPloeEWYzxDJaeAAIqZxJjCBloiReQRlTAAPzXUQZXmiUYZBh4C2Wi0CoW0PJWAAUAEoxbb5Szuh92cCIjxvVxfTBuXBeVB+eK4C8AI4yQjiAEcEWunzR2PxuAcKUCeB8WDypUqojq0haqKLfVXQ3G03mq2Wm0pmNxhN2wiOl3qCOp5sZ2jugOe9T+1nqWHGLofcGQzgfTC4WggAA0IAgVn20HEyFAYmWFgACmIEJuUIR7mrN8vQaMwDF+C9DHAADLRODIRo4SSX6+3mAvKyEMANWQJYZDgZdJCwUxgNEUDlzgcpsjRXMBBwK4RgMNE4GPd9PxAcQNSOABFGQIHgN9T1wgArcRyheAi4GI0jXyQHCwJAGMmL3ZYrGPEA40UYYMwzJcQCWW4olIQUsDyZA+JwHARPw0gjjmGAllMUE5DgPcRmfYZyI-Ni5xwAB1dBcRVADIyPA44QODJZNMEgoFsV9l2MUCAElHgZF5KVMNc5keF5MiOAzcKsZZJBM0YrFkyKsJGYw3JAaJJDsLj8hkliKLY-8JBGWTjJEyLohgEz3E8ZBlAABmXBIY1MBJMpIbLWOXARQQq4JkAAJmXGRJBuUFsNyuCsFBDMfDYR9iBIWMCgAMVsPI1KAk85AgEBNk2IA)

It looks better, doesn't it?
