### ISSUE TITLE
 background:url not support alias?

### ISSUE THREAD

**Issue by vaynevayne** [withastro/astro#6896]
### What version of `astro` are you using?

latest

### Are you using an SSR adapter? If so, which one?

neno

### What package manager are you using?

pnppm

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

not work 
`background-image: url("@assets/pre_register_btn.png")`

work 
`  background: url("../assets/pre_register_btn.png")` 

### Link to Minimal Reproducible Example

no

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
The latest version of Astro should support this, can you provide a repro?

**Comment by vaynevayne** [comment]
codesandbox not support local image, you can reproduce by youself

**Comment by bluwy** [comment]
You can use stackblitz or a github repo

**Comment by MoustaphaDev** [comment]
@bluwy I believe they're using inline style attributes (found a cross post on discord), which I don't think are subject to be processed
```html
<div style="background: url(@assets/bg.png)">Hey</div>
```

**Comment by bluwy** [comment]
Yeah it's not easy to preprocess the style tag, if needed OP can do `import bgUrl from '@assets/bg.png?url'` and ``style={`background: url(${brUrl})`}`` to make it work. Closing for now.

**Comment by brentarias** [comment]
From a [StackOverflow investigation](https://stackoverflow.com/questions/76937325/flex-item-image-not-honoring-proportionality-settings), it was concluded that Chrome has problems accurately rendering `img` tags within flex-items, under some circumstances.  The consequence being, in that case, that an `img` tag then needs to be replaced with a `div` tag using an embedded `style` (to otherwise imitate the `img` behavior as closely as possible).

Consequently, this means that the proposed Astro work-around...

```
import bgUrl from "../assets/senex_mandala_32.png?url"
...
<div class="photo" style={`background-image: url(${bgUrl})`} />
```
...should be escalated into Astro official documentation.

Also, notice my above example uses:

* The prefix `../assets` ...because the `@assets/` prefix wasn't working.
* The `?url` postfix...simply because you suggested it.  I have no idea what that accomplishes.  I think the Astro documentation perhaps should cover that as well.

For my test project, my package.json contains:

```
    "@astrojs/mdx": "^0.19.5",
    "@astrojs/rss": "^2.4.3",
    "@astrojs/sitemap": "^1.3.2",
    "astro": "^2.5.6"
```
