### ISSUE TITLE
node-fetch issue

### ISSUE THREAD

**Issue by borismoyosa** [withastro/astro#6988]
### What version of `astro` are you using?

2.3.1

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

I'm trying to use a library (MindAR) in an Astro project to add image recognition.
Installed it via npm.
I get the following error `Uncaught SyntaxError: The requested module '/node_modules/whatwg-url/lib/public-api.js?v=0104a445' does not provide an export named 'default' (at index.mjs?v=0104a445:4:8)`
which points to `node_modules/node-fetch/lib/index.mjs`. It seems to break in the node-fetch package.

I get the feeling the issue has something to do with Vite because in another project that uses webpack, but no Astro and Vite, I have used MindAR without issues.

The contents of the whatwg-url file are:
```
"use strict";
exports.URL = require("./URL").interface;
exports.serializeURL = require("./url-state-machine").serializeURL;
exports.serializeURLOrigin = require("./url-state-machine").serializeURLOrigin;
exports.basicURLParse = require("./url-state-machine").basicURLParse;
exports.setTheUsername = require("./url-state-machine").setTheUsername;
exports.setThePassword = require("./url-state-machine").setThePassword;
exports.serializeHost = require("./url-state-machine").serializeHost;
exports.serializeInteger = require("./url-state-machine").serializeInteger;
exports.parseURL = require("./url-state-machine").parseURL;
```
node: 18.16 
npm: 9.5.1

I created a minimal example on stackblitz that shows the error in the browser console.
Anybody that maybe can point me in the right direction?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ez7qc8?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Hi @borismoyosa , I opened the link, but I can't see any error. Do we need to do something in order to trigger the issue?

**Comment by ematipico** [comment]
I _think_ the issue is the combination of `node-fetch` source code and vite. `vite` doesn't transform files to `cjs`, while `webapck` does.

And `node-fetch` relies on a dependency that doesn't have a `cjs` default export. 

- [source code of `node-fetch`](view-source:https://withastroastroez7qc8-zwm0--3000--d830b1a2.local-corp.webcontainer.io/node_modules/node-fetch/lib/index.mjs?v=d1ad55f6)
- [files that `node-fetch` tries to import, which has the wrong syntax](view-source:https://withastroastroez7qc8-zwm0--3000--d830b1a2.local-corp.webcontainer.io/node_modules/node-fetch/lib/index.mjs?v=d1ad55f6)

I don't know if we can fix it on our end.

**Comment by borismoyosa** [comment]
@ematipico thanks a lot for looking into this. I'm going to look if I can come up with a workaround for this issue.

**Comment by th0rgall** [comment]
For future reference: I got the same error. I was accidentally importing a function exported from a server-side Endpoint module inside a frontend Svelte component.

This function code was using the sever-only Notion API, which also uses node-fetch down the dep chain

```
@notionhq/client 2.2.13
└─┬ node-fetch 2.7.0
  └── whatwg-url 5.0.0
```

**Comment by jakobhaerter** [comment]
@borismoyosa Have you found a possible workaround, by any chance?

**Comment by MoritzLost** [comment]
> I _think_ the issue is the combination of `node-fetch` source code and vite. `vite` doesn't transform files to `cjs`, while `webapck` does.
> 
> And `node-fetch` relies on a dependency that doesn't have a `cjs` default export.
> 
>     * [source code of `node-fetch`](https://withastroastroez7qc8-zwm0--3000--d830b1a2.local-corp.webcontainer.io/node_modules/node-fetch/lib/index.mjs?v=d1ad55f6)
> 
>     * [files that `node-fetch` tries to import, which has the wrong syntax](https://withastroastroez7qc8-zwm0--3000--d830b1a2.local-corp.webcontainer.io/node_modules/whatwg-url/lib/public-api.js)
> 
> 
> I don't know if we can fix it on our end.

@ematipico Trying to understand this issue … doesn't Vite already transform CommonJS modules? According to [Dependency Pre-Bundling](https://vitejs.dev/guide/dep-pre-bundling) it should? Or is the issue that pre-bundling doesn't discover the node-fetch dependency as mentioned [in this issue](https://github.com/vitejs/vite/issues/3024)?

**Comment by JLarky** [comment]
I had this issue happening in Astro for builder integration. They are doing [conditional](https://x.com/JLarky/status/1849309255607672875) `require` depending if global `fetch` is there or not. Great stuff. It would only show up in dev, so bundle size issues are 🤷 but because it was crashing my dev builder I had to do something... what I did is I just used `patch-package` and removed that conditional require from `node_modules/@builder.io/react/dist/builder-react.es5.js`. No code to import `node-fetch` no code to crash anything client side :) problem solved :)
