### ISSUE TITLE
astro@latest installing incorrect version

### ISSUE THREAD

**Issue by darbyjack** [withastro/astro#6998]
### What version of `astro` are you using?

2.3.2

### Are you using an SSR adapter? If so, which one?

N/A

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Running `pnpm create astro@latest` does not install the latest version (2.4.1 at the time of the post).

I was able to successfully reproduce this each time I attempted it.

![image](https://user-images.githubusercontent.com/21014720/236325441-3f9c5430-c3a3-4c7a-b6fa-9c840cb6a094.png)

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by sarah11918** [comment]
Just adding that I also tried, and got the same result! It installed v 2.3.2 for me, also!

**Comment by TheOtterlord** [comment]
Same here.

Not sure what the requirement is for it to update the package.json because it does in https://github.com/withastro/astro/pull/6914 but not in https://github.com/withastro/astro/pull/6954

**Comment by bluwy** [comment]
It's a pnpm 8 issue: https://github.com/pnpm/pnpm/issues/6463. The gist is that pnpm 8 now installs the lowest matching version instead of the highest, so `^2.3.2` => `2.3.2` and not `2.4.0`. There are discussions of a solution which pnpm would install the highest only if the lockfile is missing, but IMO it's a strange pnpm behaviour in the first place.

Anyways, what we can do is:

1. Add `.npmrc` of `resolution-mode=highest` for templates using pnpm.
2. Or, manually bump the versions in the templates for now.

I'd lean towards no2 to keep it simple, and hope that pnpm fixes this soon.
