### ISSUE TITLE
💡 RFC: Temporary page storage

### ISSUE THREAD

**Issue by okikio** [withastro/astro#706]
### Motivation

I think a global state system would be useful. While testing I realized there was no way to create svg icons, and reuse them using the `<use href="#...">` tag, I think a means of storing state temporarily during build time would be useful. Icon's in and of themselves could be a native component, but I feel a Global state system would be more versatile, and allow you to setup complex features in a pleasant way. 

### Possible solutions

`Astro.metadata.state` an empty object or map, that persists between `Astro` component usage, meaning every time a page or component is called during a singe build instance, the state will be preserved, this can be used in tandem with #491,  Astro and Markdown metadata. It would allow `Astro.metadata.state` to carry state between pages and components.

### Alternatives considered

We could use `let [getState, setState] = Astro.state()`, this would be auto scoped to each component, meaning one component can't access `Astro.state()` of another component. The scope of `Astro.state()` maybe too small to be a viable long term solution to state storage.

### Risks, downsides, and/or tradeoffs

State storage might lead to improper usage and loads of bugs with 3rd party components.... We may need to think of ways to scope `Astro.metadata.state` to each individual page and or components, to avoid security risks when using 3rd party components, and giving developers the access to create complex web sites and apps.

### Detailed Design

https://github.com/snowpackjs/astro/issues/706#issuecomment-904963705

### Open Questions

This would bring complexity to `Astro`, what are your opinons?

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
We've talked about this before, and I'm generally in favor of a state or store API inside of Astro.

> While testing I realized there was no way to create svg icons, and reuse them using the <use href="#..."> tag, I think a means of storing state temporarily during build time would be useful.

I'd love to understand this better! This sounds like a fairly unique use-case, but I may be misunderstanding. It would be great to have a really clear and specific use-case/user story to discuss if we were to bring this up on the RFC call.

**Comment by okikio** [comment]
@FredKSchott My use case has to do with avoiding redundancy. Right now when using SVG Icons as components, you need to define the entire SVG image every time, which adds bulk and unnecessary code. If we added a state management system to Astro, you can keep track of whether a specific SVG Icon is used on the page, and if the SVG Icon has already been used on that page before you use 

```html
<svg width="24" height="24"> 
    <use href="#icon-plus" />
</svg>
```

If the SVG Icon **hasn't** been used on the page you would get,

```html
<svg width="24" height="24"> 
    <path d="..." />
    <path d="..." />
    <path d="..." />
    <path d="..." />
    <path d="..." />
</svg>
```

**Comment by matthewp** [comment]
@okikio This sounds very similar to my old `<Once>` component idea. Would something like that work, where you know the number of times that the component has been rendered?

I actually like your idea a bit better as its a little lower-level. I'd like to discuss on a call if you're available to talk about it. Call is tomorrow: https://github.com/snowpackjs/astro/issues/1144

**Comment by okikio** [comment]
> @okikio This sounds very similar to my old `<Once>` component idea. Would something like that work, where you know the number of times that the component has been rendered?
> 
> I actually like your idea a bit better as its a little lower-level. I'd like to discuss on a call if you're available to talk about it. Call is tomorrow: #1144

I think having both would be useful overall

**Comment by okikio** [comment]
I'll join the RFC call tmrw

**Comment by matthewp** [comment]
Feedback:

* There are different types of state: component local, page build local, build global. Which is this about?
* Is the term `state` the best?

**Comment by FredKSchott** [comment]
Hope I didn't get too distracted by the "state" naming! Just wanted to make sure we have a clear idea of what we're trying to solve with this, since state is such an overloaded term. Happy to use this PR to focus on the "page build" state and not memoization. 

To get to a +1 I'd strongly prefer something that is clearly "page-level component state". 
- `Astro.request.context` ? is this global, vs scoped to this one component?
- `Astro.request.context.component` ?
- `Astro.context.component` ?

**Comment by okikio** [comment]
The more I think about it, I feel a "page-level storage system is better", so, every page in the pages dir. (including pages generated using `getStaticPaths()`), pages would get access to this storage via `Astro.request.storage` (I am willing to change the name, as it doesn't really matter as much as the concept), components would also get the same access via `Astro.request.storage`, and for storage access specific to each component, we could add `Astro.request.storage.component` (again the name isn't all that important), this would allow us to create a `<Once />` component based on this concept, this very specific storage system is basically an object with the pages path being the object key, and each component also being objects with the key being the component file path, so, something like this,

**_Page_**: `src/pages/awesome/right.md`
**_Component_**: `src/components/Block.astro`
```jsonc
{
    "/awesome/right.md": {
        // Other object here, e.g. how many times a component is used, etc....
        "/components/Block.astro": {
            "count": 5
        }
    }
}
```
Every time a specific page is requested, the pages storage is cleared (basically this work out to be that every time a page is changed the storage for that specific page is cleared), and every time a component is changed the storage for that component is cleared. However, I feel we could also generate a separate caching system for things that we want all components to have access to, this cache is only cleared if a file is renamed, moved, or deleted, this should allow for less duplication

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
