### ISSUE TITLE
can't read "_index.md" file using getEntryBySlug

### ISSUE THREAD

**Issue by tfsomrat** [withastro/astro#7063]
### What version of `astro` are you using?

2.4.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

can't read a file that starts with underscore `_` by using `getEntryBySlug()`. like I want to get `blog/_index.md` file with `const postIndex = await getEntryBySlug("blog", "_index");` but it's not working.

I can parse `const postIndex = await getEntryBySlug("blog", "index");`, but I want "_index"

**Comment by bholmesdev** [comment]
@tfsomrat This is expected behavior! `_` is reserved for "ignored" files that you explicitly _don't_ want to be visible from Content Collection APIs. This is meant for colocating styles, scripts, and `.md` or `.mdx` fragments you may import into content entries. I'm curious if you have a specific need where underscores are the _only_ option? All other characters should work.

**Comment by tfsomrat** [comment]
actually, I utilized it to segregate the index file for pages with solitary content (such as blogs). I employ alternative SSGs like Next.js, Hugo, and Jekyll, yet they do not disregard the _index.md file. Therefore, I presumed that I should be capable of parsing the _index.md file in Astro, similar to how other SSGs do.

**Comment by bholmesdev** [comment]
@tfsomrat Gotcha. Since this is expected behavior, I think I'll transfer this issue to our docs repo to make the underscore convention clear. We _do_ need a way to exclude files from content collection queries, so we'd need another solution besides an underscore. If there's a good reason to move away from underscores, let me know!

**Comment by tfsomrat** [comment]
> If there's a good reason to move away from underscores, let me know!
Hi, thanks for your response. there is a good reason here. if someone wants to migrate from other SSGs like "Hugo", "Jekyll" or others, they will simply copy their content folder and paste it on "Astro". but now, they actually need to change the file name convention to make it work. thank you
