### ISSUE TITLE
@astrojs/sitemap filter doesn't apply to endpoints

### ISSUE THREAD

**Issue by fflaten** [withastro/astro#7081]
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Edge

### Describe the Bug

Using astrojs/sitemap 1.3.0+ endpoints likes images, rss etc are included in sitemap (#7080). The same URLs are not processed by the filter-feature leaving no option but to stick with `1.2.2` release to avoid sitemap-entries causing 404.

Repro: Run build in sample and compare URLs printed in console with `sitemap-0.xml`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xfdxg4?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by neulandherzer-dev** [comment]
I find that the filter feature does not work at all in that version. All pages are always included in the sitemap.

**Comment by kevintanu** [comment]
it's still broken on 1.3.1, stick to 1.2.2 instead

**Comment by SenseiMarv** [comment]
It also adds the injected `_image` route from the [`@astrojs/image` integration](https://github.com/withastro/astro/tree/main/packages/integrations/image/), which results in a 404 page.
And it adds the RSS route from the [`@astrojs/rss` integration](https://github.com/withastro/astro/tree/main/packages/astro-rss) with a trailing slash, which is a problem for me because I use the [`@astrojs/vercel` adapter](https://github.com/withastro/astro/tree/main/packages/integrations/vercel/) with `"cleanUrls": true` to address [this issue](https://github.com/withastro/astro/issues/4164) and need to have the route end without trailing slash.

Since the filter no longer works, I can't remove these pages and routes with @astrojs/sitemap 1.3.0+.

**Comment by bluwy** [comment]
This should be fixed in https://github.com/withastro/astro/pull/7263
