### ISSUE TITLE
I can't run typechecking if I use srcDir config option

### ISSUE THREAD

**Issue by JLarky** [withastro/astro#7112]
### What version of `astro` are you using?

2.4.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn, npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I tried to play with `srcDir` option in `astro.config.mjs`. It works fine on dev, but I can't run typechecking on it anymore :)

<img width="1244" alt="image" src="https://github.com/withastro/astro/assets/7026/e460d53d-1712-42ad-b212-901dda305dd6">

I guess It's caused by the fact that "root project" is using astro collections.

steps to reproduce:

```
yarn create astro
# use blog template
# edit astro.config.mjs
yarn tsc --noEmit
```

I created minimal reproduction here (that's what stackblitz link does):
```
git clone git@github.com:JLarky/astro-examples.git
cd astro-examples/src-dir-collections-bug
yarn
yarn ci
```

### Link to Minimal Reproducible Example

https://pr.new/github.com/JLarky/astro-examples/tree/main/src-dir-collections-bug?startScript=ci

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Ah I was able to get this working!

I think it's just happening because your `tsconfig.json` and `srcDir` are out of sync. `tsconfig.json` was including all files in your project rather than just files inside of `srcDir`. Notice that Astro logs "No content directory found. Skipping type generation" because the `content/` directory would need to be _inside_ the `srcDir` (at `src/newRoot/content`), but the TypeScript errors are coming from _outside_ the `srcDir`. After moving the entirety of the Astro project inside of `src/newRoot/`, everything works as expected and `astro:content` is properly typed.

It's unlikely that we'll supported nesting Astro projects within each other, unless there's a valid use case we're not aware of.
