### ISSUE TITLE
Rendered <Content/> from collections is not translating (astro-i18n)

### ISSUE THREAD

**Issue by narduin** [withastro/astro#7133]
### What version of `astro` are you using?

2.5.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

any

### Describe the Bug

Hello!

I've been using [astro-i18n](https://github.com/Alexandre-Fernandez/astro-i18n) to handle translations on my website.

Until `astro@2.4.3` I was able to translate everything properly. From markdown imports to content collections.  
However, since `astro@2.4.4`, something changed that led to the `<Content />` not displaying properly. The frontmatter is ok, the `post.data.body` is ok but the rendered markdown is not updating on the actual page.

I opened [an issue](https://github.com/Alexandre-Fernandez/astro-i18n/issues/34) on the astro-i18n repo and despite some changes from the developer @Alexandre-Fernandez, it's still not working as before `2.4.4`.

We think it might be coming from astro rather than astro-i18n.
It's possible to use [`const content = await Astro.__renderMarkdown(article.body)`](https://github.com/Alexandre-Fernandez/astro-i18n/issues/34#issuecomment-1554281614) as a workaround.

Thanks a lot for any explanation :)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8n8f61?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Alexandre-Fernandez** [comment]
To clarify, we're getting the correct content object back (`{id, slug, body, ...}` but when using the `render` function it returns the wrong data (data that belongs to another content object).

**Comment by bholmesdev** [comment]
Hey @Alexandre-Fernandez! It looks like this is due to a slug collision in your app, where you've mapped `slug` to `test` for _both_ internationalized entries. We switched to using slugs for lookups in our `getCollection()` helper since `getEntry()` relies on slugs as well, and we intended for slugs to be unique when implementing the feature. I admit we should have clear warnings whenever the same slug is used by multiple entries.

To fix this, you'll need to remove the `slug` property from your frontmatter and chop off the languages during route generation instead. I understand this may be frustrating, and I'll be taking a look at our slug and routing story in the next major version.

**Comment by Alexandre-Fernandez** [comment]
> To fix this, you'll need to remove the slug property from your frontmatter and chop off the languages during route generation instead. I understand this may be frustrating, and I'll be taking a look at our slug and routing story in the next major version.

Thanks for your reply, what do you mean by chopping off the languages during the route generation ?

**Comment by bholmesdev** [comment]
Understandable @Alexandre-Fernandez! I agree permalinks-as-identifiers is tough, since duplicate slugs _are_ possible. We really want to reshape slug resolution in the next version of Astro, so I wouldn't want to explore patches like an `id` property just yet.

As for "chopping off the languages," I meant manipulating the auto-generated slug where `getStaticPaths()` is called, if you're using static site generation. For example:

```ts
export async function getStaticPaths() {
  const pages = await getCollection('pages');
  return pages.map(p => ({
    params: {
      slug: p.slug.slice(p.slug.indexOf('/')), // remove /[locale]/ from start of slug
    },
    props: p,
  })
}
```
You can also use your own identifier that _avoids_ colliding with our own, like `permalink` instead of `slug`, and filtering on this instead.

**Comment by bholmesdev** [comment]
Closing for now, but I'll track this issue for future roadmap discussion. See https://github.com/withastro/roadmap/discussions/516

**Comment by Alexandre-Fernandez** [comment]
Any news on this issue @bholmesdev ?

**Comment by bholmesdev** [comment]
@Alexandre-Fernandez No updates as of now! We're planning to rework content collections in the coming months, but sadly don't have a roadmap yet. I'll update that GH discussion once we're ready to tackle it.
