### ISSUE TITLE
Child scss classes are stripped when passing down to another component?

### ISSUE THREAD

**Issue by braco** [withastro/astro#7249]
### What version of `astro` are you using?

2.4.1

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

yarn

### What operating system are you using?

mac

### What browser are you using?

chrome

### Describe the Bug

Can't target child elements when passing classes down through a component. Is this expected?

Example:

SomeComponent.astro
```
---
const { class: className } = Astro.props;
---
<div class={className}>
     <div class="child">I should be invisible</div>
</div>
```

Parent.astro
```
---
import SomeComponent from './SomeComponent'
---

<SomeComponent class="passthrough" />

<style lang="scss">
    .passthrough {
           // this works
           border: 1px solid black;
           // this is stripped out
           div {
               display: none;
           }
           // this is stripped out
           .child {
               display: none;
           }
     }
</style>
```

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by seansmyth** [comment]
Think this would be expected behaviour. You probably want to wrap the .child class in a :global wrapper for this to work.

**Comment by bluwy** [comment]
Yeah this is expected behaviour. The `.child` class is scoped as `.passthrough:where(.astro-ABC123) .child:where(.astro-ABC123)`. The `astro-ABC123` class is passed down the the component root, but not the children, hence the style isn't applied to the children.

Using `:global` would be the easier way to fix it. Otherwise you'd have to regex match the special class from `className` and pass it down, which isn't a nice scoping pattern.
