### ISSUE TITLE
Solid components break with imports in monorepo

### ISSUE THREAD

**Issue by QuentinDutot** [withastro/astro#7267]
### What version of `astro` are you using?

2.5.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Edge

### Describe the Bug

In a monorepo with an astro app and a solidjs lib, importing a solidjs component from the lib break the component importing it.

Steps to reproduce in the reproducible example:

**pnpm i => pnpm dev/start => open the browser**

- find the error in the console `Uncaught (in promise) ReferenceError: React is not defined`
- clicking the button has not effect (should print hello world in the console)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-nj39de

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Brendonovich** [comment]
I've been experiencing this too.
I have `@macrograph/web`, an Astro app, and some packages like `@macrograph/core` and `@macrograph/interface` that export Solid components. Loading said components works fine, but when loading components from third party dependencies like `@modular-forms/solid` the `React is not defined` error is produced. (It doesn't happen during build since I `client:only` the Solid components).
Repo: https://github.com/Brendonovich/macrograph/tree/astro
Run the `web` app on the `astro` branch and it should happen.

**Comment by Brendonovich** [comment]
This may actually be a problem with Vite or `vite-plugin-solid`, as I've been experiencing this same problem when using standalone Vite + Solid

**Comment by Brendonovich** [comment]
Managed to fix this by adding a `solid` export condition to one of my packages. I'm not entirely sure how/why it works but vite-plugin-solid seems to look out for it according to [this issue](https://github.com/solidjs/vite-plugin-solid/issues/97).
Here's [the file](https://github.com/Brendonovich/macrograph/blob/astro/interface/package.json)

**Comment by bluwy** [comment]
Yeah this seems like a general publishing issue with Solidjs. Solid libraries need special care in Vite so that its internal JSX files are processed correctly. A `solid` export would be the way to fix it. There's a heuristic here: https://github.com/solidjs/vite-plugin-solid/blob/2b37a130f9f2cbece9e27bbdce6b67f16424866f/src/index.ts#L312-L319
