### ISSUE TITLE
@astrojs/image doesn't generate images in build-time for static routes when output is "hybrid"

### ISSUE THREAD

**Issue by mhuretski** [withastro/astro#7334]
### What version of `astro` are you using?

^2.5.7

### Are you using an SSR adapter? If so, which one?

@astrojs/node

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

doesn't matter

### Describe the Bug

Hi, I'm having basically static site with a couple of API endpoints that doesn't return any html, so "hybrid" output is chosen.

Images are generated OK in build-time with "static" output.

But with "hybrid" images are generated dynamically, I don't have CDN, so response time for images is huge, it there a way to generate images during build-time with "hybrid" output for static routes?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wta3bp-ywb3ne?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
`@astrojs/image` is unmaintained in favour of `astro:assets`. This issue has been fixed in `astro:assets`.

**Comment by tony-sull** [comment]
`@astrojs/image` doesn't support hybrid rendering unfortunately.  `astro:assets` (still experimental) is it's replacement though and **does** handle hybrid mode properly, generating any images on `prerender`ed pages at build time.

It's worth noting that any images on SSR'd pages have to be generated dynamically since the build may not know about the needed images ahead of time.

For build times with dynamic images, `sharp` definitely helps compared to the default WASM-based image processor.  I think `sharp` is still Node-only for now, but if you're deploying to a Node environment it will build images quite a bit faster.

**Comment by matthewp** [comment]
`@astrojs/image` has been removed for 3.0 and won't be supported going forward. We recommend migrating to `astro:assets` which supports this and will be maintained going forward.
