### ISSUE TITLE
💡 RFC: Provide Service Worker integrations for State Management solution

### ISSUE THREAD

**Issue by L1lith** [withastro/astro#735]
### Background & Motivation

I see a large number of issues surrounding the state management between the backend rendering process and the client side.

Service Workers act in the background of the web application. They are capable of maintaining a constant state in memory even as pages are reloaded. They are also capable of implementing custom caches policies in order to make intelligent and awesome caching features. 

It would be nice if there was some kind of default service worker, or enable-able service worker that could have a host of useful features. As previously stated it could cache pages in a smart manner, or it could be the built in solution for state management, or it could even intercept requests in real-time in order to detect malicious requests (though this would be out of the scope probably). Another use case would be that we could have the service worker do things like automatically append the global html (see these issues here and here) to each html page the client requests. This would strip a significant amount of network load as it would save the user time every single time they navigate to another page.

It would also be possible to use service workers to do dynamic rendering of pages by storing the .astro source file client side, then hydrate the page with the state from the service worker. I'm unsure of the exactly performance implications as it would have to be measured, but this would allow the app to work offline, and would also allow the webpages to be dynamic without having to subscribe to javascript events on the "front-end". There could be some significant performance gains as the service worker could load the Astro.build binaries into memory once, then as long as the service worker is alive it wouldn't have to reload the Astro each time the page is loaded like a normal web application would have to. The Service worker could also connect to the webpage via WebSockets to provide live updates to the page. 

I know I've laid a lot of heavy technical jargon down but I think exploring many ideas is key to what makes Astro so great (namely developer ease, and high performance). I'm also willing to help contribute to the code if help is needed. 

There's been quite a large number of issues that I think this approach could address:
https://github.com/snowpackjs/astro/issues/506
https://github.com/snowpackjs/astro/issues/706
https://github.com/snowpackjs/astro/issues/694
https://github.com/snowpackjs/astro/issues/577
(probably more)

Additionally, there was [good reception](https://github.com/snowpackjs/astro/issues/682) about providing a browser extension for Astro.js. If there was a websocket connection made between the browser extension and the service worker it would make it possible to debug the client state very easily which I think could be an amazing feature for developers!

### Possible solutions
[Here's an example](https://github.com/L1lith/SWHell) of where I made a malicious service worker in JavaScript. I think the basic code layout is the same if you wanted to make a cool application, so it could be a good starting point to understanding what service workers are (though I would more strongly recommend reading the docs [here](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers)).

I would also like to propose my state library [Jabr](https://github.com/l1lith/jabr) for Astro's state management. I believe it is one of the cleanest and easiest state management APIs and it could be very easily integrated with Astro.

### Alternatives considered
Some kind of backend integrated solution could work, but it would end up putting more strain on the network and potentially more on the cpu due to repetitious requests. So I think that service workers would be the ideal place for client related state.

### Risks, downsides, and/or tradeoffs
It could increase initial page load, but this could be offsetted by rendering an initial html page first, then registering the service worker after, then loading the .astro file after that and letting the service worker handle additional renders for maximum performance. 

Another downside is the additional complexity that comes with service worker integrations.

### Open Questions
I have proposed a lot of technical jargon and new APIs. Though it might seem overwhelming, I think these APIs were developed for good reason. So my question is what hiccups & questions might the Astro team have in implementing something like this?

I have personally worked with these APIs and I think they're very cool, useful, and are genuinely useful tools despite being more complicated than traditional frameworks. If integration was made seamless to the developer I think Astro could really dominate the "web framework war", and I'd be willing to answer questions and provide support.

Thank you for hearing out my proposal 😊 

### Detailed Design

I kind of gave this information already, sorry it's kind of compact but I felt it was more relevant above.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

Edit: Another awesome benefit is that it would allow the application to operate offline!

**Comment by FredKSchott** [comment]
I'm generally +1 for this idea, but would want to better understand the first use-case where it would make sense to add that. Adding a service worker without understanding why sounds like a recipe for disaster! :)

Is there a specific user story that you have in mind, that this would solve for? I know you mention caching above, but I think the nice thing about Astro building static sites is that everything can be cached with proper CDN headers alone.

**Comment by okikio** [comment]
I feel like this heavily collides with Astro's "no js required" vision, imo, this should be handled by a renderer, this would reduce complexity and enables the complex caching systems required while avoiding needing to compile `.astro` files outside the build process. Another, possible idea is to use astro's service worker for astro's dev mode, and allow the user to create their own complex service worker setup based on a template for production.

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
