### ISSUE TITLE
Vite Vue Nested SFC is not working

### ISSUE THREAD

**Issue by louiss0** [withastro/astro#7396]
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

Chrome

### Describe the Bug

I have found a problem when using `vue-nested-sfc` I have found that It complains about an SSR module not being imported when using this library.   

## Steps to reproduce 

1. Click on the link
2. Wait for the server to start 

You'll see the error immediately. 

The page you are looking at will attempt to import three components from A file from `/src/components/Components.vue`

 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-3en7fb?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! I would recommend opening an issue on the [`vite-plugin-vue-nested-sfc`](https://github.com/HunYan-io/vite-plugin-vue-nested-sfc) repository and asking if they are interested in supporting Astro directly via out Integration API.

Plain Vite plugins are not expected to work for component compilation in Astro because we have a separate [`AstroRenderer`](https://docs.astro.build/en/reference/integrations-reference/#addrenderer-option) interface that enables multi-framework support in Astro.
