### ISSUE TITLE
sitemap does not respect build.format = "file"

### ISSUE THREAD

**Issue by 1619digital** [withastro/astro#7422]
### What version of `astro` are you using?

2.6.5

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

Hi, the sitemap plugin doesn't respect the 'file' type of build. To reproduce:

- `npm create astro@latest`
- add `page2.astro`
- set build format to `file` in astro.config.mjs
- ensure `page2.html` is being built
- `npx astro add sitemap`
- add a `site` to astro.config.mjs
- build

Here's the output of `sitemap-0.xml`, which is incorrect:

`<?xml version="1.0" encoding="UTF-8"?>
 ...
<url><loc>https://stargazers.club/</loc></url>
<url><loc>https://stargazers.club/page2</loc></url></urlset>
`

It looks like sitemap is inferring the file list using the `directory` build format.

Thank you! Love the project.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3v2ky8

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Sorry for the late reply! AFAICT, this output is correct.

With the default value of `format: 'directory'`, the trailing `/` is included in the URL (since `index.html` exists).

With the other value of `format: 'file'`, the trailing `/` is not included in the URL (since `page2.html` will be generated instead).

I'm not sure if we need another option for the sitemap integration to emit `.html` extensions? That's a hosting concern that we can't really control. But if Astro is used as the server, we do support "clean" URLs without the `.html`.

**Comment by ivoba** [comment]
@natemoo-re I also notice that urls, trailing slashs and extensions are not handled consistently/correctly in canonical urls/sitemaps and would reopen this ticket:

With `format: "directory"` the canonical url is
`<link rel="canonical" href="https://mysite.com/datenschutz/"> `
In the Sitemap it is:
`<loc>https://mysite.com/datenschutz</loc>`

With `format: "file"` the canonical url is:
`<link rel="canonical" href="https://mysite.com/datenschutz.html">`

In the Sitemap it is still:
`<loc>https://mysite.com/datenschutz</loc>`

I (and presumably Google as well) would expect that in the sitemap the canonical url would appear.
