### ISSUE TITLE
Vue SSR - data-v attributes are not stable, due to hash mismatch

### ISSUE THREAD

**Issue by ffxsam** [withastro/astro#7503]
### What version of `astro` are you using?

2.7.1

### Are you using an SSR adapter? If so, which one?

Node.js

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I discovered an issue with the Vue integration when using SSR.

Vue components have a unique + stable `data-v-*` attribute that's used for scoping styles (and maybe other purposes I'm not aware of). If a component references `import.meta.env.SSR`, during Astro's build process, Vite generates two separate `data-v-*` hashes because of the source code differences in a particular component. In one component (the client-side build):

```ts
const test = import.meta.env.SSR;
```

but in the server-side version:
```ts
const test = true;
```

See test reproduction link. Instructions:

```shell
$ pnpm i
$ pnpm build && pnpm preview
```
Then go to `http://localhots:3000` and toggle the component. Notice that the style fails to apply when the component is revealed after being hidden, due to the `data-v-*` attribute change.

### What's the expected result?

Not sure if it's possible, but perhaps the `import.meta.env.SSR` value should not evaluate on build.

### Link to Minimal Reproducible Example

https://github.com/ffxsam/repro-vue-attr-change

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Ah yikes. It makes a lot of sense that this happens! Vite always inlines the values of `import.meta.env.SSR` (and, in fact, any `import.meta.env.*` values).

You mentioned that you found a workaround for this on Discord, so I wanted to include that here for future reference.

```ts
// Create new `is-ssr.ts` file, use stable `isSSR` function everywhere
export const isSSR = () => import.meta.env.SSR
```

**Comment by natemoo-re** [comment]
I'm almost hesitant to mark this as a bug because this is a design limitation of Vite's environment variable processing and we probably won't be revisiting this pattern in the near term.

Maybe this is best left as a thing to document? Alternatively, we could potentially expose an `astro:env` module that exports `BROWSER` and `DEV` for clarity. I'd like to consider that for Astro 3.0

**Comment by bluwy** [comment]
I think this is caused by our env handling instead. We have this:

https://github.com/withastro/astro/blob/1a9b644e20b9ff1e8484aae3e97a9ee2fa81238c/packages/astro/src/vite-plugin-env/index.ts#L88-L91

which is likely processing the Vue file, but because we have `enforce: "pre"`, we're changing the file content before Vue transforms it.

Vite also has it's env replacement behaviour, but it's plugin is executed after the Vue plugin transform.

I agree though that maybe we should re-think env handling a bit. I find it confusing to explain at times too.

**Comment by ffxsam** [comment]
I did rule this out as being a Vite SSR issue. I fired up a Vue + Vite SSR project and replicated the same scenario, and the data-v attributes were stable throughout.

**Comment by basarozcan** [comment]
Is there a solution for that issue recently? It is a huge blocker for companies who are using scoped styles inside components. How can we apply workaround @natemoo-re

**Comment by ffxsam** [comment]
@basarozcan You can use this as a workaround, like I am:
```ts
/**
 * This is a hack/workaround for this issue:
 * https://github.com/withastro/astro/issues/7503
 *
 * Basically, during build time, Vite builds client-side and server-side code.
 * On the server side, import.meta.env.SSR is being evaluated at build time to
 * true. This results in different source code hashes for the same file, and
 * that hash is used for Vue components' data-v attributes. This causes
 * hydration problems if the component is hidden and re-mounted.
 */
export const isSSR = () => import.meta.env.SSR;
```
