### ISSUE TITLE
Content collections not being added to sitemap

### ISSUE THREAD

**Issue by clarkmcc** [withastro/astro#7524]
### What version of `astro` are you using?

2.5.0

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I'm generating sitemaps using @astrojs/sitemap and it works great but none of my content collections are being added to the sitemap. Is there something special I need to do for that?

Here's my `astro.config.mjs`

```mjs
import { defineConfig } from 'astro/config';
import vercel from '@astrojs/vercel/edge';
import tailwind from "@astrojs/tailwind";
import react from "@astrojs/react";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";

export default defineConfig({
  output: 'server',
  adapter: vercel(),
  site: 'https://www.printtrackerpro.com/',
  integrations: [tailwind(), react(), mdx(), sitemap()],
  server: {
    host: true
  }
});
```

### What's the expected result?

Sitemaps would contain the slugs to each of my blogs posts contained in the content/blog/**.mdx files.

### Link to Minimal Reproducible Example

https://github.com/printtracker/landing

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by clarkmcc** [comment]
I've got to say, I've used Astro on two projects now, and it's been an absolute joy to use. I'm not a huge fan of fullstack web development, but Astro makes it an absolute delight.

**Comment by natemoo-re** [comment]
Thanks for the kind words! Glad you're enjoying Astro so far!

Unfortunately, there's not a feasible way for our Sitemap extension to support dynamically server-rendered routes. If the `/blog/[...slug]` route is always generated from a matching Content Collection, you could definitely consider [prerendering](https://docs.astro.build/en/guides/server-side-rendering/#enabling-ssr-in-your-project) this route! Then all the pages that a generated at build time will automatically be added to the sitemap, because we know exactly which pages exist before the sitemap is generated. Hope that helps!

**Comment by clarkmcc** [comment]
That's exactly what I needed! For future reference:

`content/blog/[...slug].astro`
```js
export async function getStaticPaths() {
  const blogs = await getCollection("blog");
  return blogs.map(({ slug }) => ({ params: { slug } }));
}
export const prerender = true;
```
