### ISSUE TITLE
define:vars does not work when using dynamic tags

### ISSUE THREAD

**Issue by KubaSzopa** [withastro/astro#7534]
### What version of `astro` are you using?

2.7.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Setting dynamic tag like: `const Element = shouldBeButton ? 'button' : 'div'` and than using it on the top level: ` <Element>Some Text</Element>` of the html causes define:vars to not work. There is no style="--myVar: value" inside `button` or `div` element.

### What's the expected result?

Astro should render chosen element with style="--myVar: value" attribute. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/astro-minimal-example-custom-tags

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Hmm, this is a tough one because of the way `define:vars` has to work for static analysis/bundling. If we injected `style="--myVar: value"` into every component, we'd end up with framework components that receive unexpected props. At compile time, we have no way of knowing that `Element` is a plain element like `button` or `div` and not, say, a complex React component.

There are two workarounds here, though I know they're not ideal. Either wrap the children of `Element` with a static tag like `div`, or manually add a `` style={`--myVar:${value}`} `` attribute to `Element`.

**Comment by natemoo-re** [comment]
I don't think we have any plans to fix this as of now, so I'm going to close this. Please consider using the workarounds I mentioned above!
