### ISSUE TITLE
Named Slots in MDX with Layout via Frontmatter

### ISSUE THREAD

**Issue by kinostl** [withastro/astro#7547]
### What version of `astro` are you using?

^2.7.2

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Linux 6.2.16-2-MANJARO

### What browser are you using?

Firefox 114.0.1

### Describe the Bug

When I create a layout with named slots and use MDX's Frontmatter to apply a Layout to it, such as in the example below, named slots in the layout do not recognize the named slots from the MDX file.

```html
---
layout: ../layouts/ThreeBarLayout.astro
---

# Three Bar Test

If named slots are working, there should be three columns underneath this.

<div slot="left">Left Sidebar Column</div>
<div slot="center">Center Column</div>
<div slot="right">Right Sidebar Column</div>
```
If the MDX file uses the more traditional import + <Layout> tags method, named slots work as expected, but a Layout called in this manner does not have access to MDX utilities such as the heading array.

https://github.com/withastro/astro/issues/4610 addressed a similar issue, focusing on the Layout tag method. This ticket focuses on the Frontmatter experience.

### What's the expected result?

**Expected result** Named Slots in Layouts should work when called by MDX's Frontmatter. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-w4kstp?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'm not sure if this feature request is possible for us to implement at the moment. I'm guessing it would be quite an engineering effort to pull off. We don't currently support "slot bubbling" from the rendered result of a component, which is very similar to this.

Since there hasn't been any discussion on this, I'm going to close this issue in an effort to keep our issues actionable for the dev team. Please feel free to start a discussion [on our Roadmap](https://github.com/withastro/roadmap) so that other can weigh in!
