### ISSUE TITLE
Prism not defined when rendering a Markdoc page with Prism

### ISSUE THREAD

**Issue by juliusdotdev** [withastro/astro#7795]
### What version of `astro` are you using?

2.9.3

### Are you using an SSR adapter? If so, which one?

Vercel Edge

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Situation: I deployed my website to Vercel, using the Vercel adapter to deploy on the edge runtime. In my Astro config I have an integration for sitemap, prefetch, tailwind and markdoc.

This is my Astro config:
```typescript
import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";
import prefetch from "@astrojs/prefetch"; 
import tailwind from "@astrojs/tailwind";
import markdoc from "@astrojs/markdoc";
import vercel from "@astrojs/vercel/edge";

// https://astro.build/config
export default defineConfig({
  site: "https://julius.dev",
  output: "server",
  compressHTML: true,
  integrations: [sitemap(), prefetch(), tailwind(), markdoc()],
  adapter: vercel(),
});
```

This is my markdoc config:
```typescript
import { defineMarkdocConfig } from "@astrojs/markdoc/config";
import prism from "@astrojs/markdoc/prism";

export default defineMarkdocConfig({
  extends: [prism()],
});
```

After deployment, when I open a page deployed on Vercel that was generated from an .mdoc file, I see a blank screen. In the errors logs, I get this error message:

```
03:31:11 PM [ssr] ReferenceError: Prism is not defined
    at (entry.mjs:135:45476)
    at (entry.mjs:135:48462)
    at (entry.mjs:135:48537)
    at (entry.mjs:135:50353)
    at (entry.mjs:134:46590)
    at (entry.mjs:134:46452)
    at (entry.mjs:134:46436)
    at (entry.mjs:134:46616)
    at (entry.mjs:134:47395) (x2)
```

### What's the expected result?

The renders the content from the corresponding .mdoc file

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-deu1an?file=src%2Fcontent%2Fconfig.ts

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by juliusdotdev** [comment]
Also I get this warning during builds:

```
[WARNING] Ignoring this import because "node_modules/@markdoc/markdoc/dist/index.mjs" was marked as having no side effects [ignored-bare-import]

    dist/chunks/init.1e802469.mjs:10:7:
      10 │ import '@markdoc/markdoc';
         ╵        ~~~~~~~~~~~~~~~~~~
```

**Comment by natemoo-re** [comment]
Looks like you're using `output: "server"` but the `blog/[...slug].astro` and `blog/index.astro` route are not prerendered. Is that intentional? Because you're deploying to the edge, I'm guessing that Prism isn't being bundled properly for non-Node environments.

Prerendering these pages _should_ fix the problem. I'm not sure if supporting Prism on edge deployments is in scope at the moment.

**Comment by matthewp** [comment]
We have deprecated the Vercel Edge and Netlify Edge adapters due to compatibility issues (like the one you are experiencing here) and are encouraging people to instead use the serverless versions of these adapters, along with Edge Middleware, which we feel gives you the best of both worlds. Our adapter migration plan is laid out in this [roadmap issue](https://github.com/withastro/roadmap/discussions/631).

If you're still interested in deploying to these edge platforms I'd encourage you to build an adapter for it. You can use the edge adapter code as a starting point.

Closing as we are not planning on fixing edge adapter bugs (but will continue to support edge middleware).
