### ISSUE TITLE
no way to access context object from netlify edge functions

### ISSUE THREAD

**Issue by mayank99** [withastro/astro#7863]
### What version of `astro` are you using?

2.9.5

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Firefox

### Describe the Bug

consider this edge-rendering config (everything on edge):
```js
import { defineConfig } from 'astro/config';
import netlify from '@astrojs/netlify/edge-functions';
export default defineConfig({ output: 'server', adapter: netlify() });
```

since everything runs on edge functions, all routes _should_ have access to the [Netlify Context object](https://docs.netlify.com/edge-functions/api/#netlify-specific-context-object) but they don't.

the only mention of this in docs is under the the [edge middleware section](https://docs.astro.build/en/guides/integrations-guide/netlify/#pass-edge-context-to-your-site), but that requires rendering using regular serverless functions.

### What's the expected result?

either the netlify context object should be available directly, or it should be possible to create edge middleware to populate locals for edge-rendered routes.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fhwdyg

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
We have deprecated the Vercel Edge and Netlify Edge adapters due to compatibility issues and are encouraging people to instead use the serverless versions of these adapters, along with Edge Middleware, which we feel gives you the best of both worlds. Our adapter migration plan is laid out in this [roadmap issue](https://github.com/withastro/roadmap/discussions/631).

If you're still interested in deploying to these edge platforms I'd encourage you to build an adapter for it. You can use the edge adapter code as a starting point.

Closing as we are not planning on fixing edge adapter bugs (but will continue to support edge middleware).

**Comment by mayank99** [comment]
just a nit: these issues should probably be closed as "Not planned"
