### ISSUE TITLE
Redirects don't preserve URL.searchparams

### ISSUE THREAD

**Issue by xriter** [withastro/astro#7890]
### What version of `astro` are you using?

2.9.6

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

When using Redirects, the potential `URL.searchParams` don't get transferred over.

So, when you have:
```
// astro.config.mjs
export default defineConfig({
  redirects: {
    '/find': '/search',
  },
});
```

I would expect `/find?q=myquery` to be redirected to `/search?q=myquery`.
However, it redirects to `/search`, and the searchParams get lost.

### What's the expected result?

-

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5ex6dw?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
This is an interesting one. When the redirect is handled server-side, the `searchParams` should definitely be maintained. That should be straightforward to fix if anyone wants to open a PR.

I'm not sure if there is a way to maintain `searchParams` with the `static` output though, since we're generating an `.html` file that does the redirect client-side. Also `Astro.url` won't have `hash` or `searchParams` in that case. Just calling that out since your Stackblitz example wasn't using `output: 'server'`.

**Comment by ematipico** [comment]
I'm not sure the URL Paramus should be preserved as is. 

Usually, when set redirects with services like nginix or Apache, the redirect or URL params must explicitly be set via syntax.

I think we should do the same in Astro.

**Comment by ematipico** [comment]
Netlify and Vercel are very limited, although this doesn't mean we should be limited too. Many people use our `Node.js` adapter, and there we can redirect query parameters. Still, this should be an opt-in **feature**, and **not a bug**.

Reasons:
- people might want to move a query parameter in the new URL

	```js
	// astro.config.mjs
	export default defineConfig({
	  redirects: {
	    '/find?<search-term>': '/search/<search-term>',
	  },
	});
	```
- people might **not want** to pass the query parameter in the new URL
- people might want to change the name of the new query parameter
	```js
	// astro.config.mjs
	export default defineConfig({
	  redirects: {
	    '/find': {
			destination: '/search',
			queryParams: {
				query: "search-term" // will change ?query=something to ?search-param=something
			}
		}	
	  },
	});
	```

AWS Amplify doesn't do redirects of query parameters out of the box, but it provides the syntax to do it: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#query-strings-and-path-parameters

**Comment by natemoo-re** [comment]
I think this conversation should probably move to our [`roadmap`](https://github.com/withastro/roadmap/discussions) repo since we'll have to treat is as a new feature. Definitely a change we'd be in support of, but we'll have to design the API and decide on syntax and limitations.

Please feel free to link back to this issue!
