### ISSUE TITLE
Exponential bloat in prop serialization

### ISSUE THREAD

**Issue by belluzj** [withastro/astro#7978]
### What version of `astro` are you using?

2.10.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

When passing deeply nested JSON data to a client-side component (e.g. Vue) using client:load, the serialization of the props creates a quadratic amount of quote escaping with each level of nesting. 

See this repository reproducing the issue: https://github.com/daltonmaag/astro-prop-bloat-report/blob/main/src/pages/index.astro

Screenshot: 
![image](https://github.com/withastro/astro/assets/3616772/7bdc3fc3-d602-423d-91f0-da1ff6e3be43)

One can see on the screenshot that as the length of the JSON data in bytes increases linearly (second column) the length of the contents of the props="..." HTML attribute from Astro doubles from one line to the next.

The open devtools below shows that the quote escaping is the culprit.

### What's the expected result?

The length in bytes of the Astro props should be linearly proportional to the size of the input data.

### Link to Minimal Reproducible Example

https://github.com/daltonmaag/astro-prop-bloat-report

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Ah this is a great argument for moving these props out of the quoted `props` attribute and into a [`<script>`](https://github.com/withastro/roadmap/discussions/635) element, which is a proposal that I see you've already commented on!

Given this bloat problem, I would definitely consider this an important design change rather than a brand new feature. Since we're working on Astro 3.0 at the moment, that seems like a good time to make this change. Would you want to submit a PR against the in-progress [`next`](https://github.com/withastro/astro/tree/next) branch?

Here are the areas I imagine we need to update:
- The [`serializeProps` function](https://github.com/withastro/astro/blob/main/packages/astro/src/runtime/server/serialize.ts#L112-L115) currently generates JSON data that suffers from this bloat problem. This could be updated to generate a string of JavaScript that is written to an inline `script` element. Note that the generated `script` element should remain an inline (classic) script, because hydration should occur during streaming rather than be delayed until `type=module` scripts are executed.
- The corresponding [`serialize.test.js`](https://github.com/withastro/astro/blob/main/packages/astro/test/serialize.test.js) should be updated to verify this new format.
- The [`props`](https://github.com/withastro/astro/blob/main/packages/astro/src/runtime/server/hydration.ts#L158) attribute is added to `astro-island` during rendering. This should instead be injected as a `script` element that is a child of `astro-island`.
- The `astro-island` custom element currently [tries to parse the `props` attribute](https://github.com/withastro/astro/blob/main/packages/astro/src/runtime/server/astro-island.ts#L134-L136). Instead it should read from the `script` element.

**Comment by belluzj** [comment]
Thanks for the pointers, I'll have a look at these functions. However, I think there are two issues that can be solved separately (I'll have a deeper look to confirm):
1. the JSON data gets JSON.stringify-ed too much (in theory it should require only 1 JSON.stringify at the top-level instead of 1 at each level). That first problem creates the quadratic amount of `\\\\`, which is quite bad because it inflates the size of data a lot.
2. What is pointed out in the discussion: putting JSON into an HTML attributes forces all the double quotes `"` to be written as `&quot;`. That makes double quotes take 6 bytes instead of 1, but it's a linear bloat, so it's less urgent to fix.

Since we're using Astro for an upcoming website and would like to benefit from a fix to 1., would it be OK for me to look into fixing this one first, in the current version 2?

**Comment by belluzj** [comment]
I opened a PR #7995 that fixes point 1. above, I believe in a way that should be transparent to users, so maybe it doesn't warrant a major version bump? I haven't looked into point 2. and if that's OK I would rather leave it to someone else to look into?

Let me know if you have any feedback on the PR, thanks in advance :)

**Comment by belluzj** [comment]
I misspoke about "quadratic", it's actually exponential, because it doubles each time you add one level of nesting. Here is a screenshot showing that at 24 levels the HTML code for this line of JSON is 100MB 
![image](https://github.com/withastro/astro/assets/3616772/0e47da4c-0ac2-48dc-bc80-ad0b07e74fe7)

**Comment by natemoo-re** [comment]
Thanks for the PR and the explanation. I agree that this requires a more immediate fix, and maybe revisiting our approach entirely for v3.0.

Your PR will be reviewed today!

**Comment by natemoo-re** [comment]
Going to close this since the immediate issue has been fixed in https://github.com/withastro/astro/pull/7995.

We're still tracking https://github.com/withastro/astro/pull/8004 for an even more efficient format in 3.0!
