### ISSUE TITLE
difference between dev/build regarding non-esm libraries

### ISSUE THREAD

**Issue by y-nk** [withastro/astro#7994]
### What version of `astro` are you using?

2.10.3

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

stackblitz

### What browser are you using?

stackblitz

### Describe the Bug

When using a non-esm module, the dev server runs fine, but the build crashes.

### What's the expected result?

a consistent behavior accross dev/build. either it works everywhere, either nowhere.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-q7xxew?file=src/pages/index.astro,src/components/Test.tsx

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Bundling for non-ESM projects is a Vite issue. The fix is usually to add the problematic packages to `vite.ssr.noExternal` in your config, which will force them to be bundled.

```
vite: {
  ssr: {
    noExternal: ['react-use']
  }
}
```

Obviously we would like dev/prod to be consistent all the time, but it's unfortunately not how Vite is designed at the moment, so there's not much we can do on our end.

**Comment by y-nk** [comment]
thanks @natemoo-re i realize this as you pointed out the solution to me. sorry for raising this here
