### ISSUE TITLE
MDX variable headings display badly in TOC

### ISSUE THREAD

**Issue by VojtaStruhar** [withastro/astro#8240]
### What version of `starlight` are you using?

0.7.3

### What version of `astro` are you using?

2.10.5

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

If I put a javascript variable as a heading in MDX, it looks fine on the page, but bad in the sidebar:

```mdx
export const variableName = "Javascript heading";

## {variableName}
```

Results in **Javascript heading** written on the page, but `variableName` in the sidebar.

<img width="984" alt="Screenshot" src="https://github.com/withastro/starlight/assets/49688205/e8501e19-4da1-4067-aba9-7cae709768f8">

With a function that returns a string, it writes something like `functionName` in the sidebar - but again works well on the main page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-i3eo86?file=src%2Fcontent%2Fdocs%2Findex.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
I'm not sure where we ever ended up on this. I think at one time @bholmesdev had fixed this logic, but I might not be remembering correctly. It's possible that this is just a limitation of using MDX.

We'll check and keep this issue updated!

**Comment by delucis** [comment]
Thanks Nate — I think we _may_ have had this working in Astro-Flavored Markdown back in the day, but never in MDX? It’s not impossible to support, but likely convoluted and any solution I can imagine does risk conflicting with user-defined plugins.

Question for @VojtaStruhar: what’s your use case for variable headings? Curious what need you have that makes them necessary in case that helps us understand a better fix.

**Comment by VojtaStruhar** [comment]
@delucis Thanks for the question. I wanted to use MDX for generating content. Let's say reading the file system to list all plugins present in a project. It works perfectly fine, but the headings haven't been put into TOC. This led me to try to mess around with generating headings and consequently I tried this _JS heading thing_.

The idea was that I could have

- documentation (by hand)
- generated heading (JS function)
- generated content (JSX)
- documentation (by hand)

In the TOC I thought I'd settle for a single heading to mark the section (because the JSX stuff doesn't appear at all). And again - _on the page itself_ it works and looks fine! But in the TOC just the name of the function shows.

By now I'm very confused when exactly does the TOC processing happen 😄

**Comment by bholmesdev** [comment]
Thanks @VojtaStruhar! Sorry for the radio silence here. I looked at the source code and it seems  we evaluate JSX expressions when they reference frontmatter properties, but _not_ when they reference MDX variable exports:

```md
---
title: My Title With Appear in TOC
---

export const variable = "But this won't!"

# {title}

## {variable}
```

This is because frontmatter is processed before Markdown is rendered, but MDX exports are resolved at the final rendering step. To answer your question on what runs when:
1. YAML frontmatter is resolved
2. Remark plugins are run over Markdown tree
3. Rehype plugins are run over HTML tree (**this is where the TOC is generated!**)
4. MDX JS expressions are rendered

We collect headings as part of the rehype process so users can apply their own rehype plugins to customize headings before or after the TOC is generated. If we wait for the MDX postprocessing step, this feature is lost.

I won't say this is impossible though! Now that I'm seeing our JSX expression resolver, I think a userland plugin could achieve this at least. I'm unfortunately pulled away from Astro core through the end of the year but I'll forward this along to the team. You're also welcome to [explore the source code here](https://github.com/withastro/astro/blob/main/packages/markdown/remark/src/rehype-collect-headings.ts#L43-L45) if you want to try a fix.

**Comment by bholmesdev** [comment]
Closing this as a "will not fix" due to inactivity and potential userland fix
