### ISSUE TITLE
The theme from https://astro.build/themes is unable to be built locally or deployed on Netlify or Vercel.

### ISSUE THREAD

**Issue by coolburly** [withastro/astro#8286]
### Astro info

```block
Astro version            v2.10.15
Package manager          npm
Platform                 darwin
Architecture             arm64
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind, @astrojs/svelte
```

### What browser are you using?

Chrome

### Describe the Bug

I was trying out this theme from the Astro themes library:

https://astro.build/themes/details/astro-shopify/

It can run on localhost port 3000, but I'm unable to run "npm run build". After running this command, the dist folder briefly shows up before disappearing again, even though the terminal prints "build complete".

I'm also unable to build it on Netlify or Vercel,  with the same error - the dist folder doesn't persist after the build.

### What's the expected result?

According to the documentation from Astro theme library, I should be able to run "npm run build" and "npm run preview" without issues.

### Link to Minimal Reproducible Example

can't reproducible in StackBlitz. I googled and tried contacting the developer of the theme but did not receive a response. Since the theme is listed in the Astro theme library, I carefully documented this issue and tried my best to provide as many details as possible. I am hoping someone can point out the cause of the error and how to resolve it, thanks.
### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by newtoallofthis123** [comment]
## The Problem is the adapter

Since you are using the vercel serverless adapter, you will be able to build it offline. However, you can download [Vercel CLI](https://vercel.com/docs/cli) using

```bash
npm i -g vercel
```
and run
```bash
vercel -dev
```
to open up a vercel development server [docs here](https://vercel.com/docs/cli/dev) .

However, I suggest you just use Astro in development mode

```bash
npm run dev
```

The problem is that you are trying to build locally while using the vercel's severless adapter. 
The adapter is configured to only run in vercel.  

## Will it work when you deploy

When you deploy using vercel, it will absolutely work. So don't worry. Since you are using SSR, you can't build locally and preview.

**Comment by matthewp** [comment]
Thank you for taking the time to thoroughly explain @newtoallofthis123 !

**Comment by coolburly** [comment]
excellent, thanks a lot! @newtoallofthis123

**Comment by newtoallofthis123** [comment]
Hope it worked 😄
