### ISSUE TITLE
Astro v3 pnpm build fails, symlink

### ISSUE THREAD

**Issue by pijusz** [withastro/astro#8312]
### Astro info

```block
yarn run v1.22.19
$ astro info

Astro version            v3.0.3
Package manager          pnpm
Platform                 win32
Architecture             x64
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/prefetch, @astrojs/react, @astrojs/tailwind, astro-robots-txt
```

### What browser are you using?

Chrome

### Describe the Bug

When building Astro v3 on Windows NVM and on Vercel:
With pnpm packages and node v18.17.1:
``` error   EEXIST: file already exists, symlink '.pnpm/react@18.2.0/node_modules/react' -> '/vercel/path0/.vercel/output/functions/entry._slug_.astro.func/node_modules/react'
Error: EEXIST: file already exists, symlink '.pnpm/react@18.2.0/node_modules/react' -> '/vercel/path0/.vercel/output/functions/entry._slug_.astro.func/node_modules/react'
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1
```
with yarn and node v18.17.1 - works

### What's the expected result?

pnpm is able to build Astro v3 with vercel serverless on node 18+

Stackblitz example seems to work

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gmnscw

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
I also have the issue locally with the following env:
- OS: Win 11
- Node: 18.14.1 (nvm)
- PNPM: 8.7.0

**Comment by newtoallofthis123** [comment]
I was facing a similar issue from `pnpm`, the issue was solved by switching to `npm`

**Comment by raulfdm** [comment]
Can someone add a repository to reproduce it? I'm trying to convert to a minimal and scoped project but no success.

**Comment by pijusz** [comment]
Someone else managed to reproduce, but it works for me. Might need to have static routes with react components:
"but in my case specifically, I got the slug error at an updates page of mine, which is a react component "
Other one, which works for me though
![image](https://github.com/withastro/astro/assets/20190386/eaee76c9-4c9f-4b66-9ca3-bb3f25d2d8b5)


Will try to make reproduction tomorrow if none else comes in.

**Comment by lilnasy** [comment]
Here's that screenshot in better quality.

https://cdn.discordapp.com/attachments/1146475239967047680/1146729067962433617/image.png

It is worth noting that I got a different error (EPERM). And pijusz was not able to reproduce any error when following the steps i followed on their machine.

**Comment by Princesseuh** [comment]
I'm taking a look but I kinda barely have access to a Windows machine and I definitely can't reproduce locally on macOS so, this might be a bit complicated. Thank you everyone for sharing information

**Comment by florian-lefebvre** [comment]
Feel free to ask for more details if needed 👍

**Comment by Princesseuh** [comment]
Could anyone try with `vercel({ functionPerRoute: false })` in their config?

**Comment by raulfdm** [comment]
> Could anyone try with `vercel({ functionPerRoute: false })` in their config?

Setting `functionPerRoute: false` avoids the problem 🤔

**Comment by Princesseuh** [comment]
Okay so, I spent the last 4-5 hours on this, I.. don't know. Here's what I found:

- The bug is in this code: https://github.com/withastro/astro/blob/af41b03d05f8a561990de42ccc93663343da2c0d/packages/integrations/vercel/src/lib/fs.ts#L61-L85
- This only affects `pnpm` because it's inherently a symlink issue, or at least, the issue only happens in a code branch visited during symlink-related things
- On local macOS, everything works perfectly fine
- On local Windows, I can reproduce the permission issue. I'm not exactly sure it's really a permission issue per se, I'm wondering if it's not the folder being locked by something else for some reason, but as far as I could tell this is not the case.
- `functionPerRoute: false` only fixes some parts of this, the Windows issue can still happen even with it off (because the symlinking code still run)

Even though they happen in the same code, I feel like the Vercel issue and the permission issue are kinda unrelated, but then again I could only reproduce the permission issue in local.

All in all, I don't know. I'll pick this back up when I'm back to work tomorrow if someone didn't fix it before

**Comment by Princesseuh** [comment]
> Okay so, I spent the last 4-5 hours on this, I.. don't know. Here's what I found:
> 
> * The bug is in this code: https://github.com/withastro/astro/blob/af41b03d05f8a561990de42ccc93663343da2c0d/packages/integrations/vercel/src/lib/fs.ts#L61-L85
> * This only affects `pnpm` because it's inherently a symlink issue, or at least, the issue only happens in a code branch visited during symlink-related things
> * On local macOS, everything works perfectly fine
> * On local Windows, I can reproduce the permission issue. I'm not exactly sure it's really a permission issue per se, I'm wondering if it's not the folder being locked by something else for some reason, but as far as I could tell this is not the case.
> * `functionPerRoute: false` only fixes some parts of this, the Windows issue can still happen even with it off (because the symlinking code still run)
> 
> Even though they happen in the same code, I feel like the Vercel issue and the permission issue are kinda unrelated, but then again I could only reproduce the permission issue in local.
> 
> All in all, I don't know. I'll pick this back up when I'm back to work tomorrow if someone didn't fix it before

**Comment by raulfdm** [comment]
@Princesseuh I use Mac and I'm able to reproduce in my own repository. The problem is that it's bloated with a bunch of personal things, API tokens setup, etc.

I'm gonna try to clone it and prune all the unnecessary things until I have a smaller reproducible version and I'll come back to you.

**Comment by matthewp** [comment]
I wasn't able to get very far into looking into this because I wasn't able to reproduce. If anyone can create a reproduction that would be wonderful.

@Princesseuh that code looks a bit race-conditiony so that would not surprise me of its the issue. One common mistake with fs code is checking if a file exists and then trying to write to it. Is that's what's happening with the copyFile? Do you know the exact line that throws? One solution would be to use a file handle instead of using the higher-level functions: https://nodejs.org/api/fs.html#fspromisesopenpath-flags-mode

But I don't know enough about what's happening here to know for sure. Just some pointers.

**Comment by lilnasy** [comment]
> Even though they happen in the same code, I feel like the Vercel issue and the permission issue are kinda unrelated, but then again I could only reproduce the permission issue in local.

They seem to be related. At least I think it's the same line of code that fails.

I can reproduce the EPERM, it goes away when I run as admin, but it would make sense that the same line fails on a later attempt to create a symlink because it's already been created.

I think the reproduction for EEXIST would be a project with over 10 routes (and 10 attempts to symlink) like the one pijusz has locally.

<img width="574" alt="image" src="https://github.com/withastro/astro/assets/69170106/40bd0273-e75b-4a21-839b-4e65e3fcf515">

Screenshot from the discord thread. The message is being logged once per route. Subject of another issue #8321.

**Comment by pijusz** [comment]
With FunctionPerRoute disabled it works, well somewhat works.
I'm using React components with shadcn's navigation (Mobile and Desktop modals) with:
client:load and Mobile Nav also has: `client:media="(max-width: 1024px)"`
In preview I get 2 console errors (in dev mode it works):
"SES_UNHANDLED_REJECTION: TypeError: error loading dynamically imported module: URL"
And then "Loading module from “URL” was blocked because of a disallowed MIME type (“text/html”)."
React Components dont work.

**Comment by raulfdm** [comment]
Alright crew, I managed to create a reproducible repo based on my website. I've tried to prune almost everything not relevant til I get the error, but there are still tons of pointless code there.

- Repo: https://github.com/devraul/astro-3-pnpm-symlink-error
- Stackbltiz: https://stackblitz.com/github/devraul/astro-3-pnpm-symlink-error?file=README.md

Note: stackblitz uses node 16 and it won't work properly so clone it and run.

![CleanShot 2023-09-01 at 09 49 45](https://github.com/withastro/astro/assets/12464600/1dacc8ed-022b-4611-8993-73ddbd102c0c)

**Comment by ematipico** [comment]
Hi everyone, could you guys install `@astrojs/vercel@next--vercel-symbolic-link` and please check if that solves your issues? 

I tried the possible fix using @raulfdm 's repository, but it would be great to confirm that functions render on Vercel.

**Comment by raulfdm** [comment]
@ematipico I tried in my official repository and the `next--symbolic-link`  worked fine:

![CleanShot 2023-09-01 at 15 18 20](https://github.com/withastro/astro/assets/12464600/1e32134e-ce66-4233-8237-7bad9149b735)

**Comment by raulfdm** [comment]
It worked also on Vercel infra... unfortunately:

![image](https://github.com/withastro/astro/assets/12464600/f72f93a4-663a-4455-a2b6-d3549baf33da)

But that's fine, at least it's working...

**Comment by ematipico** [comment]
That's great news! (and a bad one 😅 )

**Comment by alireza-constantin** [comment]
had the same problem, fixed by adding `functionPerRoute: false`

**Comment by ivan2214** [comment]
You need to enable Windows Developer Mode so that Preconstruct can create symlinks - https://www.howtogeek.com/292914/what-is-developer-mode-in-windows-10/

This works for me 🫡

**Comment by David-Pena** [comment]
In my case I just changed to `yarn` as tried here by https://github.com/withastro/astro/issues/8312#issuecomment-1700728669
