### ISSUE TITLE
HTML Page rendered entirely in solid-js (or other component library) does not run client <script> unless there is a html tag using astrojs

### ISSUE THREAD

**Issue by btakita** [withastro/astro#8371]
### Astro Info

```block
Astro                    v3.0.7
Node                     v18.17.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/solid-js
```

### If this issue only occurs in one browser, which browser is a problem?

All

### Describe the Bug

When the HTML page is entirely rendered using a component library such as solid-js AND there is a client side `<script>`:

The client side `<script>` does not execute unless there is at least one of a set of standard html tags (`<div>`, `<span>`) rendered using the astrojs renderer. A custom tag & some standard html tags (e.g. `<template>`) will not cause the client-side `<script>` tag to execute.

### What's the expected result?

The client side `<script>` tag should always execute.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-aeeasb?file=astro.config.mjs,package.json,src%2Fcomponents%2FPage.tsx,src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
Rendering the entire HTML page using a component library such as solid-js is not supported. Astro needs to at least render a `head` element so that we can properly inject the scripts needed for the islands to hydrate.

We don't have any plans of lifting this limitation, but if you'd like to [open a roadmap discussion](https://github.com/withastro/roadmap/discussions) to argue in favor of this feature, feel free to do so.
