### ISSUE TITLE
Abnormal Build Time When Used with Unocss

### ISSUE THREAD

**Issue by Alecyrus** [withastro/astro#8490]
### Astro Info

```block
Astro                    v3.0.12
Node                     v16.20.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

After using the new feature 'ViewTransitions' in Astro 3.0, when simultaneously using 'unocss', it takes more than 20 seconds during 'dev' or 'build', with a significant amount of time spent on building the client. However, without using 'ViewTransitions' or 'unocss', both 'dev' and 'build' processes are much faster.

### Reproduction
https://stackblitz.com/edit/withastro-astro-ptdkgl

1. run "npm run build", you will see it takes 19s to finish:
![image](https://github.com/withastro/astro/assets/13865581/f478edc0-5c7a-4f95-8db8-f2125f543a33)

2. then comment <ViewTransitions /> in BaseHead.astro or Unocss in astro.config.mjs, everything is fast as expected.
![image](https://github.com/withastro/astro/assets/13865581/aff13bb4-a1a1-4625-97cf-787eb1d96cf5)

### What's the expected result?

Build time shouldn't be this long

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ptdkgl

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Alecyrus** [comment]
https://github.com/unocss/unocss/issues/3103

**Comment by HummingMind** [comment]
+1

**Comment by ematipico** [comment]
This is really weird.

**Comment by rishi-raj-jain** [comment]
@Dunqing Shouldn't this be done in @unocss/astro?

**Comment by bluwy** [comment]
The reason we inline the sourcemap is noted at https://github.com/withastro/astro/blob/fca6892f8d6a30ceb1e04213be2414dd4cb4d389/packages/astro/src/core/compile/compile.ts#L37-L38 which is then passed through here https://github.com/withastro/astro/blob/fca6892f8d6a30ceb1e04213be2414dd4cb4d389/packages/astro/src/vite-plugin-astro/compile.ts#L34-L48

The result sourcemap generated from esbuild should combine the inline sourcemap, so _maybe_ the inline sourcemap can be stripped off after the esbuild compile.

---

There's also kinda more things regarding this:

1. Another way is to split the astro compile and esbuild transform as two different `transform()` hook so Vite/Rollup can combine the sourcemap itself.
2. Or maybe the esbuild transform can be remove altogether and configure Vite's `esbuild` option to parse `.astro` files too.
3. And the [MDX handling](https://github.com/withastro/astro/blob/fca6892f8d6a30ceb1e04213be2414dd4cb4d389/packages/astro/src/vite-plugin-mdx/index.ts#L108-L119) is still using inline sourcemap (that's related to above too)

The above are more "bigger picture" solutions, so if the first part above works I think it's good enough. And I think yeah this should be fixed in unocss, and any changes we can do to help with perf in general would be a nice to have.

**Comment by matthewp** [comment]
Looks like this was fixed yesterday: https://github.com/unocss/unocss/issues/3103
