### ISSUE TITLE
After upgrade to 3, astro check is scanning all files, ignoring eslint rules

### ISSUE THREAD

**Issue by jonyo** [withastro/astro#8548]
### Astro Info

```block
Astro                    v3.0.13
Node                     v18.17.1
System                   macOS (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/solid-js
                         @astrojs/tailwind
                         client:dom-load
```

### Describe the Bug

Running `astro check` after upgrading to astro `3.0.13` and after installing `@astro/check` version `0.2.0` it is now doing checks on all the files, including minified files, js, ts, tsx.

It also seems to ignore our eslint, typescript, etc rules - showing errors on lines that have comments above set to ignore the problem.

In the example, notice it is scanning the `some-file.ts` and showing a hint.

### What's the expected result?

When I run `astro check` I expect it to only check `*.astro` files (as it says it does in the docs for the command line).

I already have linters set up and tuned for other file types.

Either do not scan things as it says in the docs, or if it does, add some configuration option to control it so we can enforce the old behavior of only scanning *.astro files.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-s69bax?file=src%2Fsome-file.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
`astro check` now check all files that are included in your TypeScript project, so to ignore minified files, you can use the `exclude` setting in your `tsconfig.json`.

Ultimately, in the context of an Astro project, `astro check` is supposed to replace `tsc`, since the latter not only cannot process Astro files, but also cannot process .astro imports inside .ts(x) files, in addition to allowing us to support more Astro specific diagnostics.

We'll update the docs for it, sorry for the inconvenience!

**Comment by Princesseuh** [comment]
Closing as a duplicate of https://github.com/withastro/language-tools/issues/643

**Comment by JamesJosephFinn** [comment]
Hi @Princesseuh! I'm new to Astro, and setting up my first project. Running `astro check` shows `7 files` were checked. The CLI reference doesn't show a flag for verbose output, so I guess there's no way to know which files were checked? I'm asking because I have `// @ts-check` at the top of my `astro.config.mjs` file, but `astro check` didn't report this TS error:

```js
export default defineConfig({
	vite: {
		// @ts-expect-error
		plugins: [tailwindcss()],
	},
});
```

Without that `// @ts-expect-error`, the error is: `Type 'Plugin<any>[]' is not assignable to type 'PluginOption'.`

Thank you!
