### ISSUE TITLE
Pass class with className is not working

### ISSUE THREAD

**Issue by RogierdeRuijter** [withastro/astro#8622]
### Astro Info

```block
❯ astro info
Astro                    v3.1.2
Node                     v16.20.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, safari

### Describe the Bug

Passing a class to a component doesn't work properly. The color of the text should be red but it isn't.

### What's the expected result?

Color of text to be red.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-fwd5hv?file=src%2Fpages%2Findex.astro,src%2Fcomponents%2FMyComponent.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This doesn't work because `red` is scoped to your `index.astro`. If you add `is:global` to your style tag it would work. See this link for more details on how style are scoped: https://docs.astro.build/en/guides/styling/#scoped-styles

**Comment by RogierdeRuijter** [comment]
This pattern did work in 2.x. This stopped working in 3.x. I don't see this change in the Astro 3 change list. I'll get a reproduction up.

**Comment by Princesseuh** [comment]
It works in Astro 2.0 because the default [scoping strategy](https://docs.astro.build/en/reference/configuration-reference/#scopedstylestrategy) used a class, so by passing your classes around, you also passed the scoped class. If you update your config to use classes as a scoping mechanism in Astro 3, you get the same behaviour.

This is noted in this section: https://docs.astro.build/en/guides/styling/#passing-a-class-to-a-child-component

**Comment by RogierdeRuijter** [comment]
My bad. Thanks!
