### ISSUE TITLE
Cloudflare adapter update for node:crypto

### ISSUE THREAD

**Issue by jadbox** [withastro/astro#8784]
### Astro Info

Cloudflare now has initial support for `node:crypto` package. See:
https://developers.cloudflare.com/workers/platform/changelog/#2023-04-28

### If this issue only occurs in one browser, which browser is a problem?

all

### Describe the Bug

The package node:crypto should be allowlisted in the Cloudflare adapter excludes list. Note, it may be preferable to allowlist all of node:* packages as the module support changes very frequently, and each time the adapter requires an update and waiting period on a new release.

### What's the expected result?

Build fail for node:crypto but it's allowed now by wrangler

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ig3cma?file=src%2Fpages%2Findex.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by jadbox** [comment]
PR for fix with additional future proofing for future upstream issues: https://github.com/withastro/astro/pull/8787

**Comment by alexanderniebuhr** [comment]
@jadbox thank you for your contribution! Just a note, `node:crypto` is only supported since 14th September, while it is some time, it is not as long as you linked.

> Note, it may be preferable to allowlist all of node:* packages as the module support changes very frequently, and each time the adapter requires an update and waiting period on a new release.

I'm still against this. I laid out multiple times before, why I don't think it is a good idea to allowlist the `node:*` wildcard. I think it is more likely that we would go for the settings override solution, than for the wildcard.
