### ISSUE TITLE
404 for /_astro/* routes

### ISSUE THREAD

**Issue by ahmad-ali14** [withastro/astro#8809]
### Astro Info

```block
Astro                    v3.2.1
Node                     v20.4.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

I found multiple 404 for routes like `/_astro/*.js`, usually the * is replaced by some component name and hash, like: `GET  /_astro/SideBar.d5957c23.js`

I noticed the 404 increases between deployments, but how can I stop this?

I suspect it is a client component, that has the filename from the previous deployment. 

### What's the expected result?

I expect the filename to the route to stay identical between deployments, like removing the hash from the filename. 

I am also not sure where these calls are coming from, and how to deal with them if I want to put my entire application behind an auth wall. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qhuzp1

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Your reproduction doesn't work, it's missing dependencies.

**Comment by ahmad-ali14** [comment]
Astro retrieves front-end islands using GET requests like `/_astro/SignUpForm.6512ed03.js`.

The problem is the number that is added to the url is changing every build.

So if you loaded a page with `SignUpForm.65.js` island, and a deployment happened, a new file such as `SignUpForm.03.js` is created **on the server** and the old file no longer exists which breaks your page, unless you do a full refresh where the new file id is retrieved.


I mean there are pros and cons for each approach; can I configure astro to ignore the `.6512ed03` from `/_astro/SignUpForm.6512ed03.js` and just route to the latest file available with the pattern `SignUpForm.xxxxxxxx.js`?

**Comment by Princesseuh** [comment]
The hash is based on the content of the chunk, so the hash changes only when you actually have changes, in which case you do want your users to have the new content

**Comment by ahmad-ali14** [comment]
Yes, but the server in this case should route to the latest file instead of returning 404.

**Comment by bluwy** [comment]
The server should not route to the latest file, that file will have different contents and will break your site. The 404s are expected when deploying your site while your users are fetching your old site.

Different frameworks have different ways to approach this, including auto-refreshing when a difference is detected, service workers to check the status, etc. In general it's a hard problem to tackle without introducing more complexity.

Since Astro is only generating these files statically and mostly as an SSG framework, I think the current approach is good enough. You can ignore the 404 fails for `_astro/*` routes.
