### ISSUE TITLE
Astro + Svelte: importing interface into .svelte file breaks client js logic ( ambiguous indirect export: *)

### ISSUE THREAD

**Issue by ZorikovPasha** [withastro/astro#8859]
### Astro Info

```block
Astro                    v3.3.1
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/svelte
```

### Describe the Bug

Hi! I am stumbled upon an error which in a nutshell is that Importing an interface info .svelte file gets into runtime though its a ts thing. This error (`Uncaught (in promise) SyntaxError: ambiguous indirect export: IMainProps` - 
![image](https://github.com/withastro/astro/assets/86666268/c08a0e9b-86e8-4e83-9b74-d47bbcfa4888)
) breaks clientside js (onclick is not working, no alert is shown) . Please check out reproduction, its quite simple, thx.

### What's the expected result?

This should not get into runtime because its an interface import and client js logic should work)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-v1scde

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is not really a Astro bug, TypeScript (and bundlers) can't necessarily always tell if something is only a type vs a normal import. That's why [we recommend using type imports](https://docs.astro.build/en/guides/typescript/#type-imports) and all of our TypeScript presets have the option on to [warn you when you need to use a type import](https://github.com/withastro/astro/blob/c6e0d8e1cdf58e4cc797e86fb3cc4494e2111566/packages/astro/tsconfigs/base.json#L13-L14).
