### ISSUE TITLE
💡 RFC: Astro fails to compile a conditionally added attribute

### ISSUE THREAD

**Issue by jasikpark** [withastro/astro#886]
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

While working on using `aria-current="page"` I wasn't able to achieve an output like:

```tsx
<nav aria-labelledby="sidebar-site"> 
   <ul class="nav-groups">   
     {sidebar.map(category => ( 
       <li> 
         <div class="nav-group"> 
           <h2 class="nav-group-title">{category.text}</h2> 
           <ul> 
             {category.children.map(child => ( 
               <li class="nav-link"><a href={`${Astro.site.pathname}${child.link}`} {`${currentPage === child.link ? 'aria-current="page"' : ''}`}>{child.text}</a></li> 
             ))} 
           </ul> 
         </div> 
       </li> 
     ))} 
   </ul> 
 </nav> 
```

but I was only able to produce:

https://github.com/snowpackjs/astro/blob/60a2755c0a93d158fa030ae9883327190b67d190/docs/src/components/SiteSidebar.astro#L6-L21

### Steps to Reproduce

1. Replace the alternate version of the conditional aria-current code into SideSidebar.astro in `docs/`
2. Try to build
3. Error!

**Comment by matthewp** [comment]
How does Svelte handle this? This seems tricky to pull off in our compiler. I wonder if a directive for this use-case is better.

**Comment by matthewp** [comment]
Since this is currently not supported I'm going to move this to the RFC project so we can talk about how it should work.

**Comment by drwpow** [comment]
I believe dynamically-injected attributes aren’t supported in React or Svelte, so I’m -1 to support them in the Astro syntax just for consistency. If you want to omit an attribute, usually `undefined` is encouraged like so: `aria-current={current === '/' ? 'page' : undefined}`.

But to your point we could probably revisit the error thrown to make sure it’s more helpful.

**Comment by FredKSchott** [comment]
Hey everyone! Our current RFC process is beginning to break down at this size, with over 50 open RFCs currently in the "discussing" stage. A growing community is a great problem to have, but our ability to give you RFC feedback has suffered as a result. In an effort to improve our RFC process, we are making some changes to better organize things. 

**From now on, all RFCs will live in a standalone repo:** https://github.com/withastro/rfcs

This allows us to do three things: 1) Use threaded discussions for high-level ideas and improvements, without necessarily requiring an implementation for every idea. 2) Improve the quality of our RFC template and the speed/quality of all feedback. 3) Support inline comments and explicit approvals on RFCs, via a new Pull Request review process.

We hope that this new process leads to better RFC weekly calls and faster feedback on your RFCs from maintainers. More detail can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

--- 

**We can't automatically convert this issue to an RFC in the new repo** because new RFC template is more detailed that this one. But, you can still continue this discussion in the new repo by [creating a new Discussion](https://github.com/withastro/rfcs/discussions) in the RFC repo and copy-and-pasting this post (and any relevant follow-up comments) into it. Discussions are available for high-level ideas and suggestions without the requirement of a full implementation proposal.

Then, when you are ready to propose (or re-propose) an implementation for feedback and approval, you can create a new RFC using the new RFC template. More detail about how to do this can be found in the new RFC repo [README](https://github.com/withastro/rfcs).

Thanks for your patience as we attempt to improve things for both authors and reviewers. If you have any questions, don't hesitate to reach out on Discord. https://astro.build/chat
