### ISSUE TITLE
setting srcDir to '.' in updateConfig crashes

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#8883]
### Astro Info

```block
Astro                    v3.3.2
Node                     v18.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             test
```

### Describe the Bug

In an integration, when using the `updateConfig` function provided by the `astro:config:setup` hook, setting `srcDir` to `"."` crashes. However, setting it in `defineConfig` directly works.

### What's the expected result?

Server shouldn't crash

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-enoxyu?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
User-provided config is processed and paths gets converted into URL objects. `updateConfig` acts after this processing, and the issue is that it overwrites the `srcDir` URL with a string.

To repeat the string -> URL conversion that normally would have happened, you can use the `root` from the processed config.
```diff
'astro:config:setup': ({ config, updateConfig }) => {
  /** @type {import("astro/config").AstroUserConfig} */
  const newConfig = {
-   srcDir: '.',
+   srcDir: new URL('.', config.root),
  };

  updateConfig(newConfig);
},
``` 
And to get the type of the processed config that you are overwriting, you can import from `astro/@types` (internal).
```diff
- /** @type {import("astro/config").AstroUserConfig} */
+ /** @type {Partial<import('./node_modules/astro/dist/@types/astro.js').AstroConfig>} */
```

**Comment by florian-lefebvre** [comment]
@lilnasy do you know why the updateConfig parameter is not strictly typed? I'd expect it to be `Partial<AstroConfig>`. I can submit a PR if you think that makes sense

**Comment by lilnasy** [comment]
I don't, sorry
