### ISSUE TITLE
Images not optimised/resized (based on densities/widths) during build step, when output is 'server'

### ISSUE THREAD

**Issue by xriter** [withastro/astro#8945]
### Astro Info

```block
Astro                    v3.4.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### Describe the Bug

I was happy to try out the new 'image optimisation/generation during build' feature introduced in Astro 3.3.0 (using `densities` or `widths`). (https://docs.astro.build/en/guides/images/#image--astroassets)

However, I found that when you output to `server` using node for example, the images don't get optimized/resized during the build step.

See the repro link. When you run `npm run build`, and then explore the `dist/client/_astro` folder, you'll see that the original image is simply copied, and not optimised and resized to different sizes. The `<Image />` tag also now uses the `_image/...` endpoint, instead of pointing to already existing optimised images.

(When not outputting for 'server', the behaviour is as one would expect, and what is described in the docs.)

### What's the expected result?

I would expect to also get optimized/resized images when outputting to a (node) server.

I never fully got why the `_image/...` endpoint exists, instead of resizing the images during the build step. It seems much more efficient to do this just once up front, instead of doing it every single time a user requests an image.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qnzrn9?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
This is intended. We cannot know the images you need at build time in SSR since we don't run the pages. The dynamic nature of the template prevents this, for instance, maybe your image is shown differently if an user is logged-in, which we obviously cannot know at build time.

In the future, we'd like to explore an import-based solution for this use case, so that the images needed are statically analyzed and we can extract them at build time.

In the meantime, there's no way to do this.
