### ISSUE TITLE
Hot reload uses outdated data

### ISSUE THREAD

**Issue by cdtut** [withastro/astro#9177]
### Astro Info

```block
Astro                    v3.6.0
Package Manager          pnpm
```

### Describe the Bug

Start dev server and load `/test`.

```
{ first: 1 }
```

Make change to file and save so hot reload happens.

```
[astro] reload /src/pages/[test].astro
{ first: 1, added: 1 }
```

Make another change to file and save.

```
[astro] reload /src/pages/[test].astro
[astro] reload /src/pages/[test].astro (x2)
{ first: 1, added: 1 }
```

### What's the expected result?

Hot reload always needs to work with latest data no matter where it is defined.

Saving file first time should show original value not changed one from previous run.

```
[astro] reload /src/pages/[test].astro
{ first: 1 }
```

Problem doesn't happen if remove `<div>{Astro.props}</div>` from `[test].astro`.

Saving file second time should not overwrite earlier line of output in terminal.

```
[astro] reload /src/pages/[test].astro
{ first: 1 }
[astro] reload /src/pages/[test].astro (x2)
{ first: 1 }
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1o5lsw-ngc8qx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
This seems to be correct. You're mutating the data from `data.js`. When you update `[test].astro`, `[test].astro` gets invalidated, which means Astro/Vite will re-evaluate the file again. However, `data.js` is not updated, so it stays the same.

When re-evaluating `[test].astro`, it'll import `data.js` again which will get the same value as before because you mutated it. The value isn't invalidated because the file wasn't updated.

> Problem doesn't happen if remove `<div>{Astro.props}</div>` from `[test].astro`.

That's because HMR or page reload does not happen when you remove it. The HMR client script wasn't injected because the HTML page has no content.
