### ISSUE TITLE
API Route always returns 404 on Vercel depending on trailingSlash

### ISSUE THREAD

**Issue by florian-lefebvre** [withastro/astro#9206]
### Astro Info

```block
Astro                    v3.6.1
Node                     v18.14.1
System                   Windows (x64)
Package Manager          yarn
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             none
```

### Describe the Bug

When setting `trailingSlash` in both astro and vercel configs, I think there is some conflict that causes API routes to always be 404.

### What's the expected result?

The route `/api/test/` should return some json. Here is the deployment: https://astro-vercel-endpoint-issue.vercel.app/api/test/

### Link to Minimal Reproducible Example

https://github.com/florian-lefebvre/astro-vercel-endpoint-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Does not just affect vercel. The combination of base and trailingSlash is sufficient to break routing.
```ts
defineConfig({
    base: "/",
    trailingSlash: "always"
})
```

**Comment by lilnasy** [comment]
i am not sure if `base: "/"` even makes sense
i think the fix would be to error when base ends in slash or ignore base's trailing slash 💀

**Comment by matthewp** [comment]
Is `output: 'hybrid'` required to see this problem @florian-lefebvre ?

**Comment by lilnasy** [comment]
This issue is that astro's `trailingSlash` never acts on API routes. They are always served without it. When you enable vercel's `trailingSlash`, it redirects from `/api/test` (which astro could have served) to `/api/test/` (which astro currently does not; bug).

We could make `trailingSlash: "always"` apply to API routes but that would be a breaking change because currently it _only_ works without them. Since the option is for SEO use-cases, API routes have some wiggle room - we could ignore the trailing slash in all cases.

**Comment by MadSpindel** [comment]
I think I've a similar issue with /_image and Vercel. If I enable trailingSlash: true in vercel.json, all images stop working on SSR pages, since Vercel is changing the /_image URL to /_image/. And it looks like trailingSlash: 'always' doesn't affect the /_image endpoint?
