### ISSUE TITLE
URI malformed error on complex URL redirect 

### ISSUE THREAD

**Issue by SStan-prog** [withastro/astro#9361]
### Astro Info

```block
Astro                    v4.0.3
Node                     v18.17.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

 Redirect set up: 
```js
  redirects: {   
'/blogs/%e3%83%9b%e3%83%bc%e3%83%a0%e3%83%9a%e3%83%bc%e3%82%b8%e5%85%ac%e9%96%8b%e5%89%8d%e3%81%ab%e7%a2%ba%e8%aa%8d%e3%81%99%e3%81%b9%e3%81%8d%e3%83%81%e3':
      '/blogs/checklist-website-before-released',
  },
```
resulting in URI malformed error on builds and when attempting to use the redirect during dev.

### What's the expected result?

The following URL should redirect to  '/blogs/checklist-website-before-released' instead of erroring: 
/blogs/%e3%83%9b%e3%83%bc%e3%83%a0%e3%83%9a%e3%83%bc%e3%82%b8%e5%85%ac%e9%96%8b%e5%89%8d%e3%81%ab%e7%a2%ba%e8%aa%8d%e3%81%99%e3%81%b9%e3%81%8d%e3%83%81%e3'

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-suztqg?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
I'm taking a look.

**Comment by matthewp** [comment]
Hey @SStan-prog, the pages on the left side have to exist in the project in order to set up redirects. This is a technical constraint that we are hoping to fix. In the meantime, I'll make sure this error message is better.

**Comment by SStan-prog** [comment]
Thanks for your response @matthewp. 
But in the case of the first redirect, it works as expected without the left side URL existing "'/blogs_type/media">

**Comment by matthewp** [comment]
%e3%83%9b%e3%83%bc%e3%83%a0%e3%83%9a%e3%83%bc%e3%82%b8%e5%85%ac%e9%96%8b%e5%89%8d%e3%81%ab%e7%a2%ba%e8%aa%8d%e3%81%99%e3%81%b9%e3%81%8d%e3%83%81%e3`. This is because the path *must* be decodeable in order to write to disk through NodeJS. For example if you attempt to do `decodeURIComponent(new URL('/blogs/%e3%83%9b%e3%83%bc%e3%83%a0%e3%83%9a%e3%83%bc%e3%82%b8%e5%85%ac%e9%96%8b%e5%89%8d%e3%81%ab%e7%a2%ba%e8%aa%8d%e3%81%99%e3%81%b9%e3%81%8d%e3%83%81%e3', 'https://example.com').pathname)` it will throw.

**Comment by SStan-prog** [comment]
Okay, good to know; I appreciate your answers. 
Thankfully we were able to set up the redirects with Cloudflare.
