### ISSUE TITLE
HMR error after astro v4 upgrade

### ISSUE THREAD

**Issue by abolajibisiriyu** [withastro/astro#9370]
### Astro Info

```block
Astro                    v4.0.3
Node                     v18.17.1
System                   macOS (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
```

### Describe the Bug

- I upgraded to astro v4
- I made changes to my `Footer` component (referenced in `Layout`); no HMR happened
- Then manually saved(`CMD` + `S`) `Layout` file (I did this to trigger HMR); got this behaviour 

`console`
<img width="1387" alt="Screenshot 2023-12-08 at 00 06 03" src="https://github.com/withastro/astro/assets/8493924/cd7538ed-945c-4b0d-a675-f1ae6be930cb">

`browser`
<img width="1678" alt="Screenshot 2023-12-08 at 00 06 23" src="https://github.com/withastro/astro/assets/8493924/3433c772-402d-4a2b-8874-459845480402">

The link to the example(basic astro v4) doesn't seem to throw any errors, but doesn't reflect the changes(💡 making changes to `Footer`)

### What's the expected result?

I expected my changes to reflect in the browser with no errors

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ztyzx4?file=src%2Flayouts%2FLayout.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jacobthesheep** [comment]
Yeah, is anyone else noticing this? I have to refresh the page to see changes.

**Comment by jtag05** [comment]
Also experiencing this issue.

**Comment by natemoo-re** [comment]
Thanks for the report! Presumably this is an issue affecting any Vite 5 users since Astro's HMR logic hasn't changed at all. We'll take a look at this as soon as we can!

**Comment by natemoo-re** [comment]
I was able to reliably reproduce this and track it to one spot in our code! I've never had such luck with an HMR issue before. Hoping to get this fixed ASAP!

**Comment by jacobthesheep** [comment]
Does have anything to do with `data-astro-source-file` on all the elements in dev mode?

**Comment by bluwy** [comment]
> Does this have anything to do with `data-astro-source-file` on all the elements in dev mode?

No, it's related to how Vite 5 handles HMR with circular imports as Tailwind tends to do that :(

---

The issue is that the `<style is:global>` was registering all the tracked files by Tailwind as dependencies of `Layout.astro`, causing strange HMR updates as causes some URLs to be fetched where we didn't expect it to.

A workaround for now is to moving the tailwind code (`@tailwind base` etc) to an external file, and import it from `Layout.astro` instead. 

Ideally this relationship should be done by Astro as well, but we need a few things before we can support that:
1. When an Astro component's CSS is fetched directly (without compiling the core Astro file first), we need to also automatically compile the Astro file.
2. We should register the CSS dependencies (by tailwind) in the style's `load()` hook instead (Not the core Astro file). That way we can get fine-grain HMR for the CSS file only.
3. Vite also needs to support CSS dependencies through `this.addWatchFile`. Currently it's supported for its builtin CSS handling only.

**Comment by jacobdalamb** [comment]
Are Vite projects also having this problem?

**Comment by bluwy** [comment]
Yes, but it happens most often with Astro projects only. Vite projects can hit this bug but rarely.

**Comment by bluwy** [comment]
This should be resolved in https://github.com/withastro/astro/pull/9706 now. I'll follow-up with further improvements in a later PR, but it shouldn't impact the experience today. Will mostly make the internals a little cleaner.
