### ISSUE TITLE
HTML Entities in Markdown frontmatter don't render correctly

### ISSUE THREAD

**Issue by hamvocke** [withastro/astro#9431]
### Astro Info

```block
Astro                    v4.0.3
Node                     v19.7.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### Describe the Bug

1. Create a `.md` page
2. Use an HTML entity somewhere in the front matter. For example:
   ```
   ---
   title: Some &copy; Title
   ---
   ```
3. Use a `.astro` layout to render that `.md` page's front matter. For example:
   ```
   <html>
     <h1>{frontmatter.title}</h1>
     <slot />
   </html>
   ```
4. See how the title is rendered verbatim as `Some &copy; Title`

### What's the expected result?

The title should be rendered as `Some © Title`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nznnjn?file=src%2Fpages%2Fsomepage.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
If you want to use HTML entities in the rendered code, you should use `set:html`, e.g.

```html
<h1 set:html={frontmatter.title}></h1>
```

The existing behaviour is working as intended as you're rendering it as text, which explicitly escapes HTML-specific features (like entities) to prevent accidental XSS.

**Comment by hamvocke** [comment]
Thanks for the explanation!

I stumbled across `set:html` and was wondering whether that's the right thing to use. I ran into a few gotchas where `set:html` wouldn't help me, most prominently when using `frontmatter.title` in generated RSS feeds, where there's no `set:html` available if I'm following [astro's blog tutorial](https://docs.astro.build/en/tutorial/5-astro-api/4/) but I think I can work around that by providing an HTML and a plain text version of the title in my frontmatter and use the plain text title wherever `set:html` is not available.

I hope it's okay to ask two follow-up questions, maybe they'll help other folks, too:

1. Is there a way to tap into `set:html`'s functionality even when I'm not rendering HTML directly? E.g. for the sake of generating an RSS feed in a `rss.xml.js` document?
2. Why is XSS injection a concern for frontmatter but not for the body of a document? Markdown allows me to write arbitrary HTML, so this would be another source of potential XSS attacks. Does astro trust the markdown parser used under the hood to handle XSS attacks in the document body correctly?

**Comment by bluwy** [comment]
> 1. Is there a way to tap into `set:html`'s functionality even when I'm not rendering HTML directly? E.g. for the sake of generating an RSS feed in a `rss.xml.js` document?

I think it needs to be looked in a different way. `set:html` or raw HTML functionality isn't a special feature. It simply puts the specified string as plain HTML, depending if the context it's working on is plain HTML.

For example, Astro files let you template HTML. Its output is HTML, but when you use `<p>{myVar}</p>`, you aren't likely wanting `myVar` to expand as raw HTML. That would be prone to security issues. Hence, Astro applies encoding to escape as plain text rather than HTML.

From this point of view, `set:html` allows you to skip this process. It's bound to the HTML context its working on, and not a standalone feature.



> 2\. Why is XSS injection a concern for frontmatter but not for the body of a document? Markdown allows me to write arbitrary HTML, so this would be another source of potential XSS attacks. Does astro trust the markdown parser used under the hood to handle XSS attacks in the document body correctly?

As explain in no1, the concern is applied to `<p>{myVar}</p>`, not the frontmatter. The frontmatter is only the source (a plain string). For markdown files, it also has its own HTML sanitization process.

**Comment by bytrangle** [comment]
@bluwy 

If this `set:html` attribute is used in a JSX component, it will throw an error:

> Type '{ "set:html": string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Property 'set:html' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.

It's a valid error because `set:html` is not an accepted attribute on `<div>` element, but what can I do about it?
