### ISSUE TITLE
`a11y-label-has-associated-control` audit produces false positives

### ISSUE THREAD

**Issue by at-the-vr** [withastro/astro#9456]
### What version of `starlight` are you using?

0.15.0

### What version of `astro` are you using?

4.0.1

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

According to `Dev Toolbar Audit` the labels used for `ThemeSelect`& `LanguageSelect` are missing its controlled text
Complete Error according to Dev Toolbar ⬇
```js
"label" tag should have an associated control and a text content.`
The label tag must be associated with a control using either for or having a nested input. Additionally, the label tag must have text content.
```
Link to component found from Audit: [Select Component](https://github.com/withastro/starlight/blob/main/packages/starlight/components/Select.astro)

Screenshots ⬇️

![image](https://github.com/withastro/starlight/assets/88548999/bc9a2d0b-4cea-4c0d-8525-dffd8fd99239)
![image](https://github.com/withastro/starlight/assets/88548999/0e7d3345-b00d-43ca-87d9-16429438a6fa)

> Note: The Stackblitz instance for [Starlight](https://astro.new/starlight-basics?on=stackblitz) does not highlights this issue but any local starlight repo will show this issue

### Link to Minimal Reproducible Example

Not applicable

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
Quick summary of why this was moved from the Starlight repo:

The `a11y-label-has-associated-control` audit produces warnings on Starlight’s `<select>` components, which are wrapped in a `<label>` because it requires labels to always include an `<input>` element, even though other element types are supported inside `<label>`.

See @HiDeoo’s [comment](https://github.com/withastro/astro/issues/9456#issuecomment-1859284148) for links to a similar ESLint rule, which accounts for this.
