### ISSUE TITLE
`remarkPluginFrontmatter` type should associated with the schema defined in `/src/content/config.ts`

### ISSUE THREAD

**Issue by CaptainOfPhB** [withastro/astro#9538]
### Astro Info

```block
Astro                    v4.0.8
Node                     v18.18.2
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/mdx
```

### Describe the Bug

I defined a `blogs` schema in `src/content/config.ts`:

```ts
import { config } from '@/config/global';
import { z, defineCollection } from 'astro:content';

const blogCollection = defineCollection({
  type: "content",
  schema: z.object({
    slug: z.string(),
    title: z.string(),
    description: z.string(),
    tags: z.array(z.string()),
    words: z.number().optional(),
    draft: z.boolean().optional(),
    hidden: z.boolean().optional(),
    date: z.date().default(new Date()),
    readingTime: z.string().optional(),
    deprecated: z.boolean().default(false),
    lastModified: z.date().default(new Date()),
    author: z.string().default(config.author.name),
  })
});

export const collections = {
  blogs: blogCollection
};
```

But the type of `remarkPluginFrontmatter` in `/.astro/types.d.ts` file which generated by `astro sync` is `Record<string, any>`.

<img width="594" alt="image" src="https://github.com/withastro/astro/assets/30765485/d5c89cf8-9019-400b-8ac1-112da4ef9747">

So, the type of blog entry is as expected in below code:

<img width="1013" alt="image" src="https://github.com/withastro/astro/assets/30765485/4931503e-3ddd-4714-be3c-bcab1f45204c">
 

But its `remarkPluginFrontmatter` type is `Recode<string, any>`:

<img width="862" alt="image" src="https://github.com/withastro/astro/assets/30765485/7b1276aa-d633-432e-a95f-ec00aef105bc">

So, the frontmatter validation or type hint is not working as described in the document, please fix this, thank you!

### What's the expected result?

The type of `remarkPluginFrontmatter` should be same with the schema defined in `/src/content/config.ts`.

### Link to Minimal Reproducible Example

https://github.com/CaptainOfPhB/blog-built-by-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bholmesdev** [comment]
Hm, this is not expected behavior for `remarkPluginFrontmatter`. To quote the docs:

> Not recommended. Remark and rehype plugins access the raw Markdown or MDX document frontmatter. This means that `remarkPluginFrontmatter` frontmatter is handled separately from your type-safe schema, and will not reflect any changes or defaults applied through Astro. Use at your own risk!

It is meant for edge cases where content collection schemas are unsufficient, like [generating reading time from post contents](https://docs.astro.build/en/recipes/reading-time/). 

We understand this can be confusing though. `remarkPluginFrontmatter` is on our list to revisit!

**Comment by sebastienbarre** [comment]
>  Remark and rehype plugins access the raw Markdown or MDX document frontmatter. This means that remarkPluginFrontmatter frontmatter is handled separately from your type-safe schema,

This notice would be great to include in the docs to emphasize that `remarkPluginFrontmatter` contains raw values, as opposed to the type-safe, validated, and potentially coerced ones. Unfortunately, it seems this note was removed at some point, since the only mention of `remarkPluginFrontmatter` in the official docs now appears in the Runtime API section for `render()`. It says:

> remarkPluginFrontmatter - The modified frontmatter object after any [remark or rehype plugins have been applied](https://docs.astro.build/en/guides/markdown-content/#modifying-frontmatter-programmatically). Set to type any.

It is easy to miss the implications of “set to type any.” It would be helpful to reiterate that this seemingly identical frontmatter has not been validated in any way. As a result, something like `pubDate: z.coerce.date()` *may* still be a string if it was originally a string in the frontmatter, though see below.

It is easy to shoot yourself in the foot by merging validated frontmatter with `remarkPluginFrontmatter`. This is particularly tricky to spot because it appears inconsistent between Markdown and MDX. With Markdown, my `remarkPluginFrontmatter` has `pubDate` coerced to a `Date` and I've no clue why, whereas with MDX it remains a `string`, which sent me on a bit of a wild goose chase.

Thanks
