### ISSUE TITLE
Svelte component not being reactive

### ISSUE THREAD

**Issue by arch-fan** [withastro/astro#9589]
### Astro Info

```block
Astro                    v4.0.9
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### Describe the Bug

The svelte component isn't reactive. This is the svelte component:

```svelte
<script lang="ts">
  import { translateClient } from "@/lib/translation";

  export let text: string;

  let translatedText = text;

  const translate = async () => {
    console.log("hello");
    try {
      const response = await translateClient.translateText({
        contents: [text],
        targetLanguageCode: "en",
        sourceLanguageCode: "jp",
      });

      translatedText = response[0]!.translations![0]!.translatedText as string;
    } catch (error) {
      console.error("Error al traducir:", error);
      translatedText = "There was an error translating, please try later.";
    }
  };
</script>

<div>
  <p>{translatedText}</p>
  <button
    on:click={translate}
    class="bg-blue-500 text-white w-full rounded hover:bg-blue-400 mt-auto"
  >
    Translate this
  </button>
</div>
```

The component is rendered, but any event listener is being added. This is how it's being called:

`<TranslateText text={skill.detail} client:load />`

The `skill.detail` is in Japanese, just in case.

### What's the expected result?

Reactivity (onclick) working

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-dpypns?file=src%2Fcomponents%2FTranslateText.svelte

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
You're using `@google-cloud/translate` and according to https://www.npmjs.com/package/@google-cloud/translate, it's a package meant for Node.js use only, not browsers. In the browser (Chrome), you can see this error:

```
index.mjs?v=4f6590cb:4 Uncaught (in promise) SyntaxError: The requested module '/node_modules/.pnpm/whatwg-url@5.0.0/node_modules/whatwg-url/lib/public-api.js?v=4f6590cb' does not provide an export named 'default' (at index.mjs?v=4f6590cb:4:8)
```

It's trying to work in a browser context, but it's using Node.js specific APIs which made it fail in runtime. To fix this, make sure you're only using `@google-cloud/translate` on the server-side. For example, you could setup a [server endpoint](https://docs.astro.build/en/core-concepts/endpoints/#server-endpoints-api-routes) to proxy the requests from the browser. Closing as expected behaviour.

**Comment by arch-fan** [comment]
Yeh, makes sense.

Thanks!
