### ISSUE TITLE
DEV server seems stuck. Page hangs while loading.

### ISSUE THREAD

**Issue by agi-omar** [withastro/astro#9616]
### Astro Info

```block
Astro                    v4.1.0
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/sitemap
                         astro-icon
```

### Describe the Bug

I just did my first build and was preparing to finally deploy my site then suddenly npm run dev started acting weird. The page just keeps loading and loads only some of its content. Dev server seems a bit slow. _The build preview works perfectly fine, however, if that is of any help._ I had astro 4.0.3 and tried upgrading to 4.1 but to no avail. Still a beginner but I couldn't find anything like what is happening with my project online. Appreaciate any help.

PS. The dist folder was built from my local version before upgrading to 4.1. 

### What's the expected result?

Dev server to run smoothly and page to load like normal.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jcykxr?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I'm a bit stumped on this one. The issue seems to be that the `/_image` requests are never resolved (stucked at "Initial connection" in Chrome), and once you have 6 hanged connections, the rest of your app's scripts won't be loaded anymore due to HTTP implementations.

I can see on the server-side that the images are properly transformed and returned the Response, but the browser just kept hanging. Even if I skip the transform and simply return 404 for all images, it still hangs 🤔

**Comment by agi-omar** [comment]
Thanks for taking a look. I'm thinking of starting a new project and just moving all the current project's there. What do you think?

**Comment by agi-omar** [comment]
so it turns out lines 48-53 of src/styles/animation.js were causing the issue. not an astro problem. Thanks @bluwy
