### ISSUE TITLE
View Transition to 404 loses state

### ISSUE THREAD

**Issue by aminabromand** [withastro/astro#9629]
### Astro Info

```block
> green-galaxy@0.0.1 astro
> astro info

Astro                    v4.1.1
Node                     v18.14.2
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

only tried on Firefox

### Describe the Bug

when I use ViewTransitions and:
1. open a non existing url and get redirected to the 404 page
2. or open the 404 page directly
I lose the state of my `transition:persist` island.

The real life usage is the login state, which I want to maintain also on the 404 page, but in the minimal example I use a simple counter.

### What's the expected result?

A `transition:persist` island should persist its state on ViewTransition also to non existing/404 pages.

### Link to Minimal Reproducible Example

https://github.com/aminabromand/astro-404-view-transition-state

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hi @aminabromand, thanks for pointing out this issue!
Your code looks good, but unfortunately Astro's view transition loader doesn't like the 404 page because it doesn't have a text/html media type. I need to find out why Astro doesn't provide this. 

This seems to be just a DEV server issue. Could you please confirm that everything works as expected when testing with `build`/`preview`?

**Comment by aminabromand** [comment]
Oh, you are right and I can confirm:
If I do a build and serve the artifacts from an http server, the state remains persisted when navigating via ViewTransition directly or indirectly to the 404 page.
