### ISSUE TITLE
The preview in dev mode is different from the preview mode. A lot of css files and font files just return 404, or don't work.

### ISSUE THREAD

**Issue by Sapython** [withastro/astro#9632]
### Astro Info

```block
Astro                    v4.1.1
Node                     v18.18.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/solid-js
```

### Describe the Bug

The webpage when ran under the command `npm run dev` shows up like this

![image](https://github.com/withastro/astro/assets/45693173/f80df4eb-5e3c-4b4c-9576-d437517df6a0)

Whereas when deployed on vercel it shows up like this.

![image](https://github.com/withastro/astro/assets/45693173/c95e752e-034b-4ef4-ad27-723ec98fdd9d)

The repo for full code is available here: https://github.com/Sapython/portfolio-website
The deployed version is available here: https://portfolio-website-lake-three.vercel.app/ 

### What's the expected result?

The dev mode and build mode should produce same output.

### Link to Minimal Reproducible Example

https://portfolio-website-lake-three.vercel.app/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Sapython** [comment]
@lilnasy  I have made the repository public. Sorry my bad, didn't checked it on a private tab.

**Comment by lilnasy** [comment]
The issue is that the links to the fonts are relative in your project.

In dev mode, the stylesheets are inlined, and the links get resolved relative to the current page. Since there is only one page and it is `/`, they get resolved correctly.

In build, stylesheets are external, and the links to fonts are resolved relative to where the external stylesheets are served from, which fails.

Both astro and vite (which manages the dev server and bundling) are working as intended. Since you are hosting fonts from the public folder, you would want to use absolute links instead. You can do that by adding a `/` at the start.
