### ISSUE TITLE
Custom View Transitions inconsistent

### ISSUE THREAD

**Issue by peterkogo** [withastro/astro#9650]
### Astro Info

```block
Astro                    v4.1.1
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Firefox, Safari

### Describe the Bug

A simple dynamic routing where `/foo` renders a persistent component and `/foo/bar` shows an additional overlay.

```astro
---
export const getStaticPaths = (() => {
  return [{ params: { bar: "bar" } }, { params: { bar: undefined } }];
}) satisfies GetStaticPaths;
---

<Layout title="This does not work" transition:name="layout" transition:persist>
  <Persistent client:load transition:name="persistent" transition:persist />
  {Astro.params.bar && <Overlay />}
</Layout>
```

The overlay should be animated with a simple custom animation.
```css
@keyframes flyInOut {
  from {
    transform: translateY(0%);
  }
  to {
    transform: translateY(100%);
  }
}
```

The animation is applied to the overlay

```astro
---
const anim = {
  old: {
    name: "flyInOut",
    duration: "1s",
    easing: "linear",
  },
  new: {
    name: "flyInOut",
    duration: "1s",
    direction: "reverse",
    easing: "linear",
    fillMode: "forwards",
  },
};

const myFade = {
  forwards: anim,
  backwards: anim,
};
---

<a href="/foo">
  <div class="container" transition:name="overlay" transition:animate={myFade}>
    Go back to /foo
  </div>
</a>
```

### The issues
1. On Chrome (native view transitions) the **in** animation works, but the **out** defaults to a fade.
2. On other browser (firefox, safari) the **in** and **out** animations work - however the **in** animations jumps quite visibly

### Any help appreciated
I apologize if this is a non-issue and a mistake on my part. Maybe, there is some piece of documentation I overlooked or is missing.

### What's the expected result?

View Transition animations should work and be consistent over all browsers. 

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/peterkogo/astro-transitions-broken?initialPath=/foo

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hello @peterkogo, several effects seem to be interacting here. 
The overlay view transition only exists on `/foo/bar`. If you look at the HTML, you will find a style tag at the end of the head that starts with 
```
[data-astro-transition-scope="astro-7luycb3l-3"] { view-transition-name: overlay; }@layer astro { ::view-transition-old(overlay) { 
```
This definition does not exist on `/foo`. On browsers with native view transition support, the animation starts after the DOM of the new page was swapped in. Therefore it is completely controlled by the CSS of the next page. That's why you see the slide in animation when you go to /foo/bar.

If you transition back to `/foo`, there is no definition for `view-transition-name: overlay` on that page. Therefore the out animation will not slide out.
![image](https://github.com/withastro/astro/assets/94928215/66aa1fa4-b296-4a0a-b863-c2a623be3c94)

There is a way to explicitly style elements that only exist on one side of the view transition. The :only-child pseudo-class can be used for this, see the [example here](https://developer.chrome.com/docs/web-platform/view-transitions#custom_entry_and_exit_transitions)

I have not analyzed why the "in" animation starts smoothly and then jumps in on Firefox.
Astro simulates view transitions on browsers that do not natively support them. However, there are limitations, as it is not possible to imitate the built-in behavior 1:1. Simulated view transition play the "out" animation, then switch the DOM, then play the "in" animation. Native implementation do both animations in parallel. Also the simulation can neither support the ::view-transition pseudo classes nor the built-in morph animations. These differences leads to more or less large inconsistencies between the two implementations.

Minor: `transition:name="layout" transition:persist` on `<Layout ...` have no effect. They only add unused style sheets.

**Comment by peterkogo** [comment]
Sorry, just had time to look over it.

@martrapp Thank you so much for your detailed analysis and your additional notes - this helped a lot!

The missing "out" animation is fixed. Just like you pointed out, using the `:only-child` selector on the missing animation. For anyone experiencing this issue in the future, I had to add
```css
::view-transition-old(overlay):only-child {
  animation: 1s flyInOut;
}
```
to fix the issue in Chrome.

**Comment by martrapp** [comment]
I will get back to you later this week.

**Comment by martrapp** [comment]
Hi @peterkogo, I'm back  :)

I'm getting the impression that this use case runs a little counter to the design of the view transition simulation. ;-) I will close this issue and would like to point you to Astro's #support channel on Discord. There may be a better solution than view transitions for showing and hiding an overlay. 

You can force the missing animation for browsers that do not have native support for view transitions with the astro event "astro:after-swap" by adding this script after the closing `</Layout>` tag at the end of `[...bar].astro`.

```
<script>
  import { supportsViewTransitions } from "astro:transitions/client";
  const afterSwap = () => {
    document
      .querySelector(".container")
      ?.animate(
        [{ transform: "translateY(100%)" }, { transform: "translateY(0%)" }],
        {duration: 1000}
      );
  };
  !supportsViewTransitions && document.addEventListener("astro:after-swap", afterSwap);
</script>
```
