### ISSUE TITLE
"Legalize" Multi-directional View Transitions

### ISSUE THREAD

**Issue by KingPr0o7** [withastro/astro#9745]
### Astro Info

```block
Astro                    v4.2.1
Node                     v18.19.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/vercel
Integrations             astro-meta-tags
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

Doesn't apply.

### Describe the Bug

When trying to use more than two directions and one being custom, I get a TS error because I'm trying to use my own directional animation in the `TransitionDirectionalAnimations` with a uniquely named directional `TransitionAnimationPair`: `fade`. Here is that animation:

```ts
const animation = {
  forward: slideRight,
  backward: slideLeft,
  fade: fading 
};
```

What the type spec is in `astro.d.ts`:
```ts
export interface TransitionDirectionalAnimations {
    forwards: TransitionAnimationPair;
    backwards: TransitionAnimationPair;
}
```

Here is an image I get in Visual Studio Code:
![TS Error Due to Exceeding Type](https://github.com/withastro/astro/assets/64029396/d7c8014b-6cb5-48ed-a838-925b56ea0fa5)

### What's the expected result?

I should either: 

- Add my own custom directional `TransitionAnimationPair`.
- Since this isn't really a "bug" per se, have a new way to pass `transition:animate` with multiple animations. (Since I'm hijacking the `TransitionDirectionalAnimations` with a custom "directional" `TransitionAnimationPair` via setting a direction in JS:)

```js
currentPageIndex < previousPageIndex ? e.direction = 'backward' : e.direction = 'forward';
currentPageIndex === -1 || previousPageIndex === -1 ? e.direction = 'fade' : 'forward';
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-u1buj8?file=src%2FLayouts%2FLayout.astro
* Does not show an error for some reason, @OliverSpeir was also able to reproduce the error.

### Link to Discord Support Thread

https://discord.com/channels/830184174198718474/1198032407446700174

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by martrapp** [comment]
Hello @KingPr0o7 
As you rightly said, this is not a bug, but a request to extend the functionality of Astro's view transition support.

Astro supports the two natural directions for navigation, forward and backward, and they must be named exactly as `forwards` and `backwards`. We thought about extending this for other use cases, but decided against doing this for the Astro core for the sake of simplicity and maintainability. Many ideas to extend the core functionality can be covered by community contributions.

Interestingly, the underlying implementation of CSS generation for `TransitionDirectionalAnimations` can technically handle different and additional directional names.  

You can cast your object of type `Record<string, TransitionAnimationPair>` to `TransitionDirectionalAnimations`, which looks pretty ugly since you have to go through `unknown`.

```
<main transition:animate={animation as unknown as TransitionDirectionalAnimations}></main>
```
As the author of [astro-vtbot](https://github.com/martrapp/astro-vt-bot?tab=readme-ov-file#bag-of-tricks-for-astros-view-transitions), I am of course happy to recommend this prettier type-safe solution:
```
---
import { adapter } from 'astro-vtbot/animations/animation-style';
---
<main transition:animate={adapter(animation)}></main>
```
