### ISSUE TITLE
"layout" in "content" doesn't get full schema applied

### ISSUE THREAD

**Issue by dlashua** [withastro/astro#9950]
### Astro Info

```block
Astro                    v4.2.6
Node                     v18.14.2
System                   Linux (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/vue
```

### Describe the Bug

"layout" in the frontmatter of a markdown file in a content collection (in the "content/whatever" directory) doesn't honor the "schema" in config.ts in "content". The schema is checked and an error is thrown for invalid frontmatter, however, the keys in frontmatter have not been converted per the schema.

As an example, if config.ts looks like this:
```js
// content/config.ts
const blog = defineCollection({
	type: 'content',
	schema: z.object({
		title: z.string(),
		description: z.string(),
		pubDate: z.coerce.date().optional(),
	}),
});

export const collections = { blog };
```

And there is a file in the content collection like this:
```md
---
# content/blog/a-blog.md
title: Test
description: Test Description
pubDate: "2024-02-01 12:00:00"
layout: ../../layouts/blog.astro
---
# Test

This is a test
```

When the layout receives the frontmatter, `pubDate` will be a string and not a Date. 

### What's the expected result?

Ideally, the frontmatter received by the layout would have the schema fully-applied including coercions.

I realized after much confusion and digging deep in the documentation that the "layout" frontmatter is probably intended for "pages" and not "content". If that's the case, then the "layout" frontmatter in "content" should not be applied or an error should trigger to indicate that "layout" is for "pages" only. 

In the reproducible example below, view the home page, then click blogs and view each of the two blog entries. Specifically look under the title of each blog entry for the "pubDate is a string/object" text.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8lugrn

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dlashua** [comment]
I have created [a discussion](https://github.com/withastro/roadmap/discussions/832).

**Comment by sebastienbarre** [comment]
I'm not sure why this would be intentional, but maybe I'm missing something? I'm confused as to why the schema is not used on MDX frontmatter. 
I'm using Astro 6.1, following the tutorial. 
The `pubDate` value is in the frontmatter like this:
```
---
...
pubDate: 2022-07-15
...
---
```

If a blog post is in Markdown format, `pubDate` seems correctly coerced to a `Date` object. If my blog post is in MDX format, the value I'm getting is a `string`. Which is a problem since I want to use the same component/layout, and per the schema I should get a `Date`.

UPDATE: the issue is that I was merging my validated, type-safe frontmatter with `remarkPluginFrontmatter`. The documentation used to mention that the latter contains the raw values, but this mention [was removed](https://github.com/withastro/astro/issues/9538#issuecomment-4174227395). It is easy to shoot yourself in the foot by merging validated frontmatter with `remarkPluginFrontmatter`. This is particularly tricky to spot because it appears inconsistent between Markdown and MDX. With Markdown, my `remarkPluginFrontmatter` has `pubDate` coerced to a Date, whereas with MDX it remains a `string`, which sent me on a bit of a wild goose chase.
