### ISSUE TITLE
Hiding Astro behind a proxy with a base path in development

### ISSUE THREAD

**Issue by marcoacierno** [withastro/astro#9989]
### Astro Info

```block
Astro                    v4.2.7
Node                     v18.17.1
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

Hello!

I have a setup where I need to run Astro behind a "proxy" server in local development. Developers go to a Django server and navigate to (for example) `localhost:8000/admin/schedule-builder/`. This URL will render an iframe pointing to `localhost:8000/astro/schedule-builder`.

The URL `/astro/{path}` forwards all the requests to the `astro dev` local server.

To make this flow work, I need all URLs that Astro generates to be prefixed with the base /astro. I tried setting the `base` param in all places: at the root of the config, inside `vite`, inside `vite.server` but all URLs that Astro creates in the page always point to the root.

E.g. a config I tried:

```
export default defineConfig({
  vite: {
    base: 'astro'
  },
  integrations: [react(), tailwind()],
  build: {
    format: "file",
    assetsPrefix: "//django-static/",
  },
});
```

### What's the expected result?

Astro should prefix all the URLs with the base when specified in the config

As an example, if you go to the repro link, you can see that the `<script>` tag src is:

```
/@fs/home/projects/github-wrbpwn/node_modules/astro/dist/runtime/client/dev-toolbar/entrypoint.js?v=0a375a3a
```

Ideally this should be

```
/astro/@fs/home/projects/github-wrbpwn/node_modules/astro/dist/runtime/client/dev-toolbar/entrypoint.js?v=0a375a3a
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wrbpwn?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
I see you are using `vite.base`. Have you tried `base`?

https://docs.astro.build/en/reference/configuration-reference/#base

**Comment by marcoacierno** [comment]
> I see you are using `vite.base`. Have you tried `base`?
> 
> [docs.astro.build/en/reference/configuration-reference/#base](https://docs.astro.build/en/reference/configuration-reference/#base)

Yes, I tried it as well; the only thing it does is it force you to go to (in my example) /base-you-set/your-actual-path. I imagine to simulate how the address would be in production. (I updated the repro link https://stackblitz.com/edit/github-wrbpwn?file=astro.config.mjs to show if you open the inspector it always points to root)

`base` / `vite.base` / `vite.server.base` they all do nothing to what Astro puts as paths in <script>

**Comment by lilnasy** [comment]
Thanks for clarifying!

This is not a use-case we had considered. We don't support it currently.

You mention you are putting the -dev server_ behind a proxy, as opposed to a production server. That is a very specific use-case. Is there something preventing development locally on your own machine?

**Comment by marcoacierno** [comment]
> Thanks for clarifying!
> 
> This is not a use-case we had considered. We don't support it currently.
> 
> You mention you are putting the _dev server_ behind a proxy, as opposed to a production server. That is a very specific use-case. Is there something preventing development locally on your own machine?

Thanks for checking it! I suspected it wasn't supported but didn't want to give up easily. I will close the issue as I suspect it is not really a use case worth spending much time on.

About my use case:

I described my setup quite badly, this is all for local development, and the production setup would just use the HTML files served directly by Django. 

While working on my project, I want everything to go through a Django server (running on my machine) because:

1. I wanted to simulate how this would work in production as much as possible. And in production, there wouldn't be an iframe pointing to another origin.
2. I wanted an easy way to share cookies, sessions, and communicate between the Astro app and iframes opened in it that might open back a different page of the Django admin app. Use cases that different origins might make more complex to do.

The problems I flagged here for my use case (especially authentication and iframes) would probably be solved quite easily with a good CORS setup and just letting Django know to allow localhost:3002 iframes when in local development but I naively assumed it was just a matter of setting a base path and it would be done and be on the same origin 😂 

If anyone (for some reason?) wants to do something similar, this is what I did in my case:

1. When proxying from Django to Astro, I updated the JS files to fix the paths: https://github.com/pythonitalia/pycon/blob/429600e4198655dc187b0f277cb0290d641111f5/backend/custom_admin/views.py
2. I also have to proxy the Hot reload module WebSocket: https://github.com/pythonitalia/pycon/blob/429600e4198655dc187b0f277cb0290d641111f5/backend/custom_admin/ws-proxy/ws.py as the paths need to be fixed there as well to make the hot reload work like before.

At this point, I am not even sure I will keep this workaround as it might break easily with future Astro versions too! :)

**Comment by lilnasy** [comment]
Thanks for providing context and resources for others. Good luck!

**Comment by unbeauvoyage** [comment]
I don't think this is an extreme use case, although the above discussion making it look like an unusual case makes me suspect if I misunderstood the subject in question.
I have been trying for about a month to run two astro applications behind an nginx reverse proxy:
Although the "base" option (be that vite.base or base) let's the app be served under the path specified at "base", @fs, @vite, node_modules etc. are still served under the root domain.   
It is quite common for professionals and companies to use docker with nginx and vite even during development for streamlined development, where there can be more than two frontend services running under the same docker network (e. g. while migrating codebases, with micro frontends, trying out multiple services etc.)

In such use cases there are clashes. I've had this problem in multiple occasions with more than one company (with nuxt and astro specifically, due to @vite stuff.) and I know others who had the same problem. 

Indeed I found this issue while trying to solve this problem:
<img width="735" alt="image" src="https://github.com/withastro/astro/assets/70356757/94e45c70-bb0c-45a9-b5ab-c55c53646e29">

**Comment by unbeauvoyage** [comment]
I don't think this is an extreme use case.
I have been trying for about a month to run two astro applications behind an nginx reverse proxy:
Although the "base" option (be that vite.base or base) let's the app be served under the path specified at "base", @fs, @vite, node_modules etc. are still served under the root domain.   
It is quite common for professionals and companies to use docker with nginx and vite even during development for streamlined development, where there can be more than two frontend services running under the same docker network (e. g. while migrating codebases, with micro frontends, trying out multiple services etc.)

In such use cases there are clashes. I've had this problem in multiple occasions in two different jobs (with nuxt and astro specifically, due to @vite stuff.) and I know others who had the same problem. 

I was expecting the below requests were like ".../astro/@vite...", ".../astro/@fs..." having "/astro" base path prefixed before the request path.
<img width="735" alt="image" src="https://github.com/withastro/astro/assets/70356757/94e45c70-bb0c-45a9-b5ab-c55c53646e29">

**Comment by yoyo837** [comment]
Need this.

During the development phase, we have multiple ports split into different applications. After build release, it is one application, and pages with different prefixes come from different projects.

**Comment by yoyo837** [comment]
Can it be reopened?

**Comment by marcoacierno** [comment]
Happy to reopen as it seems multiple people actually have the same need :) I will leave it to the Astro team to decide if they want to fix it or not.

**Comment by Fryuni** [comment]
So, there are two ways to go on about this, and that would depend on how much you can configure on the proxy you are adding in front of Astro.

Suppose you send a request to `/project-a/foo`, and all paths under `/project-a` come from an Astro project. What should happens next?
- The proxy would forward the request unchanged to the Astro project server, so the Astro project should serve a page on `/project-a/foo` that loads assets from `/project-a` and it should serve those assets under `/project-a`
- The proxy would send a request to the Astro project server asking for `/foo`, so the Astro project should serve a page on `/foo` that loads assets from `/project-a`, but it should serve those assets at the root

Whether the proxy in front is doing a rewrite changes things significantly because, in that case, the tree that is generated by Astro is not the tree that everything that gets generated refers to. This makes things much trickier on Astro's side.

The first case seems reasonably straightforward to implement (not small tho), and I would be happy to guide someone to do that. The second case... I'd really prefer to just figure out how to not do a rewrite on whichever proxy is in front of Astro

**Comment by matthewp** [comment]
@Fryuni is this an Astro bug at all? I'm having trouble seeing one.

**Comment by Fryuni** [comment]
I wouldn't say it is a bug because I don't think Astro has ever worked in that scenario. 
It is a feature request.

**Comment by yoyo837** [comment]
Hi team. it's really a feature request.

**Comment by matthewp** [comment]
Ah yes, this is not really possible with Astro dev server as it's not able to add prefixes for things like file URLs or `@id` URLs or a bunch of other stuff Vite has.

This seems very easy to configure on your proxy server. Just make it remove the `/astro/` prefix and everything should work. Here's an example of how to do this with Nginx: https://stackoverflow.com/questions/28130841/removing-start-of-path-from-nginx-proxy-pass

**Comment by yoyo837** [comment]
I know that this can be easily done under nginx. We are actually doing this now in a production.
Actually, this feature is request for dev mode exactly.

The situation is like this:

1. Start astro containing base configuration on port 9099.
2. Start another application at 9087 through `webpack-dev-server` proxy `['/_', '/src', '/@', '/node_modules']` to 9099.
3. Access 9087 in browser, it report an error when encountering the proxy content of 9099: `[astro-island] Error hydrating /src/components/SrvInfoWrapper.vue SyntaxError: The requested module '/src/components/hooks/dom/useZindexStyle.js' does not provide an export named 'default'`, If you access 9099 directly, everything works fine.

**Comment by klodoma** [comment]
Please re-open this.

We have 3 applications (from which 2 are astro projects) that we run under the same proxy.  The production setup is ok, but the development environment is a nightmare to manage for the moment.

**Comment by dreamstar-enterprises** [comment]
I sort of need this. 

My reverse proxy routes all requests that are localhost:7080/astro/ to localhost:4321/astro

The index page loads, but all the node modules are being requested as localhost:7080/node_modules, etc. hence, the page does not load properly.

This is not a problem at all with angular by the way. 

My astro app already has the base: astro applied in the astroconfig file.

**Comment by florian-lefebvre** [comment]
Hi @dreamstar-enterprises see https://github.com/withastro/astro/issues/9989#issuecomment-2497294077

**Comment by jcdogo** [comment]
For reference in case anyone ends up here, I have Astro working behind Nginx proxy in dev mode. Note that this is ONLY for running the dev server using Vite. Assuming my astro project is at the /astro dir, the Vite dev server serves up assets from /astro/src and /astro/node_modules. In this case the critical thing was to proxy these 2 locations to Astro. I struggled trying to serve src and node_modules directly from Nginx, but got lots of issues with mime types and script errors in the browser. So just pass them along to Astro dev server to fix these errors. I did not have to modify the Vite `base` variable at all, though if you have one you probably just adjust the paths so that Nginx proxies everything properly.

```
upstream astro_app {
  server localhost:4321;
}

server {
  listen 443 ssl;
  server_name astro.local;

  root /astro/dist/client;

  location /src/ {
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Ssl on;

    proxy_set_header  X-Real-IP  $remote_addr;    
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;            
    proxy_redirect off;    
    
    proxy_pass http://astro_app;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }
  
  location /node_modules/ {
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Ssl on;

    proxy_set_header  X-Real-IP  $remote_addr;    
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;           
    proxy_redirect off;    
    
    proxy_pass http://astro_app;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }
  
  location / {
    try_files $uri @astro_app;
  }

  location @astro_app {
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Ssl on;

    proxy_set_header  X-Real-IP  $remote_addr;    
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;         
    # proxy_set_header Host $http_host;    
    proxy_redirect off;    
    
    proxy_pass http://astro_app;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }
}
```

**Comment by Matb85** [comment]
Hello, any update on this?

**Comment by natxocc** [comment]
Same situation. Impossible to use Astro with code server in docker.
With Nuxt works using internal baseURL , but Astro dislike this option.

**Comment by SnowDroids** [comment]
Hello, I too would like to reopen this issue (feature request).

With an Astro 7 project, does anyone know how to get those "special paths" (eg: `/@vite`, `/@fs`, `/@id`) to get prefixed with a specific path? For example:

- `/@vite` > `/My/Path/@vite`
- `/@fs` > `/My/Path/@fs`

The reason why I'm asking is because I'm working on a project that uses a multi-zone pattern where I have different Astro projects handling different parts of my overall web app and I'm using path based routing to keep everything under a single origin (which in my case the origin is `localhost:8080`) . For example:

- Project 1 = `http://localhost:8080/`
- Project 2 = `http://localhost:8080/admin/`
- Project 3 = `http://localhost:8080/labs/`

For local development purposes, I'm using a lightweight reverse proxy locally to handle the path routing for all my locally running worker dev instances under `http://localhost:8080/`. I am able to use Vite/Astro options like [base](https://docs.astro.build/en/reference/configuration-reference/#base), but this setting does not get applied to those "special paths" that I mentioned.

My end goal for those "special paths" to end up looking something like:

- Project 1 = `http://localhost:8080/@vite` (no change here)
- Project 2 = `http://localhost:8080/admin/@vite`
- Project 3 = `http://localhost:8080/labs/@vite`


Does anyone know how to do this? 
What's the proper term for those paths?

**Comment by florian-lefebvre** [comment]
@SnowDroids this issue is 2 year old, I'd recommend you either open a new one or ask on our Discord server: https://astro.build/chat
