### ISSUE TITLE
Fragment + nested client:only components + slots problem

### ISSUE THREAD

**Issue by comus** [withastro/astro#9996]
### Astro Info

```block
Astro                    v4.3.2
Node                     v18.18.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/react
                         simple-stream
```

### Describe the Bug

below is the "not working" case, which is webpage display nothing.
```astro
---
import { Hello, Island, World } from "@components/demo.tsx";
---

<Island client:only>
  <Fragment slot="footer"><Hello client:only /></Fragment>
  <Fragment slot="header"><World client:only /></Fragment>
</Island>
```

but, if don't use Fragment, it works
```astro
<Island client:only>
  <a slot="footer"><Hello client:only /></a>
  <a slot="header"><World client:only /></a>
</Island>
```

also, below is work if nested components not defined `client:only`
```astro
<Island client:only>
  <Fragment slot="footer"><Hello /></Fragment>
  <Fragment slot="header"><World /></Fragment>
</Island>
```

### What's the expected result?

I expected this should work
```
<Island client:only>
  <Fragment slot="footer"><Hello client:only /></Fragment>
  <Fragment slot="header"><World client:only /></Fragment>
</Island>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qczw9r-srdto2?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Kanha-Dehury-01** [comment]
Nesting `client:only` directives can cause issues with rendering components on the server. Since the Island component is marked with `client:only`, any nested components with the same directive will also be skipped during server-side rendering. This can lead to empty content being displayed initially before the browser hydrates the components.

Instead of applying `client:only` to the Island component, move it to the individual components to render conditionally. This approach ensures that only the Hello and World components are skipped during server-side rendering, while the Island component itself is still rendered on the server.

```
<Island>
  <Fragment slot="footer"><Hello client:only /></Fragment>
  <Fragment slot="header"><World client:only /></Fragment>
</Island>
```

We can also use react-hydration
